### ISSUE TITLE
Game Area Mode Xperia does not work for all devices

### ISSUE THREAD

**Issue by prem0217** [Fate-Grand-Automata/FGA#1000]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1567

### Describe the bug

When the script is running on my Xperia mkII It works as expected during the run, but will not pick a servant; it seems the support view wasnt updaated for the xperia screen size.

### Video

https://drive.google.com/file/d/1NRuXYbdxNQyAAlqVn-rNZOuUZDsSiNcd/view?usp=sharing

end of the video shows the issue

### Device model

Sony Xperia 1 MkII

### Android version

11

### Screen size

1644 x 3840

### RAM

8 GB

**Comment by reconman** [comment]
Check out #845.

Did you set this to Xperia?

![Screenshot_20211211-195808](https://user-images.githubusercontent.com/12360257/145688396-0fa5ae7b-8047-4a75-838e-a95ab8dd3be0.jpg)

**Comment by prem0217** [comment]
Yes I did and also tried turning off and on notch recognition.tried messing with whatever settings I could think of before posting this

![Screenshot_20211211-111726.png](https://user-images.githubusercontent.com/1095372/145688885-992fa996-1c46-470f-b39c-f50fd546c8a8.png)

**Comment by reconman** [comment]
Can you provide a screenshot of FGO? I need to measure the black bars.

**Comment by prem0217** [comment]
Let me know if you need a different screenshot

![Screenshot_20211211-121156.png](https://user-images.githubusercontent.com/1095372/145690287-3015f43e-863e-4e46-91a0-939281d09241.png)

**Comment by McMaster01** [comment]
![Screenshot_20211212-041259_FateGO](https://user-images.githubusercontent.com/94461007/145691818-411a5071-1ced-4848-95cb-7cbbefb8faef.jpg)

Same, i use Samsung A12 and it doesn't even select the stage

**Comment by reconman** [comment]
@McMaster01 Not Xperia, you didn't even read the Troubleshooting guide or the other issues about Samsung devices telling you to enable full screen mode.

**Comment by McMaster01** [comment]
I went to the troubleshooting and do like it said. Then it worked great. Thanks for telling me there's a fix on my device, if you don't tell me I'll never know

**Comment by reconman** [comment]
I see the exact same display size as ToastCrust's device, but the ratios are different.

In #845, the ratios were:
- 2.58 %, 89.92 %, 7.5 % (ToastCrust)
- 2.50 %, 90 %, 7.5 % (itscakebuffet)

This one is 2.34 %, 89.92 %, 7.73 %.

So the FGO ratio is the same as back then, but the navigation bar and top bar have different sizes.

I've just changed the Xperia mode to use the height of the navigation and status bars. I'm sure that the navigation bar measurement is needed, but I'm not sure if it works.

Can you check https://github.com/Fate-Grand-Automata/FGA/suites/4627847887/artifacts/125295026?

**Comment by prem0217** [comment]
The app just isnt working with this build. I ran the run manually and it still also couldn't pick a servant

https://drive.google.com/file/d/1OF3zFbzMpIf00k_GoJZNhc4hsr-Z60J_/view?usp=drivesdk

**Comment by GrauGeist** [comment]
"Game Area Mode" is poorly described.

Please update the descriptions:
* **default** (16:9 -  eg. 1920x1080 HD)
* **Experia** (21:9 - eg. 3840x1644 tall)
*  **Duo** (4:3 tall - 2784x1114 tablet)

**Comment by prem0217** [comment]
> "Game Area Mode" is poorly described.
> 
> Please update the descriptions:
> * **default** (16:9 -  eg. 1920x1080 HD)
> * **Experia** (21:9 - eg. 3840x1644 tall)
> *  **Duo** (4:3 tall - 2784x1114 tablet)
> 

Was this a remark for me?  As the Xperia resolution you mentioned is correct

**Comment by GrauGeist** [comment]
If FGA doesn't work, then it's not helpful to have "Experia" or "Duo" if there isn't any information as to what "Experia" or "Duo" means.

**Comment by Pycorax** [comment]
I would also like to add that this doesn't work on the Galaxy Fold 3's cover screen after NA updated to support wider screens. I'm to help out in any way I can to fix this issue.

**Comment by reconman** [comment]
@GrauGeist Xperia stands for Sony Xperia phones, Duo for the Surface Duo.

People owning those devices know that it affects them. Other people don't need to know about the non-default game area modes.

@Pycorax I'll need a seperate Github issue with as much info as possible, starting with a video recorded by FGA.

**Comment by Pycorax** [comment]
I've manage to fix this by simply by turning off the aspect ratio override so I guess it's not an issue anymore. Just leaving this here for whoever may have this issue in the future.

**Comment by reconman** [comment]
Aspect issue override? Can you take a screenshot of what you mean?

**Comment by Nostras** [comment]
Hi guys,

Reviving this issue as I'm having the same problem and seeing this wasn't resolved.
I'm using a MKIII, not MKII
![image](https://user-images.githubusercontent.com/4203238/160260022-6752bce0-c91f-43a2-96ba-4b214947d97a.png)
![Uploading image.png…]()
Don't be fooled by the resolution though (3840x1644), the real resolution is half (1920x822) and the phone is upscaling screenshots.
Same settings as OP, same experience as OP.
Selecting skills works fine, facecard detection is fine, but support selection (and start quest) is not working.
I tried XPERIA mode and also counted the size of the black borders (97x97), but both have the same result.

Hope someone can look at this.

**Comment by reconman** [comment]
@Nostras Did you try custom game area mode? It's not clear from your description.

**Comment by Nostras** [comment]
> @Nostras Did you try custom game area mode? It's not clear from your description.

Sorry, I wasn't very clear there. But yes, I did. 194x194 didn't work, then I used 97x97 and noticed the resolution upscaling.
Same result though.

**Comment by reconman** [comment]
In the second screenshot you posted, you can see a big red rectangle in the bottom right.

Can you try reducing the right offset until the right border of the rectangle aligns with the black bar?

For the left offset, there's a big red rectangle that appears shortly after you press the play button. The left border of that rectangle should be aligned with the black bar.

**Comment by Nostras** [comment]
I see it, this isn't recorded by the built-in screen recorder. It's indeed slightly too far to the left.

I tweaked both of them to 130 (left and right) and now it works.
Thanks for your help, I strongly recommend you put this in the tutorial.

![image](https://user-images.githubusercontent.com/4203238/160277415-7ad923a1-4402-4e9c-8620-6319533c6f6d.png)

**Comment by Mesho39** [comment]
thanks all for help but it didnt work my phon is 19.5:9 ratio i missed aroun alot in the sitteng but always get deffrenet resaulet i tried the 130 left and right but it also didnt work so any one like to susget other setting i all ready for it

**Comment by Nostras** [comment]
> thanks all for help but it didnt work my phon is 19.5:9 ratio i missed aroun alot in the sitteng but always get deffrenet resaulet i tried the 130 left and right but it also didnt work so any one like to susget other setting i all ready for it

I think you missed reconman's point. Try to identify the correct custom area you need by using the guidance provided by him to me in this issue. Just setting it to 130x130 is most certainly not going to work unless your phone screen is 1920x822 (I'm quite sure this is literally the only phone in existence that has this res).

**Comment by reconman** [comment]
Closing this now, will document Custom Game Area mode later.
