### ISSUE TITLE
Overlay is off and messes up Scripts

### ISSUE THREAD

**Issue by TogBr** [Fate-Grand-Automata/FGA#1002]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1573

### Describe the bug

The overlay is off-center causing scripts not to function properly. I have tried turning on ignore Notch calculations as well as changing the game area mode but still off by a bit.

### Video

https://youtu.be/SDBhoE5hHfI

### Device model

Motorola Edge

### Android version

11

### Screen size

2340x1080

### RAM

6Gb

**Comment by reconman** [comment]
Is your video with normal game area mode and without Ignore Notch?

**Comment by reconman** [comment]
Also, can you upload a screenshot of FGO?

**Comment by TogBr** [comment]
I think the video should be is normal game area and notch on,
![Uploading Screenshot_20211211-162946.png…]()

**Comment by reconman** [comment]
You pressed comment too early, the image didn't finish uploading.

**Comment by TogBr** [comment]
My bad, 
![Screenshot_20211211-162946](https://user-images.githubusercontent.com/95599790/145696109-f2b016ad-613d-4236-a021-6a18f7e995df.png)

**Comment by reconman** [comment]
Looks like the black bars at the top and bottom mess up FGA.

Can you check if you can get rid of them somehow?

**Comment by reconman** [comment]
From the manual:

![Screenshot_20211212-014319](https://user-images.githubusercontent.com/12360257/145696287-32907143-8758-4c3d-bda3-fd44d4d5aee1.jpg)

I think it's the Edge display settings.

**Comment by TogBr** [comment]
I turned it on edge display and the black lines are gone but now it's not working at all
![Screenshot_20211211-164759](https://user-images.githubusercontent.com/95599790/145696408-37e40178-62ca-431c-a137-5ee2e1a405f4.png)

**Comment by reconman** [comment]
What do you mean? Can you provide another video? Maybe turning the FGA service off and on again helps?

**Comment by TogBr** [comment]
Restarted both apps with edge display only on for FGO and now it's working beautifully, Thank you so much for the help
