### ISSUE TITLE
Support select screen doesn't gets detected properly

### ISSUE THREAD

**Issue by Troodon04563** [Fate-Grand-Automata/FGA#1003]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1573

### Describe the bug

The support select doesn't works unless I do it manually, already tried placing the play button in different corners and turning on/off ignore notch. Also I can properly use support image maker. Everything else seems to work fine.

### Video

https://youtu.be/QWfjfA5RfW0

### Device model

Xiaomi Redmi Note 6 Pro

### Android version

9

**Comment by yunjun-wei** [comment]
I have the same problem.
My phone is a Galaxy S20+, using the latest build for the current lotto event in JP. Everything works perfect except for the support screen where it just sits there not selecting any support. 
Screen size is 2400 x 1080.
Please refer to the attached screenshot.
![20211212](https://user-images.githubusercontent.com/18112065/145712559-459c2237-826d-46fb-bae0-01b1e1a0a72c.jpg)

**Comment by reconman** [comment]
#943 is as bad as I initially thought, once the screen ratio goes above 18:9, every single UI element is stretched by a few percent.

I have to stretch the second screenshot in this issue by 4.13 % to perfectly align every UI element with the video. I currently have no idea what formula is needed to calculate the stretch percent.

**Comment by reconman** [comment]
I'm closing this in favour of the original issue #943.

**Comment by reconman** [comment]
I've reverted the change introduced in #991, 1575 should work for most devices again.

**Comment by yunjun-wei** [comment]
Thanks for the update!
I can now use it without any problem.

**Comment by Euphy14** [comment]
I used 1592 ver, still have support selection issues, fga cant choose support and stop there.

**Comment by reconman** [comment]
@Euphy14 Open a seperate issue if you're sure the troubleshooting guide doesn't solve your issue.
