### ISSUE TITLE
automata doesn't start on Redmi Note 10s

### ISSUE THREAD

**Issue by niwaaa** [Fate-Grand-Automata/FGA#1004]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1575

### Describe the bug

it's working properly on my old device redmi note 8, but on my new device redmi note 10s it's doesn't start properly. i tried use debug mode to see what happen on the screen, and i saw the red line doesn't fit on the any button on FGO. so FGA doesn't start to press any button when it started

### Video

https://drive.google.com/file/d/11-x0P7uS5yVOvWRobT-NWLnx7duTbwJi/view?usp=drivesdk

### Device model

Redmi Note 10s

### Android version

11

**Comment by reconman** [comment]
First of all you have some black bars: https://github.com/Fate-Grand-Automata/FGA/wiki/Game-Area-detection#fgo-looks-different-on-my-phone

But even if you somehow get rid of them, you'll probably encounter #945. You can try and see what happens, though.
