### ISSUE TITLE
FGA misses the buttons

### ISSUE THREAD

**Issue by john-bao-git** [Fate-Grand-Automata/FGA#1005]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1567

### Describe the bug

FGA misses inputs, messing up the script.

Without skill confirmation, FGA presses Servant 1's S2 instead of S3.

After looking around, I found [this thread](https://github.com/Fate-Grand-Automata/FGA/issues/964):

However, with skill confirmation, FGA misses Plugsuit. I'd also like to know why this works with skill confirmation but not without.

### Video

Without skill confirmation

https://www.youtube.com/watch?v=G_hzOgLK_uo

With skill confirmation

https://www.youtube.com/watch?v=MgZ7g0ARKKo

### Device model

Samsung Galaxy S21

### Android version

11

### Screen size

2400x1080

### RAM

8GB

**Comment by reconman** [comment]
https://github.com/Fate-Grand-Automata/FGA/wiki/Game-Area-detection#case-1-borders-around-fgo-are-black

**Comment by john-bao-git** [comment]
Thank you. I thought that I already turned it on, but I guess I didn't.
