### ISSUE TITLE
Cannot Press "Start Now" on Bluestacks

### ISSUE THREAD

**Issue by aeasc1** [Fate-Grand-Automata/FGA#1006]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1575

### Describe the bug

After pressing "Start Service", the "Start Now" button is unresponsive. 

After looking at other similar issues, I tried rotating the screen but that didn't work.

### Video

https://user-images.githubusercontent.com/88807390/145835452-4e31cbdc-f9e4-4afe-a7b6-318fb97b5164.mp4

### Device model

OnePlus 5 (Bluestacks 4.280.0.1022 32-bit Android)

### Android version

7

### Screen size

1600x900

### RAM

4GB

**Comment by reconman** [comment]
Works fine on 5.4.100.1026 64 Bit.

Your rotation looks weird, FGA should be in vertical mode when you start the service.

![Screenshot_2021 12 13_19 57 42 393](https://user-images.githubusercontent.com/12360257/145871653-6e14d1c3-bc81-4f06-ada6-a179b58d6b36.png)
