### ISSUE TITLE
"FGA has stopped" error

### ISSUE THREAD

**Issue by Lordmiloskindmachinist** [Fate-Grand-Automata/FGA#1007]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1575

### Describe the bug

I have downloaded the app from https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary
So, when I click on the start button (after making script of course), fga gives an error which says "FGA has stopped" and another error following the first one "FGA keeps stopping"
It's my first time running fga on an emulator and I don't know what to do other than asking. 

### Video

https://user-images.githubusercontent.com/87274372/145858344-d7a91cea-cb85-4d0c-8374-5ede82f3a2fe.mp4

### Device model

ONEPLUS A5010 (MEMU Version 7.6.3)

### Android version

7

### Screen size

1440x810 (270 dpi)

### RAM

4GB

**Comment by reconman** [comment]
Try using root mode. According to the internet, root is enabled by default on Memu.

**Comment by Lordmiloskindmachinist** [comment]
Used it and FGA works right now. It missclicks some skill activation but I can ask it on a different issue. Thank you very much.

**Comment by reconman** [comment]
That's probably skill confirmation, check the troubleshooting guide.
