### ISSUE TITLE
Motorola One not working

### ISSUE THREAD

**Issue by The7thPrince** [Fate-Grand-Automata/FGA#1008]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1575

### Describe the bug

FGA doesnt click the skills correctly, it is full screen
I tried on the notch calculator but the problem still.

### Video

https://youtu.be/8sQMi88FzHY normal mode

https://youtu.be/FnE8ocTNUp4 Ignore notch calculator 

### Device model

Moto One

### Android version

10

### Screen size

720 x 1520 pixels, 19:9 ratio

### RAM

4GB

**Comment by reconman** [comment]
https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting#uses-skills-on-the-wrong-servant-or-doesnt-use-skills-at-all

**Comment by The7thPrince** [comment]
omg, it is working!
THANK YOU SO MUCH!
Happy holidays!
