### ISSUE TITLE
Gift Box Ember retrieval only reads the number in the ones place

### ISSUE THREAD

**Issue by sdarkpaladin** [Fate-Grand-Automata/FGA#1009]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1575

### Describe the bug

JP released a new update that allows 100 lottery rolls at one go. Which creates EXP stack with double digits like 11, 12, 13.

When FGA selects the EXP stacks, it only checks the ones place.

E.g. When set to 1, FGA selects stacks of 1, 11, 21... When set to 2, FGA select stacks of 1, 2, 11, 12, 21, 22...

### Video

https://user-images.githubusercontent.com/8553088/145926885-ab17c378-c842-4655-b80b-271d5757aff7.mp4

### Device model

Nox Player set to Google pixel 2

### Android version

12

**Comment by Tom3kk** [comment]
If FGA cant read the font then how does it know if an ember is =<4?

**Comment by reconman** [comment]
@Tom3kk it compares against images of 1, 2, 3 and 4.

**Comment by CDB-Man** [comment]
As an enhancement request, can we increase the image recognition library to include all single digit options?  Ie from 1 thru to 9.  Given the larger spins, this would be helpful!

**Comment by reconman** [comment]
@CDB-Man I would need images of x5, x6, x7, x8 and x9 on NA, CN, TW and KR servers since every server uses different fonts.

**Comment by CDB-Man** [comment]
Happy to provide for NA, attached below.

![Screenshot_20221225-160122_577bcc70c040536a6d306ef99c704547](https://user-images.githubusercontent.com/14037303/209481925-e9fbc282-9134-4b2d-a2ba-3e7e5b86b283.jpg)
![Screenshot_20221225-160131_577bcc70c040536a6d306ef99c704547](https://user-images.githubusercontent.com/14037303/209481927-28a29711-fd26-40d1-9d8e-f8da8b0b1cbb.jpg)
![Screenshot_20221225-160142_577bcc70c040536a6d306ef99c704547](https://user-images.githubusercontent.com/14037303/209481928-265d1f01-9ded-4d5b-a55f-95789a78fa14.jpg)
![Screenshot_20221225-160146_577bcc70c040536a6d306ef99c704547](https://user-images.githubusercontent.com/14037303/209481929-bb18fdec-39e1-4069-9147-792efa9e6d49.jpg)

**Comment by reconman** [comment]
Using OCR to detect the count now, can detect much higher counts now.

**Comment by DarkSorc** [comment]
Is this still a work in progress? My fga is still capped at 4. No pressure, just wondering if I'm missing something

**Comment by reconman** [comment]
No, you're using an old version.

**Comment by DarkSorc** [comment]
Oh didn't realize. Thanks
