### ISSUE TITLE
Pixel 4a, error on selecting support servant Skadi.

### ISSUE THREAD

**Issue by dwennon** [Fate-Grand-Automata/FGA#1011]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1575

### Describe the bug

When I attempt to use FGA in gesture mode it doesn't really do much, not really detecting anything.  From there trying to switch to the suggested mode for using FGA at this time I keep getting an error saying it couldn't find file for reading, specifically Skadi. I have also tried uninstalling and reinstalling FGA, as well as restarting my phone. Nothing has really changed.

I also attempted to use some of the other options for still using gesture based navigation like ignoring the notch calculations for example.  Most of this started with an update last week in Fate Grand Order, and so far I haven't been able to figure out what best to do. Before that update I was using a much older build, and it was working just fine. I do not think I still have that though, if it at all matters. And I included attempting to run FGA with gesture mode, in case that helps.

### Video

https://user-images.githubusercontent.com/75424458/145995860-ae414402-7769-47d5-b849-6ba4f14f0ef7.mp4

https://user-images.githubusercontent.com/75424458/145998180-d2b603ba-b6ad-49b6-93aa-64a0b775673a.mp4

### Device model

Pixel 4a

### Android version

11

**Comment by reconman** [comment]
Check your FGA dorectory set under Storage, it doesn't contain Skadi.
