### ISSUE TITLE
Stop FP summon once you got X amount of Y

### ISSUE THREAD

**Issue by The-Intelligent-One** [Fate-Grand-Automata/FGA#1014]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

It's great that we can give a limit to the number of FP summons FGA would do, but if possible, I'd love it if there was a way to tell it to keep summoning until a certain goal is achieved. An example would be summoning until you get enough 3* event CEs to MLB, or summoning until you get a copy of Saber Lily or something. This way the player wouldn't have to just keep an eye on what's summoned and hopefully stop it in time or just give up needlessly on more FP.

**Comment by reconman** [comment]
Sorry, that's too much work and is not feasible.
