### ISSUE TITLE
This happens when it gets to the friends list 

### ISSUE THREAD

**Issue by nofacej** [Fate-Grand-Automata/FGA#1015]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

When it gets to the friends list this Is the error it gives me. What do I do with this
null

j4.a$b
	at j4.a.b(AutoBattle.kt:3)
	at i5.c.q(EntryPoint.kt:3)
	at w5.a.run(Thread.kt:1)

**Comment by reconman** [comment]
Not a question, I need you to fill out the bug report.
