### ISSUE TITLE
Unable to select skills or cards in NA.

### ISSUE THREAD

**Issue by Obeonix** [Fate-Grand-Automata/FGA#1016]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1575

### Describe the bug

Ever since the recent update that added widescreen to NA, FGA has been unusable. I've tried both the Cl version and the original version. The furthest I managed to get was past the support screen and into the battle, whereupon it was unable to select anything due to the detection zones being misaligned. 

### Video

[YouTube Link](https://youtu.be/CYzvTK2woF8)` 
Had to compress it a bit since the video wasn't letting me upload it for some reason. 

### Device model

Oppo Reno2 Z

### Android version

11

### Screen size

2340 x 1080 Pixels

### RAM

8gb

**Comment by reconman** [comment]
https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting#uses-skills-on-the-wrong-servant-or-doesnt-use-skills-at-all
