### ISSUE TITLE
Is it intentional that the app only detects that the gift box is open if there's at least one ember stack on the screen?

### ISSUE THREAD

**Issue by The-Intelligent-One** [Fate-Grand-Automata/FGA#1021]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

So Galemas is here, and one of the rewards in the boxes is a ticket we can exchange for materials, which goes to the top of the gift box, like the monthly material tickets. Since I didn't plan to cash them out immediately, I had a few piled up, and was met with an error message from the lottery script when it opened the giftbox and didn't see any embers. Then I noticed that even if I try to open up FGA to start the gift box script on its own, the battle scripts are the ones that show up.

Is this intended to work this way? I mean, it's not a huge hassle to scroll down manually to embers first, but I'm not sure if this will work great with the lottery script.

**Comment by reconman** [comment]
Yes, for the ember feature to qork you should filter for EXP cards and nothing else.
