### ISSUE TITLE
Not picking NP/cards on Attack screen OR Got stuck in some info screen

### ISSUE THREAD

**Issue by zeek17** [Fate-Grand-Automata/FGA#1022]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

I have one of those badly lagging phones, and it's annoying as hell. Can you implement an option to check:
-if FGA is stuck in info screen and promptly close it.
-if it's stuck in Attack screen - to just tap 'back' button. It will go to previous screen and will try again. I just want to automate this thing.
-if there's NP used it the turn and any type of 'unable to determine card type' error appeared - use abovementioned 'back' thing regardless if it's stuck or not, because one of undetermined cards could me NP cards and that could ruin entire run.
For poor sods like me that are too poor to buy new phone for the sake of one game.

**Comment by reconman** [comment]
> because one of undetermined cards could me NP cards

That's not true, it only affects NP chaining.

And you can just increase the wait timers in Fine Tune.

**Comment by zeek17** [comment]
I did. 3 sec before card selection and double overall delays. It's still a thing.
After increasing delays 'unable to determine' errors shows up a lot less, but FGA still gets stuck in attack screen.
If everything above is too bothersome for you, please add just one condition in code: if it's doing nothing at attack screen for 10sec - tap back button.
