### ISSUE TITLE
The app doesn't click on friend supports

### ISSUE THREAD

**Issue by Fog-15** [Fate-Grand-Automata/FGA#1023]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

The app worked perfectly fine yesterday clicking on Skadi for a 3T Farm. I'm assuming due to the new android update, that i installed this morning, that the app is being wonky when selecting Support Servants. If there are any solutions than please do tell me. Also using current build 1575.

**Comment by reconman** [comment]
Not a question but a bug.

I need you to fill out a bug report.
