### ISSUE TITLE
App doesn't click on supports

### ISSUE THREAD

**Issue by Fog-15** [Fate-Grand-Automata/FGA#1024]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1575

### Describe the bug

The other day the app was working fine with clicking on support servants for 3T farming. This morning there was a Android update and afterwards it wouldn't work. I have uninstalled and reinstalled thinking it would work but it didn't. 

### Video

Uploading record (1).mp4…

### Device model

Samsung S21 Ultra

### Android version

12

### Screen size

2400x1080

**Comment by Fog-15** [comment]
https://user-images.githubusercontent.com/90011008/146668645-74d0358c-d3d1-4745-83e9-86fcf79474a1.mp4

**Comment by reconman** [comment]
Play button should be in the bottom right.
