### ISSUE TITLE
fga not detecting the screen on Nox Android 9

### ISSUE THREAD

**Issue by bel7san** [Fate-Grand-Automata/FGA#1028]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1575

### Describe the bug

fga is not detecting the screen
whenever i hit the play button it just sits on the support and doesn't do anything
and when i go to the fp gacha and start fga it just starts the normal farming screen
i tried using root for screenshots and turned on root but the issue persisted
i'm using the android 9 beta for nox

### Video

https://www.youtube.com/watch?v=io1FKSYxzLE

### Device model

noxplayer 7.0.1.9

### Android version

9

### Screen size

1600x900

### RAM

4gb

**Comment by reconman** [comment]
We haven't tested Android 9 on Nox yet, so we can't guarantee that it works.

**Comment by Held-Kaiser** [comment]
I have the same problem on my phone.

**Comment by reconman** [comment]
@Held-Kaiser Has nothing to do with Nox but probably with some black bars. Read the troubleshooting guide.

**Comment by bel7san** [comment]
@reconman do you plan on testing it?
