### ISSUE TITLE
Skill wont target

### ISSUE THREAD

**Issue by jukcar0797** [Fate-Grand-Automata/FGA#1030]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [x] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1755

### Describe the bug

Skills wont target servants on the target window 

### Video

https://user-images.githubusercontent.com/80792643/146816956-6498e0e6-f81a-4769-9d67-771956c073f7.mp4

### Device model

Motorola moto e6 play

### Android version

9

### Screen size

1440x720 px

### RAM

2 gb

**Comment by reconman** [comment]
It's either because of the lag or because of 18:9. Looks like the second one, but will check with Bluestacks later.

**Comment by jukcar0797** [comment]
> It's either because of the lag or because of 18:9. Looks like the second one, but will check with Bluestacks later.

It works smoothly till the past Saturday

**Comment by reconman** [comment]
So you didn't update FGA, it just randomly stopped working? Have you tried restarting your phone!

**Comment by jukcar0797** [comment]
I update it it then started to fail, then in downgraded it , didn solve the problem, reatarte the phone, uninstalled and installed the latest version still not working

**Comment by jukcar0797** [comment]
It was repaired on the 1592 build
