### ISSUE TITLE
Play button not working

### ISSUE THREAD

**Issue by skhatiwada013** [Fate-Grand-Automata/FGA#1032]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1577

### Describe the bug

Play button does not work when trying to press it on FGO screen.  I have attached screenshots of FGA, FGO, and my game mode being off. Any help is welcome!

![Screenshot_20211220-211721_FGA (CI)](https://user-images.githubusercontent.com/9464795/146862439-00fcb5b2-cb68-4437-9f0c-a2af283a24df.jpg)
![Screenshot_20211220-211754_FGA (CI)](https://user-images.githubusercontent.com/9464795/146862468-080f50a9-a524-44c1-be50-d793945c8b6b.jpg)
![Screenshot_20211220-211806_FateGO](https://user-images.githubusercontent.com/9464795/146862499-5ac94c93-049c-4aa6-a105-ef90e8d07abf.jpg)
![Screenshot_20211220-213211_Settings](https://user-images.githubusercontent.com/9464795/146862508-de579d4b-822d-491a-a3cb-6e1506fcecd0.jpg)

### Video

https://user-images.githubusercontent.com/9464795/146862304-b6e62336-e5f2-4f4c-9410-197bbe507083.mp4

### Device model

Samsung galaxy s21 ultra

### Android version

12

### Screen size

2400x1080

### RAM

12GB

**Comment by Skyjersey** [comment]
Try force closing FGA reopen it and it may ask for accessibility permission again enable it then disable it and finally enable it again.

**Comment by sitalkhatiwada** [comment]
Attempted this fix, no luck, same issue as before.

**Comment by mingchungtsai** [comment]
I have encountered this issue as well where the "Play" button is not working; although I'm using Bluestacks 5.1.110.1005 N32, and am using the latest build currently (1583).

There's an observation I can add to this which might only be relevant to an emulator setup.

On the FGA screen, I press the Start Service button, the Play button appears for a few milliseconds and quickly disappears. Clicking on "Start Now" button on the capturing message is not reactive, while "Cancel" is reactive.

![image](https://user-images.githubusercontent.com/43601465/146941891-e6bea0c5-6149-4b82-bad8-076d03de6b83.png)

When I switch to the FGO screen, the "Play" button surfaces, but does not work.

![image](https://user-images.githubusercontent.com/43601465/146941313-0ae3e03e-0c42-43b2-9351-7a03ca6bdeb4.png)

When I switch back to FGA, the "Play" button disappears, and "Stop Service" automatically resets to "Start Service"

If this is a separate issue, I'm happy to log a new one.

**Comment by skhatiwada013** [comment]
Good insight but I do not believe this will help in resolving my issue unfortunately. I have tried starting in different screen orientations to no luck.

**Comment by skhatiwada013** [comment]
I got it to work by disabling "Use Root For Screenshots"! Having issues with FGA not clicking correcting when the farming script starts but I will create another issue for that
