### ISSUE TITLE
Farm stops on the info screen

### ISSUE THREAD

**Issue by giverance** [Fate-Grand-Automata/FGA#1034]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1575

### Describe the bug

I'm a bit confused as to what happened, however I seem to have this only on NA, everything works on Korea and Jap... I think it's most likely due to the update I installed... But not sure about that at all(P.S. I've only just seen that a new version has come out... But I don't think it's going to help me in any way)

### Video

https://youtu.be/bZ1AUBY2Jyc

### Device model

Xiaomi Redmi Note 9 Pro

### Android version

11

### Screen size

1080x2400

### RAM

6gb

**Comment by reconman** [comment]
Maybe disabling skill confirmation and increasing Wait After Clicking in More Options-> Advanced -> Fine Tune will help.
