### ISSUE TITLE
FGA doesn't scroll and take 2 drop screenshots

### ISSUE THREAD

**Issue by squaresmile** [Fate-Grand-Automata/FGA#1036]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1583

### Describe the bug

FGA doesn't scroll and take 2 drop screenshots when there are more than 20 drops or the scroll bar is scrollable

### Video

This run doesn't have more than 20 drops but it should be representative. Let me know if you need a video with 20+ drops.
https://youtu.be/Efz27oCThBE

### Device model

oneplus 5t

### Android version

10

### Screen size

2160x1080

### RAM

8GB

**Comment by MathewSachin** [comment]
Looks like the whole drops area has moved up with the widescreen update.
The scrollbar area we check to see if needed to scroll needs to be adjusted for wide-screens.
