### ISSUE TITLE
Pixel 6 Screen Region Causes Issues with Offset Matching Regions

### ISSUE THREAD

**Issue by calpalimus** [Fate-Grand-Automata/FGA#1039]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1589

### Describe the bug

Failed to determine Card type: [1,2,3,4,5] and miss-clicking for skills on Pixel 6. Matched regions are offset in both screen orientations resulting in failed skill inputs and script execution. 

Tested with and without "Ignore Notch calculation", notch region left blank on screen, but bounding boxes for matching overflow anyway. 

Tested with all 3 Game Area Modes, issue persisted in all.

### Video

[Video of Issue](https://youtu.be/-8cwsilT4ks)

### Device model

Pixel 6

### Android version

12

### Screen size

1080x2400

### RAM

8GB

**Comment by reconman** [comment]
Looks like you need the opposite of Ignore Notch. A Game Area mode for when FGO still has a black notch bar.

On my phone, FGO fills out the notch area.

I tried googling for this problem and found that at least on Pixel 5 you can change the notch in Developer Options, but that affects all apps.

**Comment by calpalimus** [comment]
The issue is also that even with the wide-screen update the Pixel 6's screen is longer than FGO supports. The phone doesn't really have a "Notch Area" it's almost always populated because it's only the camera and is barely noticeable. The only time the area is black is when the resolution is not supported as is the case here. The fix would probably need to be another Screen Region option specifically for the 1080x2040 Aspect Ratio.

**Comment by reconman** [comment]
Normally, below 18:9 should have blue bars on the left and right, as far as I know.

I'm going to test it in an emulator.

**Comment by calpalimus** [comment]
> Normally, below 18:9 should have blue bars on the left and right, as far as I know.
> 
> I'm going to test it in an emulator.

This is really odd. I definitely used to have blue bars, but they don't appear to be there any more. I don't know exactly when they disappeared (although I assume probably with the wide-screen update), I didn't even notice they were gone until you mentioned them.

I'll include screenshots below. 

One from before the wide-screen update and one from after:
![Screenshot_20211026-152652](https://user-images.githubusercontent.com/9301002/147200259-e8013012-d726-497b-925d-a67969ce1da5.png)

![Screenshot_20211124-160224](https://user-images.githubusercontent.com/9301002/147200309-e40a0f54-c923-4d08-a76b-eddb774de0ec.png)

**Comment by reconman** [comment]
I double-checked, you had a typo. Your resolution is 1080x2400, not 1080x2040. That's exactly 20:9, so normally FGA fills the whole screen.

On your device, the black areas are:
- On the left 118 pixels notch + 51 pixels black bar
- On the right 51 pixels black bar

I currently can't find any rule for calculating the width of the black bars.

But I have a feature idea related to fixing your problem via configurable offsets. That way, we can fix problems for all kinds of devices with black bars, not just yours. Have to discuss it with Mathew first, I probably can't implement it on my own.

**Comment by MathewSachin** [comment]
Does this work for you:
> There should be no black bars on the screen. If there are, switch your phone from Gesture Navigation to 3-button navigation.

I know its not convenient, but, this works for Pixel 4, not sure about 6.

**Comment by calpalimus** [comment]
This does appear to fix the issue. I'll do some more testing with settings to see if there's a way to get the same screen population in gesture mode or if there's a way to partition settings across applications.

**Comment by reconman** [comment]
@calpalimus Did you ever find a solution? Facing the same problem right now.
