### ISSUE TITLE
Allow for FGA to stop after a set amount of CE drops

### ISSUE THREAD

**Issue by Twilight666** [Fate-Grand-Automata/FGA#1044]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Right now FGA recognises if there is a CE drop and in the info screen (during pause or when the script stops) it notifies how many CE drops the user got during the script's run

There is also the option to stop a script when you get a CE drop.

The issue (especially during lotteries) is that sometimes having another CE drop doesn't change anything until you get enough 
to MLB the CE.
So is it possible to combine the above and move the stop on CE drop in the script start screen. And then just like how you can set the script to end after X amount of runs (or materials) add another option for stopping the script after x amount of CE drops?

**Comment by Tom3kk** [comment]
bump

**Comment by reconman** [comment]
Please check if version 1796 works correctly.

**Comment by Tom3kk** [comment]
It does not seem to work, I got a CE drop and it did not stop

**Comment by reconman** [comment]
1797 works better now, I'll test the 1 CE limit issue myself. I only tested if the CE limit decreases after a drop.

**Comment by reconman** [comment]
Got it after 1 run

![Screenshot_2022-08-25-23-48-52-29_f98d04a6a5569a2ca2cd39796e1f730e.jpg](https://user-images.githubusercontent.com/12360257/186775165-deef2346-aa84-46f8-9b0c-9bb6adf57697.jpg)

**Comment by Tom3kk** [comment]
I've set it to stop after 4 (manually stopped after 3) and it had counted the drops, idk why it didn't stop for the first one, maybe emulator glitched

**Comment by Tom3kk** [comment]
Update, I've gotten many drops since and FGA seems to refuse to stop after the requested amount of CE drops, I've multiple times have set it to stop after 1 or two drops, and when I turn off fga, am told I got 3 drops.

**Comment by reconman** [comment]
Like I said, update to 1797 or higher.
