### ISSUE TITLE
After updating, MLB CEs aren't chosen after the first run

### ISSUE THREAD

**Issue by lolcatzidk** [Fate-Grand-Automata/FGA#1047]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1594

### Describe the bug

I'm doing the current NA event right now, so I made the bot choose to use supports that have servants with MLB CEs on them. The first run went perfectly with the bot choosing a servant with a MLB CE. After the first run, however, I noticed that the bot would just choose a non-MLB Event CE. I tested it out a few times, and it does seem like after the first run, it just stops checking to see if the CE is MLB or not. 

I did some testing and I think the issue doesn't occur if you pause the run, go to the preferred servant/CE page on FGA, uncheck the MLB choice and recheck it.

(I do not know how to check my status of my device model or my RAM as I'm using Bluestacks, so I put 7)

### Video

a

### Device model

Bluestacks 5.3.120.1002 N32

### Android version

7

### Screen size

1920x1080

### RAM

3GB

**Comment by lolcatzidk** [comment]
Sorry it took me a while to get the video.

Link: https://youtu.be/aoCDnxrbFFo

**Comment by roguralter** [comment]
At the support servants screen, set the filter to only show mlb ce. This way the app will only pick the right ce.

**Comment by reconman** [comment]
@lolcatzidk The video is without debug rectangles. But other users also reported this issue and I think it's just an issue with the current event and has nothing to do with recent code changes.

If I see the video with debug rectangles, I can say for sure whether it's because of the event CE. But the event is almost over anyways.

**Comment by lolcatzidk** [comment]
> At the support servants screen, set the filter to only show mlb ce. This way the app will only pick the right ce.

Oh true. I had it on before, but I forgot to turn it back on after doing the CQ. Thanks for letting me know.

**Comment by lolcatzidk** [comment]
> @lolcatzidk The video is without debug rectangles. But other users also reported this issue and I think it's just an issue with the current event and has nothing to do with recent code changes.
> 
> If I see the video with debug rectangles, I can say for sure whether it's because of the event CE. But the event is almost over anyways.

How would I turn on debug triangles? Maybe I can redo the video.

**Comment by reconman** [comment]
Under More Options -> Advanced -> Debug Mode
