### ISSUE TITLE
The app won't follow the commad and get stuck at 

### ISSUE THREAD

**Issue by Perseo2499** [Fate-Grand-Automata/FGA#1053]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1597

### Describe the bug

For any reason, when I start the app into the game, FGA won't follow the command that I structured in the command section. Also, when It arrives to the support servant select screen, It won't select any servant, getting stuck at that screen. 

### Video

https://youtu.be/W-7H4NFKZ1M

### Device model

Xiaomi Mi 9T pro

### Android version

12

### Screen size

2340x1080

### RAM

8GB

**Comment by reconman** [comment]
Remove the notch from FGO in your system settings.

**Comment by Perseo2499** [comment]
I did it. But even so, the problem remains...

**Comment by reconman** [comment]
You did before or after the video?

**Comment by Perseo2499** [comment]
I made some tries. In the video is working without the option enabled, but as I said, I tried with it enabled. I can uploud another one if it,s required

**Comment by reconman** [comment]
Please go ahead.

**Comment by Perseo2499** [comment]
Okey, here it goes. 

This time, the option is enabled. 

It looks like  FGA can recognize the layers but it won't follow the command you can see at the firts moments of the video and, when it arrives to the support selection screen, it stucks...

The video is [here](https://youtu.be/hDmBaQm51l4)

**Comment by reconman** [comment]
There's still a notch? Even though you changed FGO's notch settings?

Because as long as that black bar stays there, the current version of FGA won't work.

**Comment by Perseo2499** [comment]
Oh, sorry. I think I didn't understand you from the start. My device do not have a notch, so is a fullscreen device. The blank lines you see are the margins of FGO, not the notch of my phone. I used FGA in other moments and it worked well in the past with the same device, but a few days ago, when  I decide to reinstall it, it showed this problem.

**Comment by reconman** [comment]
I looked it up and indeed it's normal for FGO to show black borders on screens wider than 21:9.

Can you post a screenshot of FGO? I need to measure the black bars.

**Comment by Perseo2499** [comment]
Yes.
![photo_2022-01-02_02-19-33](https://user-images.githubusercontent.com/53657268/147863658-a5fca14e-de1e-4e68-a5de-1c01aebb68d4.jpg)

**Comment by reconman** [comment]
I miscalculated, your phone has a 19.5:9 screen ratio. The black bars shouldn't be there.

Here's one example of another user with the exact same resolution where the black bars aren't present: #1011

**Comment by Perseo2499** [comment]
Oh. In that case, what should I do to fix te error?

**Comment by reconman** [comment]
You'll have to play around with your system settings until they disappear. Did anything change since you last used FGA successfully?

**Comment by Perseo2499** [comment]
Okey. Solved. 

I changed the gestural system to the normal buttons on the phone and then the black bars dissapeared. Eventually, the app started to work well. 

Thanks for the assistance :) 
 
p.d. I can't understand why that black bars appear with the gesture system and the app stops working, but It works, so no problem by the moment.
