### ISSUE TITLE
Buffs to servants on the 1st or 2nd slots during wave 2 get redirected to the 3rd slot servant.

### ISSUE THREAD

**Issue by octapusxft** [Fate-Grand-Automata/FGA#1054]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1597

### Describe the bug

After mentioning the issue on  the gamepress FGA thread I was advice to make a bug report here:

It seems than when I have servants like waver or Skadi buff the main dps servant during the second wave, they instead target the servant on the third slot.

Here is the command list for this  run. Somehow even though I input d1 and g1 (aka dantes) instead the result is d3 and g3 (support skadi)
![wrong buff target 1 commands](https://user-images.githubusercontent.com/62168059/147879967-3443255a-dc79-41d3-86bc-e567a4c9843a.jpg)

As a work around I have been setting the buff target (aka dantes) on the third slot for now and write a new command list. 
The same had also happened in the past when the buff target (space ishtar) was on the **second slot** and so I also had to move her to the third slot and write an appropriate new command list.

I hope this somehow helps you guys to make this amazing app even better.
I also include a recording

### Video

https://youtu.be/q--drKcLQW0?t=55

### Device model

Xiaomi Poco x3 pro

### Android version

11

### RAM

8GB

**Comment by reconman** [comment]
Check if you have Skill Confirm enabled in FGA. Should be disabled.

**Comment by octapusxft** [comment]
> Check if you have Skill Confirm enabled in FGA. Should be disabled.
I can confirm that this fixed it.
So this is something that should be disabled if the ingame confirmation is also disabled?
Thank you for the solution and sorry for reporting as a bug something that was just a lack of knowledge on my part.

**Comment by reconman** [comment]
Yes, it's disabled by default in FGA but enabled in FGO.

It's also part of the Troubleshooting guide regarding wrong skill usage.
