### ISSUE TITLE
Screen Capture Prompt Flicker/Freeze

### ISSUE THREAD

**Issue by catnapcat** [Fate-Grand-Automata/FGA#1055]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1597

### Describe the bug

I tried to move FGO and FGA stuff to Bluestacks 5. So, I redownloaded FGA onto Bluestacks 5. I gave it the permissions it asked for, and when I tried to press the 'Start Service' button, the prompt kinda freezes/flickers, at which point pressing any button just makes the prompt flicker more. 

I'm not sure which version of Android I'm running on here. It's the 32-bit Nougat one, which I _think_ is 7.

### Video

Before:
![2022-01-02](https://user-images.githubusercontent.com/96456481/147883659-3ef0ce92-4120-436a-9880-053d5e2fcfe2.png)
After:
![2022-01-02 (1)](https://user-images.githubusercontent.com/96456481/147883666-471973d3-d848-4e90-a268-a093a21e242f.png)

### Device model

Bluestacks 5.5.10.1001

### Android version

7

### Screen size

1920x1080

### RAM

4GB

**Comment by reconman** [comment]
Read the Bluestacks part of the troubleshooting guide.

**Comment by catnapcat** [comment]
![2022-01-02 (2)](https://user-images.githubusercontent.com/96456481/147884156-10ef9071-92be-4c0f-9c13-6ec3b6923a5d.png)
Trying portrait mode doesn't work, either.

**Comment by catnapcat** [comment]
Issue fixed, needed to change graphics settings.
