### ISSUE TITLE
Detect Stunned Cards

### ISSUE THREAD

**Issue by saiyan11** [Fate-Grand-Automata/FGA#1059]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

It seems fga doesn't differentiate between normal cards and stunned cards, and sometimes it selects stunned cards while there were non stunned cards available.
I wonder if this can be implemented.

PD: Thanks with your amazing work with this project!

**Comment by reconman** [comment]
Can you provide a video? Afaik this should already work.

**Comment by jcdeoferio** [comment]
FGA isn't able to detect the servants affected with Oberon's Eternal Sleep debuff. Should I add a separate ticket for eternal sleep?
