### ISSUE TITLE
App Crashes when pressing start button

### ISSUE THREAD

**Issue by ahernandezr05** [Fate-Grand-Automata/FGA#1061]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1599

### Describe the bug

Using Bluestacks 5 x64 (Yes, I know guide says use 32bits, but it was working this last event with a 64bits stance).
When I press the start button on the friend select screen, FGA crashes, the play button dissapears and I have to either restart emulator or force stop on FGA.
Was working fine until now.

### Video

Cant apply cause it does not reach the script.

### Device model

Bluestacks 5 64bits

### Android version

7

### Screen size

1600x900

### RAM

4

**Comment by ahernandezr05** [comment]
It just solved on its own (second time an issue solves itself) dunno if I shuold leave this open or just close it.

**Comment by reconman** [comment]
FGA is unstable in 64 bit, don't use it.
