### ISSUE TITLE
If runs are set to a limit app ignores it and repeat losing the script

### ISSUE THREAD

**Issue by Alucardan2** [Fate-Grand-Automata/FGA#1062]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1599

### Describe the bug

Currently JP has no issues but then again there is no event for me to test. These test are on NA

After the new update the app no longer stops run if you choose a set number, it will select repeat and pick a support either the right one or not.

Set two tests.

### Video

https://youtu.be/IyRa3mLP2XI

https://youtu.be/SseRjiRvauE

### Device model

Xiaomi redmi note 10s

### Android version

11

### Screen size

1080x2400

### RAM

6GB

**Comment by Alucardan2** [comment]
Decided to do more tests and so far it seems to affect the event runs only.

**Comment by Alucardan2** [comment]
New tests: did free quest in old parts and is showing the same problems as shown in the event video. As of now I can't farm outside of the dailies

**Comment by reconman** [comment]
Did you play with min similarity by chance? FGA detects the "Repeat" button as "Retry" instead.

**Comment by Alucardan2** [comment]
> Did you play with min similarity by chance? FGA detects the "Repeat" button as "Retry" instead.

Hi, I don't know where to change that or even check

**Comment by reconman** [comment]
More Options -> Advanced -> Fine-Tune -> Similarity

**Comment by Alucardan2** [comment]
> More Options -> Advanced -> Fine-Tune -> Similarity

Amazing, yes it was that it was on 68%, don't remember ever changing but maybe my friend did. It is all working again. Thank you.

**Comment by Alucardan2** [comment]
As said above my similarity settings were wrong, system is working again.
