### ISSUE TITLE
question ?

### ISSUE THREAD

**Issue by QQHgenz** [Fate-Grand-Automata/FGA#1063]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

![Ảnh chụp màn hình 2022-01-06 193601](https://user-images.githubusercontent.com/94516873/148383925-6ec996b4-99f4-4342-bc33-2018822b1e70.png)
how can i delete this ?

**Comment by reconman** [comment]
Delete the file.
