### ISSUE TITLE
FGO CN update changed some kanji/moonrunes and card detecting is not working

### ISSUE THREAD

**Issue by Kyonyuu** [Fate-Grand-Automata/FGA#1064]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

1599

### Describe the bug

title...

### Video

https://youtu.be/6aWOS4UnL3A

### Device model

NOX 7.0.1.7

### Android version

7

**Comment by sunbqxyz** [comment]
if you have read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting), you should notice that FGA could not work at the latest NOX, and you are suggested to change the verson or using other Emulators

**Comment by Kyonyuu** [comment]
> if you have read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting), you should notice that FGA could not work at the latest NOX, and you are suggested to change the verson or using other Emulators

it's not the latest nox, which actually even the newest nox update works just fine, i tested every version but decided to stay on 7.0.1.7 cuz was the safest version.

and the bug is made by the newest cn update not nox, nox works just fine with FGA, i recomend you to test it yourself.

**Comment by sunbqxyz** [comment]
> > if you have read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting), you should notice that FGA could not work at the latest NOX, and you are suggested to change the verson or using other Emulators
> 
> it's not the latest nox, which actually even the newest nox update works just fine, i tested every version but decided to stay on 7.0.1.7 cuz was the safest version.
> 
> and the bug is made by the newest cn update not nox, nox works just fine with FGA, i recomend you to test it yourself.

Okay, you are true, i also failed in the color scaning while im using Mumu with andriod9. But compared with your video, the soft seems determined the right character (with green box) but fails at the color. Maybe there are some changes.

**Comment by Kyonyuu** [comment]
after reseeing my old sents issues videos i know what happened, like what i said they changed the kanji and moonrunes, making them "smaller" but it can also be because i changed the resolution for recording... but even after analising for about 5 minutes, i just see it became smaller... i would have to ask my friend if he has his old recordings... and asking to record or take a screenshot so i can analise...

**Comment by Kyonyuu** [comment]
i thought it was my resolution setting and my friends didn't had a screenshot b4 the update but here it is:
Before Update:
![before update](https://user-images.githubusercontent.com/55859937/148859591-3a0288f2-ee43-47dd-915e-2206a9bf0c1b.jpg)
After update:
![After update](https://user-images.githubusercontent.com/55859937/148859626-0521c664-10fe-4d45-8b77-1c32b0e17812.jpg)

**Comment by Kyonyuu** [comment]
as you can see the letters changed a little...(literally what i said at the title...) just enough to glitch FGA(pic got from a bilibili channel, same resolution, same device etc etc...)

**Comment by NepPure** [comment]
This problem still exists, do you need help with screenshots or videos?

**Comment by reconman** [comment]
I was hoping someone playing the CN version would appear who can take the necessary screenshots and directly test the changes.

I need a video with debug rectangles so I can take proper screenshots. The video in the first comment doesn't have them enabled.

**Comment by reconman** [comment]
Can you check if this build fixes the problem? https://github.com/Fate-Grand-Automata/FGA/suites/5819430630/artifacts/195003536

**Comment by NepPure** [comment]
Everything works fine, thanks!
