### ISSUE TITLE
Combine preferred servants/ces and Friend selection

### ISSUE THREAD

**Issue by jcdeoferio** [Fate-Grand-Automata/FGA#1065]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Since JP has up to 3 support lists now, using a friend support has a chance of not getting the preferred servant you actually want to use.

**Comment by MathewSachin** [comment]
I think we should we just have a single Preferred mode which allows setting friends, servants and CEs.
