### ISSUE TITLE
How can I download an older version than 1599

### ISSUE THREAD

**Issue by Alucardan2** [Fate-Grand-Automata/FGA#1066]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

I am currently using the 1599 version, it can finally np chain properly when before you got a type card error. Now though you can't have continuous runs because it loses script in the second one or pick a different support. This was tested and already opened a case.

Where can I get the versions before 1599

**Comment by reconman** [comment]
Builds are available at https://github.com/Fate-Grand-Automata/FGA/actions/workflows/ci.yml?query=branch%3Amaster for a limited time only.

Each build has artifacts listed at the bottom, one of which is a zip file containing the APK.

They're kept for 2 weeks.

**Comment by Alucardan2** [comment]
Got assistance and found the issue. It was the similarity value, it was wrong

**Comment by Alucardan2** [comment]
> 

Thanks again, and sorry for any inconvenience. The app is doing wonderful, I will test it again once I get ap
