### ISSUE TITLE
Free quest farming: worked until sunday

### ISSUE THREAD

**Issue by Alucardan2** [Fate-Grand-Automata/FGA#1068]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Hello, I am having a bit of an issue, I was farming free quest for first time rewards setting the FGA to 3 runs per quest and moving to the next after.

It was working without issue last time this Sunday, today I did the same but found that after one run it stays still. It doesn't count runs or repeat. 

Is anyone having this issue

**Comment by reconman** [comment]
Don't use questions for reporting problems. A video with debug mode is needed.

**Comment by Alucardan2** [comment]
A ok, will do so when I have ap. Just wanted to know if it was normal. Will close this
