### ISSUE TITLE
a way to not use the same servant cards repeatedly.

### ISSUE THREAD

**Issue by Kyonyuu** [Fate-Grand-Automata/FGA#1069]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

see the screenshot for example:
![Screenshot_20220111-173006](https://user-images.githubusercontent.com/55859937/149016594-24fda056-7357-45d7-b64e-3780a82f7efc.png)
following the way FGA works the script would use buster from heracles then buster and then arts from nightingale, it's fine in case of only one enemy on the screen but 3 or more will make the script lose time on the next turn and so on, bones nodes doesn't have a need to use skills or np and the use of any actually is just losing time.

my idea is very simple, following my idea would make the script do heracles buster then nightingale buster and then cu alter or in other different way but i think being more complex would make the script hit with nightingale buster then heracles buster and then nightingale arts but it actually looks way more complex to me.

i thought of it because it actually helps in 3 cases.
1. after np spam and the enemy always has a chance of surviving with just a litle HP and you don't want do a brave chain(common case for F2P buster and quick meta).

2. or the case where there's 2 enemies that survives with little HP(also very common on F2P buster and quick meta).

3. Fuyuki nodes to farm bones saving time for not doing brave chain for no reason.

**Comment by AKSoo** [comment]
Card Priority → Brave Chains → Avoid

And yes, FGA does need better documentation.

**Comment by Kyonyuu** [comment]
> Card Priority → Brave Chains → Avoid
> 
> And yes, FGA does need better documentation.

well, it worked, i think(fga on CN server is bugged card detecting is broken, can't do anything, it literally just keep selecting the first 3 cards but worked) now every bone node is literally 1minute and 3 turns, anyway ty.
