### ISSUE TITLE
FGA Doesn't Work on Fold Cover Screen

### ISSUE THREAD

**Issue by pristine-estimate** [Fate-Grand-Automata/FGA#1072]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1599

### Describe the bug

Using FGA on the inside (unfolded) screen of the Fold 3 works perfectly fine. However, it does not work when the phone is closed, and the app is used on the outside screen. I've tried using Xperia and Duo game modes, and have also tried fully uninstalling and reinstalling FGA on cover screen only. Have also tried restarting both FGO and FGA on the cover screen only. The debug video shows that FGA is searching the wrong places to find images. I've also tried enabling and disabling notch calculation as well.

I found some reference to the cover screen being unusable by @Pycorax in this thread: https://github.com/Fate-Grand-Automata/FGA/issues/1000

However, the option they're talking about only affects the main (unfolded) screen. Using "App Default" as per that post makes FGA work on the unfolded screen, but has no impact on the outside (cover) screen.

### Video

https://youtu.be/9kkIAybSFLw

The script is supposed to run <<i h a 4,#>> but you can see in the video that it is attempting <<h g...>>

### Device model

Samsung Galaxy Z Fold 3

### Android version

12

### Screen size

2268 x 832 pixels

### RAM

12

**Comment by Pycorax** [comment]
I would like to indicate that the issue I faced was on the cover screen. I did not test in the inner screen at all.

**Comment by pristine-estimate** [comment]
I found a way to make FGA work on the cover screen. In Settings -> Display -> Full Screen Apps, it's possible to force FGO to run at the full screen res, despite the aspect ratio. Doing so makes the game display the blue checkered pattern on the left and right side of the screen, instead of black bars, and FGA will recognize and work perfectly fine on the cover screen. This issue can be closed.

![Screenshot_20220121-102827_Settings](https://user-images.githubusercontent.com/97706742/150554906-43bd3f67-cc53-4553-ac96-ffe6a5b64e15.jpg)
