### ISSUE TITLE
Having Trouble when using FGA on Mumu Nebula Emulator (Could not Choose Folder)

### ISSUE THREAD

**Issue by a08381** [Fate-Grand-Automata/FGA#1075]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

1599

### Describe the bug

![MuMu20220117145549](https://user-images.githubusercontent.com/2505002/149721875-e9362569-f82e-4d3b-8e61-36cbd3a04fcc.png)
![MuMu20220117144747](https://user-images.githubusercontent.com/2505002/149721896-d52b4b5f-ff8f-40eb-b597-3f7f85111a5c.png)
![MuMu20220117145504](https://user-images.githubusercontent.com/2505002/149721902-5a7fbb81-2270-4b5a-b2d9-3debcdc554b3.png)
![MuMu20220117145512](https://user-images.githubusercontent.com/2505002/149721904-09377851-fcdf-4b5e-a027-9ce891dac5ca.png)

### Video

.

### Device model

Mumu Nebula 7.0.0.11

### Android version

7

**Comment by reconman** [comment]
Choose "Show internal storage" and then tap the 3 lines in the top left.

**Comment by a08381** [comment]
> 选择"显示内部存储空间"，然后点按左上角的3行。

It looks just the same.
![MuMu20220117145955](https://user-images.githubusercontent.com/2505002/149722420-2e1f7fe0-8927-47cf-8e4d-78a12e8c200e.png)
![MuMu20220117145959](https://user-images.githubusercontent.com/2505002/149722432-89cb875b-7d15-4b5d-ad78-2d1c77f32930.png)

**Comment by reconman** [comment]
This is how it normally looks.

We can't help you with this issue as we only support Memu and Nox officially.
