### ISSUE TITLE
Support Image Maker button is missing

### ISSUE THREAD

**Issue by MHXA** [Fate-Grand-Automata/FGA#1080]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1608

### Describe the bug

So... the button is missing. Or you guys moved it to somewhere else?

![Screenshot_20220121-033400_FateGO JP](https://user-images.githubusercontent.com/68960050/150418272-6c37a184-f95a-4bf0-806a-3a334ae19ef3.jpg)

### Video

Since i can't record using FGA in the pop-up and 3rd party screen recording is not working, so yeah only SS i can show right now. Sorry

### Device model

Samsung a20s

### Android version

11

### Screen size

1560×720

### RAM

3GB

**Comment by reconman** [comment]
The button should still be there, works on my machine.

The support screen is handled fine when you start quests, right?

**Comment by MHXA** [comment]
@reconman yes, there is no problem when selecting support

**Comment by MHXA** [comment]
@reconman no, its stopped when selecting support

**Comment by reconman** [comment]
Can you provide a video?

**Comment by MHXA** [comment]
@reconman 
Here it is. https://youtu.be/eRz2WVxpHwI
