### ISSUE TITLE
Card selection fails for buffed non-support servants

### ISSUE THREAD

**Issue by Jeff-M-Hsu** [Fate-Grand-Automata/FGA#1082]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1609

### Describe the bug

Basically the same behavior as #1076 .

After reaching a certain number of buffs on a non-support servant, their face cards stop being selected. You can see that it works fine on the second wave, but as soon as she gets the additional buffs for the third wave it avoids her cards.

I have servant priority set with her first, as well as card priority set to WA/WB/WQ as the highest.

```
{
    "card_priority":"WA, WB, WQ, B, A, Q, RB, RA, RQ\nWQ, Q, WB, A, B, WA, RB, RA, RQ\nWA, WB, WQ, RB, RA, RQ, B, A, Q",
    "use_servant_priority":true,
    "autoskill_name":"JArcher Casgil loop",
    "support_pref_servant_list":[
        
    ],
    "support_skill_max_1":true,
    "support_skill_max_2":true,
    "support_skill_max_3":true,
    "support_pref_ce_mlb":true,
    "autoskill_party":"-1",
    "auto_skill_rearrange_cards":"F,F,F",
    "autoskill_support_class":"Caster",
    "spam_x":"[{\"a\":[{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"}],\"b\":{\"a\":[1,2,3],\"b\":\"None\"}},{\"a\":[{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"}],\"b\":{\"a\":[1,2,3],\"b\":\"None\"}},{\"a\":[{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"}],\"b\":{\"a\":[1,2,3],\"b\":\"None\"}},{\"a\":[{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"}],\"b\":{\"a\":[1,2,3],\"b\":\"None\"}},{\"a\":[{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"}],\"b\":{\"a\":[1,2,3],\"b\":\"None\"}},{\"a\":[{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"}],\"b\":{\"a\":[1,2,3],\"b\":\"None\"}}]",
    "support_pref_ce_list":[
        "Chaldea Teatime.png"
    ],
    "servant_priority":"1,2,3,4,5,6\n1,3,2,4,5,6\n1,2,3,4,5,6",
    "auto_skill_brave_chains":"Avoid,None,None",
    "autoskill_cmd":"df1x21i1hgefdcba4,#,4,#,j64"
}
```

### Video

https://www.youtube.com/watch?v=yFl6KFWk3Uk

### Device model

OnePlus 6

### Android version

11

### Screen size

2280x1080

### RAM

8GB

**Comment by reconman** [comment]
Can you please also share your battle config json file?

**Comment by Jeff-M-Hsu** [comment]
> Can you please also share your battle config json file?

Updated.

**Comment by reconman** [comment]
Servant Priority is malfunctioning because of the buffs.

In build 1611 I already adjusted it a bit, but still won't be enough for JP.

What happens if you disable Servant Priority?

**Comment by Jeff-M-Hsu** [comment]
It's able to randomly select Jeanne's cards with it disabled

**Comment by reconman** [comment]
Finally fixed by moving the face detection area further up.

Sorry it took so long.
