### ISSUE TITLE
How do i get it to start farming?

### ISSUE THREAD

**Issue by Paragon7667** [Fate-Grand-Automata/FGA#1083]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

When I entered a node and pressed the play button a screen popped up asking me to set parameters such as AP refilling and the like but when I finished setting that up it didn't let me hit "ok". What am I doing wrong?
![Screenshot_20220126-141220_FateGO](https://user-images.githubusercontent.com/74631123/151179706-8194f606-b834-40ff-985a-b3a721869b34.jpg)

**Comment by reconman** [comment]
Have you watched my Youtube video?

**Comment by Paragon7667** [comment]
I must have missed the video I'll check it now, sorry for wasting your time
