### ISSUE TITLE
Can't click ok

### ISSUE THREAD

**Issue by mmoyneur** [Fate-Grand-Automata/FGA#1084]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1611

### Describe the bug

I click the play button but i cant click ok 
![Screenshot_20220129-111114](https://user-images.githubusercontent.com/85810528/151674417-dd48a066-d35d-4b04-b1f6-accffc0bffbe.png)

### Video

What

### Device model

Pixel 4a

### Android version

12

### Screen size

Idk

### RAM

64gb

**Comment by the3dsandwich** [comment]
Did you, uh, setup any configs for FGA to use?

**Comment by reconman** [comment]
Watch my youtube video in the readme.
