### ISSUE TITLE
Play button disappears when starting Fate/GO

### ISSUE THREAD

**Issue by Ziegus** [Fate-Grand-Automata/FGA#1085]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2.25.0

### Describe the bug

Play button disappears as soon as the Fate/GO app starts. Clearing the cache of both FGA and Fate/GO do not seem to do anything. Likewise, restarting the phone completely doesn't fix the issue either.  The play button sticks around outside of Fate/GO as well. If I'm in any other app in landscape mode the play button will be there fully clickable. It's not until I load up Fate/GO that it disappears. 

Force stopping the apps will allow me to replicate the play button disappearing. If I close Fate/GO and reopen the app with FGA on the button will not appear again in Fate/GO until I force stop both programs. 

Side note, it was working perfectly fine for me two nights ago. I used FGA before I went to sleep to grind out my AP but when I woke up the next morning it became unusable. 

### Video

https://user-images.githubusercontent.com/98697988/151705220-8f557320-2d9a-48ab-ae7a-8c466a115575.mp4

### Device model

Samsung Galaxy S20 FE 5G

### Android version

12

### Screen size

1080x2400

### RAM

6gb

**Comment by reconman** [comment]
Probably battery optimization or Samsung's gaming mode

**Comment by Ziegus** [comment]
I don't know if there is another one but I have Game Launcher disabled and Game Booster is force stopped. As for battery, I have both Fate/GO and FGA set to Unrestricted.

**Comment by Ziegus** [comment]
> Probably battery optimization or Samsung's gaming mode

Okay so even after my last reply this was indeed the issue. Apparently Samsung's gaming booster didn't turn off for me even when I force stopped it. It must automatically turn back on when I open Fate/GO. I noticed a notification that priority mode was enabled and after finding out how to turn this off it finally fixed my issue since priority mode will disable texts, calls, and any apps it deems unnecessary (like FGA).

**Comment by Dannycybart10** [comment]
consultation there is some tool to optimize and lower the graphics to the minimum to the FGO. something just like Real Racing 3 RR APK has. to modify the graphics
