### ISSUE TITLE
Collect valentine chocolate ce (give/get chocolate) 

### ISSUE THREAD

**Issue by runelt99** [Fate-Grand-Automata/FGA#1088]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

![Screenshot_20220205_105707_com aniplex fategrandorder en](https://user-images.githubusercontent.com/48949150/152635542-e2e48e9c-f698-45fa-adcd-5f257188b8fa.jpg)

Automatically give or receive chocolate depending on what screen user starts feature.

> Check if can see button is greyed out

> Click if not, if yes then stop program

> Skip story

> Repeat

Looked through 2 pages of is:issue and searched terms 'valentine ce' and 'receive chocolate'

**Comment by reconman** [comment]
Generally we don't really implement features which only work for single events.

It takes more time to implement this feature than to do it manually.
