### ISSUE TITLE
Script doesn't run at all

### ISSUE THREAD

**Issue by CapYuno** [Fate-Grand-Automata/FGA#1089]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1611

### Describe the bug

https://user-images.githubusercontent.com/86341130/152642135-f45e8bb8-b892-4405-990f-40b6a44a5715.mp4

As the video footage above, the script doesn't work I tried the trouble shooting but nothing worked for me. 

Device model: LG G7 ThinQ
Screen size: 2340x1080
Android Version: 10.0
RAM: 4GB

Idk what else I can do. 
It used to run fine #745 during this patch but I stopped playing a long while ago and now this new recent patch. It just won't budge at all. 

### Video

Not sure what else to say I tried looking through the trouble shooting and restarting and my old #745 but nothing idk what to do at this point. I tried removing all battery restrictions and apps that might restrict it. Still nothing.

### Device model

LG G7 ThinQ

### Android version

10

### Screen size

2340x1080

### RAM

4GB

**Comment by reconman** [comment]
The main issue here is that the black bars shouldn't be there.

Try https://www.lg.com/uk/support/product-help/CT00008356-20150886394771

Otherwise you have to measure the black bars and use the Custom Game Area Mode in the Advanced settings.

**Comment by CapYuno** [comment]
> The main issue here is that the black bars shouldn't be there.
> 
> Try https://www.lg.com/uk/support/product-help/CT00008356-20150886394771
> 
> Otherwise you have to measure the black bars and use the Custom Game Area Mode in the Advanced settings.

The script starts working but the skills are getting misclicked

**Comment by reconman** [comment]
Is it Skill Confirmation?

Otherwise provide a new video.

**Comment by CapYuno** [comment]
> Is it Skill Confirmation?
> 
> Otherwise provide a new video.

Ye skill confirmation

**Comment by reconman** [comment]
So everything works now?

**Comment by CapYuno** [comment]
> So everything works now?

No I'm telling you that the skill confirmation is what miss clicks

**Comment by reconman** [comment]
Skill confirmation is one of the most reported misconfiguration: https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting#uses-skills-on-the-wrong-servant-or-doesnt-use-skills-at-all

**Comment by CapYuno** [comment]
> Skill confirmation is one of the most reported misconfiguration: https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting#uses-skills-on-the-wrong-servant-or-doesnt-use-skills-at-all

Well that solves everything then
