### ISSUE TITLE
FGA not working

### ISSUE THREAD

**Issue by KatzeAuge** [Fate-Grand-Automata/FGA#1090]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA, JP

### FGA build number

1611

### Describe the bug

FGA doesnt detect the screen of my device, I tried ll possible options but it kept happening since the rework of display in FGO, wasnt able to use it since that day until now

### Video

![Screenshot_Fate_GO_2022-02-06-02-22-26-148](https://user-images.githubusercontent.com/87232936/152664567-3d5e48f1-e55a-4f4e-bca3-3649f91123d8.png)

### Device model

Redmagic 6

### Android version

11

### Screen size

1080x2400

### RAM

12GB

**Comment by reconman** [comment]
The black bar on the side is the issue. Try finding a system setting to influence that, otherwise use the custom Game Area mode in the advanced settings.

**Comment by KatzeAuge** [comment]
Since my mobile has no option to hide the navigation bar (the black bar on the side), I dont really know how the custom Game Area mode works, should I adjust on the left? Thanks a lot and sorry for the problems

**Comment by reconman** [comment]
If you measure the width of the game area in your screenshot above, it's 2274 pixels game and 126 pixels black bar.

Try setting left to 0 and right to 126.

**Comment by reconman** [comment]
Closing since there's no reaction.
