### ISSUE TITLE
Support unit issue 

### ISSUE THREAD

**Issue by Night1907** [Fate-Grand-Automata/FGA#1091]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Whenever it gets to the support screen it just stops. The battleconfig is set to first but it won't select anything

**Comment by Night1907** [comment]
So I'm just being thrown to the wolves? 

10/10 great service

**Comment by reconman** [comment]
It's not a question, it's an issue, which requires much more info. Fill out a bug report so we can start analyzing your issue.
