### ISSUE TITLE
No puedo crear scripts de batalla

### ISSUE THREAD

**Issue by Seph501** [Fate-Grand-Automata/FGA#1092]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1611

### Describe the bug

Cuando entro en la sección para crear el script y apretar en el +, se congela la pantalla, me aparece un mensaje que dice "la app dejó de funcionar" y solo puedo cerrar para volver a usarla.

### Video

https://youtu.be/aRt0d7jws9Y

### Device model

Huawei Y9s

### Android version

10

### RAM

4Gb

**Comment by reconman** [comment]
Why did you duplicate your issue in Spanish?

**Comment by Seph501** [comment]
Because I forgot to check the last one and my brother don't understand English haha
