### ISSUE TITLE
Ability to auto-add friends after battle / specifically choose non friends?

### ISSUE THREAD

**Issue by Sabagabu** [Fate-Grand-Automata/FGA#1093]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Hello, I'm looking to see if theres any option im missing to auto-add friends after battle? thanks. also, often times the tool clicks a skil by accident and wont close the prompt, is there something to do about it? many thanks!

**Comment by reconman** [comment]
Duplicate of #977

**Comment by Sabagabu** [comment]
I'm moreso asking since the option exists as said in 977, where do i find it?

**Comment by reconman** [comment]
977 is still an open feature request.
