### ISSUE TITLE
Wider screen issue

### ISSUE THREAD

**Issue by KainRose91** [Fate-Grand-Automata/FGA#1094]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Hey, sorry to bug all you folks but I have having a hard time getting FGA to run on the wider screen of the Google Pixel 6 Pro. I've tried diff servers both with the notch calculation and without to no avail. I tried my hand at the different game play area modes because when using debugging mode it appeared like the boxes are all shifted to the left a bit meaning the mystic code area isn't in the left most box. I tried all the game play area modes and on custom attempted to try and shit it more to the right to no avail. If anyone have some tips, suggestions, or ideas I would be grateful for the assistance.
 Any help would be greatly appreciated and if, by mistake, I have brought up an already resolved issue, then my apologies.

**Comment by reconman** [comment]
Can you report this as a bug please?

Some screenshots and videos would be nice.

**Comment by KainRose91** [comment]
Understood. Will do my best

**Comment by KainRose91** [comment]
Understood. Will do my best
