### ISSUE TITLE
Script stuck at get Reward screen

### ISSUE THREAD

**Issue by TableThetable** [Fate-Grand-Automata/FGA#1095]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA, JP

### FGA build number

1611

### Describe the bug

I have found problem that the script stuck at get Reward screen on NA.

I have try with many another screen solution but still failed.

Could you help advice on this ?
![Screenshot_20220204-230229](https://user-images.githubusercontent.com/99347964/153238029-a8e5cdc2-3ccf-4255-8e59-41162797b73d.jpg)

### Video

Attach the PIC
![Screenshot_20220204-230229](https://user-images.githubusercontent.com/99347964/153238468-b9b756e9-eb9b-4624-920f-dac48118a44f.jpg)

### Device model

Samsung Galaxy Note 9 & Note 10 Lite

### Android version

11

### Screen size

2200x1080

### RAM

6GB

**Comment by reconman** [comment]
I wasn't sure about this bug, I think they changed the displayed text and that's why it doesn't work anymore.

**Comment by TableThetable** [comment]
@reconman Then Is it possible to fix this issue ?

and How long it should be take ?

**Comment by reconman** [comment]
Was quite busy the past 3 weeks. I just fixed it by updating the image.
