### ISSUE TITLE
How do I stop my phone (android) from seeing the support images with the Gallery?

### ISSUE THREAD

**Issue by Konahrik13** [Fate-Grand-Automata/FGA#1098]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

When I use Extract Default Support Images and have them go into the Fate-Grand-Automata folder the images show up in my Gallery and I can't figure out how to have them not show up. I don't need to see them because they're just for FGA and they take up space in the Gallery. I'm sorry if it's really simple but I'm pulling my hair out with how annoying it is and google gives me answers that don't work or I don't want.

**Comment by reconman** [comment]
A .NOMEDIA file in Support should help. You can leave the content empty.

**Comment by Konahrik13** [comment]
That was it, thank you a ton.
