### ISSUE TITLE
Unexpected error : read failed :EISDIR(is a directory)

### ISSUE THREAD

**Issue by 2inchdestroyer** [Fate-Grand-Automata/FGA#1099]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1611

### Describe the bug

it is unable to pick the support servant

### Video

this also happens when i didnt record bt

https://user-images.githubusercontent.com/99825070/154316299-3a9eb28e-92d1-4db7-9627-ab3cb793343d.mp4

w

### Device model

oppo r17

### Android version

10

### Screen size

not sure(1080x2340)

### RAM

6GB

**Comment by 2inchdestroyer** [comment]
could you have instructions on how i can do the first one i am not very familiar

**Comment by reconman** [comment]
Just upload some screenshots from a file explorer like this ![Screenshot_20220216-181010.jpg](https://user-images.githubusercontent.com/12360257/154318729-c65d8b3d-42db-453c-971d-e614b50ee936.jpg)

**Comment by 2inchdestroyer** [comment]
![7b8b4b9c-0161-4ba6-8330-1aeaf4537c5f](https://user-images.githubusercontent.com/99825070/154319241-9af2cbbb-87d0-416c-9201-e8ff1f6f62c2.jpg)
![05bbd8ed-9500-4537-9cc9-eab03fd29860](https://user-images.githubusercontent.com/99825070/154319251-06135dc1-3299-4159-bcf0-7297379246ac.jpg)

like this?

**Comment by reconman** [comment]
Delete the extra Skadi folders, remove the support folder inside of "Skadi" and choose the parent folder of "support" in FGA.

In my case "Fate-Grand-Automata" was selected and contains a support folder with "servant", "ce" and "friend" folders inside.

**Comment by 2inchdestroyer** [comment]
thank for your quick replies
