### ISSUE TITLE
Getting stuck on party selection

### ISSUE THREAD

**Issue by Kotsin** [Fate-Grand-Automata/FGA#1100]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1611

### Describe the bug

When the app is trying to start the battle, it's getting stuck on the party selection screen. I know that it's an old bug in FGO and the app is supposed to handle it, but it doesn't. 

### Video

https://drive.google.com/file/d/1zBR6Ub0J1BJoMH-F2mrLch6SWoiSNhZA/view?usp=sharing

### Device model

Poco X3 Pro

### Android version

11

### Screen size

2400x1080

### RAM

8

**Comment by Puh00** [comment]
I also faced this issue when I used the emulators Nox and LDPlayer

**Comment by NoOneofConsequencePrime** [comment]
I found a temporary fix to this by clearing "party selection" to default, without the click after selecting support the battle seems to start properly (just remember to start with the correct party).

**Comment by BrutuZ** [comment]
Suggestion: FGA could work around this by going back and forth 1 party.

- Tap chosen party # 
- Tap right corner to go to next party
- Tap left corner to go to back to chosen party

**Comment by reconman** [comment]
@BrutuZ we already used that logic once but changed it to an image detection one later. Right now the bug only happens on a few devices where I don't know why.

**Comment by BrutuZ** [comment]
It's happening on BlueStacks 5 for me. Now I'm curious if it'd happen on my stand-alone device.

The way I see it, it's as OP pointed out, a FGO bug, not FGA's fault, it can be reproduced even if FGA isn't running, just tap any party dot and the start mission button becomes unresponsive. FGA could still workaround it the way we usually do when using the _skip to party_ dots manually.
