### ISSUE TITLE
Brave chain without NP

### ISSUE THREAD

**Issue by decentblack** [Fate-Grand-Automata/FGA#1102]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Is there a way to have the script select brave chains if they are available, even if there is no NP to do this off of? Currently, it seems like the script only does this when there is an NP to brave chain off of.

**Comment by reconman** [comment]
There's Servant Priority, which should achieve the same result. It's in the Card Priority config options.

**Comment by decentblack** [comment]
Oh awesome, thanks.
