### ISSUE TITLE
Game area 

### ISSUE THREAD

**Issue by rinmokazi** [Fate-Grand-Automata/FGA#1122]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Is this an issue in Game area mode or because of something else? 
![Videoframe_20220303_105947_com.huawei.himovie.overseas.jpg](https://user-images.githubusercontent.com/90479866/156531470-6e6c8d3f-21d7-41b1-b9c3-382480e1535a.jpg)
the app was working fine in the last week but it stopped working from 2 days.
i have reset the phone settings and it worked fine yesterday and today it is not working so i reset the phone settings again and it started working.
can i get help please?

video
https://streamable.com/x12xs6

**Comment by reconman** [comment]
Since it only happens sometimes I'm guessing battery optimization is at fault.

Also report this as a bug please.
