### ISSUE TITLE
FGA selecting servant in pos 3 when it is supposed to select position 1

### ISSUE THREAD

**Issue by gearan** [Fate-Grand-Automata/FGA#1124]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1651

### Describe the bug

When skills are set to target the servant in position 1 the app clicks on the servant in position 3. Space Ishtar's second skill will also pick buster even when set to quick (again picking the left option over the right option). I also tried this in version 0.22.1 on the google store (the version I normally used until this bug). FGA also started tapping each servant at the beginning of wave 1 which it never used to do.

### Video

https://youtu.be/j8PP-CPtP5U

### Device model

xperia xz1

### Android version

8

**Comment by reconman** [comment]
It's not Skill Confirmation, right? Can you also share your battle config JSON file?

**Comment by gearan** [comment]
that was indeed the issue. It was on, probably one of my attempts to get it
to loop between nodes before it was not auto going into the next run. thanks
