### ISSUE TITLE
Detect bottom of support list

### ISSUE THREAD

**Issue by NoOneofConsequencePrime** [Fate-Grand-Automata/FGA#1130]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Is it possible to add a "scroll to bottom" feature in selecting support list? I believe this could be done just by checking the bottom pixels of the scroll bar (i.e. if it's white or not). This way, no extra time would be spent after scrolling to the end of the list.

![image](https://user-images.githubusercontent.com/74110977/158087194-35e9cf8d-7e33-44e6-9cca-73d4d6804ecb.png)

**Comment by d7c0** [comment]
This would be great
