### ISSUE TITLE
Selecting Wrong Servant

### ISSUE THREAD

**Issue by azeem400** [Fate-Grand-Automata/FGA#1132]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1651

### Describe the bug

I set Koyanskaya (servant 1) to give her buster buff to my Drake, who is servant 2, but FGA keeps giving the buff to servant 3, who is a friend Koyanskaya. I verified that I set the servant receiving the buff to be servant 2, who is my Drake. Any help? 

### Video

https://photos.app.goo.gl/HHzJo2Pny1kam9yWA

### Device model

OnePlus 9

### Android version

12

### Screen size

2400x1080

### RAM

8 GB

**Comment by reconman** [comment]
Is it Skill Confirmation as mentioned in the Troubleshooting Guide?
