### ISSUE TITLE
New update 

### ISSUE THREAD

**Issue by ghost** [Fate-Grand-Automata/FGA#1135]
### Preparation

- [ ] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [ ] My question isn't answered in any other issues (even the closed ones)

### Your question

I think because of the new update Fga not working . I am not sure but it seems they made full screen battle display (in jp) . As you know lottery event is going. I was about to farm today, just finished my 3T setup. Plz 🙏 update Fga ASAP . I really need it now as my exams are near.

**Comment by reconman** [comment]
Not a question, no bug details. Open a detailed bug report instead.
