### ISSUE TITLE
S22 Ultra - Game Area Detection Problem

### ISSUE THREAD

**Issue by Laecs** [Fate-Grand-Automata/FGA#1136]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

FGA Build:
1651

Problem:
Have tried the troubleshooting guide and adjusting settings / searching history but can't find specific information.

Ignore Notch Calculation: On
FGO is running full screen no black bars.
Game Area Mode: Default

Choosing support works perfectly but it is unable to work when the game loads in.
Doesn't use abilities / choose selections correctly. 
![FGO](https://user-images.githubusercontent.com/8679401/160235658-864ca3fc-46a0-4d5a-9e5c-302059e1fbee.jpg)
![FGO](https://user-images.githubusercontent.com/8679401/160236354-1931f05c-8c6c-4d21-bc65-322b3974a465.jpg)

Not sure how to configure the game area to work properly?

Android version
12

Screen size
3088 x 1440

RAM
12GB

**Comment by o76923** [comment]
Did you ever find a solution to this? I'm having the exact same issue.

**Comment by Laecs** [comment]
I did figure it out, was stupidly that the fight speed wasn't doubled, was slow and it fixed the whole thing.

**Comment by o76923** [comment]
Darn. I'm still getting boxes drawn in the wrong place. Out of curiosity, what are your camera notch settings (both in FGA and the phone settings)?

**Comment by Laecs** [comment]
I have "Ignore Notch Calculation" ON in FGA.
The phone setting is full screen, no notch.
