### ISSUE TITLE
FGO JP - Unable to make FGA recognize all of Dark Koya's ascensions

### ISSUE THREAD

**Issue by Trubothedwarf** [Fate-Grand-Automata/FGA#1144]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

As the title says, I am having trouble making images through Support Image Maker that allow FGA to recognize all of Dark Koya (aka Yami)'s ascensions. It is able to identify her Final Ascension artwork, but not her other artworks. I believe I have all the settings enabled on my phone to make FGA work in the first place, as it can pick the default support Servant options regardless of their ascension, the default CEs, and CEs I made as a test, such as the new bone, dust, and fang CEs.

I tested this by making images through Support Image Maker for each ascension form through the friend list, saving them as Yami/asc1, Yami/asc2, Yami/asc3, and Yami/asc4. Next I made a support setup that would only look for Yami supports regardless of what CE they had equipped or their regular and skill levels. When I ran it, it would scroll past every ascension other than the Final Ascension artwork.

As for phone information, I am using a Motorola One 5G Ace. I believe I have fixed all the relevant full screen and other app-related troubleshooting issues (e.g. notch, gestures) as I was able to get FGA to work properly during the lotto event JP recently had.

**Comment by reconman** [comment]
Open a bug report instead.

**Comment by Trubothedwarf** [comment]
Was in the process of doing so when I realized I was still using 1661. Not sure if updating to 1664 solved the problem or if I didn't continue to make mistakes using Support Image Maker, but the problem appears to have resolved itself. Have a good day.
