### ISSUE TITLE
Stuck on support screen 

### ISSUE THREAD

**Issue by tonyboii808** [Fate-Grand-Automata/FGA#1147]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1664

### Describe the bug

I'm not quite sure what is wrong, as I've just begun using the program. But it always gets stuck on the support screen and I couldn't figure out why. 

### Video

https://www.youtube.com/watch?v=8UxPF6iJHMo
ignore the garbage quality

### Device model

Galaxy S21 

### Android version

12

**Comment by reconman** [comment]
The black bars at the sides are at fault. Have you enabled full screen mode according to the troubleshooting guide?

**Comment by tonyboii808** [comment]
> The black bars at the sides are at fault. Have you enabled full screen mode according to the troubleshooting guide?

No, I did not. I don't see anything about full screen on the troubleshooting guide though.

**Comment by tonyboii808** [comment]
> > The black bars at the sides are at fault. Have you enabled full screen mode according to the troubleshooting guide?
> 
> No, I did not. I don't see anything about full screen on the troubleshooting guide though.
