### ISSUE TITLE
FGA not working

### ISSUE THREAD

**Issue by lehuydiep4** [Fate-Grand-Automata/FGA#1149]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1664

### Describe the bug

![image](https://user-images.githubusercontent.com/103415670/162803451-903331a1-5fd9-4aae-9bd8-3312239d637a.png)
![image](https://user-images.githubusercontent.com/103415670/162803476-6b818045-3a20-4966-98c0-3a77b4f96607.png)
After I set it up, I press the play button but nothing happens. I try Friend support list and friend point gacha but it didn't recognize too. After reading the issues, I think it is because of screen area so could I ask how to set custom screen area for my phone?
Ps: I don't know why but the play button appears on the screen even though I don't open fgo so is it a bug?

### Video

https://user-images.githubusercontent.com/103415670/162803533-b0508b89-6262-4a20-a29b-692836a497a2.mp4

### Device model

Xiaomi Redmi Note 11

### Android version

11

### Screen size

1080x2400

### RAM

6GB

**Comment by reconman** [comment]
Try https://github.com/Fate-Grand-Automata/FGA/issues/1053#issuecomment-1003651743

**Comment by lehuydiep4** [comment]
> Try https://github.com/Fate-Grand-Automata/FGA/issues/1053#issuecomment-1003651743

It's work, tks :)

**Comment by reconman** [comment]
Also, the play button should normally disappear in vertical mode.

Can't explain why you see it.
