### ISSUE TITLE
Script not recognizing screen properly

### ISSUE THREAD

**Issue by Redhed1224** [Fate-Grand-Automata/FGA#1151]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1664

### Describe the bug

Hello! 
There appears to be something very wrong with the the script's ability to recognize what's on screen both in the servant support selection and during battle. I've tried adjusting the game area myself with no luck.
I also fished around for a while and saw some old posts (saw issue #1041 brought up a lot) about similar issues but none of the fixes worked for me so I'm not sure what to do now. 
I've included a video along with some debug screenshots 
![Screenshot_20220415-140816 1](https://user-images.githubusercontent.com/103772298/163606288-710db372-d13b-429e-bd26-63e0830773ca.png)
![Screenshot_20220415-135944 1](https://user-images.githubusercontent.com/103772298/163606349-3d239c2a-2c7d-458b-b77c-ce0364220a67.png)
of what's happening for me and I'm playing on a Pixel 4A 5G with Android 12. It looks like the script is trying to hit the story skip button even though that option isn't turned on in the settings.
Please let me know if any more info is needed!

### Video

https://youtu.be/eMPrUySjo58

### Device model

Google Pixel 4A 5G

### Android version

12

### Screen size

1080 x 2340

### RAM

6GB

**Comment by reconman** [comment]
Seems to be this issue: https://support.google.com/pixelphone/thread/87047194/landscape-full-screen-apps?hl=en

If you can't find a way to make the black bar disappear, you will have to use Custom Game Area mode and measure the width of the black bars on a screenshot of FGO.

See https://github.com/Fate-Grand-Automata/FGA/issues/1000#issuecomment-1079900047 for hints.

**Comment by Redhed1224** [comment]
Turns out the gesture settings cause the black bars. I missed that part of the troubleshooting guide. 
Thanks for the help!
