### ISSUE TITLE
My fga doesn't have "support image maker".

### ISSUE THREAD

**Issue by ElongMa** [Fate-Grand-Automata/FGA#1152]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1664

### Describe the bug

my fga(1664) doesn't have "support image maker" even i tried deleting and reinstalling and rebooting but it's still the same

### Video

I dont have video
![image](https://user-images.githubusercontent.com/103820792/163669530-cb2c5049-9557-4997-8804-2dbcc7da9818.png)

### Device model

Vsmart Joy4

### Android version

11

### Screen size

1080x2340

### RAM

3GB

**Comment by reconman** [comment]
Well, how can FGA take support images if you're not on the support selection screen?

It's only enabled there and on your friend screen.
