### ISSUE TITLE
Does not select anything.

### ISSUE THREAD

**Issue by ShirouC** [Fate-Grand-Automata/FGA#1153]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1664

### Describe the bug

I'm not sure what is going on exactly, but the service simply does nothing. To clarify it runs fine in the app itself, but it doesn't click anything. It doesn't choose skills, supports or servant cards. 

### Video

I don't have a video. The service told me it could not record one. 

### Device model

Motorola G Stylus

### Android version

11

**Comment by reconman** [comment]
Last time the could not record error happened, battery optimizations weren't turned off. After setting FGA to "do not optimize", restart the Accessibility Service.

**Comment by ShirouC** [comment]
I've done as you advised and I still am getting the splash "Could not record video" as well as no response for any selections.

My phone runs Moto Game time by default. I'm going to see if disabling this fixes things since it also has a similar overlay to your application.

**Comment by ShirouC** [comment]
I've it does not seem to be impacted by the Moto Gametime app as I disabled it and it still does not record video nor does it select anything. I am unsure of what to do at this point, as the app used to work just fine.

**Comment by reconman** [comment]
When did it work the last time? Could you also try restarting your phone?

**Comment by ShirouC** [comment]
I'll give the restart a try. And this last worked for me about a month or so ago when I last used it to grind up EXP for a servant.

**Comment by ferr-o** [comment]
https://user-images.githubusercontent.com/103905843/163734774-8ffa5886-8ccd-463a-9086-4d68e01fc638.mp4
(lag only happened in the video, the game and FGA running just fine)

i don't know if the video be any help,
my phone is Redmi Note 8, Android 11, app version 1664
i have tried disabling Battery Optimization and MIUI Optimization, also.

**Comment by ShirouC** [comment]
Thank you for the video, this is actually exactly what happened to me. 

I had put FGO in Fullscreen, without the black bars, and had disabled battery optimizations, but after restarting the phone the service now works again, although I still cannot record video.

**Comment by idk6ro** [comment]
Simply enabling fullscreen for FGO fixed the issue of FGA not responding (or touching) anything for me. 

but when fullscreen is being disabled back for FGO, the FGA back to not responding again. I don't know why this is happening, but this temporary solution works for now.

**Comment by ferr-o** [comment]
oh, right. I tried enabling Fullscreen and now it worked.
sometimes the overlay didn't show up but re-enabling the accessibility option fixed it.
