### ISSUE TITLE
Preffered Support not working as intended

### ISSUE THREAD

**Issue by TheosGG** [Fate-Grand-Automata/FGA#1154]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1664

### Describe the bug

Displays an error "Couldn't open file for reading: [Servant] 'Skadi'"
FGA preffered servant selection is blank

Bluestacks 5 Emulator
3 Cores
4 Gigs RAM
Compatiblity mode on, Direct X
![image](https://user-images.githubusercontent.com/103876366/163705487-21262e1f-dc85-4bfa-b840-15751fc21e03.png)
![image](https://user-images.githubusercontent.com/103876366/163705493-bf10d34b-7f5e-4d21-b2ca-8373811df4c5.png)

### Video

https://user-images.githubusercontent.com/103876366/163705548-6480d211-6210-4c37-ba32-fd19a5b1738b.mp4

### Device model

Bluestacks 5

### Android version

7

### Screen size

1920x900

### RAM

4

**Comment by reconman** [comment]
![IMG_20220417_103723.jpg](https://user-images.githubusercontent.com/12360257/163707117-bc38a2ed-c834-498f-939e-80c1bb7f297c.jpg)

Try this

**Comment by TheosGG** [comment]
oh sweet it worked
tysm

**Comment by xiedwards22** [comment]
hey im having a silimar issue where i set skadi as the prefered and it scrolls past all the skadis and picks a random unit, playing in recon mode it seems to want to tap the refresh servants button but hits skill display and picks a random unit from there
