### ISSUE TITLE
FGA cannot detect Poco x3 pro screen on battle

### ISSUE THREAD

**Issue by lennine3** [Fate-Grand-Automata/FGA#1155]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1664

### Describe the bug

My FGA only work with friend summoning. It cannot use on battle mode

### Video

https://user-images.githubusercontent.com/83939832/163710545-68b9b1cf-4771-4688-9788-686715b61382.mp4

Battle screen

https://user-images.githubusercontent.com/83939832/163711785-f4dcc028-d4f5-4d0b-8247-dde1ae13e9e5.mp4

Friend selected

https://user-images.githubusercontent.com/83939832/163711834-f172c112-48bc-40ac-ac9c-2f5df34b654c.mp4

Friend summoning

### Device model

Poco x3 Pro

### Android version

12

### Screen size

1080x2400

### RAM

6GB

**Comment by reconman** [comment]
Try "Ignore Notch"

**Comment by lennine3** [comment]
> Try "Ignore Notch"
I had change Area game mode to default and use ignore notch. The selecting friend is ok but the battle screen still happend
here is the video:
https://imgur.com/a/35Qt1wT

**Comment by reconman** [comment]
Clicking in the top right opens a menu? Can you get rid of that somehow?

Other than that, everything looks good.

**Comment by lennine3** [comment]
> Clicking in the top right opens a menu? Can you get rid of that somehow?
> 
> Other than that, everything looks good.

After some adjust it work correct but it still open enemy detail at the start of battle.

**Comment by reconman** [comment]
Enemy detail?

**Comment by lennine3** [comment]
> Enemy detail?

You can see this video for detail
At 0:29 and 1:08
It only happen when I enable skip servant face check 
https://imgur.com/a/mP51ZMZ

**Comment by reconman** [comment]
That's the auto targeting feature.

![IMG_20220417_153143.jpg](https://user-images.githubusercontent.com/12360257/163716611-b4838c64-6b29-4c4e-806d-3b73704b60ed.jpg)

Or maybe you have a target command in your command list?

**Comment by lennine3** [comment]
> That's the auto targeting feature.
> 
> ![IMG_20220417_153143.jpg](https://user-images.githubusercontent.com/12360257/163716611-b4838c64-6b29-4c4e-806d-3b73704b60ed.jpg)
> 
> Or maybe you have a target command in your command list?

Oh yeah, it auto targeting feature.
Thanks your for the support, I'll close this issue.
