### ISSUE TITLE
GUDAGUDA

### ISSUE THREAD

**Issue by FedRif** [Fate-Grand-Automata/FGA#1156]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1664

### Describe the bug

The app keeps getting stuck at the supplies reward screen on the GUDAGUDA Final Honnoji rerun

### Video

I dont think its needed :)

### Device model

Bluestacks samsung galaxy S10

### Android version

10

**Comment by reconman** [comment]
Tested it, I'll remove the feature again once the event ends.

**Comment by FedRif** [comment]
Thank you so very much <3.
