### ISSUE TITLE
Cannot use skills

### ISSUE THREAD

**Issue by Minhieu** [Fate-Grand-Automata/FGA#1159]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1664

### Describe the bug

After selecting a skill, the ok button isn't pressed. On my old phone fga was working fine.

### Video

https://youtu.be/UFQ813QdduQ

### Device model

Redmi note 10 je

### Android version

12

### Screen size

1080x2400

### RAM

4gb

**Comment by reconman** [comment]
Skill Confirmation, it's part of the troubleshooting guide.
