### ISSUE TITLE
Please help me with custom area mode

### ISSUE THREAD

**Issue by GanganHJ** [Fate-Grand-Automata/FGA#1160]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Sorry to bother but I don't understand how calculate the number for the custom area mode please help me
![Screenshot_2022-04-24-16-07-36-192_com aniplex fategrandorder en](https://user-images.githubusercontent.com/75168566/164964443-155784e0-4de0-4103-9ac5-9cd191e39533.jpg)

**Comment by reconman** [comment]
I used Adobe Photoshop to measure the number of black pixels on the left and right. It's 158 left, 66 right.

**Comment by GanganHJ** [comment]
It works thanks man!

**Comment by reconman** [comment]
Depending on your phone, enabling 3 button navigation could get rid of the black bars. I have the same problem on my device right now.
