### ISSUE TITLE
Width must be positive error 

### ISSUE THREAD

**Issue by Bluetocho13** [Fate-Grand-Automata/FGA#1167]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1669

### Describe the bug

Upon reaching the friends screen to select a support I get the Error width must be positive, I've tried adding new pngs and resetting the script but nothing seems to work.
![Screenshot_20220429-115915](https://user-images.githubusercontent.com/104638978/165994063-62bc5017-cf78-482d-a110-6948c49a77de.png)

### Video

https://user-images.githubusercontent.com/104638978/165994021-110c143c-772f-41ac-97ad-e518f22ee648.mp4

### Device model

Google pixel 6 pro

### Android version

12

**Comment by reconman** [comment]
There's a report about this bug about once a year, I don't think anyone has found the cause yet.

**Comment by anyangpiggy** [comment]
I have same bug as him

**Comment by reconman** [comment]
Caused by corrupted support images.

Create a new empty support folder and configure FGA to use it. Then FGA should recreate the Support images. If not, press "Extract Default Support Images".
