### ISSUE TITLE
Support is not chosen

### ISSUE THREAD

**Issue by ShikigamiEXE** [Fate-Grand-Automata/FGA#1172]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1669

### Describe the bug

Game area mode is on "Xperia". For the video I turned on "the Ignore notch" option but it doesn't work if it is turned off either.
 
In the support screen the app doesn't pick the supports; it doesn't even try. It jumps straight into card recognition as you can see in the video. Once it is in the battle it functions without problems (ignore the scuffed run).

One obvious problem are the notches, left and right. Compared to say Samsung I can't find anything in Sony that would force fullscreen for FGO. I assume I could format the detection area in FGA settings to match with mine but I'm not sure what size I would have to choose for this.

### Video

https://drive.google.com/file/d/1Wqac0zK5lhl8cctcrk1YEN8YGxBtCBYz/view?usp=sharing

### Device model

Sony Xperia 5 II

### Android version

12

### Screen size

2520x1080

### RAM

8GB

**Comment by reconman** [comment]
Please check #1000 and try Custom Game Area Mode, I might remove Xperia mode since there's no consistent black bar behavior.

**Comment by ShikigamiEXE** [comment]
I checked that one and #845 before but neither provide a good starting point how to fine-tune the Custom mode to fit your device (hence the question of the size). 

Amateurish fiddling got me some reaction with L:34, R:50, T:0, B:0 but it only amounted to FGA scrolling through the support but not actually picking one or transitioning to battle. The same settings do not work within battle either.

![Screenshot_20220502-031909](https://user-images.githubusercontent.com/104730736/166173686-a013421d-e5a9-4b17-9264-ebedfbe177f0.png)
Here's a screenshot for the notch size.

**Comment by pios1028** [comment]
when i try open debug mode i see it just scan in the right of the screen and it cannot choice support in server NA. although it run pretty good on servers JP
![Uploading Screenshot_2022-05-06-22-25-53-93_577bcc70c040536a6d306ef99c704547.jpg…]()
It is my screenshot

**Comment by reconman** [comment]
How did you come up with those numbers?

You just needed to measure the width of the black bars on the sides. That's 63 pixels on the left and 189 on the right.

**Comment by reconman** [comment]
Closing since there's no reaction.
