### ISSUE TITLE
 Support list scroll offset for true full screen

### ISSUE THREAD

**Issue by kdoquero** [Fate-Grand-Automata/FGA#1173]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1669

### Describe the bug

Hello,
Thank you for your apk really useful.
I have one issue with it as at the support screen automata isn't able to scroll down the list as the target is off.
FYI beside the video record, my fgo is now in true full screen with no black bar at all, creating this offset.
I tried custom game area mode but from my understanding it's to offset the black bar pixels from the sides.

### Video

[support scroll issue youtube link](https://www.youtube.com/watch?v=RwB9-kLdNHYl)

### Device model

HTC U11+

### Android version

9

### Screen size

1440 x 2880 pixels, 18:9 ratio

**Comment by MathewSachin** [comment]
The 'true' full screen has been around for around a year now in JP and was already supported.
It looks like you've placed the PLAY button where it swipes to scroll. Moving it to the default bottom left position should work.

**Comment by kdoquero** [comment]
Make sense thanks you for your reply. Closing.
