### ISSUE TITLE
Refill Menu UI Change

### ISSUE THREAD

**Issue by vybze** [Fate-Grand-Automata/FGA#1178]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1675

### Describe the bug

With the 2500 download campaign on jp has introduced a new apple type which has increased the different apple types to 4, so it now requires scrolling to select bronze apples

### Video

![Screenshot_20220511-122051_FateGO](https://user-images.githubusercontent.com/32293918/167912942-f1075852-cb46-461c-8d79-2cbbb6b217aa.jpg)
![Screenshot_20220511-122032_FateGO](https://user-images.githubusercontent.com/32293918/167912951-07f31789-5f1c-4638-ba0f-acb9a6e36d07.jpg)

### Device model

Samsung Galaxy J7

### Android version

8

### Screen size

1280x720

### RAM

3GB

**Comment by jcdeoferio** [comment]
And the "blue" apples are actually called bronze. while the ones we used to call bronze are actually copper.

https://fategrandorder.fandom.com/wiki/Other_Items/Miscellaneous#Apples

**Comment by reconman** [comment]
The only question remaining is how to prioritize the apples if multiple are selected.. I would say bronze over copper since they have an upper limit.

**Comment by jcdeoferio** [comment]
I'd personally prioritize copper because the bronze ones are rarer. But there are indeed people that save the copper ones for their versatility, being able to top up just 10ap when you want to stop playing for the day. 🤷

**Comment by reconman** [comment]
I've implemented Bronze apple refilles in this build, but haven't tested it yet: https://github.com/Fate-Grand-Automata/FGA/suites/6800687647/artifacts/261184567

It should now scroll down to select Copper fruits. If no Copper fruits are available, it should scroll up again to select the rest of the fruits depending on the selected refill options.

Also, Bronze Apples only show up as refill option in the UI if the Game Server is JP.

**Comment by vybze** [comment]
> I've implemented Bronze apple refilles in this build, but haven't tested it yet: https://github.com/Fate-Grand-Automata/FGA/suites/6800793942/artifacts/261190438
> 
Tested both bronze and copper fruits for 2 hours and seems to be working pretty well. Wasn't able to test the scroll back up because I have too much copper fruits on hand.

**Comment by reconman** [comment]
I only noticed after my bug fix: NA messed up the translation of Copper. Let's see how long it takes them to fix it. Maybe 2 years.

**Comment by vybze** [comment]
Maybe during the next quality of life improvements were they implement the feature 1 year earlier than expected
