### ISSUE TITLE
Toggling the Service on a Galaxy Tab S8 Ultra causes inability to interact with top and bottom menus

### ISSUE THREAD

**Issue by Kurir** [Fate-Grand-Automata/FGA#1181]
### Preparation

- [ ] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

0.22.1

### Describe the bug

When turning on FGA, it blocks access to the menu/home/back button and the top bar dropdown, so I cannot switch apps or close FGA. I have had to use a bluetooth keyboard to access the power buttons to restart the device to get around this.

### Video

Because it stops me from accessing any other programs, I am unable to take a video of the issue.

### Device model

Samsung Galaxy Tab S8 Ultra

### Android version

12

### Screen size

1848 x 2960

### RAM

12GB

**Comment by MathewSachin** [comment]
Correct, that's the PlayStore version which is around a year old.
