### ISSUE TITLE
Spam section of the battle configuration

### ISSUE THREAD

**Issue by Dimastico** [Fate-Grand-Automata/FGA#1182]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Is it a feature or a bug that in this section, for the np there is no waves 3 and for the skil there is no waves 2 and 3?
![image](https://user-images.githubusercontent.com/49933780/168752760-bf4299ce-07de-40ab-bc69-f9905546f075.png)

**Comment by DAOWAce** [comment]
I'm seeing all the settings on my end in landscape.  Can't test in portrait (emulator).

Is it a bug with portrait mode?

**Comment by Dimastico** [comment]
Ok so its a bug with the portrait mode on my device, rip.
![image](https://user-images.githubusercontent.com/49933780/169306652-c4590566-ba0f-449b-8020-6dd72e0cb29a.png)
