### ISSUE TITLE
Free Quest runs can't continue

### ISSUE THREAD

**Issue by Alucardan2** [Fate-Grand-Automata/FGA#1183]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1675

### Describe the bug

With the Avalon and free quest 50% ap down I decided to go for all the free quest pending. What I did was set the fga to run 3 times and stop at first clear reward quartz. Did ALL of Heian Kyo free quest without problem until I started Avalon. In the video the fight ends but does not count as a run and just stays idle.

Yesterday it would count 1 out of 3 select the same free quest, the support and run again until all 3 runs were done and the quartz is awarded.

### Video

https://youtu.be/pNdcvJXSrGs

### Device model

Xiaomi redmi note 10s

### Android version

12

### Screen size

1080x2400

### RAM

6GB

**Comment by reconman** [comment]
Your play button is blocking the MENU detection, move ot to the bottom left.

**Comment by Alucardan2** [comment]
Ok, did as told and is working perfectly, what I don't get is why it was working the day before. Thanks
