### ISSUE TITLE
FGA kept scrolling and not selecting the support i set

### ISSUE THREAD

**Issue by aldren133** [Fate-Grand-Automata/FGA#1184]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [x] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1675

### Describe the bug

I've been using the same script before suddenly it just won't choose Skadi/any support i set before in the battle config

### Video

https://drive.google.com/file/d/1gGJelOT1nVnBdNcmujKUR0t5bxCD4RLR/view?usp=sharing

### Device model

Oneplus 8T

### Android version

12

### Screen size

2,400x1,080

### RAM

12

**Comment by hibikikuze4dan** [comment]
I think this is due to the addition of append skills changing how support servants show up for selection.

**Comment by aldren133** [comment]
I can't tell if there's any difference. Is there anyway to fix this tho? or do i have to resort to manual selection?

**Comment by squaresmile** [comment]
> I can't tell if there's any difference. Is there anyway to fix this tho? or do i have to resort to manual selection? Edit: yeah, it resolved it when I unselected lvl 10 option for Skadi's Skill 3

The append update changed the skill icons. You should be able to workaround this by setting FGA's server setting to JP.

**Comment by aldren133** [comment]
> > I can't tell if there's any difference. Is there anyway to fix this tho? or do i have to resort to manual selection? Edit: yeah, it resolved it when I unselected lvl 10 option for Skadi's Skill 3
> 
> The append update changed the skill icons. You should be able to workaround this by changing FGA's server setting to JP.

Ahhh alright thank you so much! :D

**Comment by Eyveen** [comment]
I keep having this issue too even if I downloaded the last version released two days ago.

**Comment by reconman** [comment]
@Eyveen There can be so many reasons and you haven't provided any info to find out which one it is.

You'll need to open a new bug report with a video.
