### ISSUE TITLE
My FGA acting weird ever since the new update

### ISSUE THREAD

**Issue by DelsinDG** [Fate-Grand-Automata/FGA#1185]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1675

### Describe the bug

I choose Skadi as prefered servant but sometimes it avoid choosing skadi and somtimes went to "Confirm Support Setup"

### Video

https://user-images.githubusercontent.com/106092048/169840862-1fdfbdca-b09f-4bfc-a2b5-edd5b099567c.mp4

### Device model

Samsung Galaxy A50

### Android version

11

### Screen size

1080×2340

### RAM

6GB

**Comment by Enfinit** [comment]
Might have to do with the append skill update. Have to wait for the app to get updated.

**Comment by arucastro** [comment]
try not selecting the skill levels, it worked for me, at least untill the new update it should do the trick

**Comment by reconman** [comment]
Fixed in latest version
