### ISSUE TITLE
I can't use FGA on full screen. 

### ISSUE THREAD

**Issue by a1m6adap** [Fate-Grand-Automata/FGA#1187]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Thank you for the apk, it work wonders.

I'm using a Huawei Y7 Pro, screen res 1520x720, Android 8.2

Apparently FGA doesn't work on full screen, idk why. It doesn't do anything. 
![Screenshot_20220525-021354](https://user-images.githubusercontent.com/69198181/170116715-662ef01b-fbc9-4e3a-b370-d89b656706b2.jpg)

FGA would operate normally if I don't stretch it with full screen, though it's somehow misaligned, like it's meant for a bigger screen. What should I do?

**Comment by reconman** [comment]
Try Custom Game Area mode with left=52 and right=183.

**Comment by reconman** [comment]
Did you try the steps from the Troubleshooting Guide?

- Open Settings app
- Go to Display & brightness > More display settings > Full-Screen Display
- Turn ON the switch for FGO
