### ISSUE TITLE
FGA no longer recognize skill lvl 

### ISSUE THREAD

**Issue by fred1357v2** [Fate-Grand-Automata/FGA#1188]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

FGA canary-1676

### Describe the bug

![image](https://user-images.githubusercontent.com/106231740/170210968-c98e7f04-13ba-4643-8de6-8f41e6d755a8.png)
FGA no longer recognize skill lvl because the devs changed the size of the icons

### Video

no video

### Device model

LD Player 4.0.73

### Android version

8

### Screen size

1920x1080

### RAM

4gb

**Comment by ngoccatt** [comment]
I think this issue has been mentioned, you may want to change the FGA server setting to JP and it may work while waiting for this function to be implemented in the next version of FGA for NA server.

**Comment by reconman** [comment]
It should already be fixed with the newest version. I need a video if you're really using 1676.

**Comment by fred1357v2** [comment]
> It should already be fixed with the newest version. I need a video if you're really using 1676.

it's now fixed i don't know what the problem was, but it was probably on my side, after i restarted the emulator it worked fine...
