### ISSUE TITLE
Ignores selected support 

### ISSUE THREAD

**Issue by Hally349** [Fate-Grand-Automata/FGA#1189]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1675

### Describe the bug

Since the append skill update whenever I am trying to auto farm with any servant (The attached Video I am trying to use Skadi) the FGA is scrolling past each one for no discernable reason

### Video

![Screenshot_20220525-081918](https://user-images.githubusercontent.com/106229701/170250480-023e7ab0-3a69-4917-a687-c3e1d865129b.png)

 [Video of Debug ](https://drive.google.com/file/d/1ZveRW9sU9j3VeuJPUoyWdfrTpcbhpVox/view?usp=drivesdk) 

### Device model

Google pixle 6

### Android version

12

### Screen size

412x915

### RAM

12GB

**Comment by reconman** [comment]
Update to 1676. Also your video isn't publicly available.

**Comment by Hally349** [comment]
Updated game version and is now fixed
