### ISSUE TITLE
Hide Icon

### ISSUE THREAD

**Issue by Hokumoku** [Fate-Grand-Automata/FGA#1190]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

I would like to suggest for adding "Hide Icon", This feature is effective for OLED Screen users, because if you displaying the same static image for a long time, the screen will get burn-in.

This feature will prevent burn-in to OLED screen due to Displaying the same static image for a long time.

**Comment by reconman** [comment]
Which static image are you talking about?

**Comment by Hokumoku** [comment]
The Start icon

**Comment by reconman** [comment]
First it only appears in landscape mode, second there's already a way to hide it. Expand the FGA service notification and press Stop.

**Comment by Hokumoku** [comment]
Uh sir, that will stop the entire service right? I've tried it.
I want the icon getting hide while the service running

**Comment by reconman** [comment]
Any reason why?

**Comment by skepsun** [comment]
> First it only appears in landscape mode, second there's already a way to hide it. Expand the FGA service notification and press Stop.

I pressed Stop and whole service was stopped, then nothing continued to work. I think a option for hiding icon while service is still running is important for preventing OLED's Burn-in.
