### ISSUE TITLE
Fga not picking supports

### ISSUE THREAD

**Issue by Hiraga1** [Fate-Grand-Automata/FGA#1191]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1575

### Describe the bug

Fga apps dash through the support page even if the support servant was there

### Video

Uploading received_429776865650606.mp4…

### Device model

Lg g8x

### Android version

11

### Screen size

2340x1080

### RAM

6GB

**Comment by reconman** [comment]
Not latest release.
