### ISSUE TITLE
Fail to press the skill

### ISSUE THREAD

**Issue by saikai26** [Fate-Grand-Automata/FGA#1196]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1676

### Describe the bug

Auto doesn't click skills and proceeds as normal like it does want to click where the np should be and stuff.

### Video

https://user-images.githubusercontent.com/106642178/171320964-67d7585d-2e19-4a65-9df8-2c6d8b736c61.mp4

### Device model

LDPlayer 4.0.81(32)

### Android version

7

### Screen size

1600x900

### RAM

6

**Comment by saikai26** [comment]
https://user-images.githubusercontent.com/106642178/171320887-bd48e761-62ab-45ed-8b13-ff15048a9dd7.mp4

**Comment by reconman** [comment]
That's Skill Confirmation and part of the Troubleshooting Guide.
