### ISSUE TITLE
FGA doesn't work properly

### ISSUE THREAD

**Issue by Minh150302** [Fate-Grand-Automata/FGA#1198]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

I updated my phone and it can't work. I read and found that my FGO screen is not fullscreen and FGA needs custom in Game Area Mode.
![Screenshot_2022-06-02-12-36-49-10_577bcc70c040536a6d306ef99c704547](https://user-images.githubusercontent.com/106725503/171560752-a6ffd30b-b42c-44cd-9785-7c3547f2b549.jpg)
.
Device model
Oneplus Nord 

Android version
OxygenOS 12.1 (Android12)

Screen size
1080 x 2400 pixels, 20:9 ratio

RAM
12GB

**Comment by reconman** [comment]
If the black bar is at the top, configure this to "Hide front camera" for both FGO and FGA.

![Screenshot_2022-06-02-08-17-21-57_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://user-images.githubusercontent.com/12360257/171565718-0adb8829-a9a9-424f-9368-c33e5d804869.jpg)

**Comment by Minh150302** [comment]
- [ ]

**Comment by Minh150302** [comment]
I changed to "Hide front camera" for both apps. However, the position skill is wrong (I use 3 skills of third servant but only 2.)
![Screenshot_2022-06-05-00-48-49-30_577bcc70c040536a6d306ef99c704547](https://user-images.githubusercontent.com/106725503/172019592-6aeafd58-c70d-448c-92fd-1057ac333b03.jpg)

**Comment by reconman** [comment]
Is the thick black bar on the top or bottom of the phone?

**Comment by reconman** [comment]
Also, please provide a video recorded by FGA.

**Comment by Minh150302** [comment]
black bar is on the top
video recorded : https://youtu.be/1Ac6x22r9_Q
![image](https://user-images.githubusercontent.com/106725503/172020912-a5c809fe-b046-4f65-81cf-9cd32449c5cc.png)
image for setting up skills

**Comment by reconman** [comment]
So hiding the camera doesn't seem to have any effect.

Your images are downscaled, so I can't tell you your Custom Game Area values for sure. Looks like left=123 and right=9.

By the way, I have a OnePlus 9 with Android 12 and FGO is displayed in full screen.

**Comment by Minh150302** [comment]
it is ok now, ty

**Comment by Mostoneman** [comment]
So I tried the Custom Game Area values above, and FGA still doesn't work., probably because my game area isn't exactly the same, so how do I get the right values?

**Comment by reconman** [comment]
@Mostoneman Take a screenshot and measure the black pixels.

**Comment by reconman** [comment]
On my phone I was able to get rid of the black bars by switching navigation mode to 3 buttons.
