### ISSUE TITLE
How to use on full screen

### ISSUE THREAD

**Issue by JohnArkam** [Fate-Grand-Automata/FGA#1199]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

![Screenshot_20220602-202354_Video Player](https://user-images.githubusercontent.com/90505629/171700491-7222d926-d924-409f-8bc2-2b8e5db6628f.jpg)
This a screenshot from the debug mode.
My phone is a Samsung A71 with a resolution of 2400×1080.
Sorry if its literally the most asked question but i'm having trouble getting the right settings. I have to use the custom area mode but i can't get it right (the screen should have a modifier of 130 from both right and left). It doesn't choose the support nor it does anything in battle.

**Comment by MHXA** [comment]
Go to More option -> advanced -> ignore notch calculation, i think.

**Comment by reconman** [comment]
You don't need custom game area mode. That's only if you have black bars on the sides.

**Comment by JohnArkam** [comment]
Thank you guys. But ignore notch does nothing and i tried the custom area mode since the other 3 don't work

**Comment by reconman** [comment]
I need a video with default game mode recorded by FGA.

**Comment by JohnArkam** [comment]
Ok i also tried recording with fga a notification appears saying "couldn't start recording" so...

**Comment by reconman** [comment]
@JohnArkam Can you test this APK? https://github.com/Fate-Grand-Automata/FGA/suites/6800203910/artifacts/261148559

You should be able to see more details on why it couldn't record your screen.

Please report back what your error message is.

**Comment by JohnArkam** [comment]
@reconman downloaded it and tried, still didn't record or do anything but it did say "failed media projection"

**Comment by reconman** [comment]
So FGA's MediaProjection is broken on your device somehow? Seems like FGA can't see anything to begin with.

Have you tried disabling battery optimization for FGA and restarting the phone?

**Comment by JohnArkam** [comment]
No, i will try now

**Comment by JohnArkam** [comment]
I did it, it works perfectly. I didn't now about the battery optimization since it wasn't adked the first times i used it.
Its going a little slowly, maybe because it was recording but it works great anyway.
Thank you very much for the help!
