### ISSUE TITLE
60 FPS Support

### ISSUE THREAD

**Issue by MHXA** [Fate-Grand-Automata/FGA#1200]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Well, please make it compatible with 60 FPS FGO

**Comment by reconman** [comment]
Where can you find that version?

**Comment by potchy** [comment]
It's a "better" version of FGO NA/JP with full wide screen support and 60 FPS, shared only in Rayshift.io Discord server.
It doesn't really affect FGA in any way and I've been using both together since like forever, so I don't know why it's not working for him.

**Comment by reconman** [comment]
I've added the package names so FGA detects NA correctly, it's in build 1684. Is there another issue with BetterFGO?

**Comment by MHXA** [comment]
@reconman its always stuck at support screen when i use 60 FGO. But, it works perfectly now, thanks dude
