### ISSUE TITLE
Doesn't auto select support, nor apply skills

### ISSUE THREAD

**Issue by Gatchu** [Fate-Grand-Automata/FGA#1201]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1676

### Describe the bug

Noticed none of the scripts works after a recent Android update (Android 12, May 5th Security Update), which I was using a previous build (15XX something). Decided to update to the latest build, still doesn't work. No longer selects the supports from list automatically (vid 1), nor use the skills properly. Instead clicks other parts in on screen (vid 2) 
It like all the detection boxes are off, or should be for a larger screen size? 

Additional notes:
- never used "Ignore notch" option) for previous build, and for vids
- latest build in vid, applied the "Hide front camera" to both FGA and FGO. 
- tried custom game area mode (left: 120, right: 50) and it works to a degree (but wont repeat another round). Noticed the detection boxes are still off in debugging mode (can provide additional vid if needed)
- additional screenshot to compare vid 2 commands 

### Video

https://user-images.githubusercontent.com/106885155/172021673-2613a5f9-666d-4b86-8841-71d550482ae6.mp4

https://user-images.githubusercontent.com/106885155/172021368-bdcdc966-5de1-44e5-8317-8c4b485caa66.mp4

![photo_2022-06-05_02-43-24](https://user-images.githubusercontent.com/106885155/172021373-524b790e-acf6-47ed-ae5b-d4c970723f29.jpg)

### Device model

OnePlus 8T

### Android version

12

### Screen size

1080x2400

### RAM

12GB

**Comment by Gatchu** [comment]
Noticed some of the other open issues (at current time) have similar issues related to detection. I considered adding on in the other tickets, but thought would be better to provide more details with a new ticket. 

Also, just wanna say thanks for the work on FGA, been using it for over a year and its such a tremendous timesaver. Really, thank you.

**Comment by reconman** [comment]
Similar to the user in #1198 all your videos and screenshots seem to be scaled down.

I'm guessing left=168 and right=64 for Custom Game Area mode.

Also it's weird how your FGA screenshot doesn't have a lower black bar but FGO does.

**Comment by Gatchu** [comment]
Those values work, thanks. 

And yea, never noticed that part until you pointed it out. 
I vaguely remember FGO used to be full screen too, up to the notch area but that might have been for an older build, tho I'm not sure anymore (after various android and game updates)

> Similar to the user in #1198 all your videos and screenshots seem to be scaled down.
> 
> I'm guessing left=168 and right=64 for Custom Game Area mode.
> 
> Also it's weird how your FGA screenshot doesn't have a lower black bar but FGO does.

**Comment by reconman** [comment]
On my phone I was able to get rid of the black bars by switching navigation mode to 3 buttons.
