### ISSUE TITLE
I accidentally deleted the images for the supports? How can I redownload them?

### ISSUE THREAD

**Issue by GAddict12** [Fate-Grand-Automata/FGA#1208]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

So I just got my phone factory reset recently and it ended up deleting all of my pictures including the ones for fag. How can I redownload them? When I reinstalled fga, the images didn't come with the app.

**Comment by reconman** [comment]
![Screenshot_2022-06-09-06-56-11-30_a3958233ae0a6cb82869d8ec995a3cb9.jpg](https://user-images.githubusercontent.com/12360257/172767505-d055dc73-f0ae-4dc8-8550-42f491599e25.jpg)

Second option here.

**Comment by GAddict12** [comment]
I still can't get the images for some reason

**Comment by reconman** [comment]
Try another storage folder.

**Comment by GAddict12** [comment]
That worked! Tysm
