### ISSUE TITLE
i cant use FGA on fullscreen

### ISSUE THREAD

**Issue by Katsura-123** [Fate-Grand-Automata/FGA#1209]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1691

### Describe the bug

I cant seem to use FGA on full-screen at all, it clicks random things like servant status or game booster tab but wont progress at all. And i dont know how to set custom game area 

### Video

https://user-images.githubusercontent.com/107233402/172985169-cf54f174-8839-4497-b006-175eb6ddb582.mp4

### Device model

Xiaomi Mi 11Xpro

### Android version

11

### Screen size

1080x2400

### RAM

8

**Comment by reconman** [comment]
It's not trandom, the problem is that it clicks on the hidden gaming tools.

Please disable that feature.

**Comment by Katsura-123** [comment]
> 

Still not working

**Comment by reconman** [comment]
Video?

**Comment by Katsura-123** [comment]
https://drive.google.com/file/d/10I0o4QVb96rHrNgjfa9S99vvmFvcDO7T/view?usp=drivesdk

**Comment by reconman** [comment]
"The video cannot be played", says Google Drive.

**Comment by Katsura-123** [comment]
https://youtu.be/TSoUJipsFs0

**Comment by reconman** [comment]
That's Skill Confirmation, turn it off in FGO or on in FGA.

**Comment by reconman** [comment]
Also, I have no idea how you can record videos, even though FGA always reports broken MediaProjection.

**Comment by Katsura-123** [comment]
Its working now thanks
