### ISSUE TITLE
App misses skill buttons, opens servant info instead, and then goes on as if the skills had been activated

### ISSUE THREAD

**Issue by CloudStriker94** [Fate-Grand-Automata/FGA#1210]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1692

### Describe the bug

The app's detection seems to be wonky. Support selection doesn't work at all, and when I go into battle it apparently tries to view the servant info first, but for my first servant slot it instead triggers their first skill, and then after viewing the info for servants 2 and 3 it goes on as if their first skills had triggered as intended. This of course leads to the entire setup failing entirely.

### Video

https://youtu.be/6rIJ9RBrI1Q

### Device model

Huawei P20 Lite

### Android version

9

### Screen size

1080 x 2280

### RAM

4GB

**Comment by reconman** [comment]
Both of your problems are addressed in the troubleshooting guide.

Get rid of the black border: https://github.com/Fate-Grand-Automata/FGA/wiki/Game-Area-detection#case-1-borders-around-fgo-are-black
Configure Skill Confirmation: https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting#uses-skills-on-the-wrong-servant-or-doesnt-use-skills-at-all

**Comment by CloudStriker94** [comment]
The black border is caused by the (correctly detected) notch, which according to the troubleshooting guide should be black. Skill confirmation is off both in Automata and the game itself.

**Comment by reconman** [comment]
No, FGA always misses the skill icons and since some FGO update the notch behavior changed where FGO uses the notch area on most phones. That's why FGA was changed to treat the notch area as game area.

**Comment by CloudStriker94** [comment]
Well, drat. Now it works, but I really don't like the notch not being black. Guess I'll have to turn it on for automata and off for when I play manually.
