### ISSUE TITLE
Stage counter is not detected correctly on TW

### ISSUE THREAD

**Issue by DeemSong** [Fate-Grand-Automata/FGA#1214]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

TW

### FGA build number

1701

### Describe the bug

The 1st turn is normal but FGA seem like cant perform normal after 1st turn, my Mushashi NP should open directly at 2 turn and clear enemies but FGA go for normal attack. This is on the Bluestack 5 emulator

### Video

https://youtu.be/tGRE6EbfUGA

### Device model

One Plus 5 

### Android version

7

### Screen size

1600x900

### RAM

4GB

**Comment by DeemSong** [comment]
![image](https://user-images.githubusercontent.com/107633305/174117406-5267a0b5-7b35-4ed8-aa32-6908c7283371.png)

**Comment by reconman** [comment]
Your graphical glitches are probably the cause.

**Comment by DeemSong** [comment]
> Your graphical glitches are probably the cause.
When playing is normal graphics 60 plus fps, I think is YT eat the graphics

**Comment by DeemSong** [comment]
> I also need debug rectangles to see the exact behavior.
> 
> Please record another video with that enabled setting.

Where to enable

**Comment by reconman** [comment]
![IMG_20220616_183041.jpg](https://user-images.githubusercontent.com/12360257/174120411-cb171cdb-2186-44de-809b-e3dde90b77b2.jpg)

**Comment by reconman** [comment]
Seems like the stage counters are not in the expected location, I'm going to check the coordinates for 16:9 screens.

**Comment by reconman** [comment]
The cause is a missing image in the TW folder.

@DeemSong, @akayukipierrot can one of you please provide a 720p image of the battle screen?

I need this in good quality:
![image](https://user-images.githubusercontent.com/12360257/174145306-251b4e55-59a6-4725-bca4-1c64f60c89d4.png)

**Comment by reconman** [comment]
@akayukipierrot That's 1600x900, can you set your emulator to 1280x720 for the screenshot?

**Comment by akayukipierrot** [comment]
![Screenshot_20220616-151548](https://user-images.githubusercontent.com/45522107/174147812-6b3c4171-3eac-4a39-8b2a-182a42031e86.png)
Right here

**Comment by yuanlk** [comment]
I have the same issue on Nox 7.0.2.9 too. It is indeed the stage counter problem since it behaves normally if I use [next turn in the same wave].

**Comment by reconman** [comment]
Can you test this build? https://github.com/Fate-Grand-Automata/FGA/suites/6967986069/artifacts/272186801

**Comment by reconman** [comment]
Can I see a debug rectangle video?

**Comment by akayukipierrot** [comment]
https://youtu.be/7nVEKhBUx8c

**Comment by yuanlk** [comment]
> Can you test this build? https://github.com/Fate-Grand-Automata/FGA/suites/6967986069/artifacts/272186801

This build cant seem to select the quest, I had to manually select the quest. The stage counter problem still persists but the [next turn in the same wave] trick still work.

Videos:
Next turn | c2i2d5,#,ab2h2l25,#,ge2fj25:
https://youtu.be/YP03wAvhVKg

Next turn in the same wave | c2i2d5,ab2h2l25,ge2fj25:
https://youtu.be/zJTi62U1f98

**Comment by yuanlk** [comment]
The first one is working, thx!

**Comment by DeemSong** [comment]
> Sorry, I named the file incorrectly.
> 
> Here are 2 builds: https://github.com/Fate-Grand-Automata/FGA/suites/6968734024/artifacts/272237218 https://github.com/Fate-Grand-Automata/FGA/suites/6969087253/artifacts/272256287
> 
> Please try the first one. If that doesn't work, try the second one.
> 
> The second one has some special code for TW stage counters based on the old code before @the3dsandwich's changes.

Can I ask how to use this?

**Comment by reconman** [comment]
I already released a new official version with the fix, no need to use those zip files anymore.
