### ISSUE TITLE
Support Screen not working 

### ISSUE THREAD

**Issue by Crescent07891** [Fate-Grand-Automata/FGA#1217]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1707

### Describe the bug

FGA does not do anything when the support screen gets pulled up. I can either start the script on the support screen or after a battle and both times FGA just stops acting on the support screen.

### Video

https://user-images.githubusercontent.com/107718579/174392764-40a27870-f23b-4b07-b297-28f5bff1455b.mp4

### Device model

Samsung S10

### Android version

12

### Screen size

~6.1 inches

### RAM

128GB

**Comment by Crescent07891** [comment]
Force Stoping the app made it work after rebooting the app and restarting the script on the support screen; however it still froze after the battle ended

**Comment by reconman** [comment]
Your play button is covering the top left, move it to the bottom left.

**Comment by Crescent07891** [comment]
I saw that in the troubleshooting and fixed it after I posted this but that didnt immediately fix the issue

**Comment by Crescent07891** [comment]
I accidentally took a screenshot while it was frozen and it seemed to fix the issue somehow. If it happens again I will open a new issue.

**Comment by reconman** [comment]
Also please double check battery optimization.

**Comment by Crescent07891** [comment]
Will do
