### ISSUE TITLE
Add scrolling when in Landscape in Card Priority when Servant Priority is enabled.

### ISSUE THREAD

**Issue by PatrickL546** [Fate-Grand-Automata/FGA#1218]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

I've feel kind of dumb when I realize that Servant Priority had an option because I always use FGA in Landscape. When I enable Servant Priority, I am not able to scroll down to see the option when in Landscape.

**Comment by reconman** [comment]
I wasn't able to add any indicator since scrollbars in Android are easy to implement. But now you can scroll.
