### ISSUE TITLE
Use skills on the wrong servant

### ISSUE THREAD

**Issue by ariesngo** [Fate-Grand-Automata/FGA#1219]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1707

### Describe the bug

It keeps choosing waver instead of arjuna when i use skills

### Video

(https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.youtube.com/watch%3Fv%3D5UZNbqFeIfY&ved=2ahUKEwixye7hqM_4AhUHl1YBHVoUCzQQtwJ6BAgKEAI&usg=AOvVaw2djcgIzcTRmG6y-tHJrI6N) 

### Device model

Galaxy J7 pro

### Android version

8

**Comment by reconman** [comment]
Is Skill Confirmation disabled in FGA?

**Comment by ariesngo** [comment]
Yes it was
But I just downloaded the latest version and it works perfectly now
Sorry for bothering you and thanks for creating such an amazing tool
