### ISSUE TITLE
Configs ignore "Next Wave" check, instead running commands for other waves in turns of incorrect wave

### ISSUE THREAD

**Issue by Jwguy** [Fate-Grand-Automata/FGA#1228]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1716

### Describe the bug

When using Battle Config and setting commands, you can designate that commands be separated by waves, with the card priority taking over when those commands run out for the current wave. Unfortunately, the program fails to actually determine whether it is the next wave or not.

For example, with the following setup:

![image](https://user-images.githubusercontent.com/16468732/177192875-03663724-8bdf-47f6-af4a-e3435e98dc74.png)

You would reasonably expect this to be interpreted as "Use Servant 1's second skill, then Servant 1's NP, then use card priority defaults until the next wave", at which one it'll begin using Servant 2's second skill and NP, and so on.

Unfortunately, the program instead skips the next wave check and instead just interprets each set of commands as part of turns in the same wave.

It does coincidentally work if the first set of commands clears the wave, as the second set will fire off in the next wave once it gets there, but not because the instructions are working as intended.

Incidentally, this also comes up because the Anniversary has released several limited time Master Goals, the notifications of which cause the program to not be able to use Noble Phantasms while they are ongoing, mostly because the click is far too high on the screen.

See the third mission in the video linked for proof.

### Video

[Youtube Video Upload](https://youtu.be/drAbKFGB80w)

The first two waves are fine, but the third wave shows the issue. 3:37 is the timestamp for the beginning of the issue, where Lancelot misses his NP because of the anniversary notifications

### Device model

Samsung Galaxy Note20 Ultra 5G 

### Android version

12

### Screen size

1280x720

### RAM

12GB

**Comment by reconman** [comment]
As you said, the cause are the Master Mission popups, which are included in the stage counter screenshot.

I don't think there's anything we should change in FGA since all missions will be completed in a few days.

**Comment by Jwguy** [comment]
Perhaps, and you're probably right that the master missions will be finished in short order, but while I might be more on the layman side when it comes to coding, it does seem to be that the expected course of order when the program can't determine if the wave has changed is to assume that it has not, rather than that it has, as we're currently experiencing.

It also means that this will be a repeating item that pops up any time a user completes several master missions at once. While it is unlikely that a user can complete the standard set in one farmable mission, it is still possible, and becomes more likely as the game continues to introduce more and more permanent bonus master missions, as well as limited ones during special events.

I think, at this point, that's all I can contribute as a comment.

**Comment by reconman** [comment]
FGA doesn't know what "undetected" means in the context of stage counters.

It doesn't check for numbers, instead it just takes screenshots of the first number.

If the number is hidden, FGA still assumes that the screenshot was a number.
