### ISSUE TITLE
When i click the button to start the auto but nothing happen

### ISSUE THREAD

**Issue by DinhNgocDo** [Fate-Grand-Automata/FGA#1230]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1676

### Describe the bug

I finished setup for my team auto farming in fga but when i started the tool wasn't working, when i cant use fga in my phone so im trying to download some emulator like bluestacks (new version) i met a new problem that when i click to the button start services in fga screen and some bug appear, idk how to describe it so i clip it. Can you give me a solution to fix it, fga is the only reason i keep playing fgo

### Video

https://user-images.githubusercontent.com/83223275/177310924-76ff00a1-83ae-4267-8172-2745e90d27b8.mp4

first video in my phone

https://user-images.githubusercontent.com/83223275/177313854-b1033a19-e9b6-46b5-add9-47dfacb0d5d7.mp4

the second that my bluestacks 5

### Device model

Xiaomi Redmi Note9S

### Android version

10

### Screen size

i dont know

### RAM

6GB

**Comment by reconman** [comment]
For your phone, enable fullscreen for FGO, also see https://github.com/Fate-Grand-Automata/FGA/issues/1053#issuecomment-1003651743 for the black bar at the bottom.

For Bluestacks, did you follow the guide for emulator settings?

**Comment by DinhNgocDo** [comment]
Ok, I solved the problem in bluestacks by change to compatibility
On the phone I changed the gestural system to the normal buttons and enable full screen for FGO and now the app started work

Thank you so much for supporting, have a nice day man
