### ISSUE TITLE
FGA stop when select Castoria support

### ISSUE THREAD

**Issue by zero11187** [Fate-Grand-Automata/FGA#1232]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1716 

### Describe the bug

FGA stop when select Castoria support. In the battle, it sill work very good.

### Video

https://youtu.be/TB_R66BBcFQ

### Device model

Xiaomi Mi 11 Lite 5G

### Android version

12

### RAM

8

**Comment by reconman** [comment]
Check your Castoria image in the support directory, seems like there are broken images inside.

**Comment by zero11187** [comment]
> 

This is my support image folder. I just extracted image from FGA to my phone storage
![z3544632292131_e23036916bd820a3359781b1491dbf92](https://user-images.githubusercontent.com/79573554/177352337-13ece82a-84e2-4b6b-855e-fc25000d5051.jpg)

**Comment by reconman** [comment]
Can you create an empty folder and choose that one as new Support folder? Maybe that fixes your problem.
