### ISSUE TITLE
Max-limit broken CE doesn't work

### ISSUE THREAD

**Issue by redo1139** [Fate-Grand-Automata/FGA#1236]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA, JP

### FGA build number

1716

### Describe the bug

I turn on max-limit broken in preferred CEs tab but it automatically choses the first-looked Bella Lisa despite it max limit or not

### Video

https://user-images.githubusercontent.com/108769532/177435581-79904b3b-6811-44b7-b0d2-febdefe584de.mp4

### Device model

Nox player 7.0.3.1

### Android version

7

### Screen size

1920x864

### RAM

4GB

**Comment by Ansem93** [comment]
Same issue here with Bluestack. FGA is updated to the latest 1771

**Comment by reconman** [comment]
I think that's because the MLB star is detected by accident.

**Comment by reconman** [comment]
Try increasing More Options -> Advanced -> Fine-Tune -> Similarity -> MLB similarity by a few %.

**Comment by Perseo2499** [comment]
> Try increasing More Options -> Advanced -> Fine-Tune -> Similarity -> MLB similarity by a few %.

I was facing the same issue and this actually solved the problem. I rised the percentage to 85% and it started to detect the MLB CEs again. Thanks!
