### ISSUE TITLE
Skill selection issue due to overly wide phone screen

### ISSUE THREAD

**Issue by XiaoMyst** [Fate-Grand-Automata/FGA#1239]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1719

### Describe the bug

Unable to select skills due to overly wide screen - my current phone's aspect ratio is 19.8:9 / 2376 x 1080 and im unsure how to use custom game area to rectify the issue if thats the way to do it ; if not do advise on the steps to allow the app to work as as intended because it selects cards/supports fine ; its just the skill selection positioning issue, so it clicks between the ''Cancel'' and ''OK'' button so i cant use skills on auto.

Thanks in advance, this app really helps our day to day grind so i hope i can solve the issue soon.

### Video

[Video](https://imgur.com/tiIlo1x)

### Device model

Vivo X60 pro

### Android version

11

### Screen size

2376x1080

### RAM

12GB

**Comment by reconman** [comment]
You didn't enable debug mode for your video. I need that in order to help you.

**Comment by XiaoMyst** [comment]
Hi is this what you meant
I reenabled debug mode in the app settings and re recorded
https://imgur.com/a/30t0Dvj

**Comment by reconman** [comment]
I think the issue is just one of the ones answered by the troubleshooting guide. Enable Skill Confirmation in FGA.

**Comment by ezriel566** [comment]
> I think the issue is just one of the ones answered by the troubleshooting guide. Enable Skill Confirmation in FGA.

I had the same problem and this fixed it TY ^^

**Comment by XiaoMyst** [comment]
I turned it on and off a few times and initially didnt work,decided to just reinstall the app to see if that changed anything
For some reason reinstalling then turning it on did fix it,TY SO MUCH for the assistance!
