### ISSUE TITLE
Apple Refil Selection not working as intended.

### ISSUE THREAD

**Issue by Luci4k** [Fate-Grand-Automata/FGA#1240]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1720

### Describe the bug

Not able to select multiple types of apples for use in the menu before battles.

Ive tried uninstalling and reinstalling. 

I updated from version 1645 recently, which did had this functionality to select multiple types of apples.

### Video

https://www.youtube.com/watch?v=Hq4NHcNzcbI

### Device model

ldplayer V.4.0.81 (Latest release)

### Android version

7

### Screen size

1920 x 1080

### RAM

4GB

**Comment by reconman** [comment]
Not a bug, intended behavior for now.

Had to change that behavior because of blue bronze apples.

**Comment by Luci4k** [comment]
Ah ok thank you for the response
