### ISSUE TITLE
Script doesn't match with my screen

### ISSUE THREAD

**Issue by BcmgChemito** [Fate-Grand-Automata/FGA#1250]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1721

### Describe the bug

I updated recently but looks like it doesn't match anymore.

Also, already tried to use "Custom, Duo and Xperia Mode" but none if I choose any of them, the script doesn't do anything, no touches, nothing.

### Video

https://youtu.be/4gkIUf1lh9k

### Device model

Xiaomi Mi A2 Lite

### Android version

10

### Screen size

2280 x 1080

### RAM

4GB

**Comment by reconman** [comment]
You haven't enabled debug mode in your video.

I'm guessing that your issue is at least partially caused by Skill Confirmation being turned on in FGO but not in FGA.

**Comment by BcmgChemito** [comment]
Debug mode actually works, i apologize for don't try it but i was not sure what it does lol. Anyways is taking a bit more to clear the quest but it's working that's fine to me.

Thank u

**Comment by reconman** [comment]
Debug mode alone doesn't fix anything.

Could be battery optimization, then.
