### ISSUE TITLE
No way to create the battle script EDIT: Sorry, i fixed it. I forgot the very first time you use it, you have to assign it to a folder for some images. I'm stupid

### ISSUE THREAD

**Issue by OG-RoachBoi** [Fate-Grand-Automata/FGA#1251]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1721

### Describe the bug

When i launch the app and try to make a battle script, it requires me to choose a folder, and doesn't give the plus sign option to create a script like it normally would on a mobile device. I am using Bluestacks btw.

https://user-images.githubusercontent.com/96732679/179394174-805b0273-543a-480b-805a-6688d68857f7.mp4

### Video

https://user-images.githubusercontent.com/96732679/179394186-b5ac7e61-ba00-41f8-8483-15eb694fbd64.mp4

### Device model

Bluestacks

### Android version

12

### RAM

4

**Comment by reconman** [comment]
Click on the ONEPLUS A5000 button on the left when it asks you to select the directory.

The default screen is "Recent files".
