### ISSUE TITLE
FGA is ignoring my NP card on every wave. 

### ISSUE THREAD

**Issue by RaimeiAzure** [Fate-Grand-Automata/FGA#1252]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1728

### Describe the bug

I was using it normally this afternoon. An hour later I went back to using the FGA and it started with this bug of not recognizing the NP card. 
I already recreated everything inside "Battle Configs" and the FGA keeps ignoring the NP card. 

### Video

https://youtu.be/rKL7e_iRPEU

### Device model

Xiaomi Redmi note 8 Pro 

### Android version

10

### Screen size

2340x1080

### RAM

6GB

**Comment by reconman** [comment]
Looks like the cards don't load fast enough.

See More Options, Advanced, Fine Tune, Wait, Wait before cards.
