### ISSUE TITLE
Area recognition seems to be broken?

### ISSUE THREAD

**Issue by FWCrash** [Fate-Grand-Automata/FGA#1255]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1741

### Describe the bug

After being forced to re-install my BlueStacks Emulator, i got the most recent FGA version. I had previously used 16xx and had no issues. But with this release, it seems area recognition is busted, or at least partially. Once the script starts and my support has been selected, the battle starts. Like always, the script clicks on the faces of each servant. On the third servant (support Castoria in my case here), it seemingly fails and instead accidentally clicks on the second Skill of my second Servant? I am unable to fix this issues, despite:
- Going Fullscreen to get rid of the black borders (even tho that wasn't an issue for me beforehand)
- Messing around with a multitude of settings inside the Emulator and FGA itself
- Looking up similar posted issues and applying their fixes
I'm at a loss at what to do, and what's even more upsetting is that i desperately need to farm Summer 5 as Castoria ate up all my resources. Any help would be appreciated, thanks!
PS: I got an error from the FGA script when i enabled Screen Recording (Attempt to read from field int android.media.camcorderprofilefileformat failed...), so i resorted to using OBS. Why is all this such a hassle, been trying all day just to start farming in the BG... 

### Video

https://user-images.githubusercontent.com/109912797/180655563-41908120-5825-43ae-9c4b-cf412fb8138e.mp4

### Device model

BlueStacks 5.3.145.1003 P64

### Android version

9

### Screen size

1920x1080

### RAM

16GB

**Comment by reconman** [comment]
That's Skill Confirmation, turn it off in FGO or on in FGA.

Everything else looks fine.

**Comment by FWCrash** [comment]
> That's Skill Confirmation, turn it off in FGO or on in FGA.
> 
> Everything else looks fine.

Oh my god... it was literally that simple. Cannot believe i spent hours trying to fix this and missed that simple detail, i guess i got a little confused by it not doing a check on the support servant, but i suppose thats due to it being a dupe of my second servant? Regardless, it now works flawlessly, thanks a lot and my apologies!

**Comment by reconman** [comment]
The support servant is detected by looking at the +SUPPORT icon on the top right. That +SUPPORT icon is always present on NP and face cards.
