### ISSUE TITLE
FGA not choosing servant after game update.

### ISSUE THREAD

**Issue by Kyonyuu** [Fate-Grand-Automata/FGA#1258]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

1741

### Describe the bug

Fgo cn update changed something? ig... it isn't detecting ce or cards? dunno which, i just wanted to farm QP...

### Video

https://youtu.be/yZwFqhhVgzE

### Device model

MEMU

### Android version

7

**Comment by Kyonyuu** [comment]
forgot to say fga was configured to choose Altria Caster with Bella Lisa.

**Comment by reconman** [comment]
That's Append Skills. I'll fix it today or tomorrow.

**Comment by Kyonyuu** [comment]
i think you might already know this but... reload/reset supp list isn't working tho... it's not a big problem on the first run but if FGA don't find the servant needed it will missclick the button and then select a random servant and stop till you stop and start fga setup again...

**Comment by reconman** [comment]
Thanks for the info, they moved the update list button to the same position as in JP. In NA it's still in the old location.

Please test build 1742, which will be available in a few minutes.

**Comment by 1717231** [comment]
Still doesn't work.
https://user-images.githubusercontent.com/84433555/181424465-057049cc-3588-42d6-b11e-681e3a433a8f.mp4



> Thanks for the info, they moved the update list button to the same position as in JP. In NA it's still in the old location.
> 
> Please test build 1742, which will be available in a few minutes.

**Comment by Kyonyuu** [comment]
> Still doesn't work. https://user-images.githubusercontent.com/84433555/181424465-057049cc-3588-42d6-b11e-681e3a433a8f.mp4
> 
> > Thanks for the info, they moved the update list button to the same position as in JP. In NA it's still in the old location.
> > Please test build 1742, which will be available in a few minutes.

Just tested and it's working... it's just not detecting cards of quick and burster type.
![Screenshot_20220728-173930](https://user-images.githubusercontent.com/55859937/181474587-83dc09de-70a8-4bb8-a747-e70e175f4e51.png)
![Screenshot_20220728-174210](https://user-images.githubusercontent.com/55859937/181475082-9059dc91-da50-4869-9b6f-8d691f287972.png)
dunno if they changed something with the cards...

**Comment by reconman** [comment]
Try build 1743. Seems like they change the buster/arts/quick font once a year.

**Comment by Kyonyuu** [comment]
Well... problems happened... 
https://youtu.be/shnzv3C9fKQ
i saw that also happening with Musashi Berserker Arts cards so i thought something happened with Arts with Weak but it doesn't look like that actually happened...

**Comment by reconman** [comment]
The arts card also changed slightly. The similarity between the old and new image is somewhere around 80 %, which is the default image detection limit.

If it's slightly above 80 %, it works, if it's slightly below, it doesn't.

Try 1744, which is building right now.

**Comment by Kyonyuu** [comment]
It's Working, should i close the issue?

**Comment by 1717231** [comment]
1744Still can't work



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 29, 2022 19:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Fate-Grand-Automata/FGA] FGA not choosing servant after gameupdate. (Issue #1258)




 
The arts card also changed slightly. The similarity between the old and new image is somewhere around 80 %, which is the default image detection limit.
 
If it's slightly above 80 %, it works, if it's slightly below, it doesn't.
 
Try 1744, which is building right now.

**Comment by reconman** [comment]
@1717231 Your video above is broken. Can you record a new one?

**Comment by Kyonyuu** [comment]
> 1744Still can't work
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Fri, Jul 29, 2022 19:45 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [Fate-Grand-Automata/FGA] FGA not choosing servant after gameupdate. (Issue #1258) The arts card also changed slightly. The similarity between the old and new image is somewhere around 80 %, which is the default image detection limit. If it's slightly above 80 %, it works, if it's slightly below, it doesn't. Try 1744, which is building right now. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

record with full screen with debugg so they can actually see what is the problem...

**Comment by 1717231** [comment]
There seem to be more problems

https://twitter.com/lanjiahuan1/status/1553039380444356608?s=19



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 29, 2022 20:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Fate-Grand-Automata/FGA] FGA not choosing servant after gameupdate. (Issue #1258)




 
@1717231 Your video above is broken. Can you record a new one?

**Comment by Kyonyuu** [comment]
> There seem to be more problems https://twitter.com/lanjiahuan1/status/1553039380444356608?s=19
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Fri, Jul 29, 2022 20:32 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [Fate-Grand-Automata/FGA] FGA not choosing servant after gameupdate. (Issue #1258) @1717231 Your video above is broken. Can you record a new one? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

try leaving the bottom at bottom left , and record with debug mode(open fga>More Options > advanced >Debug Mode.

**Comment by rchan3** [comment]
Using 1744. Support servant selection still not working for me.

**Comment by Kyonyuu** [comment]
> Using 1744. Support servant selection still not working for me.

Record and send a video with Debug mode so they can see which is the problem and how to fix, if you are on cellphone also use record screen.

**Comment by reconman** [comment]
@1717231 Try the 忽略刘海 (Ignore Notch) option, also turn off 技能确认 (Skill Confirmation) in FGO or turn on 技能确认 in FGA.

And as Kyonyuu said, move the play button to the bottom left.

**Comment by 1717231** [comment]
Thank you. It's working again.



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 29, 2022 23:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Fate-Grand-Automata/FGA] FGA not choosing servant after gameupdate. (Issue #1258)




 
@1717231 Try the 忽略刘海 (Ignore Notch) option, also turn off 技能确认 (Skill Confirmation) in FGO or turn on 技能确认 in FGA.
 
And as Kyonyuu said, move the play button to the bottom left.

**Comment by reconman** [comment]
@1717231 Which phone are you using? I probably have to change some logic related to Ignore Notch.

**Comment by 1717231** [comment]
vivoiQOO5



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 30, 2022 00:02 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Fate-Grand-Automata/FGA] FGA not choosing servant after game update. (Issue #1258)




 
@1717231 Which phone are you using? I probably have to change some logic related to Ignore Notch.

**Comment by rchan3** [comment]
> Using 1744. Support servant selection still not working for me.

https://user-images.githubusercontent.com/57269877/181867527-82750701-2d10-47be-9a31-f1c524f9e744.mp4

**Comment by reconman** [comment]
@rchan3 Try 1745

**Comment by rchan3** [comment]
> @rchan3 Try 1745

works now. thanks!
