### ISSUE TITLE
FGA can't detect and select support servant on MIUI 13

### ISSUE THREAD

**Issue by niwaaa** [Fate-Grand-Automata/FGA#1274]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1745

### Describe the bug

FGA cant detect support servent after Miui update. previously it can select support servant on miui 12 but in miui 13 it cant detect, battle config can run normally but on selecting support servant it always stopped

### Video

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/bulwiSP6EdU/0.jpg)](https://youtube.com/shorts/bulwiSP6EdU)

### Device model

Redmi Note 10s

### Android version

12

### Screen size

1080 x 2400

### RAM

6GB

**Comment by reconman** [comment]
Play button is in the way, and you didn't record with FGA so it only sees black until you restart the FGA service.

**Comment by niwaaa** [comment]
my bad. thanks for the solution. it's solved
