### ISSUE TITLE
trojan script detected with build 1771

### ISSUE THREAD

**Issue by DNLMow** [Fate-Grand-Automata/FGA#1278]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1771

### Describe the bug

Build 1716 did no trigger windows defender, but 1771 will with Trojan:Script/Wacatac.B!ml

### Video

placeholder

### Device model

Bluestack 5.9.0.1061 N32

### Android version

7

**Comment by reconman** [comment]
My Windows Defender, ESET Internet Security and https://www.virustotal.com/gui/file/bd4f295a7eb1ce135eb5de66abf07851b1e1bbf193aeda35f2b82510f3237790?nocache=1 can't find anything.
