### ISSUE TITLE
Notification when completing all scheduled runs

### ISSUE THREAD

**Issue by spiral6** [Fate-Grand-Automata/FGA#1279]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

I want a notification in the notification bar and a toast message for when all runs have been completed for FGA. I haven't found this feature in the closed or open issues.

A sound notification would be nice too, to know when it's been finished. Otherwise, FGO just waits on confirmation on whether I'd like to input more AP for the current node.

**Comment by reconman** [comment]
There's already a notice covering the screen and a vibration.

Make sure it's not hidden by something like "gaming mode".

**Comment by spiral6** [comment]
This is a bit of a weird issue because of my setup. I'm running FGO on an instance of the official Android emulator, and it closes itself for some unknown reason after idling for too long (memory issues, presumably, under Qemu). As a result, I don't know if it actually completes or not. 

Vibration doesn't work on emulator. Notice covering the screen would be fine if the emulator didn't close itself.
