### ISSUE TITLE
MIUI,JP not available

### ISSUE THREAD

**Issue by lianli2352** [Fate-Grand-Automata/FGA#1280]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1771

### Describe the bug

can't do the correct identification. For details, see the video. These，CN is OK and can be used normally, but Jp can't be used and many Xiaomi users in China can't use it。I think the problem is that the overall screen optimization has not been done, but it is useless to modify the system Settings or FGA. I hope it can be solved, thank you

### Video

https://youtu.be/o2Q0GzD_HWY

### Device model

radmi k30

### Android version

12

### Screen size

2400*1080

### RAM

6

**Comment by reconman** [comment]
That's an Android 12 bug I reported this week to FGO US support.

I measured the black pixels on the sides. Use Custom Game Area with left=65, right=159 or right=160.

Also move your Play button to the bottom left.

**Comment by lianli2352** [comment]
thank you

**Comment by reconman** [comment]
Actually, Xiaomi users can enable fullscreen for FGO in Settings -> Display -> Fullscreen Mode.

Please check if you can get rid of the black bars that way.
