### ISSUE TITLE
Story Skip doesn't work in CN

### ISSUE THREAD

**Issue by skyio** [Fate-Grand-Automata/FGA#1282]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

1771

### Describe the bug

When I play the CN server ,I trun on the 'skip story' function and press 'play' botton on the screen, but it couldn't work , I'm sure my configration is correct because it worked in my JP server. 

### Video

https://youtu.be/XOxuHIMsBqs

### Device model

xiao mi 11

### Android version

12

### RAM

12G

**Comment by reconman** [comment]
Can you please give me a screenshot with the Skip button in it? The video is not enough.

 CN is the only version where it doesn't say SKIP.

**Comment by skyio** [comment]
![Screenshot_2022-08-06-16-19-12-986_com bilibili fatego](https://user-images.githubusercontent.com/11185767/184052853-704ef888-6a4c-4ad7-9a1b-315912bcd891.jpg)
![Screenshot_2022-08-06-16-19-02-735_com bilibili fatego](https://user-images.githubusercontent.com/11185767/184052896-7363425e-6784-4877-bcde-ed26d4283303.jpg)
Take it😁

**Comment by reconman** [comment]
Should have specified: it's best if the background is black.

**Comment by NepPure** [comment]
![E106BF6D-80B4-43C2-AFF4-9CD4EC4B37E2](https://user-images.githubusercontent.com/12379907/189896168-5453e7f5-597c-4ed2-be2a-ace722c38ac8.png)
