### ISSUE TITLE
Script works in battle but not on support [Workaround Found]

### ISSUE THREAD

**Issue by vajrakongou** [Fate-Grand-Automata/FGA#1284]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA, JP

### FGA build number

1651

### Describe the bug

**UPDATE:** _It sort of works now. I had to turn off both max ascended and MLB CE. Tried it on both JP and NA, both requires max ascension and MLB options to be off._

The script works fine in battle. It's just that when it's on the support page, it just keeps scrolling without picking the support I want. I've tried notch on and off. I thought it might be detection area issue, but as said, it works fine in battle and in the support page, the red boxes do cover the area of the servants' face.

I've already used the image maker to save morgan screencaps but it still wouldn't pick them.

### Video

https://streamable.com/0cvp6u

### Device model

Samsung A52s

### Android version

12

### Screen size

1080x2400 

### RAM

8GB

**Comment by reconman** [comment]
Can you show me your battle config?

Best would be as json file after you exported it.

**Comment by vajrakongou** [comment]
![Screenshot_20220809-054449_FGA (CI)](https://user-images.githubusercontent.com/110834286/183527607-9a4c8d95-618e-46e0-84ed-509010b473e3.jpg)

**Comment by bgaoprovidertrust** [comment]
I wanted to add that I'm seeing a similar issue with my oneplus 8t+5g phone after it updated to Android 12, with some caveats. As a result of the update, FGO is showing black bars on the sides of the screen when I have gesture navigation turned on.

Originally, it wouldnt work on the battle at all, but then I messed with the game area mode settings to get it working. Now it works on the battle screen, but it still won't scroll the supports list

**Comment by BailinGao** [comment]
I wanted to add that I'm seeing a similar issue with my oneplus 8t+5g phone after it updated to Android 12, with some caveats. As a result of the update, FGO is showing black bars on the sides of the screen when I have gesture navigation turned on.

Originally, it wouldnt work on the battle at all, but then I messed with the game area mode settings to get it working. Now it works on the battle screen, but it still won't scroll the supports list

**Comment by reconman** [comment]
@BailinGao off topic, measure the black bars in Photoshop (or online via Photopea)

**Comment by vajrakongou** [comment]
It sort of works now. The workaround is that I had to turn off both max ascended and MLB CE. 

Tried it on both JP and NA, both requires max ascension and MLB options to be off. Not an issue during events (namely lottos and raids) since there's in-game filters to ensure picking MLB CEs and that's what matters.

**Comment by reconman** [comment]
There's a setting in More Options -> Advanced -> Fine-Tune -> Similarity called MLB Similarity.

Some users have to increase the value, you probably have to lower the value to 65 % or so.
