### ISSUE TITLE
It goes well, but the servant icons are clicked in first wave

### ISSUE THREAD

**Issue by Meteor-Rei** [Fate-Grand-Automata/FGA#1285]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

I use Nox emulator to run this script. It goes well, but servant icons are clicked. It costs time.
Below lies the video that I record. I intercepted the first wave of battle and accelerated it by 3.5 times.

https://user-images.githubusercontent.com/63620926/183688896-952cc435-9560-41d7-92ea-cb3c44fc29b7.mp4

**Comment by reconman** [comment]
See the last entry of the troubleshooting guide.

**Comment by Meteor-Rei** [comment]
> See the last entry of the troubleshooting guide.

Thank you. It's my fault that I didn't understand that guide yesterday.
