### ISSUE TITLE
FGA not work on redmagic 7 phone

### ISSUE THREAD

**Issue by ntk512** [Fate-Grand-Automata/FGA#1286]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

sometimes appear the play button, sometimes none when open game and start FGA. When appear play button, press on it but FGA not work =(

**Comment by reconman** [comment]
Check battery optimization

**Comment by ntk512** [comment]
> Check battery optimization

Can you explain? i turned off battery saver and my phone is full of battery. What should i check? 
Thank you!

**Comment by ntk512** [comment]
https://user-images.githubusercontent.com/110986481/184012714-3f82d1bb-2a30-4b64-8590-f21a6f16f604.mp4

**Comment by reconman** [comment]
It's the black bars on the sides which cause the problem.

Can you upload a screenshot?

**Comment by ntk512** [comment]
> It's the black bars on the sides which cause the problem.
> 
> Can you upload a screenshot?

![Uploading Screenshot_Fate_GO_2022-08-12-09-32-57-865.jpg…]()

**Comment by reconman** [comment]
Why is the screenshot so small? 458x206 pixels

**Comment by ntk512** [comment]
Sorry! I can't upload from my phone, then i send it to facebook and use my PC to upload. I think that why my photo is down in resolution.

**Comment by ntk512** [comment]
![Uploading Screenshot_Fate_GO_2022-08-12-09-32-57-865.jpg…]()

**Comment by ntk512** [comment]
![Screenshot_Fate_GO_2022-08-12-09-32-57-865](https://user-images.githubusercontent.com/110986481/184550581-088074bc-45da-470c-a7a7-744a466a8027.jpg)

**Comment by reconman** [comment]
Should be left=66, right=66.

**Comment by ntk512** [comment]
> Should be left=66, right=66.

What can i do to fix it or make it work?

**Comment by reconman** [comment]
Use Custom Game Area mode with those values. It's under More Options -> Advanced.

**Comment by ntk512** [comment]
> Use Custom Game Area mode with those values. It's under More Options -> Advanced

Thank you very much, Sir! It's worked :D

**Comment by reconman** [comment]
Can you please tell me what's your phone model so I can add your Custom Game Area values to the megathread?

**Comment by ntk512** [comment]
> Can you please tell me what's your phone model so I can add your Custom Game Area values to the megathread?
Nubia red magic 7
