### ISSUE TITLE
consecutive miss clicking 

### ISSUE THREAD

**Issue by Amirgundam6** [Fate-Grand-Automata/FGA#1287]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA, JP

### FGA build number

1771

### Describe the bug

when i start the script it clicks on a very wrong place consecutively wich eventually stops the script,its a place for special tool bar of poco phones.the weird thing is i hadn't this problem before and it appeared suddenly.

### Video

https://user-images.githubusercontent.com/111076418/184187298-a643cfa7-d529-41de-b005-d8f891d2a222.mp4

### Device model

Poco x3 pro

### Android version

10

### RAM

256GB

**Comment by reconman** [comment]
Another user managed to disable the top right menu. https://github.com/Fate-Grand-Automata/FGA/issues/1155#issuecomment-1100866856

Can't find how it's called, maybe something like "gaming tools"?
