### ISSUE TITLE
Second wave ignores commands

### ISSUE THREAD

**Issue by runelt99** [Fate-Grand-Automata/FGA#1289]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1771

### Describe the bug

Im using it to make ooku event braindead, since even though event uses custom 3 servant only, fga still activates.

![image](https://user-images.githubusercontent.com/48949150/184395875-b5125f20-9c3d-4b15-8e37-bc3aedcbdafa.png)

First turn is Ok, the second one completely shuts down and acts like it has no commands. Initially thought it was issue with SPAM np thing since i selected to spam all, it lead to the script using all skills on 1st turn, after turning it off first turn started going fine, but now second turn doens't work. 

![image](https://user-images.githubusercontent.com/48949150/184396112-547cad66-0bd7-431b-93a9-cf9a325862ab.png)
Clicked no spam to fix first issue.

Turn 2 starts at 1:26, I stopped the video when it ignored skills, the fully charged np and used normal attacks. I only manually needed to click dialogue after it selects support and starts.

Using LDPlayer emulator, apparently its android version is 7.1.2

Closest i've found was #1228 but  its more in line with the issue I had with spam all. 

### Video

https://youtu.be/9fchEJM37UM

### Device model

SM-G975N

### Android version

7

### Screen size

1080x1920

### RAM

4gb

**Comment by reconman** [comment]
That's because the 4th and 5th enemy are in wave 1, but turn 2.

Choose "next turn same wave" in the battle command.
