### ISSUE TITLE
Improve Battle command UI

### ISSUE THREAD

**Issue by vietng322611** [Fate-Grand-Automata/FGA#1290]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

The space between buttons and the size of the button should not be static because the screen size of the phones are different. It should depend on the height and width of the screen because some devices have small screens, it would cause some buttons to disappear and that is not good for user experience.
The screenshot is from my device which is samsung galaxy j7 prime.
![Screenshot_20220814-205232_FGA_CI](https://user-images.githubusercontent.com/90992374/184540196-681ce39d-50b3-441a-907a-bba9ad779545.jpg)
.

**Comment by reconman** [comment]
How does the UI now look in the APK from https://github.com/Fate-Grand-Automata/FGA/suites/7896748289/artifacts/335671573?

Tell me if you need a new build in case you've updated to the ones with NP skip already.

**Comment by vietng322611** [comment]
Well... At least i can see the skill 3 button now.

![Screenshot_20220821-204850_FGA (CI).jpg](https://user-images.githubusercontent.com/90992374/185794083-561a2b7c-37c9-459d-befd-6a50adce2b27.jpg)

**Comment by reconman** [comment]
I may have found the solution, please test https://github.com/Fate-Grand-Automata/FGA/suites/7909399059/artifacts/336685549

**Comment by vietng322611** [comment]
I think you shouldn't set maxWidth then use fillMaxSize
![Screenshot_20220823-102514_FGA (CI).jpg](https://user-images.githubusercontent.com/90992374/186062922-bbe3e683-12c5-4d17-b9ea-79038531f7b4.jpg)

**Comment by reconman** [comment]
This one should definitely look correct: https://github.com/Fate-Grand-Automata/FGA/suites/7946563927/artifacts/339215748

Had to give each button the same weight so they're the same size. Without it, Android starts adding buttons with max size and then when it runs out of space, it puts the rest of the buttons in weird positions.

**Comment by vietng322611** [comment]
Yeah it worked, thank you for your hard work to solve this problem.
![Screenshot_20220824-071511_FGA (CI).jpg](https://user-images.githubusercontent.com/90992374/186287908-daf076e3-2fa0-4bbe-832c-1a6cf3c67fd9.jpg)
