### ISSUE TITLE
FGA won't refresh if support is empty

### ISSUE THREAD

**Issue by ZuraJura** [Fate-Grand-Automata/FGA#1291]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1771

### Describe the bug

It suddenly won't refresh support when it's empty. It runs fine if there's any in support, I tried reinstalling 3 times too but doesn't work. Now I'm stumped.

Also, after quest it won't repeat it. It just stuck in "Repeat quest?" screen.

### Video

https://youtu.be/wrNkO1p-Rk4 
I'm sorry for not uploading directly since it's too big and FGA only works on root mode if not it will crash.

### Device model

Bluestacks 5.2.110.1003 N32

### Android version

7

### Screen size

1920x1080

### RAM

4

**Comment by ZuraJura** [comment]
ok, i somehow got it working but it's by reintalling fgo

**Comment by reconman** [comment]
Why was there English text in the JP version?

**Comment by ZuraJura** [comment]
> 

yeah it's probably that makes not running. it's ui tl on beta
