### ISSUE TITLE
i cant use fga on xiomi 10c full screen

### ISSUE THREAD

**Issue by Pakdani** [Fate-Grand-Automata/FGA#1292]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

help i cant use fga full screen in xiomi 10c  Resolution, 720 x 1650 pixels
![3f689d98-8da7-4eda-9b87-0cf059801314](https://user-images.githubusercontent.com/111302823/184702729-72be30d9-b01d-4d33-8664-d262431d29e3.jpg)

**Comment by reconman** [comment]
Not a question, open a bug report instead.
