### ISSUE TITLE
FGA bug report

### ISSUE THREAD

**Issue by bhjs** [Fate-Grand-Automata/FGA#1293]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1771

### Describe the bug

My FGA work normal at first. But then it become like this, start this loop infinity. I have read all of the guide and try to fix it but they all not work.

### Video

https://youtu.be/vybQwS46K5s 

Link to the video 

### Device model

Redmi 9T

### Android version

10

### Screen size

6,53 inches

### RAM

4GB

**Comment by reconman** [comment]
You didn't use FGA's recorder, so FGA cannot see the screen anymore.

Restart the phone and enable the recording function in More Options -> Advanced. Then press the Play button and upload the video file created by FGA.

**Comment by bhjs** [comment]
>The problem was solved, thanks
