### ISSUE TITLE
Implement support for BetterFGO's new NP skip feature

### ISSUE THREAD

**Issue by matthewasage** [Fate-Grand-Automata/FGA#1296]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

BetterFGO has implemented NP skip as of 8/19/2022 01:34 UTC. A demonstration of the feature can be found [here](https://www.youtube.com/watch?v=3CexBmjq1cM).

The feature can be accessed simply by double tapping on the screen during the NP animation.

Please add support for this feature.

**Comment by Yunnie-pin** [comment]
hope they will implement these features so

**Comment by shikkatedo** [comment]
I want to see support to this future aswell :)

**Comment by reconman** [comment]
The main question is: How do you detect, that a NP animation is playing right now?

The only reliable indicator I can find is the white flash at the start and end.

**Comment by niwaaa** [comment]
> The main question is: How do you detect that a NP animation is playing right now?
> 
> The only reliable indicator I can find is the white flash at the start and end.

i think with add some tap/clicking after np card selected like after using skill there was an tap/click on the top-right to trigger double speed animation. just like that np animation in "better fgo" need some tap/clicking to skip the np animation

**Comment by reconman** [comment]
> i think with add some tap/clicking after np card selected like after using skill there was an tap/click on the top-right to trigger double speed animation. just like that np animation in "better fgo" need some tap/clicking to skip the np animation

Contrary to skills, NPs only start after selecting 3 cards and playing some animations.

If the user wants 2 or 3 NPs in a row, double tapping after x seconds doesn't work.

**Comment by Tom3kk** [comment]
> > i think with add some tap/clicking after np card selected like after using skill there was an tap/click on the top-right to trigger double speed animation. just like that np animation in "better fgo" need some tap/clicking to skip the np animation
> 
> Contrary to skills, NPs only start after selecting 3 cards and playing some animations.
> 
> If the user wants 2 or 3 NPs in a row, double tapping after x seconds doesn't work.

I think it would work, just make it tap in the top right of the screen after going into card selection, you can't go out of it by tapping somewhere else on the screen and it could just keep pressing there until it detects that the next round has started. But if it can't tap in the corner AND select facecards I have an another idea; it has facecard detection (for avoiding chains and stuff) it should be able to tell that it already selected all np's and facecards it can and its time to start spamming np, right?

**Comment by BlueishVolt** [comment]
I would love to see this feature added, I think it would be good enough even if it only activated during the first NP.

**Comment by reconman** [comment]
For now I'm trying a strategy where I check the screen for white and then double click in the top right as @niwaaa suggested.

I can test my code once I start farming lottery in the next event.

**Comment by Tom3kk** [comment]
> For now I'm trying a strategy where I check the screen for white and then double click in the top right as @niwaaa suggested.
> 
> I can test my code once I start farming lottery in the next event.

I could test it over the weekend if you'd like, I'm farming some materials anyway

**Comment by reconman** [comment]
Can be tested with build 1776, worked on my phone.

After detecting the white screen, FGA waits a bit and then clicks 5 times in the top right.

**Comment by Tom3kk** [comment]
Tested it, doesn't seem to work on LDPlayer, haven't tested my phone yet

**Comment by Tom3kk** [comment]
> Can be tested with build 1776, worked on my phone.
> 
> The option needs to be activated in More Options -> Battle Config.
> 
> After detecting the white screen, FGA waits a bit and then clicks 5 times in the top right.

Does not work on LDPlayer nor on my phone (Galaxy Note 9)

**Comment by reconman** [comment]
@Tom3kk Can I see a video with debug mode?

**Comment by Tom3kk** [comment]
> @Tom3kk Can I see a video with debug mode?

[yes you can](https://youtu.be/b8t0m0c-0CI)

**Comment by reconman** [comment]
@Tom3kk I don't think you enabled the config option. I don't see the new rectangle anywhere on your screen.

**Comment by Tom3kk** [comment]
> @Tom3kk I don't think you enabled the config option. I don't see the new rectangle anywhere on your screen.

Okay my bad I actually am blind and stupid, I went through the fga options to make sure I didn't actually miss it before recording the video please believe me
_Yeah it works now.._


_sorry..._

**Comment by reconman** [comment]
I've changed the logic in 1777 so no config changes are necessary.

FGA checks if BetterFGO is running. If that's the case, NP skip is automatically active.
