### ISSUE TITLE
i cant use fga on xiomi 10c full screen

### ISSUE THREAD

**Issue by Pakdani** [Fate-Grand-Automata/FGA#1297]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1771

### Describe the bug

help i cant use fga full screen in xiomi 10c Resolution, 720 x 1650 pixels just miss click everything
![3f689d98-8da7-4eda-9b87-0cf059801314](https://user-images.githubusercontent.com/111302823/185636812-a9952118-8d8b-4b2a-b813-9951f5ce161e.jpg)

### Video

https://user-images.githubusercontent.com/111302823/185640083-24a43b0f-ee31-4482-a7a9-a5af1fb8f2a1.mp4

### Device model

xiomi 10c

### Android version

11

### Screen size

720x1650

### RAM

8

**Comment by reconman** [comment]
What do you mean with "misclick everything"? I can't see any clicks in your video.

It would be best if you could use FGA's recording function with enabled debugging mode as suggested in the bug template.

**Comment by Pakdani** [comment]
> What do you mean with "misclick everything"? I can't see any clicks in your video.
> 
> It would be best if you could use FGA's recording function with enabled debugging mode as suggested in the bug template.

**Comment by Pakdani** [comment]
After active debug mode its work, thanks
