### ISSUE TITLE
FGA dont work properly

### ISSUE THREAD

**Issue by Bone33** [Fate-Grand-Automata/FGA#1298]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1771

### Describe the bug

![Screenshot_2022-08-19-14-26-14-668_com aniplex fategrandorder](https://user-images.githubusercontent.com/111600976/185683399-fa6fcfb9-cbfa-47db-9c37-e68e9a3b14ed.jpg)
![Screenshot_2022-08-19-14-27-17-159_com aniplex fategrandorder](https://user-images.githubusercontent.com/111600976/185683402-47647d0d-e27c-4f1e-b4d7-bc7915399c6d.jpg)
The First wave Works Fine but on the Second wave fga says the error' fail to determine card type'  dont use the skills and stucks on servant information screen or sometimes goes to atack button.  I dont know what to do.

### Video

https://user-images.githubusercontent.com/111600976/185691683-abddbc7f-8d30-4c9f-9b79-a4b13cca8411.mp4

https://user-images.githubusercontent.com/111600976/185684811-d948ef52-f176-4362-8c05-43eb38fdbff1.mp4

### Device model

Xiaomi redmi Note 9S

### Android version

11

### Screen size

1080x2400

### RAM

8GB

**Comment by reconman** [comment]
Are you running root mode? If not, you're not allowed to use the Android recorder while using FGA.

Also you didn't enable debug mode so I can see the green and red rectangles.

**Comment by Bone33** [comment]
@reconman on the donwload fga says ( Android 7 or later dont need a rooted device) My phone its not rooted ( and i haven't found the ' root mode' on options. Here is the videos with debug mode

https://user-images.githubusercontent.com/111600976/185712119-2308a8fb-a360-42c4-8ffb-f0314fa24d03.mp4


https://user-images.githubusercontent.com/111600976/185712126-c0360b35-c5e9-4bb2-8c26-8865b780abf7.mp4

**Comment by reconman** [comment]
If you're not using root mode, you need to record with FGA, not using your phone.

FGA cannot see anything otherwise.

Restart your phone and enable recording in More Options.
