### ISSUE TITLE
What is BetterFGO?

### ISSUE THREAD

**Issue by PatrickL546** [Fate-Grand-Automata/FGA#1300]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Just saw the new commits and I'm not sure what that is. From short google, is it an apk mod made by rayshift io? what's the difference from normal fgo?

**Comment by reconman** [comment]
An APK with forced NP widescreen, Altria changed to Artoria and NP skip.

You can get it from their discord. First get the BetterFGO role in #roles, then the BetterFGO NA in #betterfgo-roles.

Then download from #betterfgo-ci.

**Comment by PatrickL546** [comment]
ok, thanks for the info!

**Comment by reconman** [comment]
One more thing: SQ needs to be bought in the real app, not in BetterFGO.
