### ISSUE TITLE
I can't turn on Accessibility Service even after messing with battery optimization

### ISSUE THREAD

**Issue by DepressedGudao** [Fate-Grand-Automata/FGA#1301]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

**FGO Server**: JP

**FGA Build Number:** 1778

I just got a new phone, which is the Black Shark 4 Pro, and I tried installing FGA in it. However, when I want to toggle the Accessibility Service,  it won't turn on no matter what. 

I read through the Troubleshooting Guide and tried to optimize the battery, turn off MIUI optimization, force stopping and rebooting, and etc. But it does nothing
![Screenshot_2022-08-20-17-20-12-075_com android settings](https://user-images.githubusercontent.com/111634863/185738730-e206d646-cd3a-47ea-8ef9-79fe1c90c7bd.jpg)

When I try to toggle the damn thing, it just automatically turned off, like I never pressed it
I apologize if this is already answered, but I just couldn't find any solution in both opened and closed threads. Those that I saw are after they enabled the Accessibility Service.

**Comment by reconman** [comment]
I found this: https://www.reddit.com/r/Xiaomi/comments/u03g3o/_/

Maybe it helps.

**Comment by reconman** [comment]
Broken accessibility permissions seems to be widespread in Xiaomi phones.

There are a few Reddit posts about it without any solutions other than the one comment I found.

**Comment by DepressedGudao** [comment]
> I found this: https://www.reddit.com/r/Xiaomi/comments/u03g3o/_/
> 
> Maybe it helps.

Unfortunately I've already tried that before, and did it again just now, but it didn't do anything

**Comment by DepressedGudao** [comment]
I'VE FIGURED OUT A FIX

Switch the System Launcher to Poco Launcher. Boom
