### ISSUE TITLE
Add Materials Class In Material List

### ISSUE THREAD

**Issue by Luiso9** [Fate-Grand-Automata/FGA#1302]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Add Material Class to the list of materials in the battle configuration. because the drop materials drop randomly like other materials. Usually I only need a few, with the material feature which usually stops when the amount of material is reached so I can casually wait for the battle and will make it easier for me to save apples.

**Comment by reconman** [comment]
Build 1781 should work, please test.

**Comment by Luiso9** [comment]
Work!! thank you.
