### ISSUE TITLE
FGA not activating & targetting skills on Samsung S20 FE

### ISSUE THREAD

**Issue by AIUN1111** [Fate-Grand-Automata/FGA#1303]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1781

### Describe the bug

FGA can recognize and select support servants but it cannot activate any servant skills. It instead opens up the servant and skill tabs and closes em right after. 

### Video

https://drive.google.com/file/d/1_T4f_25zjFz_fwVTG3PdxVpRWJBV70UJ/view?usp=sharing[](url)

### Device model

Samsung S20 FE

### Android version

12

### Screen size

2400 x 1080

### RAM

6GB

**Comment by vybze** [comment]
You have skill use confirmation turned on in fgo so you need to turn it on in fga too, conversely if you turn it off in fgo then it also needs to be off in fga too

**Comment by reconman** [comment]
Part of the troubleshooting guide.

**Comment by AIUN1111** [comment]
I have already tried turning skill confirmation on and off for both but the problem persists. the issue is that FGA simply doesn't activate the skills. It only opens the skills tab and closes it.

**Comment by vybze** [comment]
Try turning on skip servants face card checks and see what happens

**Comment by AIUN1111** [comment]
> Try turning on skip servants face card checks and see what happens

Much appreciated! Everything works now.

**Comment by vybze** [comment]
Yeah it's working for me too
