### ISSUE TITLE
fga doesn't select support castoria

### ISSUE THREAD

**Issue by rossengarten** [Fate-Grand-Automata/FGA#1307]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1577

### Describe the bug

the support picker continuously scrolls past numerous castoria's on support, doesn't choose any other support either, just keeps scrolling 

### Video

https://youtu.be/Dp4UOFfUAvc 

file size too big, here's the youtube link

### Device model

Galaxy A21s

### Android version

12

### Screen size

6.5 inches, 720x1600

### RAM

6gb

**Comment by RedialGH** [comment]
Got the same issue, even used the support maker to try to get another castoria image, also didn't work

**Comment by vybze** [comment]
Turn off max ascended in preferred support

**Comment by Draque90** [comment]
Same issue. Turning off max ascend dosent fix it

**Comment by namenamae** [comment]
Same issue. Also tried using the support maker to try to get another castoria image, didn't work.

**Comment by vybze** [comment]
With max ascended off don't add a ce to preferred ce selection and use the ingame filters to filter out non event ce

**Comment by namenamae** [comment]
> With max ascended off don't add a ce to preferred ce selection and use the ingame filters to filter out non event ce

I tried this but it didn't work. OPPO A73

**Comment by reconman** [comment]
You're 200 versions behind the current one. Update FGA.
