### ISSUE TITLE
FGA Using Wrong Skill (Not a skill that should be used at all for the rest of the run)

### ISSUE THREAD

**Issue by gakiloroth** [Fate-Grand-Automata/FGA#1310]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1781

### Describe the bug

Most of the runs go well, but say about 5-10% of the time, on wave 2 FGA would hit the wrong skill and then the rest of the inputs would be messed up. I have tried changing turn delay up to 1000-1500ms, but the issue remained. 

I'm unsure if this is a FGA bug, or an accessibility issue. I have noticed that after leaving FGA on, if I tap anywhere on the screen, a secondary "ghost" tap also appears, which actually counts as an input. Maybe this is related?

Below is what the input is set to.
![Screenshot_20220822-235507](https://user-images.githubusercontent.com/9069768/186097222-7a306d7d-edb4-4502-8a05-2e29d3faef6b.png)

### Video

https://youtu.be/RJWHYl_AwEY

### Device model

Google Pixel 6

### Android version

12

**Comment by vybze** [comment]
I'm also having the same issue too but for me it can happen between either wave 2 or 3 and it's the third servants second skill. I also tried increasing wait times to no avail, I'll upload a video shortly

**Comment by reconman** [comment]
Try disabling Story Skip.

If that's it, I'm removing the story skip feature altogether.

**Comment by gakiloroth** [comment]
Story skip isn't on for me, but I'll try turning it on and off

**Comment by vybze** [comment]
Story skip is working for me so far, still testing to see if it was the problem

**Comment by RikuNoctis** [comment]
Can confirm the same thing happens on build 1781 on my end.
Most runs are fine, even with the recent NP Skip feature, but on some runs FGA selects a wrong skill for the third servant and the rest of the inputs are wrong, pretty much causing a wipe, or it completely skips using plugsuit for the other servant.

I tried disabling Story Skip as it was mentioned above and for now it seems to be running fine; it uses plugsuit correctly and doesn't seem to select a wrong skill for the third servant anymore.

I agree it requires more testing as most runs were fine previously so I don't know what exactly triggers the error.

**Comment by reconman** [comment]
Fixed most cases where this could happen with FGA build 1786.
