### ISSUE TITLE
Poco X3 Pro Configuration Settings

### ISSUE THREAD

**Issue by deadxpoolz** [Fate-Grand-Automata/FGA#1311]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

I have seen and read other posts similar to mine in this forum and I've noticed this app actually works on the specified phone. I just want to know how they did it (for some reason they never explain what to do specifically lol). Sorry to bother you all but can I ask for instructions on how to setup my app settings?

These are the issues that I'm experiencing right now with all settings untouched: 

https://user-images.githubusercontent.com/111864032/186147953-955c7c53-9c69-4375-a5f0-5418d2a6a4b6.mp4

Issue: Improper skill usage (skills used are not what I inputted in the command at all)

**Comment by reconman** [comment]
Try https://youtu.be/GZWPr2epXnA

**Comment by reconman** [comment]
The other users probably activated 3 button navigation.

FGO shows black bars in Gesture Navigation.

You'll have to use Custom Game Area mode if you want to keep using Gestures.

**Comment by deadxpoolz** [comment]
> The other users probably activated 3 button navigation.
> 
> FGO shows black bars in Gesture Navigation.
> 
> You'll have to use Custom Game Area mode if you want to keep using Gestures.

Is this what you mean?
![Screenshot_2022-08-24-08-23-24-307_com android settings](https://user-images.githubusercontent.com/111864032/186288452-aa0bb4e7-ecdb-4d44-ad59-31e601dc4839.jpg)

**Comment by deadxpoolz** [comment]
YO DUDE IT WORKED!! THANK YOU!!

What I did: 
1. Turn to Full Screen Gestures if you use Buttons
2. Turn off Game Turbo support for the game (not doing so would confuse the app by repeatedly tapping on the screen corner that opens the Game Turbo UI)
3. That's it!

Note: Sometimes when the battle starts, the app would suddenly open the Servant Detail of the middle servant. Though its not an issue since the app closes the window and resumes farming anyway. Hope this helps to fellow Poco X3 Pro users out there!

**Comment by reconman** [comment]
> Sometimes when the battle starts, the app would suddenly open the Servant Detail of the middle servant.

See bottom of the troubleshooting guide.

**Comment by reconman** [comment]
According to other users, you can get rid of the black bars in Settings -> Display -> Fullscreen mode.
