### ISSUE TITLE
Script just stops when prompted to select a support

### ISSUE THREAD

**Issue by ArdorXX** [Fate-Grand-Automata/FGA#1315]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1781

### Describe the bug

It runs the script fine but then just stops when selecting a support. I tried almost everything in settings but nothing seems to make it run again. Running on Ldplayer

### Video

![image](https://user-images.githubusercontent.com/111920295/186261323-c1375cf7-0237-4c0a-ad90-6558e93e5c38.png)

### Device model

LdPlayer4

### Android version

7

### Screen size

1920 x 1080

### RAM

4

**Comment by reconman** [comment]
Move the play button to the bottom left.

**Comment by ArdorXX** [comment]
Just tested it omg i cant believe it was that easy tyty
