### ISSUE TITLE
Support not being picked

### ISSUE THREAD

**Issue by JordanTheAmazing** [Fate-Grand-Automata/FGA#1316]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1784

### Describe the bug

For some reason it isn't tapping a support servant or swiping to look for one even when it is the first option

I have tried different things like changing the script or prefered mlb and such but still no luck
Normally I just delete and redownload but it doesn't seem to be working anymore

Any advice or guidence on this issue?

### Video

[https://youtu.be/DAHCnilaAFc](https://youtu.be/DAHCnilaAFc) 
![Screenshot_20220823-160902_FGA (CI)](https://user-images.githubusercontent.com/111921719/186268708-969c9be2-a6ce-4a87-930d-a61f3445ba39.jpg)
![Screenshot_20220823-160907_FGA (CI)](https://user-images.githubusercontent.com/111921719/186268726-649418bc-3de1-43f7-8299-a135b78ef2bb.jpg)

### Device model

Samsung note 8

### Android version

12

### Screen size

1440 x 2960

### RAM

6gb

**Comment by ArdorXX** [comment]
What was messing me up was the position of the play button. make sure that it is in the bottom left

**Comment by JordanTheAmazing** [comment]
> What was messing me up was the position of the play button. make sure that it is in the bottom left

It doesn't get in the way when it does its thing so I just left it

**Comment by vybze** [comment]
Play button is blocking the all icon which fga uses to check if it's on the support screen, check the troubleshooting guide for button placements

**Comment by reconman** [comment]
Basics are: Don't put the button anywhere with red rectangles or over any buttons, which only leaves bottom left in most cases.
