### ISSUE TITLE
FGA wont interact with new phone 

### ISSUE THREAD

**Issue by Hally349** [Fate-Grand-Automata/FGA#1317]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1871

### Describe the bug

FGA won't interact with the screen on a Samsung Galaxy Flip 3 

It won't use skills, interact with the support screen

### Video

![Screenshot_20220824-005326_FGA (CI)](https://user-images.githubusercontent.com/106229701/186286629-8000e599-4d41-485a-a148-1fabc9410c46.jpg)

### Device model

Samsung Galaxy Flip 3

### Android version

12

### RAM

12

**Comment by vybze** [comment]
How about posting a video showing the issues you're having, heck even a screenshot ingame with debug mode on would have been useful

**Comment by reconman** [comment]
I can say it should work according to #883.

As vybze said, I'll need more info to help you.
