### ISSUE TITLE
FGA gets stuck at support select menu

### ISSUE THREAD

**Issue by ManateeSmushy** [Fate-Grand-Automata/FGA#1320]
### Preparation

- [x] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [x] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1787

### Describe the bug

I use preferred support selection for selecting support servants and ce. My fallback is set to manual.

When FGA gets to the support menu, they are stuck on that menu and they do not move or select any servants, I have to manually select the support servant for FGA to continue. Besides that, FGA works fine.

### Video

https://youtu.be/K7W0JeC3yUo

### Device model

Galaxy Note10

### Android version

11

**Comment by reconman** [comment]
You broke FGA by recording with a 3rd party app.

Restart FGA's service and this time, use FGA's recording function as instructed.

**Comment by ManateeSmushy** [comment]
> 

okay, I've redone the video.
Also updated some new info, the issue onĺy affects my NA server now.
