### ISSUE TITLE
Help with configuration 

### ISSUE THREAD

**Issue by Alucardan2** [Fate-Grand-Automata/FGA#1323]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA, JP

### FGA build number

1709

### Describe the bug

With a new MIui update and the JP game going 60fps I was testing playing with Turbo in the Xiaomi Note 10 and I found that is running the game far better than expected. My issue begins when trying to start FGA with it. The moment FGA is testing the servant cards it pulls the Turbo menu and desynchs. Any advice on how to configure the FGA so both can work together?

### Video

https://youtu.be/gVHcU4CB_-U

### Device model

Xiaomi redmi note 10s

### Android version

12

### Screen size

1080x2400

### RAM

6GB

**Comment by reconman** [comment]
Sorry, FGA needs the top right because that's the only place we can use to close dialogs because everything else is covered in buttons or windows.

**Comment by Alucardan2** [comment]
Sucks but it is what it is, the new Game Turbo is great, Pushes NA to 60FPS and allows JP to go steady with almost no drop. But honestly I value FGA more. Thanks

**Comment by reconman** [comment]
For NA, there's BetterFGO by rayshift.io: #1300 
There's also a JP version, but FGA can't handle translated buttons right now.

**Comment by Alucardan2** [comment]
Mmm, don't think I will use it. Thanks anyway, I will save Turbo for fights, lostbelt and any other thing we're I don't need to farm.
