### ISSUE TITLE
FGA still not properly targeting

### ISSUE THREAD

**Issue by Fdot666** [Fate-Grand-Automata/FGA#1324]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1787

### Describe the bug

As the title says, the most recent update still has a bug that stops the correct servant from being targeted with skills. This may also prove to just be an emulator issue, because this exact macro works perfectly fine on my phone with my other account in the same aspect ratio.

### Video

https://user-images.githubusercontent.com/94520930/186691763-4bd6913d-ab4e-4a62-a398-1a61c9fddad0.mp4

### Device model

NoxPlayer 7.0.3.3

### Android version

7

### Screen size

1480x720

### RAM

4Gb

**Comment by reconman** [comment]
Don't open a new bug report for a non-fixed issue. Instead leave a comment on the original one.

**Comment by reconman** [comment]
Duplicate of #1314
