### ISSUE TITLE
Bad alignment/zone detection on Pixel 4a5g

### ISSUE THREAD

**Issue by MikiWho** [Fate-Grand-Automata/FGA#1326]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1796

### Describe the bug

FGA does not properly recognize full screen 

### Video

https://youtu.be/8fZr-s43kx0

### Device model

Pixel 4a5G

### Android version

12

**Comment by reconman** [comment]
Can you please do another video where you start from a fresh battle?

The issue is not caused by Skill Confirmation, right?

**Comment by MikiWho** [comment]
I tried Skill Confirmation both on and off with similar results. Which would you like for this video?

**Comment by reconman** [comment]
Please turn it off in both FGO and FGA.

**Comment by MikiWho** [comment]
![Screenshot_20220825-165528](https://user-images.githubusercontent.com/112128941/1
![Screenshot_20220825-165139](https://user-images.githubusercontent.com/112128941/186777552-c1a74154-7435-4cbe-9e0b-150830f34da6.png)
86777544-3c48c533-9006-4bf6-ac23-99ae475614ec.png)
![Screenshot_20220825-165205](https://user-images.githubusercontent.com/112128941/186777550-62d88e5f-f443-4791-965b-6b5eb5423809.png)


https://youtu.be/jSlezLexUfA

Script is supposed to be spishtar s1 then buffs onto her. It's placing onto Waver

**Comment by reconman** [comment]
Let me guess, the camera is in the top right during your recording?

Try rotating the screen by 180 degrees so the camera is in the bottom left.

**Comment by MikiWho** [comment]
Wild. Okay yeah that did it. Thanks

**Comment by reconman** [comment]
The issue is that the camera is blocking some taps in the top right, which are used to close the Servant details windows.

That's why FGA thought that only 1 Servant is alive, so every skill targeted the "only one" alive.
