### ISSUE TITLE
REDMAGIC 6S PRO WON'T LET ME START FGA

### ISSUE THREAD

**Issue by ghostdata2** [Fate-Grand-Automata/FGA#1327]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1798

### Describe the bug

when I start it those red lines appear, I was investigating and it seems that it is because of the black sides but it seems to me that my cell phone has other measurements because the one that is already resolved is 7 and mine is the REDMAGIC 6S PRO, I do not know if they have the same distance but could you help me tell me what I could do in this case please

### Video

![319f95ac-2012-42d0-9971-1b7c5e598682](https://user-images.githubusercontent.com/112136967/186792047-74fdd4ba-9cdd-4400-b3c3-c0348e262ec2.jpg)

### Device model

REDMAGIC 6S PRO

### Android version

11

### Screen size

1200x540

### RAM

16gb

**Comment by vybze** [comment]
Black bar on the right is what's causing the problem.
In more options, go to the advance tap and put game area on custom mode then increase right to 66

**Comment by ghostdata2** [comment]
I was trying several parameters and it turned out that 132 on the right is the right one, anyway thanks for your support <3
