### ISSUE TITLE
Black bars on Redmi Note 10S

### ISSUE THREAD

**Issue by HeteropodaMaxima** [Fate-Grand-Automata/FGA#1330]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1787

### Describe the bug

FGA is not working, simply when I play the button nothing happens, but when debug mode active show a lot of red squares flashing, can you help me to set a custom area mode appropriate to my phone?

### Video

https://streamable.com/0s55mx

### Device model

Xiaomi Redmi Note 10S

### Android version

11

### Screen size

2400x1080

### RAM

6GB

**Comment by vybze** [comment]
Similar to [#1308](https://github.com/Fate-Grand-Automata/FGA/issues/1308#issue-1347127223), you need to post a screenshot of fga ingame to get custom game area values. Hopefully they work for you unlike the last person

**Comment by sardilal** [comment]
Hey. Check if full screen mode is enabled for FGO.
Go to Settings > Screen > Full Screen Mode By App and enable FGO.
Should work by now, i had the same issue 15 mins ago and that solved it (Note 9s)

**Comment by HeteropodaMaxima** [comment]
> Hey. Check if full screen mode is enabled for FGO. Go to Settings > Screen > Full Screen Mode By App and enable FGO. Should work by now, i had the same issue 15 mins ago and that solved it (Note 9s)

Worked, thank you very much, I've tried this option before but the screen settings on fga was not on default
