### ISSUE TITLE
Won't read card info, can't record, and wont select right servant or skills

### ISSUE THREAD

**Issue by FinalQueue** [Fate-Grand-Automata/FGA#1333]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1801

### Describe the bug

As the title states, the app can't seem to properly tap the right things anymore (it worked fine for the prior two days), getting an error about card type error and i can't provide a video here because i can't record anything 

### Video

![Screenshot_20220826-200033_FateGO](https://user-images.githubusercontent.com/112219043/187005977-dcaef425-259f-499d-8aad-806eedcdd02a.jpg)
![Screenshot_20220826-200034_FateGO](https://user-images.githubusercontent.com/112219043/187005978-64c7186e-a4df-4b05-b373-0c8b9ae17faf.jpg)
![Screenshot_20220826-200043_FateGO](https://user-images.githubusercontent.com/112219043/187005980-d8f4a108-9dea-4a78-a1ab-365b4576748b.jpg)
![Screenshot_20220826-200050_FateGO](https://user-images.githubusercontent.com/112219043/187005981-57c41457-a0e5-47e6-ab38-26b7cb95b772.jpg)
![Screenshot_20220826-195947_FateGO](https://user-images.githubusercontent.com/112219043/187005982-f2d8e274-c7fd-4327-b62d-0e7e986df608.jpg)

### Device model

Galaxy Tab S7+

### Android version

12

**Comment by FinalQueue** [comment]
Ok, so i think i figured out a solution myself. I just screenshotted the starting turn and moved the screenshot into the folder that had the other FGA files to see if that will help the application understand where the skills were, which seems to work. No idea why it became an issue now when it was fine before

**Comment by ajbnrx** [comment]
you just put the screenshot inside the folder?

**Comment by FinalQueue** [comment]
> you just put the screenshot inside the folder?

When i first installed FGA i just told it to save the files to my Pictures folder. As i was messing with things to find a solution i saw a sub-folder has appeared with an empty video file inside (which i assumed was the failed recording attempt) so i just threw it in there to see what would happen. Didn't care if it would break it since it was already messing up anyways.

**Comment by ajbnrx** [comment]
oh I don't have a folder containing a video. I hope they will fix this soon lol

**Comment by reconman** [comment]
Pictures folder?

Usually you create and select a new folder somewhere in /storage/emulated/0 so the system ignores it.

Could be that some file access rights got messed up somehow.

Since the issue seems to be fixed, can you close this issue?
