### ISSUE TITLE
Stuck on support screen?

### ISSUE THREAD

**Issue by minhducsun2002** [Fate-Grand-Automata/FGA#1334]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1801

### Describe the bug

Literally the bug report title.

### Video

https://user-images.githubusercontent.com/32769878/187014015-ed64b56e-a781-4dbf-b322-2279f4318353.mp4

### Device model

BlueStacks 5.9.12.1003

### Android version

7

### Screen size

1280x720

### RAM

4GB

**Comment by ajbnrx** [comment]
did you fix it?

**Comment by reconman** [comment]
Do you mind trying 1080p resolution? Have you set up everything as instructed in the Emulator wiki page?

**Comment by slerch666** [comment]
Hello.

I see this same issue.

Samsung Galaxy Note Ultra.

I tried all of the 3 resolution options with the same results as the original poster.

If I manually choose support, then start FGA, it will play through one battle, then gets confused on the final item screen at the battle end

**Comment by minhducsun2002** [comment]
> Have you set up everything as instructed in the Emulator wiki page?

It has been working fine for 3 to 4 days before this issue, so I didn't really paid attention to the instructions. Nevertheless I think I didn't rotate the screen.

> Do you mind trying 1080p resolution?

Sure. Will report back.

**Comment by minhducsun2002** [comment]
I tried the rotation method mentioned in the wiki, and also used 1080p, in any order possible.

However it didn't fix the issue. Reinstalling did. I guess there is something inside BlueStacks messing with FGA when I choose the `Don't ask again` option (seems to happen on my phone too so this should be noted in the wiki?)

Closing.
