### ISSUE TITLE
App crash on load battle config with invalid file selection

### ISSUE THREAD

**Issue by item4** [Fate-Grand-Automata/FGA#1338]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

KR

### FGA build number

1801

### Describe the bug

1. Click Load AB config button
2. Select invalid file such as `.mp4` (not correct `.fga` file)

### Video

(Maybe not required for this case)

### Device model

Galaxy Note 20 Ultra

### Android version

12

### Screen size

Doesn't matter

### RAM

Doesn't matter

**Comment by reconman** [comment]
Android only seems to accept files with .json extensions now.

So existing battle config files need to be renamed to .json before they can be imported.
