### ISSUE TITLE
Gift box scrolls to bottom forever

### ISSUE THREAD

**Issue by runelt99** [Fate-Grand-Automata/FGA#1340]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1771

### Describe the bug

When  collecting embers (from lotto) in the gift box it will scroll down forever. Even after it passes all the actual embers and start moving into nothing. At first I thought the issue was me using filler (to only see one type of ember) but then tried without filter and still had same result. Then thought that maybe I have outdated fga but there wasn't an update.

Also once its over taking stuff from lotto it also continues clicking.

### Video

https://youtu.be/-O4MBE6W67s

### Device model

LDPlayer9

### Android version

9

### Screen size

1080x1920

### RAM

4gb

**Comment by runelt99** [comment]
Oh forgot to mention, at end it looks like its scrolling up, it actually isn't. Since fga is constantly trying to click, I was unable to stop the script so I kept clicking the one spot which conflicted a bit. In normal case where I don't interfere it scrolls..

**Comment by reconman** [comment]
The region for detecting the end of the scrollbar was too low.

I fixed it just now. It will still scroll a bit after reaching the end, that's a mechanism for ensuring that it didn't miss any embers at the end of the list.
