### ISSUE TITLE
Unable to choose folder for Support images, etc

### ISSUE THREAD

**Issue by Flowtaro** [Fate-Grand-Automata/FGA#1342]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1805

### Describe the bug

Howdy folks, I feel like I'm missing something fundamental here, but when I go to select the folder for support images, etc., I'm just sent to the Recent directory, and there's nothing there. I can't select anything else, and for whatever reason I can't create a new folder. Even having a separate file directory app, folders I create with it aren't appearing. I've followed the instructions in the Emulator troubleshooting section and I've tried searching through multiple closed issues but didn't find an answer to my issue. If this is a Bluestacks problem, I can check with them too. Thanks!

### Video

![choose folder 1](https://user-images.githubusercontent.com/112279945/187046555-e94bcf42-ae9d-4263-b26a-338f0eba698d.PNG)
![choose folder 2](https://user-images.githubusercontent.com/112279945/187046557-2e134768-1161-452a-bcec-f2122626c0ff.PNG)
![choose folder 3](https://user-images.githubusercontent.com/112279945/187046560-4fff1e27-f971-421f-b11d-e1f7b57c829d.PNG)

### Device model

Bluestacks 5

### Android version

12

### RAM

4

**Comment by reconman** [comment]
Click "Show internal storage", then click Recent again and you should have a selection of directories.

**Comment by Flowtaro** [comment]
I appreciate the quick response, reconman. I forgot to mention in the description, I've tried to "Show internal storage," but unfortunately it just shows the same thing:
![choose folder 4](https://user-images.githubusercontent.com/112279945/187048332-8cf45169-476e-47c7-b168-37b4e0ba7f04.PNG)

**Comment by reconman** [comment]
> then click Recent again

Should be different from screenshot 2 now.

**Comment by Flowtaro** [comment]
wow, I feel like a big idiot. I swear I tried that a few times. folders are showing up now. thanks so much!! I felt like I was losing my mind.

**Comment by reconman** [comment]
I struggled with it too at first. The stock file selector is badly designed.

**Comment by Flowtaro** [comment]
Agreed. And thank you for your thorough video tutorial! Everything's working perfectly for me now.
