### ISSUE TITLE
FGA don´t make any click

### ISSUE THREAD

**Issue by Aardavak** [Fate-Grand-Automata/FGA#1343]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1818

### Describe the bug

After starting the PLAY button my FGA don´t make any click

### Video

https://youtu.be/3r2kHazxkrk

### Device model

Xiaomi MI 8 Lite

### Android version

10

### Screen size

1080x2280

### RAM

4GB

**Comment by vybze** [comment]
Try this https://github.com/Fate-Grand-Automata/FGA/issues/1330#issuecomment-1228051383

**Comment by Aardavak** [comment]
Thanks, it´s worked!

If anyone have the same issue, try sardilal comment linked above:

Hey. Check if full screen mode is enabled for FGO.
Go to Settings > Screen > Full Screen Mode By App and enable FGO.
Should work by now, i had the same issue 15 mins ago and that solved it (Note 9s)
