### ISSUE TITLE
Image maker doesn't appear on bottom left

### ISSUE THREAD

**Issue by AlessandraYH** [Fate-Grand-Automata/FGA#1344]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1818

### Describe the bug

Image maker doesn't appear as an option on the bottom left.  I saw some with the same problem, but didn't find the if they found a solutions. 

### Video

https://www.youtube.com/watch?v=JZDKx7zcnAQ

### Device model

Xiaomi MI 9 SE

### Android version

10

### Screen size

1080 x 2340

### RAM

6 GB

**Comment by reconman** [comment]
You're not recording with FGA as instructed.

Because you used Android's built-in recorder, you made FGA blind.

Stop the FGA service, enable Recording in More Options, start the FGA service again and then try again.

The problem will probably disappear as soon as you've restarted the service.

**Comment by AlessandraYH** [comment]
I did enable the record screen now and restarted it. But i noticed that the use root for screenshots failed to get access, do you have any idea how to resolve this problem?
https://imgur.com/a/JlaufeA

**Comment by reconman** [comment]
You can only use "root mode" if you've unlocked your Bootloader and installed Magisk.

If you don't know what this means, ignore that config option.

**Comment by AlessandraYH** [comment]
I restarted my device, restarted the app too. Also i noticed that the app doesn't start the battle tbh. 
I'm trying to follow the guide frow youtube. That's why i asked about the root settings.  
Now the record file appeared at least, and it's like this https://www.youtube.com/watch?v=VRLJsU2ey14

The tap was made by me. Should i try usign the later versions?

**Comment by reconman** [comment]
https://github.com/Fate-Grand-Automata/FGA/wiki/Game-Area-detection#case-1-borders-around-fgo-are-black

**Comment by AlessandraYH** [comment]
Everything is working smoothly now, the button appeared too, thank you so much!
