### ISSUE TITLE
Is there Z fold 4 Support?

### ISSUE THREAD

**Issue by Dragonking890** [Fate-Grand-Automata/FGA#1345]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Hi, I've been trying to use FGA on the Samsung z Fold 4 since Wednesday. I got it a few days early. It gets stuck on the select support screen. I'm not sure if the screen on the fold 4 is the problem or not, so if someone could help that'd be great. 
[](https://user-images.githubusercontent.com/112303702/187059524-f7ba296b-5fd1-492d-8094-5ef3a83184de.jpg)

**Comment by vybze** [comment]
From what I read from https://github.com/Fate-Grand-Automata/FGA/issues/1072 it does seems to work on the fold 3. Does your screen have black bars on any side of the screen when you're playing fgo?

**Comment by Dragonking890** [comment]
> From what I read from #1072 it does seems to work on the fold 3. Does your screen have black bars on any side of the screen when you're playing fgo?
Nope, it's in full-screen mode. Also it's the Z fold 4 that just came out this past Friday

**Comment by vybze** [comment]
Can you post a video with fga running in debug mode?

**Comment by Dragonking890** [comment]
Here you go, hopefully this helps

https://user-images.githubusercontent.com/112303702/187068347-ec0139d8-f34f-4cdc-9880-e5fa9ff89e4c.mp4

**Comment by reconman** [comment]
Video seems broken. Can't play it.

**Comment by Dragonking890** [comment]
I see that, I'm getting an error saying this.
![Screenshot_20220828_061740_FateGO](https://user-images.githubusercontent.com/112303702/187069016-278cea8e-48cd-489f-98c2-d23e54faf0eb.jpg)

**Comment by Dragonking890** [comment]
I did manage to catch a screenshot of how the support list in debug mode looks though if that helps
![Screenshot_20220828_063341_FateGO](https://user-images.githubusercontent.com/112303702/187069806-f7fff61e-8bf9-40c1-921b-8faad84f79cc.jpg)

**Comment by vybze** [comment]
Does fga works if you start it at the battle screen?
I remember that a one time some got the support screen to work by starting from the battle screen instead of the support or the quest selection screen.

**Comment by vybze** [comment]
I think you need to change the label from a question to a bug report and I you need change the to something like Support Section not working on the Fold 4

**Comment by Dragonking890** [comment]
It does work on the battle screen. It just won't select support even after battle. I will change the label

**Comment by reconman** [comment]
Can you try to get the recording working somehow? Maybe deleting the existing mp4 file helps.

The rectangles on the support screen look normal to me.

**Comment by Dragonking890** [comment]
Okay, it started working even though I didn't change anything. I don't know what happened but I will keep this thread open for a little bit longer in case it stops working again.

**Comment by bakoolgun** [comment]
I'm having the same issue as well, it works fine on the main screen, but on the cover screen, battle is fine, but when it's on the support select, it doesn't do anything. Even when I start the script from the battle itself, when it repeats and reaches the support list, it just doesn't do anything.

**Comment by reconman** [comment]
@bakoolgun Where's your play button? Do you have black bars?

**Comment by bakoolgun** [comment]
@reconman 
![Screenshot_20220904_054017_FateGO](https://user-images.githubusercontent.com/112778234/188288512-b63f6431-6a1b-4821-9966-cbc849e3fa0a.jpg)

This is how my screen looks like and it doesn't select the support.

**Comment by Songend** [comment]
I'm also having this same issue on my Fold 4. FGA never scrolls or selects on the support screen if I'm playing on the cover screen. It's pretty inconvenient if I want to farm discretely at work, and I don't know what the issue is.

https://user-images.githubusercontent.com/112224873/208313857-23424c59-e164-445d-b177-83bcb5ae1d89.mp4

**Comment by reconman** [comment]
@Songend You broke MeriaProjection by not using FGA to record.

You have to restart the FGA service and record with FGA under More Options -> Advanced.

**Comment by Songend** [comment]
I tried that a couple of times, and it just gives me an error like Dragonking890 with a corrupted recording.

**Comment by reconman** [comment]
It seems like the Android API doesn't give me any options to specify which screen should be captured.

I can only find stackoverflow posts without answers like this one: https://stackoverflow.com/questions/69538637/screen-projection-not-supported-on-secondary-displays

So sadly, FGA can't work on the cover screen.

**Comment by ValleyWindy** [comment]
Hi, I just wanted to check, so FGA won't work on the cover screen? I recall it working a few months ago. I'm not able to get the FGA recording to work, but what I recorded below is essentially what I see when I try using FGA. It looks like it's trying to tap but unable to? I turned off battery optimizationfor both FGO and FGA.

For me, it's not working on the cover screen or the inside screen. I can share the inside screen footage too if the cover screen is a lost cause. Thanks!

https://user-images.githubusercontent.com/121014366/208744050-68e3df07-c14b-411f-ac18-efd864ded785.mp4

**Comment by ValleyWindy** [comment]
Actually, here is the inside screen just in case that helps!

https://user-images.githubusercontent.com/121014366/208744878-5578ffa2-9c83-4a68-b780-e491869cfdaa.mp4

**Comment by reconman** [comment]
In both videos, FGA is extremely slow.

Takes 5x as long as normal to detect images.

Not really sure why.

**Comment by F3DE1897** [comment]
I'm having the same issue as well

**Comment by reconman** [comment]
From Discord:

You want to go in Settings -> Display -> Camera cutout. In there find the FGO app and set it to 'Hide camera cutout'. This should introduce a black bar when you open the game like in the picture. 
Then in the FGA app change your 'Game area mode' ('More options' -> 'Advanced') to 'Custom' and set 'Left' to 87. (Or you can go to the megathread on github and post a screenshot of your game, to get the offsets yourself - https://github.com/Fate-Grand-Automata/FGA/issues/1347#issuecomment-1621072878, but this should work for the Fold 4)
