### ISSUE TITLE
Will not select support on OnePlus 8t

### ISSUE THREAD

**Issue by tricerazord** [Fate-Grand-Automata/FGA#1346]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1818

### Describe the bug

After pressing the play button, fga fails to select a support and instead just tries to detect small random parts of the screen. 

### Video

https://user-images.githubusercontent.com/112324288/187073675-32854c55-5c06-4077-80ba-c8ec9ed77cba.mp4

### Device model

OnePlus 8t

### Android version

12

### Screen size

2,400x1,080

### RAM

12GB

**Comment by FroyaReikansei** [comment]
Hello, I had the same problem since yesterday, and I just "solved it" by moving the button that starts the script to the right side of the screen, you don't lose anything trying, good luck!
I use Nox emulator.

I wanted to record a video but the error no longer occurs.

**Comment by reconman** [comment]
Since you have black bars and probably configured Custom Game Area mode, it currently only works in one rotation.

Rotate your screen so the camera is in the bottom left.

**Comment by tricerazord** [comment]
> Since you have black bars and probably configured Custom Game Area mode, it currently only works in one rotation.
> 
> Rotate your screen so the camera is in the bottom left.

It still does not select a support

https://user-images.githubusercontent.com/112324288/187074625-038b22cd-e17c-4314-95d2-d1a1d48714ee.mp4

**Comment by reconman** [comment]
That means you've updated your OS or you've changed your navigation mode to Gesture navigation.

Both make the black bars on the sides appear. I've already reported the black bars to FGO support. Maybe they'll fix it sooner if more people report the same problem.

For now, use the same values as https://github.com/Fate-Grand-Automata/FGA/issues/1201#issuecomment-1146669870 to deal with the black bars.

**Comment by tricerazord** [comment]
> That means you've updated your OS or you've changed your navigation mode to Gesture navigation.
> 
> Both make the black bars on the sides appear. I've already reported the black bars to FGO support. Maybe they'll fix it sooner if more people report the same problem.
> 
> For now, use the same values as [#1201 (comment)](https://github.com/Fate-Grand-Automata/FGA/issues/1201#issuecomment-1146669870) to deal with the black bars.

Thank you so much you are a life saver!
