### ISSUE TITLE
Stuck in Status Servant after fail Skill.

### ISSUE THREAD

**Issue by ferdinand957** [Fate-Grand-Automata/FGA#1350]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1707

### Describe the bug

Hi, i have the problem when old version installed in my emulator bluestacks the problem is after the FGA failed to determinate the order of cards stucks in the status servant.

the unique form for me to solve is close the window and the FGA starts to work again.
is a problem with my old version o there is another thing?

![com mathewsachin fategrandauto_Screenshot_2022 08 29_07 07 14](https://user-images.githubusercontent.com/112396625/187202269-17b1b57c-bf05-47b4-bab5-09b71ba6c72a.png)

### Video

Uploading BlueStacks_Recording_2022.08.29_07.28.44.30.mp4…

https://user-images.githubusercontent.com/112396625/187202782-492ad8f0-c404-433a-a133-458ff79cfbf4.mp4

### Device model

Bluestacks

### Android version

7

### Screen size

1280x720

### RAM

3GB

**Comment by reconman** [comment]
Duplicate
