### ISSUE TITLE
Android 13 screen recording issues

### ISSUE THREAD

**Issue by dwennon** [Fate-Grand-Automata/FGA#1351]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1820

### Describe the bug

Currently FGA will sometimes go through the normal processes it's supposed with servant/team select, then when in battle it doesn't actually do anything beyond occasionally click servant status or click battle then click off. Leaving it be for a few minutes will see this repeat, and no changes occuring.

Recently I was forced into updating to android 13, my device installed it and rebooted without my permission, and I had though it might be an issue with the version of FGA. So I tried updating it. Then I attempted to uninstall and reinstall FGA, which also didn't fix anything. So I'm unsure if the android update is the issue, or something else that should be very obvious.

### Video

https://www.veed.io/view/5beaf8eb-691e-4d74-bfcd-ffe207d5f889?sharingWidget=true

### Device model

Pixel 4a

### Android version

12

**Comment by reconman** [comment]
Looks to me like FGA's screenshot service only sees the image you're starting with.

If you start on the Support screen, it will only see that you're still in Support selection. If you start in battle, it will only see the first wave.

The weird thing is that video recording is still fine.

What happens if you disable recording, does it still happen?

**Comment by dwennon** [comment]
Turning off video recording fixed it, I didn't even think that might factor into things. Although I still occasionally need to turn FGA on and off again to get it to actually work. Kinda worries me though if other issues pop up and I can't record the screen with FGA.

**Comment by reconman** [comment]
I might have an idea, but it will take some time to test.

Most app developers either record video or take screenshots, but don't do both at the same time.

**Comment by dwennon** [comment]
> I might have an idea, but it will take some time to test.
> 
> Most app developers either record video or take screenshots, but don't do both at the same time.

Well alright, at least it's working now so I'm not in a huge rush. But getting it fixed if reasonably possible would be nice.

**Comment by reconman** [comment]
Please test https://github.com/Fate-Grand-Automata/FGA/suites/8038504796/artifacts/345614597

**Comment by dwennon** [comment]
That didn't seem to do much of anything that's observable to me. Pretty much acting as it was before with the auto record on, turning it back off and toggling FGA on and off got it working again.

No clue what's up though.

**Comment by reconman** [comment]
Can reproduce it now that I've updated to Android 13.

I'll try and find a solution in the near future.

**Comment by reconman** [comment]
@dwennon Can you please test https://github.com/Fate-Grand-Automata/FGA/suites/9272837883/artifacts/434387737

I've made it so the screen capture is more resilient and I've removed FGA's screen recording functionality.

Instead, FGA should now continue to work when using Android's recording function.
