### ISSUE TITLE
Skadi(Ruler)

### ISSUE THREAD

**Issue by Fiero317mamut** [Fate-Grand-Automata/FGA#1353]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Can you put Skadi(Ruler) in specific selection of support?
Thanks

**Comment by vybze** [comment]
I have 3 of the ruler skadi ascension already but I can't seem to find someone using the 4th 
![Ruler Skadi 1](https://user-images.githubusercontent.com/32293918/187338024-4531079d-6ce8-4a19-bcaf-a0497f9e9d82.png)
![Ruler Skadi 2](https://user-images.githubusercontent.com/32293918/187338026-62719731-36a6-4efb-ba65-26b5f95a2ec6.png)
![Ruler Skadi 3](https://user-images.githubusercontent.com/32293918/187338028-22ef7bd6-ddec-436e-abd2-5c340a1b6181.png)

**Comment by reconman** [comment]
Probably because of this setting

![Screenshot_2022-08-30-07-02-51-64_f98d04a6a5569a2ca2cd39796e1f730e.jpg](https://user-images.githubusercontent.com/12360257/187353439-ca009835-1c8c-43ff-b832-6ccf88d0a1e1.jpg)

It's the second on/off switch after text speed.

**Comment by vybze** [comment]
Yeah the spoiler setting was preventing me from finding the 4th

**Comment by reconman** [comment]
I was talking about Final Ascension, since Skadi isn't part of any Lostbelt.

**Comment by vybze** [comment]
The event was hiding her final ascension because they considered it spoilers for some reason

**Comment by egotistix** [comment]
Will Skadi Ruler be added?

**Comment by reconman** [comment]
@egotistix Was already added, you probably have to press Extract Default Support Images
