### ISSUE TITLE
Can't select support servant

### ISSUE THREAD

**Issue by NgBi** [Fate-Grand-Automata/FGA#1356]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1823

### Describe the bug

Hello,

As the title describes it, FGA isn't selecting any support servant. I have tested the support in ALL of the different settings possible (first, manual, preferred etc...) and they all just look like manual setting and that's it.

Based on what I see while on debug mode, when arriving on the support window FGA just totally skip the support selection process and go directly into battle process. My phone screen size do match FGA's basic configuration (because it was working totally fine few days ago) and now it just doesn't anymore.

### Video

https://user-images.githubusercontent.com/72802549/187541207-3cd93cbc-4c99-4ab1-b361-c6a67f47cf4f.mp4

### Device model

Xiaomi MI 9

### Android version

10

### Screen size

2340 x 1080

### RAM

6GB

**Comment by reconman** [comment]
Move play button to bottom left
