### ISSUE TITLE
Apple Screen JP Updated (Again) 

### ISSUE THREAD

**Issue by vybze** [Fate-Grand-Automata/FGA#1357]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

A new update for jp now allows you to refill the ap bar with multiple apples at once (using more than one of the same apple) depending on which apple you use which also adds changes to the apple refill screen https://youtu.be/TCK68wHG2ik

**Comment by vybze** [comment]
https://youtu.be/TCK68wHG2ik

**Comment by reconman** [comment]
How does it look like when starting a quest?

FGA doesn't tap on the AP bar but instead uses the dialog opened when you try starting a "red" quest.

For example, if you select a Copper Apple after clicking on the AP bar, it will refill 10 AP. If you instead try starting a quest, it uses multiple apples at once until you have enough for the quest.

**Comment by vybze** [comment]
It seems nothing much has changed apart from being able to fill your ap gauge with lower ap apples in one go instead of doing it multiple times 
https://youtu.be/e5Bf_yDfiRI

**Comment by reconman** [comment]
Can you please test refill? Does it miss the confirm button?

I saw that FGO selects 3 Copper Apples automatically, for the other ones 1 apple fills more than 21 AP, so 1 is selected as default.

**Comment by vybze** [comment]
https://user-images.githubusercontent.com/32293918/187796817-62428c1b-c7f7-42ea-b0c5-ebee64cf08d4.mp4

Refill seems to be working fine too

**Comment by reconman** [comment]
Then I'm closing this issue.
