### ISSUE TITLE
It can't choose the right servent 

### ISSUE THREAD

**Issue by JoshLin0526** [Fate-Grand-Automata/FGA#1358]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

TW

### FGA build number

1823

### Describe the bug

I had many time seeing this.
Everything goes well but this.

### Video

![Screenshot_2022-09-01-06-26-11-982_com xiaomeng fategrandorder](https://user-images.githubusercontent.com/60044184/187796395-d4578a5f-de2b-41bd-987c-169c58dc804b.jpg)

### Device model

Xiaomi Redmi note 7

### Android version

12

**Comment by reconman** [comment]
Try "Extract Default Support Images".

If that doesn't help, delete and recreate the support folder.
