### ISSUE TITLE
Samsung Galaxy tab s7 FE wont target my characters with corrceth skills

### ISSUE THREAD

**Issue by sayyid011** [Fate-Grand-Automata/FGA#1365]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1823

### Describe the bug

the app is not properly targeting my servants with the single taerget skills

### Video

https://drive.google.com/file/d/1nDcorRFj_BxqRoDcjJ0gkVOoDYHD9mwn/view?usp=sharing

### Device model

Samsung Galaxy tab s7 FE

### Android version

12

### Screen size

2,560 x1,600

### RAM

4GB

**Comment by vybze** [comment]
https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting#uses-skills-on-the-wrong-servant-or-doesnt-use-skills-at-all

**Comment by sayyid011** [comment]
@vybze tried all of that not sure which is wrong did you see the video?
