### ISSUE TITLE
Add Lady Avalon's images to default supports

### ISSUE THREAD

**Issue by jcdeoferio** [Fate-Grand-Automata/FGA#1367]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Arts version of Merlin. Will get some use in raids or other farming parties.

**Comment by vybze** [comment]
![Lady Avalon 1](https://user-images.githubusercontent.com/32293918/188070218-88f9f8a5-2888-407c-9e82-4c44c791a26f.png)
![Lady Avalon 3](https://user-images.githubusercontent.com/32293918/188070224-0adeae4c-0a29-4c72-aa41-8aee81ee5aac.png)
![Lady Avalon 2](https://user-images.githubusercontent.com/32293918/188070226-1247437e-22f1-4eaf-9fd0-40ae045274e9.png)
![Lady Avalon 4](https://user-images.githubusercontent.com/32293918/188070227-2ba05839-13a1-4efc-b0a6-945f0f0d96f7.png)
The first and third looks too much alike

**Comment by reconman** [comment]
@vybze Don't you mean 1 and 2?

**Comment by vybze** [comment]
Ascension 1 and 3 looked too much alike, ascension 2 is the swimsuit version so the face looks different. The images got mixed up during the upload

**Comment by vybze** [comment]
![Lady Avalon 1](https://user-images.githubusercontent.com/32293918/188183072-228871fa-9fda-42a6-a038-f222a6cae5e5.png)
![Lady Avalon 2](https://user-images.githubusercontent.com/32293918/188183119-dba24402-5b27-468c-8e58-885309e3554c.png)
![Lady Avalon 3](https://user-images.githubusercontent.com/32293918/188183156-e22958f2-4e4f-48e4-9691-84bcebc86050.png)
![Lady Avalon 4](https://user-images.githubusercontent.com/32293918/188183212-06b38cd7-f479-4f65-9941-274d04e25aac.png)

**Comment by reconman** [comment]
@vybze Next time, you could open a Pull Request to save me some trouble.

This folder contains all default Servants: https://github.com/Fate-Grand-Automata/FGA/tree/07ad2f739c922cf1115cf9278715d9f85f1813ab/app/src/main/assets/Support/servant

Here's how I added Skadi Ruler: https://github.com/Fate-Grand-Automata/FGA/commit/07ad2f739c922cf1115cf9278715d9f85f1813ab

**Comment by vybze** [comment]
@reconman I'll keep that in mind for next time
