### ISSUE TITLE
how to fix unexpected error width must be positive fga

### ISSUE THREAD

**Issue by Rin5211** [Fate-Grand-Automata/FGA#1368]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1023

### Describe the bug

![Screenshot_20220902-233124_FateGO](https://user-images.githubusercontent.com/112718992/188200566-38657e5b-bde2-4242-b3cd-055566ff1fdc.jpg)

### Video

null

t4.a$b
	at t4.a.b(AutoBattle.kt:3)
	at t5.e.z(EntryPoint.kt:3)
	at g6.a.run(Unknown Source:2)

### Device model

Samsung A31

### Android version

11

**Comment by Rin5211** [comment]
https://user-images.githubusercontent.com/112718992/188201622-53a72a5f-b128-44c5-82de-1d0ac3d3ca4d.mp4

**Comment by reconman** [comment]
> I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))

https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+width+must+be+positive
