### ISSUE TITLE
FGA not working fine on my Samsung galaxy A12

### ISSUE THREAD

**Issue by xXIIDeaDLocKIIXx** [Fate-Grand-Automata/FGA#1371]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

I followed every troubleshooting steps and watched different guides but still nothing works. even tried restarting my phone several times now. I've been struggling for days now and I am running out of time to clear the shishou event. anyone can help me how to fix this? except for lottery, nothing works fine on my fga. whenever I use my configs fga clicks the wrong parts of the screen until I stopped it. I figured I should ask here since no one on fb and yt can answer my question. my phone model is Samsung Galaxy A12

edit: pls don't mind my background noise, I was watching a podcast and didn't realize the screen record included my mic

https://user-images.githubusercontent.com/87340337/188279396-3eb5e76d-1945-455e-b2c0-aa8f8aed31dd.mp4

**Comment by vybze** [comment]
1) move the play button back to the back to the bottom left corner of the screen or look in the troubleshooting guide for button placement
2) it seems that during the first few seconds of the video your phone locked up which can really mess with fga, is normal for your phone to freeze when playing fgo? 
3) it seems you have skill confirmation on in fgo but you didn't turn it on in fga. Please go through the troubleshooting guide again https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting

**Comment by reconman** [comment]
Additionally to the points above, recording the screen while FGA is running while mess up everything.

That's why you're told to use FGA's recording function in the bug template, which you didn't use, even though you're clearly reporting a problem.

**Comment by TheRealPlagiariser** [comment]
The freeze is an occuring FGO issue on new android version (not related to FGA)
Please download/update "Android System WebView" available via playstore (get the beta version where possible)
Additionally on Samsung phone, disable game launcher app. and always start FGO from app drawer instead.
Restart phone after doing everything
Source - FGO unofficial discord
Should be closed as it's not related to FGA
