### ISSUE TITLE
Lady Avalon and Vitch not appearing in preferred servants

### ISSUE THREAD

**Issue by iloveerio** [Fate-Grand-Automata/FGA#1372]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Hey there! Both servants wont appear even if I tried reinstalling the app. I have a friend that shares almost the same phone model(mi10t pro) and both servants appear on their list. 
![Screenshot_2022-09-07-14-43-04-677_com mathewsachin fategrandautomata debug](https://user-images.githubusercontent.com/113009478/188807752-ec13d7b2-60db-4036-87f5-bc7dc979f54e.jpg)

I tried searching topics related to this but I am unable to find one. Thanks!

**Comment by reconman** [comment]
Press Extract Default Support Images under More Options -> Storage
