### ISSUE TITLE
FGO problem with clicking 

### ISSUE THREAD

**Issue by Aster871** [Fate-Grand-Automata/FGA#1373]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1830

### Describe the bug

Now, I'm using a Galaxy S20. I tried running the script. Looks at info, no problem, However, when it comes to actually clicking skills, it doesn't respond as it should when it comes to actually select the skills

### Video

[Here's the video](https://youtu.be/QX6kDw7CjLw)

### Device model

Galaxy S20+

### Android version

12

### Screen size

1440 x 3200

### RAM

8 GB

**Comment by reconman** [comment]
https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting#uses-skills-on-the-wrong-servant-or-doesnt-use-skills-at-all
