### ISSUE TITLE
auto Sappling to Bronze Apple when stamina fills?

### ISSUE THREAD

**Issue by thunderkai** [Fate-Grand-Automata/FGA#1379]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

no more wasted AP, when 40 ap comes in (i think) it converts it into Bronze Apple

**Comment by reconman** [comment]
I don't know what you want. You'll need to provide a better description.

**Comment by vybze** [comment]
I believe they are asking for auto making of blue apples when ap is full. Strange someone would that automated and not something more tedious 🤔

**Comment by reconman** [comment]
Closing because of missing information.
