### ISSUE TITLE
An error was reported when selecting support

### ISSUE THREAD

**Issue by Nagoto1096** [Fate-Grand-Automata/FGA#1381]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1836

### Describe the bug

An error was reported when selecting support. An unknown error: Java. Lang. Illegalargumentexception: width must be positive

### Video

![Screenshot_2022-09-13-12-37-36-511_com bilibili fatego](https://user-images.githubusercontent.com/59811293/189811021-e99533ec-9f5e-4225-ad5d-8e688007b3b1.jpg)

https://user-images.githubusercontent.com/59811293/189811823-39360b62-b67e-4cfa-b1ea-83c1322ad88e.mp4

### Device model

redmi k50

### Android version

12

### Screen size

3220*1440

### RAM

12

**Comment by reconman** [comment]
https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+width+must+be+positive

Can you please tell me if it works?

**Comment by Nagoto1096** [comment]
> https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+width+must+be+positive
> 
> 你能告诉我它是否有效吗？

It seems to be an older version of the support images. After deleting it and putting in a new support servant image, the problem was resolved.
thanks.
