### ISSUE TITLE
I have a problem with FGA, it doesn't let me use the np, only the skills. Help me

### ISSUE THREAD

**Issue by RhennSM** [Fate-Grand-Automata/FGA#1384]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1836

### Describe the bug

When I enter the quest, FGA only activates the abilities of the servants but does not activate the np of them.
![WhatsApp Image 2022-09-17 at 02 07 54](https://user-images.githubusercontent.com/113757440/190845115-26db9820-4263-4088-a220-4ada7adb30fb.jpeg)

### Video

.

### Device model

Motorola G7 power

### Android version

10

### Screen size

1512x720

### RAM

4

**Comment by reconman** [comment]
Video is needed. Also, what's your command?

**Comment by RhennSM** [comment]
> Se necesita vídeo. Además, ¿cuál es tu comando?

How do I find my command?

**Comment by reconman** [comment]
![Screenshot_2022-09-17-09-17-39-89_a3958233ae0a6cb82869d8ec995a3cb9.jpg](https://user-images.githubusercontent.com/12360257/190845414-30d07225-c6d6-4a3e-9a93-16934d919a2c.jpg)

**Comment by RhennSM** [comment]
![WhatsApp Image 2022-09-17 at 02 25 37](https://user-images.githubusercontent.com/113757440/190846380-6108b98f-2308-43b7-ab78-00dfa49f3932.jpeg)

Video: https://fromsmash.com/videofga

**Comment by reconman** [comment]
You chose the middle NP, but Jeanne is on the right.

Replace 5 with 6.
