### ISSUE TITLE
FGA Picks Wrong Servant For Targetable Skills

### ISSUE THREAD

**Issue by PotatEx** [Fate-Grand-Automata/FGA#1386]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1836

### Describe the bug

On the first turn, when targeting the servant in the middle with Castoria's skills, it'll instead select the right most Castoria instead. The servant in the center will still use her skills on herself as instructed.
On the 2nd turn Oberon will also use his skills on himself (right most) instead of middle servant.
NP Selection seems to be working in the intended order.

At a certain point, "Unable to determine card type" starts appearing.

### Video

[Video](https://www.youtube.com/watch?v=vYzFSA_DCgA[](url))

### Device model

POCO X3 Pro

### Android version

12

### Screen size

1080x2400

### RAM

8

**Comment by vybze** [comment]
Can you post a screenshot of your battle script?

**Comment by PotatEx** [comment]
![Screenshot_2022-09-23-21-41-13-014_com mathewsachin fategrandautomata debug](https://user-images.githubusercontent.com/114202537/192054308-ba620c93-b7d8-4f7f-a120-9687db00ed99.jpg)
Will this be enough?

**Comment by vybze** [comment]
Do you have skill use confirmation turned on in fga?

**Comment by PotatEx** [comment]
![Uploading Screenshot_2022-09-24-01-08-49-436_com.mathewsachin.fategrandautomata.debug.jpg…]()

**Comment by PotatEx** [comment]
![Screenshot_2022-09-24-01-08-41-312_com mathewsachin fategrandautomata debug](https://user-images.githubusercontent.com/114202537/192071363-e5c98a48-fd69-41ce-8c24-8c919d709aad.jpg)

**Comment by vybze** [comment]
That's the problem, just turn it off and you're good to go

**Comment by PotatEx** [comment]
...Just tested. It works. Apologies for opening a ticket on something so easily fixable.
