### ISSUE TITLE
About Enable Withdraw

### ISSUE THREAD

**Issue by LinSDK** [Fate-Grand-Automata/FGA#1387]
### Preparation

- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

I have a specific strategy to clear a battle, and it requires the Battle 1/2 to be cleared in less than 2 turns, and I've been trying to find an option that allows you to withdraw if Battle 1/2 lasts longer than 2 turns, because the next Battle will be sure to fail.

I figured Enable Withdraw could help with this, I can't seem to find in the Troubleshooting Guide about what exactly this option does and it doesn't appear to be doing anything. Is there a possible way to do the above? Or perhaps a way to have control over when to withdraw?

Thanks

**Comment by vybze** [comment]
Withdraw from battle only happens after your entire party dies during battle and the three options that allows you to either use quartz, command seal or the blue cubes to revive and the option to withdraw appears

**Comment by reconman** [comment]
I'll add a short description in the app, @vybze is right.
