### ISSUE TITLE
FGA cannot select support servant on my realme gt

### ISSUE THREAD

**Issue by 20040819** [Fate-Grand-Automata/FGA#1388]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

TW

### FGA build number

1836

### Describe the bug

FGA cannot select support servant on my realme gt

### Video

Pls help me

https://user-images.githubusercontent.com/114370033/192174391-d52e79fa-93c4-4572-8c3b-bf5a9c28588b.mp4

### Device model

realme gt

### Android version

12

### Screen size

2400×1080

### RAM

12

**Comment by vybze** [comment]
https://github.com/Fate-Grand-Automata/FGA/issues/1347

**Comment by reconman** [comment]
Your play button is in the wrong position, should be in the bottom left.

https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting#doesnt-work-on-some-screens
