### ISSUE TITLE
FGA Skipping Face Card Check & Failed to Determine Card Types

### ISSUE THREAD

**Issue by cobra88king8** [Fate-Grand-Automata/FGA#1389]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1836

### Describe the bug

This began when my phone upgraded to Android 13 so it may be related to that. I have set the Game area to left=169, right=51, as suggested in the Custom Game Area (black bars) megathread and turning off Gesture Navigation does fix this bug. Skip servant face-card checks is turned off. 

When first engaging FGA in a quest, it will skip the normal face card checks and go straight into selecting the skills (it seems to select the correct skills on the right servants). Then when it comes time to selecting the NP, it stalls on that screen, indicating it fails to determine the cards, but then in the first round it does select the correct NP. Then as the NP plays out it tries to start selecting the next round's skills and then is unable to select the next NP, even if available, in round 2. 

None of this is a big deal as I just navigation types whenever I use FGA, just was curious if I'm being dumb with one of the settings or something, or if it's Android 13 related. 

### Video

https://user-images.githubusercontent.com/8955137/192213633-e31dd15b-e9a7-4a91-9f9d-49c9fbd9959e.mp4

### Device model

Pixel 6

### Android version

12

**Comment by vybze** [comment]
When you say that it stalls when selecting np do you mean that the game freezes or if fga idles for a few seconds before the failed to read card types message appears? Also your video that you posted isn't working, could you post another showing the issue.

**Comment by reconman** [comment]
Video is probably broken because of #1351

**Comment by cobra88king8** [comment]
> When you say that it stalls when selecting np do you mean that the game freezes or if fga idles for a few seconds before the failed to read card types message appears? Also your video that you posted isn't working, could you post another showing the issue.

It seems to be FGA idling because if I do it manually it registers the inputs 

Here's a [upload of the video ](https://www.youtube.com/watch?v=l2HE2N-yMcA) on youtube because it was too big to upload to github.

**Comment by reconman** [comment]
Your custom game area isn't correct. Check #1347

**Comment by cobra88king8** [comment]
> Your custom game area isn't correct. Check #1347

That was the first thing I checked, and had it set up and working with on Android 12, offset left=169 right=51. Then the Android 13 update broke that. 

![Screenshot (Sep 26, 2022 1 06 57 PM)](https://user-images.githubusercontent.com/8955137/192338757-c54043aa-8f46-4e84-8c97-b9d4a5b821cb.png)

![Screenshot (Sep 26, 2022 1 08 18 PM)](https://user-images.githubusercontent.com/8955137/192338751-7715bf58-88e7-481d-8ff9-1c21c95f5068.png)

**Comment by reconman** [comment]
Is that the old or new screenshot?

**Comment by cobra88king8** [comment]
> Is that the old or new screenshot?

New. Made it just now.

**Comment by reconman** [comment]
Your offsets are left=192, right=74

**Comment by cobra88king8** [comment]
Ah okay thank you. I'm surprised Android 13 changed the offset by that much

**Comment by reconman** [comment]
Android 13 apparently has a bigger navigation bar.

The formula for the black bars is:
Left = notch + (navigation bar / 2)
Right = (navigation bar / 2)

But when I measure the navigation bar in FGA, it's not giving me the real value, because the navigation bar is invisible in FGO.
