### ISSUE TITLE
Ability to copy an already existing battle config?

### ISSUE THREAD

**Issue by Tom3kk** [Fate-Grand-Automata/FGA#1390]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Sometimes if you want a farm a new node all you need is a small adjustement to the script like using a certain skill you didn't have to before or something, and instead of having to make a whole battle script, selecting what supports you want, what CEs you want etc. it just would be faster to be able to copy and paste an already existing script and then edit that, but right now all you can do is export and delete a script after selecting it.
While it is easy to edit the existing script some pepegas like me might just forget they did it 💀and get rekt when they try to use it for something else

**Comment by vybze** [comment]
Feature already exists 
![20220926_115320](https://user-images.githubusercontent.com/32293918/192335943-47677c1c-e51c-48e5-88bb-e25390c975ed.jpg)

**Comment by Tom3kk** [comment]
wtf I never saw that button before am I blind
