### ISSUE TITLE
Nox(root mode) and samsung galaxy tab s7 can't work at selection of the friends list

### ISSUE THREAD

**Issue by SA8620** [Fate-Grand-Automata/FGA#1392]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

TW

### FGA build number

1836

### Describe the bug

When I updated my FGA 1830 to 1836,it didn't work at friend list.Is that a bug?Thanks

### Video

Nox: https://youtu.be/HqjAlSzmynE
Samsung galaxy tab s7: https://youtu.be/f313WzaM_7o

### Device model

Nox

### Android version

7

### Screen size

1920x1080 

### RAM

4GB

**Comment by vybze** [comment]
https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting#where-should-i-place-the-play-button

**Comment by vybze** [comment]
For events I recommend using the ingame filters for ce instead of the preferred ce selection in fga
