### ISSUE TITLE
Fga bug report

### ISSUE THREAD

**Issue by bhjs** [Fate-Grand-Automata/FGA#1405]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1855

### Describe the bug

I think it cant scan the screen properly. I try to choose the map for it and it scan the support set up like normal but do nothing. I try to turn on and off ignor notch too but it wont work either 

### Video

 Link to the video  https://youtu.be/M7mcaGD3izM

### Device model

Redmi 9T

### Android version

10

### Screen size

6,53 inches

### RAM

4GB

**Comment by vybze** [comment]
Disable and re-enable accessibility services and check out this [site](https://dontkillmyapp.com/xiaomi)

**Comment by bhjs** [comment]
> Disable and re-enable accessibility services and check out this [site](https://dontkillmyapp.com/xiaomi)

I have done like you said and it still wont work. What should i do next ?

**Comment by reconman** [comment]
The screen detection is not the problem, clicks aren't triggered.

Can you try restarting your phone after disabling the battery optimizations?

**Comment by bhjs** [comment]
> The screen detection is not the problem, clicks aren't triggered.
> 
> Can you try restarting your phone after disabling the battery optimizations?

Thx you so much, it work normal now
