### ISSUE TITLE
Xperia custom area is no longer valid

### ISSUE THREAD

**Issue by Gerhert** [Fate-Grand-Automata/FGA#1407]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1855

### Describe the bug

After the recent update the game area is bigger, so the preset for Xperia phones is smaller than what it used to be. I don't think a video is needed since it's visible on a picture.
There are no black bars anymore

### Video

![image](https://user-images.githubusercontent.com/114924002/193576640-b225a988-0171-4420-a452-4c877e9a98dc.png)

### Device model

Sony Xperia III 1

### Android version

12

### Screen size

1096 x 2560

### RAM

12GB

**Comment by reconman** [comment]
Xperia mode never worked for all devices.

Are you suggesting that it should be removed?

**Comment by Gerhert** [comment]
> 

No, I think it should stay. It works perfectly for Xperia on NA. 

Also I figured out that FGA doesn't need in anymore on JP, since it no longer has black bars.

**Comment by reconman** [comment]
Let's hope that the update reaches NA in a few months.
