### ISSUE TITLE
It can't be started, and it's stuck from the beginning.

### ISSUE THREAD

**Issue by Laxwei** [Fate-Grand-Automata/FGA#1409]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

18 55

### Describe the bug

Can't start normally, click Start Service and it will get stuck directly.

### Video

https://youtu.be/CTqGhRCPXxQ

### Device model

bluestacks5

### Android version

8

### Screen size

1600×900

### RAM

4GB

**Comment by Heinenz** [comment]
The same thing is happening to me. Did you managed to solved? or you are still having that issue?

**Comment by Laxwei** [comment]
I don't use Blue Stack anymore, and I'm using the lightning simulator 9
&nbsp;


おや~爱~
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月9日(星期三) 晚上8:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Fate-Grand-Automata/FGA] It can&#39;t be started, and it&#39;s stuck from the beginning. (Issue #1409)





 
The same thing is happening to me. Did you managed to solved? or you are still having that issue?
