### ISSUE TITLE
Galaxy m53 app AI dont work

### ISSUE THREAD

**Issue by ninja12749** [Fate-Grand-Automata/FGA#1414]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

0.22.1

### Describe the bug

![image](https://user-images.githubusercontent.com/72307870/196290801-be54f7d7-d497-4219-aaf8-a1c18b83306d.png)
![image](https://user-images.githubusercontent.com/72307870/196290821-d30c5f59-6e49-4ba3-a4cf-ab1c21520ee6.png)
The app wont start in battle or at selection, i tried to do all the recomendations in the guides but it wont start.
i changed my phone to a new one. im using a Sansung Galaxy M53

### Video

i tried to record but i took so much time trying to do it and failed so.
my phone has a tiny dot wheres the camera is at.

### Device model

Galaxy m53 5g

### Android version

12

### Screen size

164.70 x 77.00

### RAM

8GB

**Comment by ninja12749** [comment]
https://youtu.be/O0ocuyRT1LA
i used my old phone to record the new one

**Comment by ninja12749** [comment]
i already fixed , i was using the one that was the (buster app) im now using the (quick app) and is all fixed 
https://fate-grand-automata.github.io/ i dowloaded the red one in apkpure

**Comment by ARCHER123559** [comment]
Hello.
If i may ask does M53 5G run fgo smoothly ? , because i wanna buy a phone and i can't decide which one is the best M52 5G or M53 5G . and thank you.

**Comment by ninja12749** [comment]
its good, i can run the game for the entire day, i also have some other
games on it

Em seg., 27 de fev. de 2023 às 16:45, ARCHER123559 ***@***.***>
escreveu:

**Comment by ARCHER123559** [comment]
There is no lag or crash ?

**Comment by ARCHER123559** [comment]
i am puting all my money on it

**Comment by ARCHER123559** [comment]
Thank you for your answer .

**Comment by ARCHER123559** [comment]
How about gunshikrn impact ? does it give best performance ?

**Comment by ARCHER123559** [comment]
Sorry you are the only one i know as fgo freind.

**Comment by ARCHER123559** [comment]
sorry that i bother you so much.

**Comment by ARCHER123559** [comment]
Can you record play in it clear quest so can see how it is ?

**Comment by ARCHER123559** [comment]
Thank you so much

**Comment by ARCHER123559** [comment]
i bought it it is wonderful
