### ISSUE TITLE
Script not starting on s22 ultra (part 2)

### ISSUE THREAD

**Issue by cgaming117** [Fate-Grand-Automata/FGA#1432]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1857

### Describe the bug

I made a new thread as this issue is similar but slightly different and i didnt know if the old one would get checked. I cant record video and the script wont function. I got a different error this time. Currently using FHD+ #
![Screenshot_20221103-010304_FateGO](https://user-images.githubusercontent.com/116938149/199658448-1f3ce705-9541-4357-afc7-07e689c16865.jpg)

### Video

![Screenshot_20221103-010304_FateGO](https://user-images.githubusercontent.com/116938149/199658726-2372a2c1-3c17-4051-ab32-dd68ca1f6445.jpg)

### Device model

S22 ultra

### Android version

12

### Screen size

3088x1440

### RAM

12gb

**Comment by reconman** [comment]
Use the existing issue.
