### ISSUE TITLE
After Android 12 update not working correctly on wave 2 and support Screen 

### ISSUE THREAD

**Issue by vybze** [Fate-Grand-Automata/FGA#1435]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1856

### Describe the bug

Ever since updated Android  to Android 12, very small black bars started appearing on the sides of FGO and now fga seems to be misaligned on both support screen and wave detection even with custom game area values set, even setting stage similarities to 100 didn't seem to help ![Screenshot_2022-11-02-16-06-39-79_577bcc70c040536a6d306ef99c704547](https://user-images.githubusercontent.com/32293918/200126633-de501846-7854-416d-a1a0-86ee082206dd.jpg)

### Video

Battle = https://drive.google.com/file/d/1jl-itNmqban-3JCzHQN7PSXNU5rjE3Wf/view?usp=share_link

Support = https://drive.google.com/file/d/1jsfPPRe2WSfoKRjokPkH480M8uU8zLHS/view

### Device model

OnePlus 7T Pro

### Android version

12

### Screen size

1440 x 3120

### RAM

8GB

**Comment by rasiel33** [comment]
I have this bug too

**Comment by reconman** [comment]
Are you reporting for yourself or for someone else?

What are you current offsets?

**Comment by reconman** [comment]
@rasiel33 Not an FGA bug, but an FGO one. Use the Custom Game Area thread. #1347

**Comment by rasiel33** [comment]
> @rasiel33 Not an FGA bug, but an FGO one. Use the Custom Game Area thread. #1347

I use realme gt 2 pro and use realme gt neo 2 offset.
It cant select support auto

**Comment by reconman** [comment]
@rasiel33 Post a screenshot there, don't just use some values from another phone.

**Comment by vybze** [comment]
> Are you reporting for yourself or for someone else?
> 
> What are you current offsets?

Reporting for someone else. Offsets are 66 left and right

**Comment by reconman** [comment]
@vybze The screenshot you uploaded to the custom game area thread and this bug report was not a fullscreen one. It has a resolution of 1920x886 pixels.

The real offsets should be 107 left and right.
