### ISSUE TITLE
No Castoria Support?

### ISSUE THREAD

**Issue by Alnilam3** [Fate-Grand-Automata/FGA#1436]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1856

### Describe the bug

Few days ago the system could select castoria, but now it does not work. I tried reinstalling the app and found out that Castoria was removed from Preferred Support list.
Just an answer to this question would be nice or if I am doing something wrong.

### Video

![Screenshot_20221107-161808_FateGO](https://user-images.githubusercontent.com/117661081/200346823-1321f2ae-c43f-487e-9d8b-547eff673bde.jpg)

### Device model

Samsung Galaxy S20 FE

### Android version

11

**Comment by vybze** [comment]
More options - storage - extract default support images
