### ISSUE TITLE
Fga got stuck at the start 

### ISSUE THREAD

**Issue by Super10vnpower** [Fate-Grand-Automata/FGA#1438]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1856

### Describe the bug

When i clicked run it dosent choose the level or any support friends. Im new to the app so sorry if i did something wrong ;-;. Im currently using a huawei y9 2019. 
![Screenshot_20221108_220651_com mathewsachin fategrandautomata debug](https://user-images.githubusercontent.com/117752698/200605839-0ba4c76c-4a6b-438b-b7e9-a55060755b6b.jpg)
![Screenshot_20221108_220658_com mathewsachin fategrandautomata debug](https://user-images.githubusercontent.com/117752698/200605895-068c36cf-fa02-4ce5-a4ed-795334ddc545.jpg)

### Video

https://user-images.githubusercontent.com/117752698/200608602-9448625d-c5f9-4db3-8811-cad2425ce26b.mp4

### Device model

Huawei y9 2019 

### Android version

9

### Screen size

2340x1080

### RAM

4GB

**Comment by reconman** [comment]
I can only think of battery optimization. Have you checked those settings?

It detects the screen, but doesn't click.

**Comment by Super10vnpower** [comment]
> I can only think of battery optimization. Have you checked those settings?
> 
> It detects the screen, but doesn't click.

Thanks for replying. No i dont think its the battery optimization since i have used the same settings for fga in the past and it worked. I have also tried redownloading fga multiple times but got the same results.

**Comment by reconman** [comment]
Nothing in the app related to clicking changed, so I have no idea what it could be.
