### ISSUE TITLE
Selecting a support after completed a battle completed

### ISSUE THREAD

**Issue by Misfit137** [Fate-Grand-Automata/FGA#1440]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

![Screenshot_20221110_182747_com aniplex fategrandorder en](https://user-images.githubusercontent.com/96072797/201067540-1df89648-d2d5-4cde-9c5c-c449343d607c.jpg)

I received this error when selecting the support after conpleted a battle. Anyone know how to solve this?

**Comment by reconman** [comment]
That error means there's a corrupted image in your support folder.

Can you delete the support images and then press "Extract Default Support Images"?

**Comment by Misfit137** [comment]
> That error means there's a corrupted image in your support folder.
> 
> Can you delete the support images and then press "Extract Default Support Images"?

Thanks... That solved it... Previously I did ectract without deleting the older support image but it doesn't work 😂
