### ISSUE TITLE
FGO crashes on JP, but works fine on NA

### ISSUE THREAD

**Issue by zzokou** [Fate-Grand-Automata/FGA#1442]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

I guess this is more of an FGO issue, but I never really noticed it until using FGA to farm the current lottery event. I can farm na endlessly with 0 crashes or errors, the other day I farmed a stage 93 times and it only stopped because I ran out of bronze apples, but on jp I only can get through at most 5 stages before the app crashes. Has anyone else had this issue, and if so how can I fix it? It kinda defeats the purpose if I have to refresh the app after every single run ):

**Comment by vybze** [comment]
Jp has become quite resource intensive and unless you have a more powerful device I wouldn't recommend running both fgo and fga at the same time. The only other advice I can give you other than upgrading to a newer phone is to find a way to keep your phone has cool has possible when both are running

**Comment by zzokou** [comment]
> 

I'm using Bluestacks to play fgo on my pc, which is why I find it so odd that it never freezes or crashes on NA, only on Jp ): I've tried changing my settings on bluestacks, but it just always gets stuck on loading into the 5th run.

**Comment by vybze** [comment]
Sadly you're not the only one I heard having issues with jp on blue stack

**Comment by Ryrin45** [comment]
FGO JP has become quite unstable and laggy. This issue is even worse on emulators. I've found that LDPlayer9 doesn't crash nearly as frequently as Bluestacks and LDPlayer4. Though accessibility mode seems to cause even more significant stuttering on LDPlayer9 than 4, so it's a tradeoff no matter what.

**Comment by zzokou** [comment]
> 

omg i meant to post an update ! i switched to LDPlayer the other day and it fixed my problem completely, it crashes maybe once every 80 runs, it also runs a lot smoother and it's a lot more responsive, so I'm really happy with the switch
