### ISSUE TITLE
Not use skill when turn 4+

### ISSUE THREAD

**Issue by NgocNA** [Fate-Grand-Automata/FGA#1444]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1871

### Describe the bug

Servant dont use skill when turn 4
Command:
   abfi2g1h5,#,x31i1f14,#,g1d1h1e1aj4,#,**b4**

### Video

[Video](https://drive.google.com/file/d/11Uh2tMbTqWcSpysT4Qydq1iVUcR8zD6K/view?usp=drivesdk) 

### Device model

Poco f2 pro

### Android version

11

### Screen size

1920x1080

### RAM

6GB

**Comment by reconman** [comment]
Every # means next "Battle", not turn.

You're in Battle 3, turn 4
![image](https://user-images.githubusercontent.com/12360257/201547759-941263de-c2cc-4073-b763-55d40f8338a8.png)

abfi2g1h5,#,x31i1f14,#,g1d1h1e1aj4,#,b4 should be
abfi2g1h5,#,x31i1f14,#,g1d1h1e1aj4,b4

So choose "Next Turn in same wave" in the Command builder.
