### ISSUE TITLE
Scrolling doesn't work in support page

### ISSUE THREAD

**Issue by azeem400** [Fate-Grand-Automata/FGA#1447]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1871

### Describe the bug

I tried reinstalling FGA, force closing the app, etc, but FGA still doesn't scroll through the support list. Sometimes it even just sits there on the node selection screen. 

### Video

https://youtu.be/9rZRGejYXLM

### Device model

Samsung Galaxy S22 Ultra

### Android version

13

### Screen size

3088 x 1440

### RAM

12

**Comment by azeem400** [comment]
> Where do the + and - buttons in the bottom left come from? An external recorder?

Volume buttons as my phone's volume up doesn't work. Even with it not enabled, the support list still doesn't scroll when fga is running.

**Comment by azeem400** [comment]
Does no one have any idea on what's going on?

**Comment by reconman** [comment]
Ah, Android 13, recording is broken.

Use build 1888 and record with the system recorder.

**Comment by azeem400** [comment]
> Ah, Android 13, recording is broken.
> 
> Use build 1888 and record with the system recorder.

I forgot to update you. This resolved the issue. Thanks!
