### ISSUE TITLE
FGA on samsung galaxy Tab S6 Lite

### ISSUE THREAD

**Issue by zenosama1245** [Fate-Grand-Automata/FGA#1449]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

![Screenshot_20221118-134040_FateGO](https://user-images.githubusercontent.com/61688948/202653037-40f8f07e-18c2-44c0-84ac-da4cd28cc28d.jpg)
is there any way for me to use FGA with this resolution? (15:9)

**Comment by zenosama1245** [comment]
> Should work out of the box, have you tried?

the clicks are a little off so the skill doesnt work properly

**Comment by reconman** [comment]
Can you provide a video with version 1906?

**Comment by zenosama1245** [comment]
thank you for the help. it works now
