### ISSUE TITLE
FGA misses skills on repeats

### ISSUE THREAD

**Issue by Uathach** [Fate-Grand-Automata/FGA#1452]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1892

### Describe the bug

FGA skipped some skills while running. I tried to restart my phone, and it worked normally for the first run, but the bug appeared again when I run the script for the second time.

### Video

Here's a screen shot of my script
![Screenshot_20221120_041015_com mathewsachin fategrandautomata debug](https://user-images.githubusercontent.com/88569345/202894181-61986adb-a15b-4caf-b0f3-30faa52fb851.jpg)

And here's the video
https://youtu.be/lxOVwufMJxg

### Device model

HUAWEI Mate 20

### Android version

10

**Comment by reconman** [comment]
Try increasing Wait Before Turn in the Fine Tune settings.

The popup window for Support Artoria Caster is the targeting for b2.

**Comment by Uathach** [comment]
> Try increasing Wait Before Turn in the Fine Tune settings.
> 
> The popup window for Support Artoria Caster is the targeting for b2.

I set it to 800 and it still didn't work

**Comment by gino9955** [comment]
same situation in the same build number,device is Asus Zenfone 5z

**Comment by reconman** [comment]
I have an idea, what happens if you add Target 1 to each wave?

So you command would look like **t1**b2c2dfh2i25,#,**t1**a5,#,**t1**gx31e2gi2j45,#,

If that works, I'll try adding an extra click at the start of the turn in the top right corner. Maybe FGO's tap detection gets messed up on repeats.

**Comment by Uathach** [comment]
> I have an idea, what happens if you add Target 1 to each wave?
> 
> So you command would look like **t1**b2c2dfh2i25,#,**t1**a5,#,**t1**gx31e2gi2j45,#,
> 
> If that works, I'll try adding an extra click at the start of the turn in the top right corner. Maybe FGO's tap detection gets messed up on repeats.

Yes that works now

**Comment by reconman** [comment]
Please test this APK without the `t1` commands: https://github.com/Fate-Grand-Automata/FGA/suites/9431441772/artifacts/445786430

You can make a copy of the battle config first in case it doesn't work.

**Comment by Uathach** [comment]
> 

No this version still needs t1 to work

**Comment by reconman** [comment]
Please try https://github.com/Fate-Grand-Automata/FGA/suites/9455560943/artifacts/447475628

**Comment by Uathach** [comment]
I turned off the skill speedup, but it still needs t1 to work

**Comment by gino9955** [comment]
> I have an idea, what happens if you add Target 1 to each wave?
> 
> So you command would look like **t1**b2c2dfh2i25,#,**t1**a5,#,**t1**gx31e2gi2j45,#,
> 
> If that works, I'll try adding an extra click at the start of the turn in the top right corner. Maybe FGO's tap detection gets messed up on repeats.

it works! thanks.

**Comment by reconman** [comment]
@gino9955 Please check if https://github.com/Fate-Grand-Automata/FGA/issues/1450#issuecomment-1335279749 helps

**Comment by Inkaflare** [comment]
Tried the release you posted, did not fix the issue for me. The first skill in waves 2 and 3 is still being skipped if I remove the t1 command at the start of these waves.

**Comment by TravelerHD** [comment]
> The issue doesn't happen on my emulator which runs the game in 16:9 actually. Might be related to the ~20:9 aspect ratio on my phone?

I'm having all kinds of issues with the 1892 build on my 20:9 ratio phone as well (Pixel 7). Cards not identifying, wrong servants being targeted, and freezing scripts when viewing servant details.

**Comment by Uathach** [comment]
Tried 1903, still skips skills without t1

**Comment by froz3n** [comment]
> @gino9955 Please check if [#1450 (comment)](https://github.com/Fate-Grand-Automata/FGA/issues/1450#issuecomment-1335279749) helps

Tried this too, and still getting issues like fail at identifying cards and wrong skill targets.
I'm on Android 13 with 20:9 res.
What fixed it for me so far is using root to screenshot. If anyone else has this problem on rooted phone, maybe you can try this workaround and see if it helps.

**Comment by Inkaflare** [comment]
Thanks for the tip but sadly my phone isn't rooted, which means I cannot toggle the option.

**Comment by TeslasFoil** [comment]
On pixel 6, the target skill on servant #2 sometime click to the right of servant (between servant 2 / 3 in skill target selection)

**Comment by xHomu** [comment]
I have a Pixel 7 Pro, disabling Navigation Gestures to enable full screen app.


Watching the battles with debug mode on - I noticed that this occurs whenever the game skips or fails face-card check, so most often it fails on repeat battle.

**Comment by reconman** [comment]
> I have a Pixel 7 Pro, disabling Navigation Gestures to enable full screen app.
> 
> Watching the battles with debug mode on - I noticed that this occurs whenever the game skips or fails face-card check, so most often it fails on repeat battle.
> 
> Was it always the case that FGA skips facecard check on repeats or is that new behavior?

Yes, it always worked like that. What I've noticed in some videos is that FGA suddenly thinks that Servants are dead because the NP bar is not detected.

That's also why face cards can't be associated with Servants anymore. FGA has already marked them as dead so the face cards shouldn't show up anymore.

**Comment by froz3n** [comment]
From my quick test, 1906 seems to have fixed the problem.

**Comment by xHomu** [comment]
Can confirm, the fix works! 

Thank you for your hard work @reconman!

**Comment by Uathach** [comment]
1906 works now, thank you!
