### ISSUE TITLE
After a few runs, the phone shuts down 

### ISSUE THREAD

**Issue by Iambatman103** [Fate-Grand-Automata/FGA#1454]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1892

### Describe the bug

After a few runs using FGA, my phone automatically shuts down. I tried force stopping and restarting my phone and it didn't work. The same thing happened. I haven't seen anyone talk about it either. My phone is up to date so it shouldn't be shutting my phone off. I been using FGA for months and after the 1892 version it started happening.

### Video

The recorder would turn off since the phone would be turned off.

### Device model

OnePlus 6t

### Android version

11

### Screen size

1080x2340

### RAM

8gb

**Comment by reconman** [comment]
Don't know if you got the notification because I miswrote your name: https://github.com/Fate-Grand-Automata/FGA/issues/1450#issuecomment-1335279749

**Comment by reconman** [comment]
Is this foxed with 1906?
