### ISSUE TITLE
Is there any possibility of keeping the in-app recorder?

### ISSUE THREAD

**Issue by animeavi** [Fate-Grand-Automata/FGA#1460]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

I'm trying to catch a bug on video, I had it happen with debug on but the system recorder simply stops recording when I start the FGA service or doesn't let FGA work with "Unexpected Error: Invalid media projection", depending on which I start first, so not very helpful.

I have reverted [the commit that removes it](https://github.com/Fate-Grand-Automata/FGA/commit/9c0a14ff400876c93d1a358e1f65623bb20b4b31) locally and compiled my own APK to try to catch the bug, but I bet there's other people in the same situation where they cannot record while using FGA and may not be in the position to compile themselves and deal with git commits.

**Comment by reconman** [comment]
I also thought of that since the solution I thought of only works on some phones.

But there's no solution for Android 13 afaik. You can either take screenshots or record video, but not both.

So sooner or later we'll have to find another way to debug issues.
