### ISSUE TITLE
Maybe a serious bug

### ISSUE THREAD

**Issue by EarthPretender** [Fate-Grand-Automata/FGA#1461]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

1892

### Describe the bug

Keep showing screenshots on the left-up corner of my phone. Every screenshot is only a flash, but it keeps appearing that the scipt always fails to work correctly. It never does like that before 1892 is updated:)

### Video

Sorry for that I cannot make a video... The bug is just as what I described.

### Device model

Xiaomi mix 2s

### Android version

10

### Screen size

2160*1080

### RAM

6GB

**Comment by reconman** [comment]
How's 1906 from https://github.com/Fate-Grand-Automata/FGA/releases in comparison?

**Comment by EarthPretender** [comment]
> 

It's already ok on 1908:)

**Comment by EarthPretender** [comment]
> How's 1906 from https://github.com/Fate-Grand-Automata/FGA/releases in comparison?

It's already ok on1908:)
