### ISSUE TITLE
My Cellphone Crush when i Farming

### ISSUE THREAD

**Issue by Abyss63** [Fate-Grand-Automata/FGA#1462]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1892

### Describe the bug

Hello, the bug consist in this, when i programing the script for Farming in 3T with  two Castorias, My Kiara Summer and my Waver (Order Change) something happening in my battle.

In the first round, the script work excellent but... In the second round o the third round my phone turn off inmediatily, so... I need somebody to re-work the app or update the settings because before the last update, My FGA in my device it was working perfectlly and the best hours Farming in this phone (Maybe 1 hours or More)

Please help us, this Is important for me

### Video

Sorry i don't have another phone yo recording my Situation 

### Device model

TCL10L

### Android version

11

### Screen size

1080x2340

### RAM

6GB

**Comment by reconman** [comment]
Duplicate of #1454

I'll look into it this week.

**Comment by Abyss63** [comment]
Hello @reconman 

Thank you so much for your help, the build what you send me in my account is work excellent.


I don't have any problems now... So i repeat this for you, Thank you for your help.
