### ISSUE TITLE
Crash problem

### ISSUE THREAD

**Issue by NepPure** [Fate-Grand-Automata/FGA#1463]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

1892

### Describe the bug

[log.txt](https://github.com/Fate-Grand-Automata/FGA/files/10099578/log.txt)

adb log

### Video

None

### Device model

Simulator

### Android version

12

### RAM

6GB

**Comment by reconman** [comment]
What exactly crashes? Does your phone shut off? Does FGA stop working?

**Comment by NepPure** [comment]
> Is this issue fixed with 1906?

It has been running stably for 48 hours.

**Comment by NepPure** [comment]
It's been working fine for days.
