### ISSUE TITLE
Phone Suddenly shutdown 

### ISSUE THREAD

**Issue by balonbao247** [Fate-Grand-Automata/FGA#1465]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

My redmi note 11 Suddenly shutdown while using FGA

**Comment by reconman** [comment]
Duplicate of #1454
