### ISSUE TITLE
won't start due to a code popping out when i do

### ISSUE THREAD

**Issue by yukki10105** [Fate-Grand-Automata/FGA#1477]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1908

### Describe the bug

when i tried to play the program it shows some kind of code and won't start 
![Screenshot_20221212_153551_com aniplex fategrandorder](https://user-images.githubusercontent.com/120365206/206990052-00c212c7-9fba-4b7a-99d3-37dc149929e3.jpg)

### Video

https://user-images.githubusercontent.com/120365206/206990660-d78a0118-e582-4a78-a1e6-51ac264cd96c.mp4

### Device model

Huawei Nova 7i

### Android version

12

### Screen size

2310x1080

### RAM

8GB

**Comment by reconman** [comment]
Check your support folders for broken images.

If you find any, delete them and press "Extract Default Support Images".

If you can't find a corrupted image, delete the contents of the support folder and press the Extract button.

**Comment by yukki10105** [comment]
thank u for replying...yes it worked when i deleted the whole folder and opened it the app created a new one itself and now works again
