### ISSUE TITLE
The script just freezes on the support selection screen

### ISSUE THREAD

**Issue by JairSiles** [Fate-Grand-Automata/FGA#1478]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1908

### Describe the bug

When i start a battle the script works fine, skill and NP selections and replenish AP but when it goes to support selection screen the script just freezes and do nothing, i have to manually select a support then the script works again in battle.
I used the script before and worked fine but i didnt use it for some time, when i tried again for the event i found this problem

### Video

https://user-images.githubusercontent.com/120408549/207119131-3d6a1f87-ae46-4e37-9d58-12efb5acf879.mp4

### Device model

Motorola Edge 2021

### Android version

12

### Screen size

2460x1080

### RAM

8 GB

**Comment by reconman** [comment]
Move the play button to the bottom left.
