### ISSUE TITLE
Fga doesn't work on my redmi note 11

### ISSUE THREAD

**Issue by mtrd10** [Fate-Grand-Automata/FGA#1480]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1908

### Describe the bug

Fga doesn't work on my redmi note 11, specifically battle mode, lotto does work but it just keeps clicking and ignoring  the command to prevent box reset. But in battle mode it just doesn't, cant even pick the support.

### Video

https://youtu.be/zG_pF6gyQ00

### Device model

Xiaomi Redmi note 11 

### Android version

12

### Screen size

1080 x 2400

### RAM

6gb + 2gb

**Comment by vybze** [comment]
Are you using the custom game area option?

**Comment by mtrd10** [comment]
> Are you using the custom game area option?

Nope, default

**Comment by vybze** [comment]
Take a screenshot ingame, make sure it's of a bright screen and post it here https://github.com/Fate-Grand-Automata/FGA/issues/1347 to get the values for your screen then input those values into the custom game area option in the advance section of the more options menu in fga

**Comment by vybze** [comment]
> Still dont work https://youtu.be/YCBvrnXn5I8 ![IMG_20221215_210414](https://user-images.githubusercontent.com/86212022/207866236-5168c67e-17ec-4a13-988b-9a98451ae270.jpg)

What's that white thing in the top left?

**Comment by mtrd10** [comment]
> > Still dont work https://youtu.be/YCBvrnXn5I8
> 
> What's that white thing in the top left?

A performance booster for games, somethin like that
![Screenshot_2022-12-15-22-02-45-317_com aniplex fategrandorder en](https://user-images.githubusercontent.com/86212022/207880972-d190826a-061d-4d10-9baa-8a477f6a7673.jpg)

**Comment by vybze** [comment]
Is your issue resolved?

**Comment by reconman** [comment]
If not, post another video.
