### ISSUE TITLE
Servant details not opening

### ISSUE THREAD

**Issue by Lydraen** [Fate-Grand-Automata/FGA#1484]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1908

### Describe the bug

When i start a run it doesnt open the first servants details window but opens the seccond one without problem and after that the buffs that are supposed to be for servant 1 misclick.
I havent done any fine tuning at all and used reset to default a few times.

### Video

https://youtu.be/IQJ9oCGWkek
(https://youtu.be/IQJ9oCGWkek) 

### Device model

Galaxy S20 Ultra 5G

### Android version

12

**Comment by vybze** [comment]
https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting#where-should-i-place-the-play-button

**Comment by Lydraen** [comment]
i didnt even notice that i moved the play button.
its working again now tyvm for the time.
