### ISSUE TITLE
FGA stopped working

### ISSUE THREAD

**Issue by prathameshgogate25** [Fate-Grand-Automata/FGA#1486]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1908

### Describe the bug

The app won't pick supports. It used to work just fine. It started having this problem after the system on my phone (OnePlus Nord) updated to Android 12. Tried restarting the phone, force-stopping the app, but none of these worked.

I'm sorry if this is a stupid problem, but I did see a similar post [here](https://community.gamepress.gg/t/fate-grand-automata-discussion-and-help-thread-round-2/107040/908) before. Tried to find the solution in the thread, but couldn't find it. 

### Video

[Video with debug mode](https://imgur.com/a/SFAj9Hj) 

### Device model

OnePlus Nord

### Android version

12

### Screen size

2400 x 1080 (screen size is about 6.3 in)

### RAM

8GB

**Comment by vybze** [comment]
https://github.com/Fate-Grand-Automata/FGA/issues/1480#issuecomment-1352401864

**Comment by prathameshgogate25** [comment]
@vybze that worked! Thanks for the quick help, I really appreciate it.
