### ISSUE TITLE
Stop on CE get broken

### ISSUE THREAD

**Issue by akun90** [Fate-Grand-Automata/FGA#1489]
### Preparation

- [x] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1907

### Describe the bug

The script doesnt stop after DROPPING  the ce  even if the Stop on Ce Get is on. When the CE drops it emit sound like the script stopped but it keeps going.

I remember in the previous versions of the fga it was working fine, but now it just doesnt.

### Video

Cant register a video of it not stopping it might just take hrs to drop one. Evrything else is just fine.

### Device model

Glaxy s10

### Android version

12

**Comment by akun90** [comment]
Think i figured it out ill test it

**Comment by Inkaflare** [comment]
I'm having the same issue. How did you solve this?

**Comment by akun90** [comment]
> I'm having the same issue. How did you solve this?

Ita no longer in the config menù under "sotp ob ce drop" or "stop o  ce get"
When you start the fga to commence farming it ask for number of refill, runs etc and there is "CEs -1+" you can select after how many ces drop the script has to stop

**Comment by Inkaflare** [comment]
Oh, how did I not notice that, lol. Thanks.

**Comment by akun90** [comment]
> Oh, how did I not notice that, lol. Thanks.

I asked the same to myself, but if you are here you are not alone :)
