### ISSUE TITLE
Receiving embers is picking stacks with more than 10 in number.

### ISSUE THREAD

**Issue by rospec14** [Fate-Grand-Automata/FGA#1492]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1908

### Describe the bug

Since I think no one still raised this, I noticed that receiving embers is picking stacks more than 10.

### Video

https://user-images.githubusercontent.com/117153936/208386895-2b0e679d-6f8d-4713-a57b-b147346f028c.mp4

### Device model

ROG Phone 6

### Android version

12

### Screen size

1080 x 2448

### RAM

16GB

**Comment by rospec14** [comment]
After observing more, it picks 11 and 12 stacks, it skips 13 and more stacks. I don't have 15 and more stacks so I'm still not sure about them though.

**Comment by reconman** [comment]
You didn't check the closed issues.
