### ISSUE TITLE
is there another way i can turn on accessiblity

### ISSUE THREAD

**Issue by mocream** [Fate-Grand-Automata/FGA#1495]
![image_2022-12-20_130945597](https://user-images.githubusercontent.com/121078872/208588490-c47712fd-6ee0-4134-88a5-61e08be3d648.png)
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

when i try to turn on accessibility my phone wont allow it

**Comment by vybze** [comment]
https://community.gamepress.gg/t/fate-grand-automata-discussion-and-help-thread-round-2/107040/1264?u=skitts

**Comment by reconman** [comment]
Question was answered, closing.
