### ISSUE TITLE
FGA Stuck on Servant Screen (despite setting Custom Game Area)

### ISSUE THREAD

**Issue by Justus188** [Fate-Grand-Automata/FGA#1496]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1908

### Describe the bug

Does not press the screen at support screen.

I suspected it to be a black bar issue, but it doesn't work even with the offsets provided by the bot in #1347.

Also the record screen toggle is greyed out and untoggleable, so attached screenshot with debug mode.

Might be similar to #1422 ? Not too sure. Have not tried running it in battle yet.

My phone is an Oneplus Ace, pretty new to it and it's an import model so I'm not too familiar with it.

I have another autotapper app that I use for Friend Summoning that taps predetermined areas but doesn't use screen capture and that works fine. I disabled it on Accessibility before starting FGA though so it shouldn't be the issue.

Thanks!

### Video

![photo_6129916383463584913_y](https://user-images.githubusercontent.com/54542803/208607333-dbfe4c2f-09f6-41a8-ab5f-808bfd68fccb.jpg)
![photo_6129916383463584930_y](https://user-images.githubusercontent.com/54542803/208607335-d2c6e550-ab5a-4f51-865b-6e60fbe61270.jpg)

### Device model

Oneplus Ace

### Android version

13

### Screen size

6.7 in

### RAM

12.0GB

**Comment by reconman** [comment]
The screenshot you posted in the black bar thread was scaled down to around 570p.

Please upload a full screenshot there.

**Comment by Justus188** [comment]
Sending the screenshot over telegram to my computer was probably a bad idea.

Even with the new offsets its still not pressing though..

![Screenshot_2022-12-20-15-40-47-18_577bcc70c040536a6d306ef99c704547](https://user-images.githubusercontent.com/54542803/208610611-eddf4c27-043c-4dea-8428-cd253d17e38c.jpg)

**Comment by reconman** [comment]
Does FGA work on other screens?

**Comment by Justus188** [comment]
It similarly doesn't press anything on the Party screen.

It works properly in battle now.

Will update on the end screen once I'm done with this node.

**Comment by vybze** [comment]
Try left = 170

**Comment by Justus188** [comment]
Support select works with left = 170, but party confirmation seems rather off now.
![Screenshot_2022-12-20-16-50-20-40_577bcc70c040536a6d306ef99c704547](https://user-images.githubusercontent.com/54542803/208624624-e6b8d2bc-4735-4aa3-850f-25b2165dc5b1.jpg)

I can live with this thanks to the repeat button, but any idea why its so wonky?

**Comment by Justus188** [comment]
Left = 170 works smoothly for all screens now! Thanks for your help!
