### ISSUE TITLE
App stops/crashes when hitting the repeat button

### ISSUE THREAD

**Issue by Kanon86** [Fate-Grand-Automata/FGA#1497]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1908

### Describe the bug

Hello,

I've discovered this wonderful app yesterday and it's already been a great help. However, I'm encountering a pretty big issue: after the first run finishes and the app clicks the repeat button, the play button on the bottom left disappears as soon as FGO gets to the support selection screen and my device tells me the FGA app stopped working and I need to close it.

This also happens if I select only one run, close the "FGA wrap up" window, and then click "repeat" myself. However, if I select one run and click "close" instead, the app keeps working and I just need to click play again when getting to the support selection screen. I've attempted it more than a dozen times, it never fails. This has been my work around but it's of course not ideal.

I initially thought it was an accessibility problem and I've tried everything related to that and more, still doesn't work.

I've attempted to record a video in debug mode but for some reason the app crashes even earlier. I think it's because skills for my servants don't work in debug mode for some reason. A video wouldn't tell you much I think anyway, since it obviously stops recording when the app stops. There are no warning signs whatsoever.

Thank you in advance for your help.

### Video

Wouldn't help.

### Device model

Samsung Galaxy Tab A7

### Android version

12

### Screen size

2000x1200

### RAM

3GB

**Comment by Kanon86** [comment]
Update: FGA now randomly crashes during battle. Happens on second or third wave.

Forgot to mention disabling battery optimization was of course the first thing I did.

**Comment by reconman** [comment]
I'm thinking of memory issues.

Please check
![IMG_20221222_181253.jpg](https://user-images.githubusercontent.com/12360257/209189621-3e66ae33-dede-439b-92e1-a1c5b4662af3.jpg)

Click on it and then on "Memory usage by app".

It should list the memory usage of all apps in the last 3 hours.

![Screenshot_2022-12-22-18-14-39-70_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://user-images.githubusercontent.com/12360257/209189879-8ac4b57a-6887-4f09-8c19-7e1c566b7964.jpg)

**Comment by Kanon86** [comment]
There you go

![Screenshot_20221222-183424_Settings](https://user-images.githubusercontent.com/121064060/209193543-9b04c867-8b51-4e9c-b67e-afebdf650467.jpg)
![Screenshot_20221222-183405_Settings](https://user-images.githubusercontent.com/121064060/209193559-382452f9-2948-49cb-8327-6612ef123fc1.jpg)

Ran one battle and it crashed after getting back to the support screen once again.

**Comment by reconman** [comment]
There's also another setting called "Running services", showing overall memory usage.

I'm interested in this part
![Screenshot_2022-12-22-19-15-29-32_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://user-images.githubusercontent.com/12360257/209199718-32296375-506c-480c-8fac-6d486768f551.jpg)

**Comment by Kanon86** [comment]
Oops, realized it was set to display last day. Last three hours:
![Screenshot_20221222-190935_Settings](https://user-images.githubusercontent.com/121064060/209199482-6ceaee5b-5311-4eca-8e42-1c44e85f39f7.jpg)
![Screenshot_20221222-190956_Settings](https://user-images.githubusercontent.com/121064060/209199495-cb2f797d-09ea-4180-8bd6-21e581da9507.jpg)

I should probably tell you I did try to uninstall Avast, rebooted, and still ran into the same issue. I attempted to change preferred servant to first instead of a friend but it still crashed going back to support selection.

**Comment by Kanon86** [comment]
![Screenshot_20221222-193936_Settings](https://user-images.githubusercontent.com/121064060/209204479-58c3736a-e362-473e-b27e-eb6d4f7ae248.jpg)

Maybe it's actually a FGO issue? Been experiencing a bit of lag since the Christmas update while the game used to run super smoothly before then.

**Comment by reconman** [comment]
I can say that most users don't experience crashes.

Can't tell you why it does on your device.

Can't see anything obvious regarding memory.

**Comment by Kanon86** [comment]
I was hoping there was an obvious fix I somehow missed during all my researches and troubleshooting, but too bad.

Thanks anyway. All I can hope is that it will work once FGO fixes its current issues.
