### ISSUE TITLE
Nox Emulator setup

### ISSUE THREAD

**Issue by AfterSuns** [Fate-Grand-Automata/FGA#1498]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Hi, I've recently started using FGA after not using it for about a year on Nox Emulator on my laptop. Everything used to work fine and now I'm having a few problems. I've updated it and played around with the settings but I'm having some issues. 

1. It takes a very long time to start looking at selecting support servants, sometimes it just won't. Also it goes past regularly goes past Castoria only to reset support list and choose the same Castoria it already went past. 
2. Same issue as the first but with recovering AP. It takes a long time to select a fruit and sometimes it never will.
3. Sometimes it won't select an NP on the third turn.

I assume these problems are occurring because I'm just stupid and am doing something fundamentally wrong. The main thing I want to ask is what Nox setup is recommended that might fix this, for example, what screen res should I use, what device should I set the emulator too, game mode area and so on. 

Its been a long time so I'm very rusty with the service and have forgotten lots. Sorry if this is stupid and thanks for your time.

**Comment by reconman** [comment]
I can't run Nox on my PC anymore, it tells me to disable some security settings I've already disabled.

Try 720p or 1080p resolution. Use default game area.

You're using root mode as described in the emulator guide, right?

**Comment by AfterSuns** [comment]
Lowering the resolution and turning on root helped massive (which is weird because I never used it before and it worked fine) thanks a lot for helping my dumb ass
