### ISSUE TITLE
google pixel 6a fga not working

### ISSUE THREAD

**Issue by mocream** [Fate-Grand-Automata/FGA#1499]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1908

### Describe the bug

it just does nothing at all
![image_2022-12-21_023719013](https://user-images.githubusercontent.com/121078872/208741207-0cea8c82-555b-470b-a1a1-e249985a1583.png)

### Video

https://user-images.githubusercontent.com/121078872/208742184-75c6046b-b3b3-4f85-9b68-64eca75486cf.mp4

### Device model

google pixel 6a

### Android version

13

### Screen size

2400 x 1080

### RAM

6GB

**Comment by reconman** [comment]
Please read vybze's comment in the black bar megathread again. It also wouldn't hurt to look at the format of other users' screenshots.
