### ISSUE TITLE
App doesn't start when I press play and the skills are placed at the wrong place

### ISSUE THREAD

**Issue by LimST36** [Fate-Grand-Automata/FGA#1500]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1908

### Describe the bug

1) The app doesn't start when I click play
I've disabled any game booster on my phone

I'd to go into the battle manually in the video

2) The skill presses are off
In the video, the press done by the app for skadi's skill 1 is too far left so it messes the battle up

[](url)

### Video

https://youtu.be/EIMknB-wTV8

### Device model

Samsung S20FE

### Android version

12

### Screen size

1080x2400

### RAM

6GB

**Comment by LimST36** [comment]
Issue 2 is fixed 
Issue 1 still remains and FGA doesn't start
Supports aren't automatically selected

**Comment by vybze** [comment]
https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting#where-should-i-place-the-play-button
