### ISSUE TITLE
Screen recording toggle greyed out

### ISSUE THREAD

**Issue by Justus188** [Fate-Grand-Automata/FGA#1503]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1908

### Describe the bug

Record Screen toggle is greyed out on the menu.

I want to use it to troubleshoot my setup which died overnight on me, which I suspect to be due to some stuttering issues I've been having recently (game freezes for a second or two after certain button presses) messing up some timing-based followup button presses.

### Video

![photo_6129916383463584930_y](https://user-images.githubusercontent.com/54542803/209065599-1b32ddd6-23a4-43a9-b243-8101344f4080.jpg)

### Device model

Oneplus Ace

### Android version

13

### Screen size

6.7 in

### RAM

12.0GB

**Comment by reconman** [comment]
![IMG_20221222_073207.jpg](https://user-images.githubusercontent.com/12360257/209071898-526cf02c-2768-415c-a54a-79a7abaf8fe7.jpg)
