### ISSUE TITLE
Folder Skadi is empty

### ISSUE THREAD

**Issue by AsuraGW** [Fate-Grand-Automata/FGA#1505]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1908

### Describe the bug

When you activate the soport prrefered application ceases to work normally.
The battle script does not work, and if it works, then after the battle does not select the saport and stops the script.
What do I do?
Mobile of my phone poco x3 pro
https://youtu.be/oEen_9Fh-q8

### Video

https://youtu.be/oEen_9Fh-q8

### Device model

Poco x3 pro 

### Android version

12

### Screen size

1080x2400

### RAM

8

**Comment by vybze** [comment]
Your YouTube video is privated, can't help if we can't watch the video

**Comment by AsuraGW** [comment]
> Ваше видео на YouTube является конфиденциальным, не может помочь, если мы не можем посмотреть видео

**Comment by AsuraGW** [comment]
> Ваше видео на YouTube является конфиденциальным, не может помочь, если мы не можем посмотреть видео

Opened access

**Comment by AsuraGW** [comment]
> Your YouTube video is privated, can't help if we can't watch the video

Opened access

**Comment by reconman** [comment]
The error is "Folder Skadi is empty".

Press Extract Default Support Images in the Storage options.
