### ISSUE TITLE
Fga stuck on support (also doesn't work on battle) 

### ISSUE THREAD

**Issue by IneedHelppleaseeeee1** [Fate-Grand-Automata/FGA#1506]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1908

### Describe the bug

Works fine at first but keeps getting stuck on support with those 2 boxes. I'm still new to fga but I've been researching related problems about this.

### Video

https://drive.google.com/file/d/1nHNtLz0gVjz7Ya_MvDyLbdu56Zq_Mo_U/view?usp=drivesdk
![Screenshot_20221224-080219](https://user-images.githubusercontent.com/121291694/209414753-2ae6d42c-0514-451a-85d3-fcba6c50135d.jpg)
![Screenshot_20221224-080214](https://user-images.githubusercontent.com/121291694/209414756-d417045e-3952-46c5-8c0b-ac29bf1c0a9d.jpg)

### Device model

Huawei Y7 2019

### Android version

8

### Screen size

1520 x 720

### RAM

4gb

**Comment by reconman** [comment]
Why do your settings say left=20 and right=5 when the bot told you to use left=52?

**Comment by IneedHelppleaseeeee1** [comment]
Even If I did use it, it wouldn't work like at the beginning of the vid when the fga clicks the node.

**Comment by IneedHelppleaseeeee1** [comment]
Even If I did use it, it wouldn't work like at the beginning of the vid when the fga clicks the node.

**Comment by reconman** [comment]
Also, you used an external recorder instead of FGA's recorder as instructed in the bug report form. (More Options -> Advanced)

So you'll have to restart the FGA service after applying the correct offsets.

If it still doesn't work after that, upload a video recorded by FGA.

**Comment by IneedHelppleaseeeee1** [comment]
https://drive.google.com/file/d/1nML0qhhZR2O9GGuWqtpfMt_fdV7v_cKX/view?usp=drivesdk

this is with the LEFT=20 and RIGHT=5

https://drive.google.com/file/d/1nYKJnxR1jojq4jWRrD6aFvc39SJVcPap/view?usp=drivesdk

this is with the LEFT=52

**Comment by IneedHelppleaseeeee1** [comment]
Ohh and the fine tunes are on default never touched it

**Comment by reconman** [comment]
FGA's recordings start after you press the play button, but here the recording is already running and you're unpausing the script.

Are you recording with Android again instead of using the record.mp4 file produced by FGA?
