### ISSUE TITLE
Gift Box Skipped

### ISSUE THREAD

**Issue by cryptlord4** [Fate-Grand-Automata/FGA#1510]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

KR

### FGA build number

1919

### Describe the bug

![1](https://user-images.githubusercontent.com/57585849/209450242-b21ba047-076f-46c7-a786-bea5ae1042f5.png)
![2](https://user-images.githubusercontent.com/57585849/209450247-3ca6e088-e6f4-4634-bd66-09373b26660a.png)

After updating the latest version
all 4stars skiped ...

### Video

https://user-images.githubusercontent.com/57585849/209450362-9b22140c-a715-4e27-b24b-a90cc8f1de2d.mp4

### Device model

bluestak 

### Android version

7

### Screen size

1600x900

### RAM

8GB

**Comment by reconman** [comment]
Please test build 1921, which is available soon.

**Comment by cryptlord4** [comment]
> Please test build 1921, which is available soon.

Thx I will :)

**Comment by cryptlord4** [comment]
> Please test build 1921, which is available soon.


https://user-images.githubusercontent.com/57585849/209454456-61bb01c0-de33-48dc-8c98-96a2d8d15e9a.mp4

It hasn't been revised yet

**Comment by reconman** [comment]
Oops, I moved it to the right!

**Comment by reconman** [comment]
Please test 1922.

**Comment by cryptlord4** [comment]
> Please test 1922.

thx, working now !!! :)
