### ISSUE TITLE
My FGA doesn't choose the supports 

### ISSUE THREAD

**Issue by KoumaTL** [Fate-Grand-Automata/FGA#1511]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1921

### Describe the bug

I have had this problem for some time with the FGA, maybe since I changed smartphones. Now that I have an Infinix HOT11s NFC, my FGA never chooses the stand. I have tried several times to uninstall and install the app again, but it never works. Besides, I have already extracted all the images of the supports, the CEs, and I have already put an CE to be able to farm at Christmas (CE that I put the name Cristiano Ronaldo).

Sorry for the flaws in the writing, I'm using a translator and I don't know very well the English language.

### Video

![Screenshot_20221224-184043](https://user-images.githubusercontent.com/121323987/209451723-f3e6bb73-cd74-44ff-8a99-defc466499da.jpg)
![Screenshot_20221224-184047](https://user-images.githubusercontent.com/121323987/209451730-cadc9ba6-dd3b-46f9-a80d-48fa88f155f2.jpg)
![Screenshot_20221224-184051](https://user-images.githubusercontent.com/121323987/209451731-5b0c0beb-6921-4d83-b0d7-cc6f7f8f944a.jpg)
https://drive.google.com/file/d/1Xh5RCQ-En9Zt3SIDjp_y-YzdR06JJjRe/view?usp=drivesdk

### Device model

Infinix HOT11s NFC

### Android version

11

### Screen size

1080x2460

### RAM

6GB

**Comment by vybze** [comment]
https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting#where-should-i-place-the-play-button

**Comment by KoumaTL** [comment]
> https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting#where-should-i-place-the-play-button

I don't understand my friend. Should I use the method below this thread that you sent me? Because if so, I tried it twice and it didn't work.

**Comment by vybze** [comment]
Your play button is blocking an important area of the screen that is use for the support screen, if you want fga to work on that screen then move the button back to its original location 
![Screenshot_20221224-203517_FateGO](https://user-images.githubusercontent.com/32293918/209454776-ecc05f07-2c2c-4c3b-965c-4847919cd210.jpg)

**Comment by KoumaTL** [comment]
> Your play button is blocking an important area of the screen that is use for the support screen, if you want fga to work on that screen then move the button back to its original location 
> ![Screenshot_20221224-203517_FateGO](https://user-images.githubusercontent.com/32293918/209454776-ecc05f07-2c2c-4c3b-965c-4847919cd210.jpg)
> 

I can't believe that was my problem... I am very upset with myself, I admit it.

But thank you friend, now everything will happen as it should.
