### ISSUE TITLE
Bronze apples have been updated in the country 

### ISSUE THREAD

**Issue by 64luo** [Fate-Grand-Automata/FGA#1517]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

The national service updated the bronze apple on January 1st. Can you adapt it, thank you

**Comment by reconman** [comment]
Which server are you talking about?

**Comment by 64luo** [comment]
> Which server are you talking about?

Simple clothes

**Comment by 64luo** [comment]
> > Which server are you talking about?
> 
> Simple clothes 

CN

**Comment by reconman** [comment]
@MetLee Just making sure, so CN got (blue) bronze apples now?

**Comment by MetLee** [comment]
@64luo typed some odd phrases because of the stupid Google translation lol. `simple` means `simplified Chinese character` and `clothes` means `server` (they're of the same character in Chinese).

> @MetLee Just making sure, so CN got (blue) bronze apples now?
 
Yes, we got blue apples last week. Do you need some screenshots in CN server?

**Comment by 64luo** [comment]
> @MetLee Just making sure, so CN got (blue) bronze apples now?

![Screenshot_20230108_213933.jpg](https://user-images.githubusercontent.com/93940182/211199188-d72145e1-7e96-4488-adf0-29f96feb7bc5.jpg)
