### ISSUE TITLE
Automation and recording not working S21+

### ISSUE THREAD

**Issue by Colmirage79** [Fate-Grand-Automata/FGA#1518]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1925

### Describe the bug

Settings:
![Screenshot_20230102-102656_FGA (CI)](https://user-images.githubusercontent.com/112106526/210261654-a6473285-8329-4799-bf73-57990ea9b0f2.jpg)
![Screenshot_20230102-102736_FGA (CI)](https://user-images.githubusercontent.com/112106526/210261661-4f43c0ab-a981-48cf-ae21-fb4f2cd024a3.jpg)
![Screenshot_20230102-102748_FGA (CI)](https://user-images.githubusercontent.com/112106526/210261669-691b42af-8b62-4b55-bc50-7f6a473d8998.jpg)

Detection doesn't aling according to game UI and wont let me use the record feature due to invalid media projection error.
![Screenshot_20230102-115654_FateGO](https://user-images.githubusercontent.com/112106526/210261812-a8121ae3-feee-4efa-8b40-526cce24548a.jpg)

### Video

https://youtu.be/8tKyCNBdoiE

### Device model

Samsung Galaxy S21+

### Android version

12

### Screen size

2400x1080

### RAM

8GB

**Comment by reconman** [comment]
Have you tried restarting the FGA service? Seems like some other app broke MeriaProjection.

That's why FGA doesn't detect anything and recording doesn't work.

**Comment by Colmirage79** [comment]
> 

Already did, everything still the same way

**Comment by reconman** [comment]
Is there maybe an app interfering with FGO?

**Comment by Colmirage79** [comment]
> Is there maybe an app interfering with FGA?

Which kind of app could be interfering in that way? I didn't have any open apps other than fgo and FGA, maybe the game booster? (but i don't think so, since i have it set to not interrup or show itself while in game)

**Comment by reconman** [comment]
Usually it's a recording app, either one provided by the manufacturer or a third-party one.

Do you remember any app which asked for Media Projection rights?

**Comment by Colmirage79** [comment]
> Usually it's a recording app, either one provided by the manufacturer or a third-party one.
> 
> Do you remember any app which asked for Media Projection rights?

I don't have any recording third party app, just the Samsung one that's included.
I don't remember giving that sort of permission to any app, but just in case, where could i check it?

**Comment by Colmirage79** [comment]
Found the problem, I guess the phone detected i didn't use it often so it "manually disabled" the app. Just activated it and it works just fine.
