### ISSUE TITLE
How does card priority work?

### ISSUE THREAD

**Issue by ozxr** [Fate-Grand-Automata/FGA#1519]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

alright so I have an issue with the card priority, im not sure if its a bug or im just stupid but it goes like this
I have card priority set on B-A-Q-WB-WA-WQ-RB-RA-RQ for all waves and servant priority is default
my spishtar is on slot 1 and I want her to always be the one attacking, however the autofarm sometimes selects other servants cards even though there are spishtar cards available
it happens even when there are 4 spishtar cards and 1 support card, is there something wrong with the servant priority? should I just put support servants least on priority, maybe it'll work?

**Comment by reconman** [comment]
Can you share your battle config file and preferably a video of the issue?

**Comment by ozxr** [comment]
> Can you share your battle config file and preferably a video of the issue?

I recorded and im uploading the video to youtube rn, im not sure how to send the file or if you can do that on github though

**Comment by ozxr** [comment]
[https://www.youtube.com/watch?v=uGJU4D6M5zA](url)

video posted, im aware that it works on wave 1 & 2 and sometimes on wave 3 but there are times when its going for support cards over spishtar cards without brave chain (check 2:55 for example)
also do I have to upload the file on a site like mediafire then send the link here?

**Comment by reconman** [comment]
Add .txt to the file name, then you can upload it to github.

**Comment by reconman** [comment]
Shortly before the bug happens, FGA opens the details window of Space Ishtar because it thinks that Ishtar died.

If you can reproduce it again with Debug Mode enabled, I can check how to avoid this bug.

As a workaround, you can try setting the Servant Priority to 1 4 2 3 5 6 so the "new" Space Ishtar still has higher priority over the other servants.

**Comment by ozxr** [comment]
> Add .txt to the file name, then you can upload it to github.

[spishtar_90.txt](https://github.com/Fate-Grand-Automata/FGA/files/10356314/spishtar_90.txt)

**Comment by ozxr** [comment]
btw I uploaded the video on my channel & replied to your comment on youtube

**Comment by reconman** [comment]
Can't see a 2nd video with the debug rectangles yet.

**Comment by ozxr** [comment]
> Can't see a 2nd video with the debug rectangles yet.

posted vid with debug mode on

**Comment by reconman** [comment]
I fixed this back in September. Are you using the latest version of FGA?

**Comment by ozxr** [comment]
not sure, i'll reinstall it and check if it works

**Comment by ozxr** [comment]
it seems to work now, i've only tested it 3 times so can't say for sure, nice UI update btw

could you make it so it prioritizes cards with more critical chance over those with less/none
eg 30% critical chance arts card vs no crit, still picked the no crit one

**Comment by reconman** [comment]
Sorry, can't do critical chance. That would involve too much work and won't work reliably.
