### ISSUE TITLE
Installing AAAD & Fermata Auto on Realme 9pro Plus 

### ISSUE THREAD

**Issue by Tej1234567890** [Fate-Grand-Automata/FGA#1520]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Need methods on how to install AAAD & Fermata Auto as I am too confused and tried few way which didn't work
Current:
Android Auto : 8.5.624594
Android: 13

**Comment by reconman** [comment]
So what problems are you currently facing?

**Comment by Tej1234567890** [comment]
Only can see Fermata Controller and not Fermata Auto on the Android Auto Launcher 
![Screenshot_2023-01-08-07-42-03-76_31f2d1fb8a9cb6537600cbf449362b94](https://user-images.githubusercontent.com/122137304/211177651-00e365ad-5571-40ae-bc22-18d8ef531c9b.jpg)

**Comment by reconman** [comment]
I think you're in the wrong repository. This is Fate Grand Automata, not Fermata.
