### ISSUE TITLE
Skill - Character selection failure on 2nd and 3rd wave

### ISSUE THREAD

**Issue by zephyranthes03** [Fate-Grand-Automata/FGA#1521]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1927

### Describe the bug

Device : Pixel pro 7 pro
(It required custom area update left : 201 right 71)

Issue
I couldn't execute character selection required skill on 2nd and 3rd wave.
(I can use it when 1st wave only)
It clicked little left side of character selection area.

Thanks,

### Video

No video Using android 13.

### Device model

Pixel 7 pro

### Android version

7

### Screen size

3120x1440

### RAM

8GB

**Comment by reconman** [comment]
I'm pretty sure something is incorrectly configured.

Are you familiar with `adb`? If so, try doing
```
adb shell screenrecord /storage/emulated/0/fga.mp4
adb pull /storage/emulated/0/fga.mp4
```
To create a recording and then download it to the current Windows directory. The video is limited to 90 seconds and I don't know yet if it messes up FGA's screen detection.

**Comment by reconman** [comment]
I only just now noticed that you closed the issue, did you find the problem?
