### ISSUE TITLE
Servant support selection not working on the outer screen of the Z Fold 4 

### ISSUE THREAD

**Issue by kevinnaoko** [Fate-Grand-Automata/FGA#1523]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1927

### Describe the bug

I found a thread posted here, but it's labeled as a question and I don't see the fix mentioned there. [Here's what I'm talking about](https://github.com/Fate-Grand-Automata/FGA/issues/1345) 

So, the issue lies only on the outer screen of the fold (inner screen works flawlessly). FGA could still detect and do battle, but when it got to the support servant selection, it stops working and it wasn't able to detect the menus. 

Any potential workaround?

### Video

Although this isnt my footage, [here's how the game detection looks like in the support selection with debug mode on](https://github.com/Fate-Grand-Automata/FGA/issues/1345#issuecomment-1356851992)

### Device model

Z Fold 4

### Android version

13

### Screen size

Outer screen : 904 x 2316
Inner screen : 1812 x 2176

### RAM

12GB

**Comment by reconman** [comment]
Closing because I'd rather keep discussion about this in one place.

Also see the latest comment in #1345
