### ISSUE TITLE
Servant selection when active skill go wrong

### ISSUE THREAD

**Issue by locnguyen212** [Fate-Grand-Automata/FGA#1524]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1927

### Describe the bug

when i start the FGA, and when it active selection skill, there are 2 posibility:
- it chose the wrong position
- it chose the servant in the middle

### Video

The servant in the middle case: https://www.youtube.com/watch?v=sKwPh4eDZPg
The FGA chose wrong position case: https://www.youtube.com/watch?v=3Pr23PaVjBE
*Note: all the selection skills in this setting are set for Chen Gong only

### Device model

nox v7.0.5.1018

### Android version

12

### Screen size

1280x720

### RAM

4

**Comment by reconman** [comment]
There's something going on limiting image recognition.

Did you configure Nox as documented?

**Comment by reconman** [comment]
https://github.com/Fate-Grand-Automata/FGA/wiki/Running-on-Emulators#nox

**Comment by locnguyen212** [comment]
@reconman though i cant find "Use Root for Screenshots" option, but i am can find and enable Root, but still it still usually go to "select the servant in the middle" case

**Comment by locnguyen212** [comment]
@reconman im sorry, i though it was for nox, i found it but new problem occur
![ảnh](https://user-images.githubusercontent.com/77820509/213731113-a08cfab1-e8b5-42f3-9178-9861d1f677f9.png)

**Comment by locnguyen212** [comment]
i give up on the solution and decide to download ldplayer instead, it work perfectly fine
