### ISSUE TITLE
New Skill Confirmation for Kukulkan

### ISSUE THREAD

**Issue by imniwa** [Fate-Grand-Automata/FGA#1532]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Request new confirmation skill like space ishtar. this servant have 2 option ltr (cancel, use without absorb star, use absorb 10 star). 

![Screenshot_2023-02-08-07-31-08-117_com aniplex fategrandorder](https://user-images.githubusercontent.com/42795054/217398251-3f301b54-88d2-4ae2-ac33-1bc3ed1630b4.jpg)

**Comment by vybze** [comment]
Why didn't you post images for all three skills?

**Comment by imniwa** [comment]
> Why didn't you post images for all three skills?

all three skills have the same option. later I will post with videos

**Comment by imniwa** [comment]
https://drive.google.com/file/d/1E5GhWyp3125wlayzsryryn53ykfdowwc/preview

**Comment by chillooo** [comment]
This skill confirmation mode could be a new trending, especially those servants have quick NP.
