### ISSUE TITLE
repeatedly click on top right screen and makes script not working properly

### ISSUE THREAD

**Issue by Yaaku** [Fate-Grand-Automata/FGA#1533]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1938

### Describe the bug

while on choosing support servant is working properly and after enter the battle always clicking on top screen and makes the script not working properly

### Video

https://www.youtube.com/watch?v=Q0tQgef5Yk0

### Device model

xiaomi redmi note 8 pro

### Android version

11

### Screen size

1080 x 2340

### RAM

6 gb

**Comment by vybze** [comment]
Skill use confirmation is on ingame while it's off in fga

**Comment by reconman** [comment]
Closing this since the solution was provided
