### ISSUE TITLE
FGA doesn't activate skills properly

### ISSUE THREAD

**Issue by ghostkhue** [Fate-Grand-Automata/FGA#1534]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1938

### Describe the bug

can't active skill

### Video

https://drive.google.com/file/d/1lup18u9ZCW8oThRiSjVPy_xs6mCUtCx5/view?usp=share_link

### Device model

reedmi note 11 pro

### Android version

13

### Screen size

1280x720

### RAM

8gb

**Comment by vybze** [comment]
Can't open link

**Comment by reconman** [comment]
@vybze I clicked on edit and fixed the link. It had the format of `[htttps://drive.google.com](url)`. `[](url)` is Github's default URL when you use the markdown buttons. The `[]` part is for the description, the `()` for the URL, but users don't know that and it's never explained to them by Github.

@ghostkhue Check Skill Confirmation. Should be On in FGA or Off in FGO.

**Comment by reconman** [comment]
Closing since the solution was provided and there was no reaction.
