### ISSUE TITLE
Fga se atasca al iniciar la batalla 

### ISSUE THREAD

**Issue by Daruba135** [Fate-Grand-Automata/FGA#1535]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1938

### Describe the bug

Fga se atasca al iniciar la batalla

Funciona bien al inicio, elije el soporte, pero cuando inicia la batalla se atasca. Si yo termino la batalla de manera manual vuelve y funciona. 

Ya lei los temas, la guía y no encontré solucion

### Video

![Screenshot_20230210-080851](https://user-images.githubusercontent.com/92073463/218112492-de8ca10b-3086-4d10-a0ed-d6df7d0b9f45.jpg)
![Screenshot_20230210-100133](https://user-images.githubusercontent.com/92073463/218112535-701e8bb6-3c36-49fa-b2ed-8d37df39a396.jpg)

### Device model

Huawei Honor 8x 

### Android version

8

### Screen size

2340 x 1080

### RAM

6 Gb

**Comment by Daruba135** [comment]
https://drive.google.com/file/d/10flUTEUHIGTbrWoEsmXwLm-K0KdgBsH9/view?usp=drivesdk

**Comment by bergerst** [comment]
Top of black bar megathread:

> Huawei, LG, Samsung and Xiaomi users can ignore this issue. You can get rid of the black bars through [system settings](https://github.com/Fate-Grand-Automata/FGA/wiki/Game-Area-detection#case-1-borders-around-fgo-are-black)

**Comment by reconman** [comment]
Top of black bar megathread:

> Huawei, LG, Samsung and Xiaomi users can ignore this issue. You can get rid of the black bars through [system settings](https://github.com/Fate-Grand-Automata/FGA/wiki/Game-Area-detection#case-1-borders-around-fgo-are-black)

**Comment by Daruba135** [comment]
Esta activado

**Comment by reconman** [comment]
Can you show me?

**Comment by Daruba135** [comment]
[
![Screenshot_20230210-103317](https://user-images.githubusercontent.com/92073463/218117741-ccdd8039-4b41-41c6-9d30-3e07482a394b.jpg)

**Comment by reconman** [comment]
Is the black bar on the top (near the camera) or bottom (home button)?

What is the "Hide Notch" setting in Display settings? Show Notch or Hide Notch? https://www.youtube.com/watch?v=ErRcvRa01dM

**Comment by Daruba135** [comment]
Ocultar muesca también está activo
![Screenshot_20230210-105332](https://user-images.githubusercontent.com/92073463/218122198-8ad4ccdc-ff1d-4c78-814a-d4ea718d8cdf.jpg)


Antes la tenía personalizada para que se oculte en fgo y a fga

**Comment by Daruba135** [comment]
Y a fga

**Comment by Daruba135** [comment]
Ok

**Comment by Daruba135** [comment]
https://drive.google.com/file/d/114ZDeuiTnUg-Hx8TuAh6yR66FK7BVq5i/view?usp=drivesdk




Aquí está en predeterminado

**Comment by reconman** [comment]
Is that with Default offsets? Can you try restarting the FGA service?

**Comment by Daruba135** [comment]
Ok

**Comment by Daruba135** [comment]
https://user-images.githubusercontent.com/92073463/218134517-3a25dcc9-0d61-4d4a-8425-0ddede4d9864.mp4

Compensaciones predeterminadas después de reiniciar fga

**Comment by Daruba135** [comment]
Hizo el primer gesto y luego se atasco

**Comment by reconman** [comment]
Wait, why is the black bar back again? Did you change some system settings again?

I only wanted you to change the FGA offsets from left=80 to Default.

**Comment by Daruba135** [comment]
Ok lo haré de nuevo

**Comment by Daruba135** [comment]
https://user-images.githubusercontent.com/92073463/218150984-e3175065-e5d4-4027-bb4d-5db682c03c7c.mp4

Ya   este el predeterminado sin ocultar muesca y reiniciando fga

**Comment by reconman** [comment]
Hmm clicks are broken now. Does restarting the phone help?

**Comment by Daruba135** [comment]
Ok

**Comment by Daruba135** [comment]
Lo intentare

**Comment by Daruba135** [comment]
https://user-images.githubusercontent.com/92073463/218159563-ce2360de-effd-4a01-9c1f-dd0853c7d032.mp4

Ya reiniciado


Creo que es mejor probar sin la muesca ya que antes era capaz de entrar a la batalla antes de atascarse

También en la solución de problemas decía  que si tenias Android 8 y tu celular tenia múesca que la desactive. Ya que solo es detectada en Android 9

**Comment by Daruba135** [comment]
Ya resolví el problema. Fui a casa de un amigo a que me pasara su fga

La versión 1927 y me funcionó

Luego vi que la versión 1938 es un prelanzamiento

MUCHAS GRACIAS POR INTENTAR AYUDARME A SOLUCIONAR EL PROBLEMA 😁😁😁😁😁😁

**Comment by reconman** [comment]
Every APK is marked a pre-release.

You probably only needed to reinstall FGA. Try updating to 1938 again.

**Comment by Daruba135** [comment]
Ok
