### ISSUE TITLE
Fga bug report

### ISSUE THREAD

**Issue by bhjs** [Fate-Grand-Automata/FGA#1537]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1938

### Describe the bug

Fga do not work properly, i can see it still scan the screen normaly  but it wont tab the screen. I tried restart my device but it still not work

### Video

https://youtu.be/i6UtyX0iDXY

### Device model

Redmi 9T

### Android version

10

### Screen size

6,53 inches

### RAM

4GB

**Comment by vybze** [comment]
Black bars on the left and right of the screen and something white in the top left corner of the screen. Post a screenshot here for custom game area values https://github.com/Fate-Grand-Automata/FGA/issues/1347 and you'll need to remove that white thing from the screen before you do anything

**Comment by bhjs** [comment]
> Black bars on the left and right of the screen and something white in the top left corner of the screen. Post a screenshot here for custom game area values #1347 and you'll need to remove that white thing from the screen before you do anything

That white thing is game turbo and it does not affect the fga, fga still work like 3 month ago with that white thing so i think it not that white thing fault

**Comment by vybze** [comment]
Ok let me ask you what version of fga are you using?

**Comment by bhjs** [comment]
> Ok let me ask you what version of fga are you using

It say 1938

**Comment by vybze** [comment]
From the video you posted we can see that fga is not properly aligned to your screen if you look at the video you'll see that the red box is showing up in the black bars in the bottom right corner of the screen. Has I said in my first post take a screenshot ingame of fgo and post it in this thread #1347 to get the values for your phone custom game area and input them in More Options > Advance > Game Area Mode. You'll also might have to turn off game turbo (the white thing) before you take the screenshot

**Comment by bhjs** [comment]
> From the video you posted we can see that fga is not properly aligned to your screen if you look at the video you'll see that the red box is showing up in the black bars in the bottom right corner of the screen. Has I said in my first post take a screenshot ingame of fgo and post it in this thread #1347 to get the values for your phone custom game area and input them in More Options > Advance > Game Area Mode. You'll also might have to turn off game turbo (the white thing) before you take the screenshot

I understand, but it cant turn off the game turbo, i even deleted it but somehow it still show up. I think it integration with my phone system. Can i upload the screenshot with that white thing ?

**Comment by vybze** [comment]
You can try

**Comment by reconman** [comment]
@bhjs Maybe the white thing can be hidden by modifying these system settings: https://www.youtube.com/watch?v=CMgVpfILWeQ

The bot in #1347 will not report correct values as long as the white line is there but I could determine the values manually if the video doesn't help.

**Comment by bhjs** [comment]
> @bhjs Maybe the white thing can be hidden by modifying these system settings: https://www.youtube.com/watch?v=CMgVpfILWeQ
> 
> The bot in #1347 will not report correct values as long as the white line is there but I could determine the values manually if the video doesn't help.

Thanks for your help but i somehow get the correct value when i randomly input number. Fga work normally now.
