### ISSUE TITLE
Redmi phone FGA wont start

### ISSUE THREAD

**Issue by DeemSong** [Fate-Grand-Automata/FGA#1540]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

TW

### FGA build number

1938

### Describe the bug

I start the run but it wont do anything
https://youtu.be/GEU-lzVnBCY

### Video

https://youtu.be/GEU-lzVnBCY

### Device model

Redmi Note 5 Pro

### Android version

9

### Screen size

2160x1080

### RAM

6

**Comment by reconman** [comment]
Does FGA click or scroll?

If not, some users were able to resolve this issue by reinstalling FGA.

**Comment by DeemSong** [comment]
> Does FGA click or scroll?
> 
> If not, some users were able to resolve this issue by reinstalling FGA.

It did not sir, let me try to reinstall

**Comment by DeemSong** [comment]
still not working sir

**Comment by DeemSong** [comment]
> Does FGA click or scroll?
> 
> If not, some users were able to resolve this issue by reinstalling FGA.

after reinstall still no working

**Comment by reconman** [comment]
What do you mean with "if I stop the app"?

Force kill? Stop service via notification? Close app in task manager? Press the play/stop button or run out of AP?

If anything but force kill check battery optimization and lock the app in the "recent apps" view. (Android Square button)
