### ISSUE TITLE
Miss click of servant skill

### ISSUE THREAD

**Issue by V-Baron** [Fate-Grand-Automata/FGA#1543]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Anyone know how to solve this problem? Using poco x3 pro

https://user-images.githubusercontent.com/126192371/220987784-68cee528-54d4-49cb-b01b-eca01fe794e3.mp4

**Comment by reconman** [comment]
I'll need a proper video with Debug mode recorded by FGA to help you.

**Comment by V-Baron** [comment]
I hope this helps
https://youtu.be/g9XmDTJEmII

**Comment by vybze** [comment]
I recommend you move the play button back to its default position

**Comment by V-Baron** [comment]
Tried placing the play button on default but still misses the input. The phone camera is on the middle, rotated it and give same result.

**Comment by V-Baron** [comment]
The only possible solution that I can make now is stop the script and restart it again.

**Comment by reconman** [comment]
The issue here is that FGA can't click in the top right because of something on your phone.

Is game turbo mode enabled on your device? If so, try disabling it.

**Comment by V-Baron** [comment]
Works well now. Thanks for helping.
