### ISSUE TITLE
About FGO

### ISSUE THREAD

**Issue by ARCHER123559** [Fate-Grand-Automata/FGA#1552]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Can Samsung M53 5G run FGO smoothly without any lag or crash while playing ?

**Comment by reconman** [comment]
Wrong place for asking. Only FGA related questions should be posted here.

You're better off asking reddit or gamepress.

**Comment by ARCHER123559** [comment]
what a harsh reality

**Comment by ARCHER123559** [comment]
i need a device so i can use fga on fgo without problems

**Comment by ARCHER123559** [comment]
and M53 i was asking if it will work on it

**Comment by reconman** [comment]
Like I said, this is not a forum. It's a way to report FGA bugs and ask the developers.
