### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by funggy** [Fate-Grand-Automata/FGA#1553]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1951

### Describe the bug

Not sure is it a bug or not, but I could not turn on the Accessibility for this app. It says something related to security reason. I don't have any idea where to do the settings, maybe other users with the same device can solve this for me?

### Video

https://cdn.discordapp.com/attachments/1054022573769359381/1081936950937788476/Screenshot_20230305-215021_Settings.jpg
https://cdn.discordapp.com/attachments/1054022573769359381/1081936951223009380/Screenshot_20230305-215023_Settings.jpg

### Device model

ROG phone 6D

### Android version

7

### Screen size

1080 x 1920

### RAM

16

**Comment by reconman** [comment]
See https://community.gamepress.gg/t/fate-grand-automata-discussion-and-help-thread-round-2/107040/1264

If you can make a screenshot of that setting, I'll add it to the FAQ.

**Comment by funggy** [comment]
OK, I kind of solved the problem. I have to give permission to the app which I never had to do on other phones.
It is on the top right corner on the screenshot.
https://cdn.discordapp.com/attachments/1054022573769359381/1081941626773061783/Screenshot_20230305-220727_Permission_controller.jpg
