### ISSUE TITLE
Melusine Buster loop doesn't work

### ISSUE THREAD

**Issue by Darkrider000** [Fate-Grand-Automata/FGA#1555]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1951

### Describe the bug

So this bug happened when at turn 2
When the game match start it check the servant info first before doing anything right?
so that also happened in turn 2 with Melsuine due to her changing form
and then the script just go for command card instead of picking skill first

### Video

I use andriod 13 so can't record video

### Device model

Oneplus 8

### Android version

13

### Screen size

6.55 inches

### RAM

12

**Comment by vybze** [comment]
Sounds like either fgo locked up during melusine change or the change took too long and fga just continue with its operations while the change is happening

**Comment by Darkrider000** [comment]
Ok I not sure if it solve or not, but for some reason I try to record while doing it the new problem occur which is it check "servant 2" 2 times instead then miss out the skill it supposed to press
I decide to clear the script and make a new one instead since the farm won't work if miss that skill
however when I try the new script which should be the same one (I only clear the command and do it again the export on same one) it everything worked again
so......I don't know what is the problem anymore
PS. also you seem to misunderstand but Melusine is changing form in wave 1 however the problem is it check her info again in wave 2 for some reason....not that it a problem anymore for some reason though

**Comment by vybze** [comment]
If you're still not having problems 3 days from now then I'm gonna close this has solved

**Comment by reconman** [comment]
Melusine isn't handled by FGA right now so it treats the new Melusine sprite as a sub-member. That's also why it takes new screenshots.

Would have to implement some special logic to overwrite the old sprite with the new one.

Honestly, I'm surprised that you're the first one to open an issue about Melusine.

**Comment by vybze** [comment]
> Melusine isn't handled by FGA right now so it treats the new Melusine sprite as a sub-member. That's also why it takes new screenshots.
> 
> Would have to implement some special logic to overwrite the old sprite with the new one.
> 
> Honestly, I'm surprised that you're the first one to open an issue about Melusine.

I was using her when koyanskaya came out and fga would just recheck her portrait during the first wave and it didn't mess with my runs any of the 100th of times I used her back then so I'm guessing that's why no one reported a issue until now

**Comment by danilaml** [comment]
For me it works but complains about failing to detect servant cards. It does probably make sense to special case Melusine (don't think anyone is farming with Hyde).
