### ISSUE TITLE
Cannot detect servent face

### ISSUE THREAD

**Issue by Graylily** [Fate-Grand-Automata/FGA#1556]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1951

### Describe the bug

I just updated to Android 13 yesterday.
Now Fga keep scrolling and reset on the Support Servent screen. It wont choose the servent i want. 

So i tried 'First' on Support Selection mode. The first wave was ok. But on the second wave, it didnt use skill or Np, just randomly 3 card. Oh and there a popup 'Cant detect card.. Belong to unknow servent'..

I thought maybe something wrong with the extract file so i deleted it and extract again but notthing work. 

### Video

I cant record, the record option turn gray

### Device model

Rogphone 6 

### Android version

13

### Screen size

1080x2448

### RAM

16

**Comment by reconman** [comment]
Can you please provide a screenshot of FGO on your phone?

**Comment by Graylily** [comment]
![Screenshot_20230308-160037](https://user-images.githubusercontent.com/121684408/223678388-5cb59eed-89e4-4ff8-affd-8430a52b56c7.jpg)

**Comment by reconman** [comment]
Did you use custom offsets?

#1347

You'll have to get rid of the thin white line on the right and move the play button away from the black bars for the bot.

The setting causing the white line is called "Smart Sidebar" on my phone.

**Comment by Graylily** [comment]
> Your offsets from #1347 are wrong.
> 
> You'll have to get rid of the thin white line on the right and move the play button away from the black bars for the bot.
> 
> The setting causing the white line is called "Smart Sidebar" on my phone.

I use offset r=134 l=134, turn off that sidebar, move play button but it still not  choose any servent, just keep scrolling and reset..

**Comment by reconman** [comment]
Those offsets are wrong.

The things I told you were for taking a good screenshot for the bot, not for running FGA.

**Comment by Graylily** [comment]
> Those offsets are wrong.
> 
> The things I told you were for taking a good screenshot for the bot, not for running FGA.

My bad. 
Thanks, its work. Before i updated Android 13 it was 134, now its 156.
