### ISSUE TITLE
Fga bug

### ISSUE THREAD

**Issue by ShadowDragon1329** [Fate-Grand-Automata/FGA#1557]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1951

### Describe the bug

Not choosing support skills properly 

### Video

Video 

### Device model

Samsung s23 ultra 

### Android version

12

### Screen size

1440×3088

### RAM

12

**Comment by ShadowDragon1329** [comment]
Screen shots
![Screenshot_20230314_235404_FateGO](https://user-images.githubusercontent.com/102644403/225101944-0754604c-74d0-49e0-b87c-2f3fa653e1d5.jpg)
![Screenshot_20230314_235417_FateGO](https://user-images.githubusercontent.com/102644403/225101951-575a5f0f-acaa-4319-980c-da64f709a488.jpg)
![Screenshot_20230314_231139_FateGO](https://user-images.githubusercontent.com/102644403/225101959-d2c56495-8ee0-4ce6-bbbd-fc1f4ec8a922.jpg)

**Comment by reconman** [comment]
Did you turn skill confirmation off in FGA?

**Comment by ShadowDragon1329** [comment]
Yes works now
