### ISSUE TITLE
FGA won't select a support unit 

### ISSUE THREAD

**Issue by Lolett69** [Fate-Grand-Automata/FGA#1559]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1951

### Describe the bug

When a node ends and Fga will find a support unit to pick, it stops for some reason because of width or something even though it used to work fine before. And yes I already did full screen display for fgo. 

### Video

https://youtu.be/y_QXKp5ojP8

### Device model

Huawei Y7A 

### Android version

10

### Screen size

1600x720, 6.67 inches

### RAM

4gb

**Comment by vybze** [comment]
Try moving the play button back to the default location

**Comment by Lolett69** [comment]
> Try moving the play button back to the default location
I tried it and nope, it still doesn't work.

**Comment by Lolett69** [comment]
I don't know where the default is but I tried it in a lot of different areas and it still shows the same error

**Comment by vybze** [comment]
Do you have gesture navigation turn on?

**Comment by Lolett69** [comment]
Yes, I turned it on.

**Comment by reconman** [comment]
Width must be positive indicates broken support images.

Try "Extract Default Support Images" under More Options -> Storage.

If that doesn't help, recreate the Support folder and press Extract Default Support Images again.

**Comment by Lolett69** [comment]
> Width must be positive indicates broken support images.
> 
> Try "Extract Default Support Images" under More Options -> Storage.
> 
> If that doesn't help, recreate the Support folder and press Extract Default Support Images again.

I deleted the old folder I used and made a new one to store the extracted suppott images and it finally worked again. Thanks a lot!
