### ISSUE TITLE
fga not getting enabled security issue OnePlus 9

### ISSUE THREAD

**Issue by CapYuno** [Fate-Grand-Automata/FGA#1563]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1951

### Describe the bug

![Screenshot_2023-04-01-21-34-36-65_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/86341130/229303327-089a0163-8bbe-401a-81fb-7f78f9299ac1.jpg)

The screenshot pretty much describes the bug. It doesn't let me enable it. I'm on the OnePlus 9 android 13

### Video

The script ain't even the issue.

### Device model

OnePlus 9

### Android version

13

### Screen size

1080 x 2400

### RAM

8GB

**Comment by reconman** [comment]
Duplicate of #1553

**Comment by CapYuno** [comment]
> Duplicate of #1553

The  “allow restricted settings” doesn't appear for me.
