### ISSUE TITLE
Can you add Koyanskaya of Light to the preferred support? 

### ISSUE THREAD

**Issue by zsolti94** [Fate-Grand-Automata/FGA#1580]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Want to loop with Koyan light

**Comment by reconman** [comment]
You know you can add her yourself, right?

Post them and I'll add them to the app.

**Comment by zsolti94** [comment]
oh, I got it somehow
thanks

**Comment by zsolti94** [comment]
Ok it works, kinda, but Koyan doesn use her 1st skill on wave 2, she presses the 3rd skill
