### ISSUE TITLE
Can't choose servant in servant support

### ISSUE THREAD

**Issue by Minh150302** [Fate-Grand-Automata/FGA#1581]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1951

### Describe the bug

fga doesn't pick characters in support, but battle runs normal

### Video

https://youtu.be/8qznleOty_8
![Screenshot_2023-05-09-15-14-25-17_577bcc70c040536a6d306ef99c704547](https://user-images.githubusercontent.com/106725503/237042369-1b6356c5-1edf-48f6-803c-f4f721d4d29c.jpg)
![Screenshot_2023-05-09-15-16-41-78_a3958233ae0a6cb82869d8ec995a3cb9](https://user-images.githubusercontent.com/106725503/237042384-c9e700c4-03ab-4404-90f5-b1f3950f5032.jpg)

### Device model

OnePlus Nord

### Android version

12

### Screen size

1080 x 2400

### RAM

12GB

**Comment by reconman** [comment]
FGO offsets changed with the latest update.

Try left=112, right=0.

Also move your play button to the bottom left.
