### ISSUE TITLE
TW server updated to 6th anniversary Version (Append Skill introduced)

### ISSUE THREAD

**Issue by ALIAZ333** [Fate-Grand-Automata/FGA#1583]
### Preparation

- [x] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

TW

### FGA build number

1951

### Describe the bug

Append Skill introduced and FGA won't select servants. Thanks in advance!!

### Video

https://github.com/Fate-Grand-Automata/FGA/assets/133506428/acc95b1b-01cf-47c1-b9ee-f42815ad37be

### Device model

Galaxy Note20 Ultra 5G

### Android version

11

**Comment by a7875512** [comment]
me too
TW server updated to 6th app no work

**Comment by the3dsandwich** [comment]
@a7875512 @ALIAZ333 Please help check if #1584 fixes your problem once it finishes building, thanks!

**Comment by ALIAZ333** [comment]
> @a7875512 @ALIAZ333 Please help check if #1584 fixes your problem once it finishes building, thanks!

Absolutely! Will report back once tested!!

**Comment by ALIAZ333** [comment]
Thanks for the quick reply!!

**Comment by a7875512** [comment]
@the3dsandwich app FGC 2006Version  still not working...

**Comment by the3dsandwich** [comment]
@a7875512 yeah I loaded it up and saw an error when I run it. I'll look into it.

**Comment by ALIAZ333** [comment]
After updating to the newest version (2009), servant selection seems fine, yet now I have this problem
![Screenshot_20230514-092019.jpg](https://github.com/Fate-Grand-Automata/FGA/assets/133506428/3f3dac31-2f18-44b7-9b97-c2b6027be149)

Is this something related with the new update? Or is this issue related to the full screen?

**Comment by the3dsandwich** [comment]
From the video is #1584 it seems that regular resolution works, I did produce the same error and I think it is related to fullscreen app margins.

**Comment by ALIAZ333** [comment]
May I ask is there a solution to this problem? Since the full screen settings on my phone was disabled, I assume this is probably something app related that I can't control? Forgot to mention I had the "ignore notch calculation" settings enable in the advance tag.

**Comment by the3dsandwich** [comment]
From my experiences this needs an update for FGA to bring TW up with other servers. I'm currently working on it but my development environment needs fixing before I can do any real work (a rather sad inconvenience)

For now, it seems that bluestacks + a standard 16:9 instance is your best bet.

**Comment by ALIAZ333** [comment]
Understood! Guess I'll stick to emulators for the time being… and do the rest on my phone manually XDD Thanks a lot for all the help!!

**Comment by the3dsandwich** [comment]
When I load the latest commit (that contains 2006 & 2009) with android studio and run a test battle on its Pixel 4 (2280x1080, 19:9) virtual device, it works just fine (was even using your Spishtar + Castorias comp)

update: just edited the AVD to 2400x1080, still works. Would you mind re-installing the latest version @ALIAZ333 
A fresh install might just work

**Comment by ALIAZ333** [comment]
Hi, thanks for the quick response! But after a fresh install, the issue still persists ha ha. I'm guessing it probably has something  to do with it not recognizing the attack button? Because up until selecting the attack button, everything was working smoothly, but once all skill selections were done, the error screen appeared.
Though this maybe unrelated, my Galaxy Note20 Ultra's resolution is 1440 x 3088. Really really appreciate your help!!!

**Comment by ALIAZ333** [comment]
<iframe src="https://drive.google.com/file/d/1GD52BJB3_RpPzt03B4g9V6JNC61ThHUM/preview" width="640" height="480" allow="autoplay"></iframe>

**Comment by the3dsandwich** [comment]
Now I'm honestly super confused. But if it works then I guess all is well.

If future TW player sees this, reinstalling the whole app may very well work.

@ALIAZ333 again thanks for your help!

**Comment by ALIAZ333** [comment]
Thank you too! I guess the issue has to be something with my old scripts ha ha! I can't thank you enough!

**Comment by reconman** [comment]
I think there's one more change necessary for the update list button.

Can you try specifying a support Servant/CE combination where FGA won't find a Support and has to update the list?

Does it update the list or switch between main and append skills?

**Comment by reconman** [comment]
Oh also, does FGO cover the notch area on your phone or not?

Wasn't really sure so TW is the only server where the "Ignore Notch" setting is still used.

**Comment by the3dsandwich** [comment]
@reconman Now it taps on append skills unfortunately. Not sure about notch since I don't have access to a phone with notch

**Comment by reconman** [comment]
I'll build a version without "Ignore Notch".

If someone is affected, they can use Custom Game Area.

**Comment by reconman** [comment]
Build 2010 should have the fixes. Please test.

**Comment by ALIAZ333** [comment]
Hi, after testing the latest version (2011), the list refreshes just fine, but it doesn't seem to scroll until the very end. I'll provide a video once I have the time!
