### ISSUE TITLE
how to fix it

### ISSUE THREAD

**Issue by raqupi** [Fate-Grand-Automata/FGA#1588]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

![Screenshot_2023-05-25-08-47-44-282_com android settings](https://github.com/Fate-Grand-Automata/FGA/assets/134567997/6609b2d0-bc9f-4b8f-97af-ab713fab5196)

**Comment by Bluetocho13** [comment]
https://youtu.be/0bcLjpfrmHw

**Comment by reconman** [comment]
Long click on FGA -> App Info-> Click on ... in the top right -> Allow restricted settings.
