### ISSUE TITLE
Adjust the order of treasures

### ISSUE THREAD

**Issue by ashyfox** [Fate-Grand-Automata/FGA#1589]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

When setting the script, I found that it is impossible to release and adjust the order of the treasures. If you use a servant likeMiss Crane, there will be a need to adjust the order of the treasures. I would like to ask if there is a way to set it.

**Comment by vybze** [comment]
I'm guessing that you're using a translator to write this question which is probably why it's a bit confusing to read. I'm guessing when you say treasure you mean noble phantasm in which case you can already set the order for their use already

**Comment by ashyfox** [comment]
Thank you for your reply. I later found out that the order can be adjusted on the script, just because there is no obvious UI performance when I click and setting it in attack button. I later saw that the order of the settings was confirmed and changed. Thank for your information.
