### ISSUE TITLE
If Servant face-card checks are disabled and Brave Chains are set to Avoid, Rearrange Cards become disabled 

### ISSUE THREAD

**Issue by Toratorap** [Fate-Grand-Automata/FGA#1594]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2012

### Describe the bug

If options are set to skip "Servant face-card checks" and "Brave Chains" are set to "Avoid" then "Rearrange Cards" will not work.
Expected Result is that Brave Chains can not be avoided because Servant face-card checks weren't done, so cards should just be selected in a standard rearranged order with no regards to what servant they belong to.
Seen result is that Rearrange Cards becomes completely disabled and command cards are selected in the standard high priority to low priority order.
Problem does not occur if Servant face-card checks are turned on or Brave Chains are set to Don't Care or After NP.
Not a terrible problem, but something to know.

### Video

Pending

### Device model

Samsung Galaxy S9

### Android version

10

### Screen size

1440x2960

### RAM

4GB

**Comment by vybze** [comment]
![20230607_223115](https://github.com/Fate-Grand-Automata/FGA/assets/32293918/262156c3-2f7f-44e9-8064-40f433c4ba06)
