### ISSUE TITLE
Gift Box EXP searching and clicking error or just broken ;(

### ISSUE THREAD

**Issue by reihunter360** [Fate-Grand-Automata/FGA#1595]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

2012

### Describe the bug

When i'm at 1x / 100x in lottery screen i get the Gift Box prompt to search and tap; seems like the giftbox is broken.
It also seems like it keeps prompting me into Gift Box prompt to search, even i'm on the normal screen (for battle nodes or friend gacha screen)

I think it broke when i shot that vid ... I managed to get it to work again by restarting the app. Then it broked again when i tried the 2nd video. The Battle and stuff is working at least.

Anyways, for my phone stuff... its Poco F3. I'm running a miui 12.5.19 by xiaomi.eu

### Video

https://youtu.be/ams2lMs5wvQ
https://youtu.be/4u3_b0hl8HM

### Device model

Poco F3

### Android version

12

### Screen size

2400x1080

### RAM

8GB

**Comment by reconman** [comment]
Use the built-in recorder under More Settings -> Advanced, not Android's recorder.

**Comment by yiqunl2-1863642** [comment]
I have a similar issue where gold embers are not selected at all.

Here is a video using built-in recorder:
https://youtu.be/ilgwhZMp0LQ

**Comment by chairmanxyz** [comment]
> I have a similar issue where gold embers are not selected at all.
> 
> Here is a video using built-in recorder: https://youtu.be/ilgwhZMp0LQ

Same here. On JP it's ignoring gold embers in the present box and only selecting silver. Doesn't matter what number I set for the max size.
