### ISSUE TITLE
Why i cant enable the accessibility?

### ISSUE THREAD

**Issue by Kalampag638** [Fate-Grand-Automata/FGA#1600]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

214

### Describe the bug

Help me 

### Video

https://github.com/Fate-Grand-Automata/FGA/assets/136629951/20d35c0b-f748-42c7-aa8d-77f145f813a9

### Device model

REALME 8 5G

### Android version

13

**Comment by reconman** [comment]
![Screenshot_2023-05-14-21-43-23-24_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://github.com/Fate-Grand-Automata/FGA/assets/12360257/c65cad09-431d-4c50-a502-5ef28be8ac92)
