### ISSUE TITLE
Latest JP update app can't find support

### ISSUE THREAD

**Issue by zsolti94** [Fate-Grand-Automata/FGA#1602]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

2020

### Describe the bug

Just updated to the latest version 2.74.0 and the app can't select the right support

### Video

I unable at the moment

### Device model

Samsung Galaxy s20+

### Android version

13

### Screen size

2400x1080

### RAM

12

**Comment by topopchips** [comment]
Its because of the addition of the class upgrade button on the support screen so turning skill level check off fixes it for now

**Comment by zsolti94** [comment]
> Its because of the addition of the class upgrade button on the support screen so turning skill level check off fixes it for now

Thanks, it works now 👍

**Comment by reconman** [comment]
Experimental fix is here, please test: https://github.com/Fate-Grand-Automata/FGA/suites/13658608263/artifacts/754261405
