### ISSUE TITLE
Why is the 2038 version a separate software?

### ISSUE THREAD

**Issue by Setsuei959** [Fate-Grand-Automata/FGA#1606]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Why is the 2038 version a separate software? Previous 2012 versions were able to be directly updated.

**Comment by reconman** [comment]
Announced in Discord first:

From now on, the canary APK is published under the package io.github.fate_grand_automata.debug on Github.

This means you'll have to transfer your settings from the old app manually.

The package change was required so I can publish the app as beta-only in the play store. Google doesn't allow me to publish the old app as beta unless I also make it publicly available, which attracts users who refuse to read instructions and leave 1-2 star ratings.

If Google accepts the play store submission for the new app, it will be published with the package io.github.fate_grand_automata (no .debug at the end), which will fix problems with restricted accessibility permissions and will install new builds through the play store.

Installing it through the play store is the only way to use FGA on Android 14 right now, that's the main reason why I had to trigger these major changes.

I'll notify you again once the play store entry is live.

**Comment by Setsuei959** [comment]
Fine！Thank you very much for your explanation.
