### ISSUE TITLE
Show QP Gathered for X rounds

### ISSUE THREAD

**Issue by Jokakun** [Fate-Grand-Automata/FGA#1609]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Basically, the app will show how much qp you have gathered after fighting in the treasure vault quests for X times.

**Comment by reconman** [comment]
Sorry, won't happen as that requires parsing numbers which is something FGA doesn't do.

**Comment by Jokakun** [comment]
i see. Can't expect fga to do everything anyways
