### ISSUE TITLE
I wonder what is wrong?

### ISSUE THREAD

**Issue by Zethio0121** [Fate-Grand-Automata/FGA#1610]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

It's been a while since I've noticed this kind of problem, and it's becoming annoying to me as I have already entered which servants and CEs I want, but the programs keep scrolling and scrolling, forcing me to pick the support servants manually, that's all.
![Screenshot_20230625-010114](https://github.com/Fate-Grand-Automata/FGA/assets/137643354/e133cfee-5cde-4b8e-9e59-2f87cade4257)
![Screenshot_20230625-010125](https://github.com/Fate-Grand-Automata/FGA/assets/137643354/9b72a2b3-5fa4-44aa-b9eb-0916c57b4a42)

**Comment by reconman** [comment]
Did you update the app? There was a recent bugfix for UI changes.

**Comment by Zethio0121** [comment]
> Did you update the app? There was a recent bugfix for UI changes.

i think I do? let me check

**Comment by Zethio0121** [comment]
> > Did you update the app? There was a recent bugfix for UI changes.
> 
> i think I do? let me check

yeh, just updated it.
kinda suck tho, need to readjust all over again :(
