### ISSUE TITLE
Add new Silver Material "Ether Photon Converger" into list of Materials

### ISSUE THREAD

**Issue by sdarkpaladin** [Fate-Grand-Automata/FGA#1613]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

New material found in Paper Moon: Ether Photon Converger

**Comment by reconman** [comment]
What's also missing:
- Sunscale
- Obsidian Edge
- Vestige of Madness

2 of them were introduced in LB7, Vestige of Madness is Paper Moon.

**Comment by reconman** [comment]
Fixed in version 2056, will be available as canary in 15 minutes and via play store in a few hours.
