### ISSUE TITLE
Unable to select support after 1st run

### ISSUE THREAD

**Issue by shockzcasts** [Fate-Grand-Automata/FGA#1619]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2074

### Describe the bug

I am unable to select supports after run 1, tried with multiple attempts, phone has no Notch option available, no other screen matching software, default support images extracted and folder replaced. No offset and game area set to default. Play button is also on the bottom left as suggested. I don't know if any offset is required, used FGA since like 2020 and had no issues back then.

![Screenshot_20230704-032229_FGA](https://github.com/Fate-Grand-Automata/FGA/assets/138525362/3cba1c43-608e-4619-968d-009bd2d755ab)
![Screenshot_20230704-033757_FGA](https://github.com/Fate-Grand-Automata/FGA/assets/138525362/50e26dab-e86d-40c1-aed7-b1235d58327b)
![Screenshot_20230704-033812_FGA](https://github.com/Fate-Grand-Automata/FGA/assets/138525362/3ca5ee73-b61b-44fe-9f0c-66351cd4c838)

![Screenshot_20230704-032243_FGA](https://github.com/Fate-Grand-Automata/FGA/assets/138525362/9c1d4287-6992-4970-ad8c-b811212f4eee)

### Video

[record_001.webm](https://github.com/Fate-Grand-Automata/FGA/assets/138525362/bdd68a86-3f72-4746-bdb9-59c570fd4d9a)

### Device model

Samsung Galazy A30

### Android version

11

### Screen size

1080 x 2340

### RAM

4GB

**Comment by vybze** [comment]
Did you get a recent phone update?

**Comment by shockzcasts** [comment]
Last software update for my phone was back in February, no further updates after.

**Comment by vybze** [comment]
You could try stopping and starting the service and also try clearing the cache. If that doesn't work you could export your scripts and uninstall and reinstall again to see if that helps

**Comment by shockzcasts** [comment]
Have tried to restart the service a few times to no avail. Also exported my scripts from an older build (1655) to import to this latest build and it also hasn't worked. Can't clear cache as well because this happened immediately after a fresh install so there is no cache to clear. I have both the CI build and the EA build and only the EA is enabled right now, though both aren't working either.

**Comment by vybze** [comment]
It seems to be having trouble telling which screen it's on, maybe @reconman can tell what's happening

**Comment by reconman** [comment]
Did you change any fine-tune similarity values?

If not, try lowering the Min Similarity by a few % and see if that helps. I wouldn't recommend going below 75 %.

**Comment by shockzcasts** [comment]
So I tried again today and it did end up working despite not changing any settings, but it is slightly inconsistent, having to restart every 4-11 runs. FGA doesn't seem to be able to track the screen in a few instances (Usually happens when the phone has a bit of a freeze)

**Comment by reconman** [comment]
Battery optimization?

**Comment by shockzcasts** [comment]
Doesn't seem to really be affecting anything, seems tuning down the similarity has helped a lot, though any time the game freezes it will completely bork the script and I'd have to restart it. I'd chalk that up to my phone more than anything though
