### ISSUE TITLE
Bot targeting the skills in the wrong servant

### ISSUE THREAD

**Issue by VirtualGohst** [Fate-Grand-Automata/FGA#1624]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2084

### Describe the bug

I was farming using the castoria system and Muramasa as NP spammer. But somehow FGA is always targeting the third servant in the game with every buff. I tried the trubleshooting guides to help but nothing changed, and aparently someone a year ago had the same issue in JP while farming with Drake and Koyanskaya, and all the help in the coments tell him to look at the trubleshooting guide. I also tried to swap the place of the servants and it alwais target the third, even if the target is the first servant.

### Video

I was not able to record, but the script for the bot is : d e1 fi g h1 i1 4,#, c l1 4,#, a a j1 k1 4,#,

### Device model

Samsung Galaxy S20 FE

### Android version

13

### Screen size

2400x1080

### RAM

4 GB

**Comment by reconman** [comment]
Disable Skill Confirmation in FGA. It prompted you to choose a value when you updated the app and you left it on enabled (I think)

**Comment by VirtualGohst** [comment]
> Disable Skill Confirmation in FGA. It prompted you to choose a value when you updated the app and you left it on enabled (I think)

It worked, thanks ;)
