### ISSUE TITLE
Support servant cannot be read 

### ISSUE THREAD

**Issue by Katsura-1234** [Fate-Grand-Automata/FGA#1625]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2087

### Describe the bug

I started the FGA after the latest update.
Now usually it the support caster artoria would boost my Muramasa along with my own. But now support caster artoria keeps boosting herself instead of Muramasa. Also i cannot start the record option.
Please help.

### Video

I am not able to

### Device model

Xiaomi 11X Pro

### Android version

13

### Screen size

1080 x 2400 

### RAM

8GB

**Comment by vybze** [comment]
Skill confirmation is on by default after the last update if you didn't set it to off during the initial setup that was introduced during the latest update

**Comment by Katsura-1234** [comment]
Thanks it works now

**Comment by Katsura-1234** [comment]
Thanks it works now
