### ISSUE TITLE
Clicking slightly to the left after selecting skill that needs a target

### ISSUE THREAD

**Issue by FMRavelli** [Fate-Grand-Automata/FGA#1628]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2091

### Describe the bug

I just updated the app and made sure to disable skill confirmation.

I started the script normally and left it running while doing something else. Some hours later, I found that there was something broken with my script (which had been working fine since the first week of the anniversary event).

I started to pay attention to what was wrong and found out that skills that require a target (for example, every skill from Koyanskaya) were clicking slightly to the left of where they were supposed to be. I'll try to record it.

My device never had any problems like this in over 3 years of use. I have yet to try some other comps, but it's frustrating that something that was working fine just a few days ago suddenly stopped, especially since the event is coming to an end...

I checked every config and all seems fine, restarted the phone and every app involved

### Video

https://youtu.be/Wjhi2Y0jPHs

### Device model

Xiaomi Redmi note 8 pro

### Android version

13

### Screen size

2340x1080

### RAM

4

**Comment by reconman** [comment]
Skill confirmation is off in FGA but on in FGO.

**Comment by FMRavelli** [comment]
> Skill confirmation is off in FGA but on in FGO.

First of all, thanks for the quick response, but this is not correct, the confirmation screen was appearing only because some of the skills were already used, I assure you, Skill confirmation is not ON and the problem stands

![Screenshot_2023-07-11-08-44-07-906_com aniplex fategrandorder en](https://github.com/Fate-Grand-Automata/FGA/assets/43186110/c721c632-12a3-4c9c-9dae-2f8832368b5a)

**Comment by Gaphid** [comment]
I can confirm this happens to me as well, I'm trying to set a 3 turn farming team with Koyanskaya as well and it always clicks to the side when selecting the character which leads to it selecting the wrong target.

**Comment by FMRavelli** [comment]
> I can confirm this happens to me as well, I'm trying to set a 3 turn farming team with Koyanskaya as well and it always clicks to the side when selecting the character which leads to it selecting the wrong target.

check FGA if the skill confirmation is on

**Comment by reconman** [comment]
Sorry for the wrong answer, didn't take a look at your full video.

The actual issue in the video was that the play button was in front of Waver's HP/NP bars.

Their right side is used to detect if a Servant is dead.

In your case it believed only the 2nd and 3rd Servant were alive.

If that happens, the skill target layout is different in FGO.

Instead of
```
| Servant 1   Servant 2   Servant 3 |
```
it's
```
|        Servant 2     Servant 3           |
```
See how Servant 2 and 3 are more centered?

So it expects only 2 targets but 3 are alive in your case.

Move the play button to the left screen edge to fix this.

**Comment by FMRavelli** [comment]
I cleared all data storage, reinstalled and updated to the newest version and tried your solution, everything seems to work fine now, thanks!

:)
