### ISSUE TITLE
FGA not selecting support

### ISSUE THREAD

**Issue by MaeGershwin** [Fate-Grand-Automata/FGA#1632]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2101

### Describe the bug

Case 1: 
If FGA starts quest -> It taps the quest but gets stuck at the support picking.

Case 2: 
If quest is already started and the quest is set to repeat -> It executes the commands without issue but gets stuck again at support picking.

### Video

Case 1: 
![Screenshot_2023-07-17-04-49-26-678_com aniplex fategrandorder en](https://github.com/Fate-Grand-Automata/FGA/assets/139716926/8cd25464-6581-41ac-b72e-1705a833936c)

Case 2: 
![Screenshot_2023-07-17-05-17-44-258_com aniplex fategrandorder en](https://github.com/Fate-Grand-Automata/FGA/assets/139716926/760e07be-f042-4f78-bc2d-16abd53c04fe)

Those red boxes keep spazzing out the support picking. I can't give a screen recording due to me being in android 13.

### Device model

Xiaomi POCO M5

### Android version

13

### Screen size

1080 x 2400

### RAM

6 + 5 GB

**Comment by reconman** [comment]
Move the play button to the bottom left.

See the red rectangle near the play button in your screen shots? Support detection is done through that rectangle and you're covering the game content with the button.

**Comment by MaeGershwin** [comment]
Okay it works now. Thanks for the quick and detailed response!
