### ISSUE TITLE
stuck on support and picking wrong servant

### ISSUE THREAD

**Issue by IneedHelppleaseeeee1** [Fate-Grand-Automata/FGA#1633]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1908

### Describe the bug

Fga stuck on support, I have turned off the notch display, and game mode area is on default, it also keeps picking the middle servant on support, fine tune is also all on default. 

### Video

https://youtu.be/oprJySnjdc8

### Device model

Huawei Y7 2019

### Android version

7

### Screen size

1520 x 720

### RAM

4gb
![Screenshot_20230719-070433](https://github.com/Fate-Grand-Automata/FGA/assets/121291694/e3bb74c1-ff9c-4872-bedf-caee1ce87fd5)
![Screenshot_20230719-070429](https://github.com/Fate-Grand-Automata/FGA/assets/121291694/dfef9ce3-4f30-443d-8ec2-b514d30e0f13)

**Comment by IneedHelppleaseeeee1** [comment]
I meant the "Ignore Notch Calculation"

**Comment by IneedHelppleaseeeee1** [comment]
I meant disabling the "Ignore Notch Calculation". Sorry I didn't explain well.

**Comment by reconman** [comment]
Ignore Notch Calculation does nothing, how exactly did you disable the notch?

**Comment by IneedHelppleaseeeee1** [comment]
@reconman sorry for not explaining I meant like changing notch to default. (sorry couldn't reply faster cus I was at hospital) 
![Screenshot_20230726-134959](https://github.com/Fate-Grand-Automata/FGA/assets/121291694/1db88ffa-0f1d-41c2-9874-f7e599564065)

**Comment by reconman** [comment]
Are FGO and FGA set to the same value in "Default"?

What did you set them to?

**Comment by IneedHelppleaseeeee1** [comment]
@reconman yes both fga and fgo are all to default. And yes by default I did not touch "fine tune" and "Game mode area" in fga.

**Comment by reconman** [comment]
I meant what's behind the "Custom >" button in the screenshot above

**Comment by IneedHelppleaseeeee1** [comment]
@reconman it makes you choose what supported apps to have a full display or to have a notch. Probably only available on huawei. 

![Screenshot_20230727-194329](https://github.com/Fate-Grand-Automata/FGA/assets/121291694/9344e629-8aa3-44ee-8e50-2539146f5bca)

![Screenshot_20230727-194349](https://github.com/Fate-Grand-Automata/FGA/assets/121291694/fdd60c94-1ab9-4919-b3de-e84d57a0532c)
![Screenshot_20230727-194345](https://github.com/Fate-Grand-Automata/FGA/assets/121291694/dca80ba3-ffc7-4d2e-abfa-f8bd9f57a564)
![Screenshot_20230727-194337](https://github.com/Fate-Grand-Automata/FGA/assets/121291694/4d48ebb1-eb13-46ee-95fd-46a711c8cf27)

**Comment by IneedHelppleaseeeee1** [comment]
@reconman mines an Huawei y7 2019, an old one that cant update to the current one.

**Comment by reconman** [comment]
What do you mean? What's blocking you from installing the new version?

Have you tried installing from the play store? https://play.google.com/store/apps/details?id=io.github.fate_grand_automata

**Comment by IneedHelppleaseeeee1** [comment]
Ohh wait i thought u meant the phone version not the fga version
 sorry.

**Comment by IneedHelppleaseeeee1** [comment]
Gimme a sec

**Comment by IneedHelppleaseeeee1** [comment]
@reconman it works but only up to support picking and it says this. 
![Screenshot_20230728-074717](https://github.com/Fate-Grand-Automata/FGA/assets/121291694/050f3874-9b0a-4905-9e57-5654f22769e3)
![Screenshot_20230728-074714](https://github.com/Fate-Grand-Automata/FGA/assets/121291694/3c1d7744-37ce-4ae2-bfe0-a01cc05d6e24)

**Comment by IneedHelppleaseeeee1** [comment]
Batlle configs
![Screenshot_20230728-074843](https://github.com/Fate-Grand-Automata/FGA/assets/121291694/9836f976-9d2d-4929-bd13-25843bf8fdc3)
![Screenshot_20230728-074840](https://github.com/Fate-Grand-Automata/FGA/assets/121291694/4290bfeb-346b-4301-9285-1c139280a60c)

**Comment by IneedHelppleaseeeee1** [comment]
@reconman and all the advance options are all on default, especially the fine tunes. 
![Screenshot_20230728-074938](https://github.com/Fate-Grand-Automata/FGA/assets/121291694/6f3ea8ed-cd12-47ba-a50b-39ec87e862a0)
![Screenshot_20230728-074935](https://github.com/Fate-Grand-Automata/FGA/assets/121291694/45b6b714-9722-4e8d-ba51-efb5bdcefebf)

**Comment by IneedHelppleaseeeee1** [comment]
https://youtu.be/QTKqDdI3PUA

@reconman problems still the same, still stuck on support

**Comment by IneedHelppleaseeeee1** [comment]
this is the updated version on fga 2112 @reconman

**Comment by reconman** [comment]
I misdiagnosed the issue. Debug rectangles are misplaced but FGA seems to detect the support screen.

The issue is that scrolling doesn't work and I have no idea why. It only happened to a few users so far with no known solution other than reinstalling.

**Comment by IneedHelppleaseeeee1** [comment]
@reconman I managed to fix fga by making both fgo and fga "Hide notch" in the custom notch and rotating my phone (where the camera is on the right side) It works normally now. All the setting on fga are on default. 

![Screenshot_20230729-082227](https://github.com/Fate-Grand-Automata/FGA/assets/121291694/514ae08e-4520-40d3-b6d4-64470bfcac85)

**Comment by reconman** [comment]
What you should do so the rotation doesn't matter:
Take a screenshot and post it in https://github.com/Fate-Grand-Automata/FGA/issues/1347

Just make sure that the screenshot has the black bars in it.

Then use the offsets calculated by the bot.
