### ISSUE TITLE
Have FGA scroll further to account for more support servants

### ISSUE THREAD

**Issue by ezhu7** [Fate-Grand-Automata/FGA#1635]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

NA version, Build 2103

Request: Have FGA scroll further to be able to see all servants before refreshing the supports. 

Because of Triple Support, NA will scroll a certain amount and then refresh the support page. However this amount of scrolling is not the entire length of all supports shown. As you can see from the video linked, FGA only scrolls about 1/3 of the entire supports list. 

https://drive.google.com/file/d/1W5MJx7EOGLbq_UD6IlKXg21MbVNSdPW0/view?usp=drive_link

This will be beneficial because it will get a wider search of different support servants before falling back to the secondary selection.

**Comment by reconman** [comment]
Already implemented in More Options -> Advanced -> Fine-Tune

![Screenshot_2023-07-19-09-01-56-58_44e4053104beb6e0bb0551f0dc5dd970.jpg](https://github.com/Fate-Grand-Automata/FGA/assets/12360257/63829320-5cf2-4137-b228-afdbbd15232a)

**Comment by ezhu7** [comment]
Ah, thank you!
