### ISSUE TITLE
Add Sima Yi (Reines) to the preferred servants

### ISSUE THREAD

**Issue by duradara** [Fate-Grand-Automata/FGA#1640]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Currently Reines is the only support who is not in there. 
Someone asked about this in 2021 but she is still not there #919
Sorry if my English is bad.

**Comment by reconman** [comment]
>  No one has asked for this feature before in other issues (even the closed ones)

Which is obviously not true.

Next time create a comment in the original issue.
