### ISSUE TITLE
When selecting the wrong Servant skill during the battle screen and giving it to another Servant.

### ISSUE THREAD

**Issue by dateyanai** [Fate-Grand-Automata/FGA#1641]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

2103

### Describe the bug

00:36When selecting the wrong Servant skill during the battle screen and giving it to another Servant.
![Screenshot_2023-07-24-18-38-08-45_44e4053104beb6e0bb0551f0dc5dd970](https://github.com/Fate-Grand-Automata/FGA/assets/71442886/15882487-3556-428a-8ec2-921a6e153b4c)
![Screenshot_2023-07-24-18-38-26-81_44e4053104beb6e0bb0551f0dc5dd970](https://github.com/Fate-Grand-Automata/FGA/assets/71442886/6d63e8cb-0bfd-4d6d-a101-7a3f33759571)

### Video

(https://youtu.be/OTJeGTn7O30) 

### Device model

Realme narzo 50 Pro

### Android version

13

### Screen size

2400x1080

### RAM

32.77G(92.6G/128G)

**Comment by reconman** [comment]
Did you accidentally enable Skill Confirmation?

**Comment by sesshodr** [comment]
same for me, don't understand why

**Comment by sesshodr** [comment]
check skill confirmation in more settings, disable that

**Comment by dateyanai** [comment]
> 您是否不小心在 FGA 中启用了技能确认？

**Comment by dateyanai** [comment]
> 您是否不小心在 FGA 中启用了技能确认？

I didn't confirm the skill activation.

**Comment by dateyanai** [comment]
> 在更多设置中检查技能确认，禁用它

All settings in FGA are default and the skill confirmation option in the game's battle interface was not turned on. It worked properly in the previous versions, but I encountered this problem after updating to the new version from the Play Store.

**Comment by dateyanai** [comment]
> 您是否不小心在FGA中启用了技能确认？

All settings in FGA are default and the skill confirmation option in the game's battle interface was not turned on. It worked properly in the previous versions, but I encountered this problem after updating to the new version from the Play Store.

**Comment by reconman** [comment]
But Skill Confirmation doesn't have a default value anymore, you have to decide.

You've closed this issue, so did it work after disabling Skill Confirmation in FGA?

**Comment by dateyanai** [comment]
> 但技能确认不再有默认值，你必须决定。
> 
> 您已经解决了这个问题，那么在 FGA 中禁用技能确认后它是否有效？

"I still can't run it properly. I tried updating FGA to version 2110, but it still doesn't work correctly."

**Comment by dateyanai** [comment]
> ### 准备
> * [x] 我测试了[最新版本](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
> * [x] 我查看了其他问题（甚至是[已关闭的问题](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed)）
> * [x] 我阅读了[故障排除指南](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)
> 
> ### FGO服务器
> 中国
> 
> ### FGA 内部版本号
> 2103
> 
> ### 描述错误
> 00:36在战斗画面中选择错误的Servant技能并将其交给其他Servant时。 ![截图_2023-07-24-18-38-08-45_44e4053104beb6e0bb0551f0dc5dd970](https://user-images.githubusercontent.com/71442886/255565665-15882487-3556-428a-8ec2-921a6e153b4c.jpg) ![截图_2023-07-24-18-38-26-81_44e4053104beb6e0bb0551f0dc5dd970](https://user-images.githubusercontent.com/71442886/255565672-6d63e8cb-0bfd-4d6d-a101-7a3f33759571.jpg)
![Uploading Screenshot_2023-07-25-14-40-53-15_aea65f8d686cc6c065dfd97f67f4a929.jpg…]()

> 
> ### 视频
> （https://youtu.be/OTJeGTn7O30）
> 
> ### 设备型号
> Realme narzo 50 Pro
> 
> ### 安卓版本
> 13
> 
> ### 屏幕尺寸
> 2400x1080
> 
> ### 内存
> 32.77G(92.6G/128G)

**Comment by reconman** [comment]
![Screenshot_2023-07-25-09-15-12-76_44e4053104beb6e0bb0551f0dc5dd970.jpg](https://github.com/Fate-Grand-Automata/FGA/assets/12360257/b5d1159b-f79c-4353-97f7-e69408bebf63)

**Comment by dateyanai** [comment]
> ![截图_2023-07-25-09-15-12-76_44e4053104beb6e0bb0551f0dc5dd970.jpg](https://user-images.githubusercontent.com/12360257/255820650-b5d1159b-f79c-4353-97f7-e69408bebf63.jpg)

Thank you very much for your solution, and I'm also sorry that I was so fixated on the game settings that I didn't realize it was my own mistake of accidentally turning on the FGA skill confirmation setting.
