### ISSUE TITLE
FGA is not able to select support servent

### ISSUE THREAD

**Issue by Gunkun1** [Fate-Grand-Automata/FGA#1642]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2112

### Describe the bug

I just downloaded the latest FGA and it looks like the selection process of support servents is not working. I checked the more option>Advance for notch calculation as I thought that's the issue but the option was not there.

### Video

https://youtu.be/sTgYCwZi_NY

### Device model

Redmi K20 pro

### Android version

11

### Screen size

6.38 inches, 1080×2340

### RAM

8gb

**Comment by reconman** [comment]
So which support are you looking for in the video?

**Comment by Gunkun1** [comment]
Castoria+Caldea teatime

**Comment by reconman** [comment]
Can you upload the battle config file?

**Comment by Gunkun1** [comment]
![1690739216543](https://github.com/Fate-Grand-Automata/FGA/assets/140953904/af565971-f3f9-49c3-b78d-de29c937c575)
![1690739216550](https://github.com/Fate-Grand-Automata/FGA/assets/140953904/36cc4c48-b7ff-42b1-9cc7-44a93ad36a38)

**Comment by reconman** [comment]
You selected Chaldea Lunchtime instead of Teatime and the video had no Castorias with Lunchtime.

And I meant to export the battle config and upload the file, not to take screenshots.
