### ISSUE TITLE
Support Selector not working 

### ISSUE THREAD

**Issue by rossengarten** [Fate-Grand-Automata/FGA#1648]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2113

### Describe the bug

The App was working fine on an older build on my phone but couldn't refresh the supports. After downloading the newest release on my android phone (fga ci 2113) the app stopped working entirely, ran it on debug mode and it got to the support screen and then stopped working  

### Video

https://youtu.be/VEsB0OSANPM 

Youtube link depicting the bug 

### Device model

Galaxy A21s

### Android version

12

### Screen size

6.5 inches, 720x1600

### RAM

6gb

**Comment by reconman** [comment]
What's your battle config? Can you export it and upload it here?

**Comment by rossengarten** [comment]
Github doesn't support the .json files so here's the pdf 
[--plswork.fga.pdf](https://github.com/Fate-Grand-Automata/FGA/files/12242179/--plswork.fga.pdf)

in case this is wrong here are the screenshots of the config
![Screenshot_20230802-212901_FGA (CI)](https://github.com/Fate-Grand-Automata/FGA/assets/111813472/5d425c99-846d-485d-9a4e-e925df064f48)
(1/2)
![Screenshot_20230802-212907_FGA (CI)](https://github.com/Fate-Grand-Automata/FGA/assets/111813472/4d81c914-e498-4309-be95-4096d62707aa)
(2/2)

**Comment by reconman** [comment]
Can you check if moving the play button to bottom left helps?

The first screen looks normal (for the current version) where it rejects the non 10/10/10 Koyanskaya.

On the All screen it tries to scroll but hits the Merlin by mistake.

**Comment by rossengarten** [comment]
I did but the issue is still there. I checked on an older build for fga ci which was working prior to the update and it's rejecting the preferred support too

**Comment by reconman** [comment]
Can you record another video where a 10/10/10 Koyanskaya is visible?

**Comment by rossengarten** [comment]
this will sound ingenious but it started working again, is it okay to reply back on this thread if there are more hiccups ?

**Comment by reconman** [comment]
Sure, I'll mark this issue as closed for now.
