### ISSUE TITLE
command bug

### ISSUE THREAD

**Issue by Nicxr** [Fate-Grand-Automata/FGA#1649]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2113

### Describe the bug

my phone is an A20S and I use the Castoria + Space Ishitar + Castoria and Oberon loop. I activate the FGA and it runs normally in the quest, but after 2-3 runs the game simply crashes in the second wave of the quest and the NP of the DPS (Space Ishitar) does not activate, it goes straight to the cards (does not activate the NP, only attacks normal even with full Noble Phantasm). What do I do?

### Video

Bought A20s 2 years ago. 3 GB of RAM and 32 GB of internal memory.

### Device model

A20s Samsung

### Android version

11

### Screen size

1560x720

### RAM

3GB

**Comment by YoshiA55** [comment]
I've been having the same issue as yours for a whole day now with my J7pro and I've just found the solution. Turn the battery optimization ON. Idk why but it acts the contrary way it says on a potato phone and protect it agains a RAM usage explosion. I recomend turning even the opmization of FGO on, as it made lag stop completely in my phone.
