### ISSUE TITLE
skill is used on the wrong object

### ISSUE THREAD

**Issue by mikulove233** [Fate-Grand-Automata/FGA#1651]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

skill is used on the wrong object
I read the guide and found the problem and fixed it.
This report is mainly to ask that the previous version can be used normally without opening the skill confirmation
In this update, if the skill confirmation is not turned on, it will appear to be used on the wrong object.
I want to use the previous version.
Is there any previous app available.

**Comment by reconman** [comment]
What are you talking about?

Keep your Skill Confirmation settings in sync between FGO and FGA.

If you don't want Skill Confirmation in FGO, then turn it off in both.

**Comment by mikulove233** [comment]
> What are you talking about?
> 
> Keep your Skill Confirmation settings in sync between FGO and FGA.
> 
> If you don't want Skill Confirmation in FGO, then turn it off in both.

What I mean is that the last version I used, even if the confirmation skill is not turned on, it will not be used on the wrong character.
After updating the new version, there was an error in the action I had set before, and there was no problem after turning on the confirmation skill.
So I want to switch back to the previous version

**Comment by reconman** [comment]
That's just wrong.

Turn it off both in FGO and FGA.

**Comment by mikulove233** [comment]
> That's just wrong.
> 
> Turn it off both in FGO and FGA.

It turns out that both sides are out of sync.
Skill confirmation is enabled in fga
sorry it's my problem
Thanks
