### ISSUE TITLE
FGO doesn't respond to FGA when on lockscreen

### ISSUE THREAD

**Issue by Dreamingfl0wer** [Fate-Grand-Automata/FGA#1652]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2113

### Describe the bug

Whenever the screen goes to lock while the app is running FGO stops responding. This never happened before, it runs fine when unlocked, but after the first run the phone automatically goes to lock screen and won't respond anymore. I checked debug mode and it shows that FGA is working fine. But FGO stops responding to the inputs. 

I already restarted my phone and forced stop FGA app and also turned off battery saver mode, but nothing seems to work.

### Video

![image](https://github.com/Fate-Grand-Automata/FGA/assets/141519780/2ad32681-3555-4b6b-abd6-4e3054b5bedb)

### Device model

Samsung Note 8

### Android version

9

### Screen size

2960x1440 

### RAM

6GB

**Comment by misakamayako** [comment]
samsung's game center will  prevent any input when locked, i think it's not a bug. you can set auto touch production to never to prevent this.
