### ISSUE TITLE
FGA don't click anything on Support Servant screen

### ISSUE THREAD

**Issue by sdwbbl** [Fate-Grand-Automata/FGA#1654]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2113

### Describe the bug

FGA never click anything on servant screen even though i choosen servant class and "first" instead of "manual" on FGA app, it started to do this when i updated this app

### Video

.

### Device model

Xiaomi Note 9

### Android version

11

**Comment by reconman** [comment]
I can't help you without a video

**Comment by ThiBei** [comment]
Hello, I had the same issues (I'm on NA). It clicks to go to the next quest but it doesn't select the servant class (and the servant)in the support liste. When I go directly into the fight, it completes the entire fight, but when it goes back to the support servant selection, it repeats the same thing as before. By closing FGO and FGA several times, it worked at some point.
Hope it helpt a bit

**Comment by xuanye-li** [comment]
try lowering the fga button so it doesn't block the support icons

**Comment by konoha-kido** [comment]
Having same issue, even when the FGA button doesn't block the support icon

**Comment by antactics** [comment]
same problem

**Comment by Zerviscos** [comment]
I have the same issue with this one. It happened after updating. At first it was just scrolling down the support screen not choosing any servant, but after a restart it wasn't doing anything at all anymore.

**Comment by Zerviscos** [comment]
Ok I think I found the issue. If you have a phone that hides the camera notch, turn it off. I have an S21 Ultra and it has that feature, it's probably messing with how the script looks at the entire screen.

**Comment by reconman** [comment]
Since OP doesn't respond and others post comments without any helpful info, I'll close this issue.
