### ISSUE TITLE
Abnormal script interaction

### ISSUE THREAD

**Issue by skyperion04** [Fate-Grand-Automata/FGA#1656]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

2113

### Describe the bug

servant 3 is being picked instead of servant 1 based on the script I made. this is on Ldplayer. Changing display resolution, reinstalling the app did not help.

No recent changes, apart from updates to Ldplayer/FGA. Have tried carving out a new instance, reinstalling game/FGA, importing scripts, same issue.

![Screenshot_20230807-155933](https://github.com/Fate-Grand-Automata/FGA/assets/30910950/60bc7574-4918-4868-aefb-f718a8b04652)

### Video

https://youtu.be/sI55-tZg9is

### Device model

Ldplayer9

### Android version

9

### Screen size

1600x900, 1280x720

### RAM

4GB

**Comment by vybze** [comment]
Skill confirmation is on in fga
