### ISSUE TITLE
Can additional NP be selected

### ISSUE THREAD

**Issue by Misha-Ma** [Fate-Grand-Automata/FGA#1659]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Sorry if it has been asked i couldn't find it. If after the preselected script is run can noble phantasms be added to card selections to clear a wave?

**Comment by reconman** [comment]
I'm not sure if I understand you correctly. Do you mean using face cards before the NP? If so, then that's already implemented in the bottom left after pressing the Attack button in the command builder. (Cards before NP)

**Comment by Misha-Ma** [comment]
I'll try to be clearer. if for whatever reason the battle isn't over once all the commands you chose FGA is set to use face cards until the wave or battle is finished or the party is killed and you have to withdraw. I'm asking if FGA can be set to use an NP that becomes available instead of only using face cards. 
I hope i explained it better that time.

**Comment by reconman** [comment]
That's Spam mode. You can enable automatic skills and NPs for wave 3 in your case.

**Comment by Misha-Ma** [comment]
Thank you so much.
