### ISSUE TITLE
Don't select Command Cards of immobilized servants in battle

### ISSUE THREAD

**Issue by metapone** [Fate-Grand-Automata/FGA#1666]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Similar to how FGA avoid cards of stunned servants, which I assume works fine on NA.

**Comment by reconman** [comment]
Can you make a video of the situation you mean?

**Comment by blue-lightning** [comment]
I'll get a video later. In the meantime, you can replicate this easily by using a support Oberon's 3rd skill on turn 1 to immobilized a servant, then let FGA auto attack next turn.

**Comment by blue-lightning** [comment]
Now that I think about it, does FGA avoid Charmed servant cards?

**Comment by metapone** [comment]
I have taken a video here. It would be better if FGA can avoid useless cards.
https://drive.google.com/file/d/1VfAnu10SVt2fiPzYSZOF9MRCgrZuJ8UH/view?usp=sharing

**Comment by reconman** [comment]
> Now that I think about it, does FGA avoid Charmed servant cards?

No it doesn't, it only checks for stun right now.
