### ISSUE TITLE
FGA getting stuck in battle after selecting support/CE

### ISSUE THREAD

**Issue by spiral6** [Fate-Grand-Automata/FGA#1668]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

2093

### Describe the bug

Every time FGA selects a new support for farming, it gets stuck between two selections. 

### Video

https://youtu.be/6-aep_cj8VQ?si=-yLywBAaQvSqzazZ&t=370

### Device model

Official Android Emulator

### Android version

11

### Screen size

1080x2220

### RAM

4.1GB

**Comment by reconman** [comment]
Your Emulator seems to be severely underpowered.

Please try Nox, Bluestacks, Memu or LDPlayer instead with the settings in https://github.com/Fate-Grand-Automata/FGA/wiki/Running-on-Emulators
