### ISSUE TITLE
FGA does not use commands in wave 2

### ISSUE THREAD

**Issue by BloodBuster** [Fate-Grand-Automata/FGA#1676]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

2152

### Describe the bug

【【FGO】FGA脚本问题，第二回开始就不放技能直接出卡平a-哔哩哔哩】 https://b23.tv/d1OOmRE

### Video

[【【FGO】FGA脚本问题，第二回开始就不放技能直接出卡平a-哔哩哔哩】](https://b23.tv/d1OOmRE) 

### Device model

vivo iQOO Neo5

### Android version

13

### Screen size

2400x1080

### RAM

12GB

**Comment by reconman** [comment]
You used `下一回合（同一波敌人）` instead of `下一波` in the command builder.

Your command should contain `4#,´ instead of `4,`.

**Comment by BloodBuster** [comment]
Problem solved, thank you感谢
