### ISSUE TITLE
I can't click "ok"

### ISSUE THREAD

**Issue by Duchtao1609** [Fate-Grand-Automata/FGA#1681]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

I can't seem to click "ok" I'm not sure why because it was just working fine before : ( please help me!

**Comment by vybze** [comment]
If you need help with something please fill out a bug report
