### ISSUE TITLE
Opening Treasure Chest in Summer Event

### ISSUE THREAD

**Issue by Twilight666** [Fate-Grand-Automata/FGA#1684]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

While it doesn't look like this event gets a rerun, and I didn't find a similar event in JP history, is it possible to add an auto-opener for the summer event.
Something similar to lotteries, since we can only open chests in groups of 100

**Comment by vybze** [comment]
I don't think adding support for a feature that will only be used once makes much sense
