### ISSUE TITLE
Android 13"Oneui 5.1" accessibility unavailable.

### ISSUE THREAD

**Issue by 7pillo7** [Fate-Grand-Automata/FGA#1689]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

KR

### FGA build number

2170

### Describe the bug

Android 13"Oneui 5.1" accessibility unavailable.
![Screenshot_20231006_161912_Papago](https://github.com/Fate-Grand-Automata/FGA/assets/147136326/efb8aa3a-4b78-4b41-a248-5886c4624c13)

### Video

Android 13"Oneui 5.1" accessibility unavailable.
![Screenshot_20231006_161912_Papago](https://github.com/Fate-Grand-Automata/FGA/assets/147136326/efb8aa3a-4b78-4b41-a248-5886c4624c13)

### Device model

Galaxy S22 Ultra

### Android version

13

### Screen size

1280x720

### RAM

8GB

**Comment by reconman** [comment]
Install via the play store

**Comment by 7pillo7** [comment]
I downloaded it through the Play Store.
It worked fine at first, but after a few days it just stopped at the servant selection screen.
After directly selecting a servant, you can run dungeons or skip the story.

**Comment by reconman** [comment]
Is the play button in the bottom left?

**Comment by 7pillo7** [comment]
Everything has been resolved. I pressed the play button and confirmed that it was not recognized because of that.

**Comment by 7pillo7** [comment]
Everything has been resolved. I pressed the play button and confirmed that it was not recognized because of that.

**Comment by 7pillo7** [comment]
Everything has been resolved. I pressed the play button and confirmed that it was not recognized because of that.
