### ISSUE TITLE
FGA "ap run out" screen when apple selecting

### ISSUE THREAD

**Issue by Jairogalassi** [Fate-Grand-Automata/FGA#1699]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2239

### Describe the bug

After finishing the run and the apple selection screen comes up, it looks like it selects the apple but the "ap run out" screen appears and the fga stops. Tried FGA and FGA(CI) and with both i got the same problem. I don't know if this could be of importance but i was using it before and didn't had this problem at all but i had to format my pc and then after installing everything again i have this issue.
Emulator: LDPlayer 9 (Latest version 10/29/2023)
Screen size type: cellphone - 720x1280(dpi 320)
Model: Samsung - SM-S901N
CPU: 6 cores

![1](https://github.com/Fate-Grand-Automata/FGA/assets/136653195/487685ea-ec26-4329-97ed-f2c0b67ce9be)

### Video

https://github.com/Fate-Grand-Automata/FGA/assets/136653195/7610a61d-31c8-4ceb-8883-70a4e043e40f

### Device model

LDPlayer

### Android version

9

### Screen size

1280x720

### RAM

4GB

**Comment by EquinoxPhoenix** [comment]
Yeah I am getting the same issue with using SQ. Though I am using the Samsung Galaxy Fold 3

**Comment by luruijie23** [comment]
exact same issue

**Comment by transformer214** [comment]
I have this problem as well after the update earlier.
