### ISSUE TITLE
Skip animation between waves clicks the servant portrait sometimes

### ISSUE THREAD

**Issue by mackoz** [Fate-Grand-Automata/FGA#1711]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2281

### Describe the bug

Sometimes when skipping the wave animation, the click will click on the rightmost servant portrait and will be stuck. Can we move the click to another part of the screen?

### Video

I couldn't get a video since it happens randomly depending on the pause between waves

### Device model

Pixel 7 Pro Android 14

### Android version

13

**Comment by reconman** [comment]
Thanks for the feedback, I'll adjust the click position.
