### ISSUE TITLE
FGA automation tool follows Macro at first, then ignores macro to use all skills.

### ISSUE THREAD

**Issue by jchou111** [Fate-Grand-Automata/FGA#1716]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2283

### Describe the bug

FGA app is activated on Bluestacks X with High Performance mode enabled and Graphics set with OpenGL as Graphics Renderer. Using Direct X makes F/GO not render in Bluestacks.

Activated both apps and ran a mission node. FGA app follows macro instructions at first, then ignores macro to begin using S1 skills in order from left to right.

See attached files and video preview for demonstration.
![FGA macro configuration](https://github.com/Fate-Grand-Automata/FGA/assets/153958883/43592b10-af4b-44a0-9901-810558045a5b)

### Video

Google Drive video link. Debug mode is enabled.

https://drive.google.com/file/d/1iKCrqn7pA-BqzPDHD6twO7j8e0RWrnBQ/view?usp=sharing

### Device model

Bluestacks X emulator for PC version 5.14.10.1008 P64

### Android version

7

### Screen size

1920 x 1080

### RAM

4GB

**Comment by reconman** [comment]
You're probably using the skill spam feature unintentionally.

Please check the battle config.

**Comment by jchou111** [comment]
After some testing, I found the [Spam All] option enabled. I disabled it and the macro works perfectly!

Thank you very much! A friend who used the app and I were absolutely stumped by this issue.
