### ISSUE TITLE
Tunguska raid intro is not skipped

### ISSUE THREAD

**Issue by MatheusOPP** [Fate-Grand-Automata/FGA#1722]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2305

### Describe the bug

When running the script at the Tunguska final raid, the long "Evil of Humanity" intro and dialogue do not get skipped, even though this could be easily done with one tap manually. Although not a game breaking bug, this does slow down farming considerably, and it would be ideal if it could be remedied.

### Video

N/A

### Device model

Samsung Galaxy S21+

### Android version

13

**Comment by ntk512** [comment]
sorry, but I can't see where the "skip intro" button is

**Comment by ntk512** [comment]
Thanks, I saw it. However my phone cannot enable accessibility service to applications from unknown sources, I'm looking to fix it =(

**Comment by MatheusOPP** [comment]
Would like to confirm this fix works perfectly on my phone. Was also having the issues in #1720 and can confirm they also are fixed in this build after setting stage similarity to 100% and "next turn" in the battle config.
