### ISSUE TITLE
Run only when AP is max/Run only every X minutes

### ISSUE THREAD

**Issue by d7c0** [Fate-Grand-Automata/FGA#1757]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Would it be possible to make it so that it only runs when you've reached your AP cap (maybe by checking if it can use a Bronze Apple or not) to prevent AP waste?

Or alternatively "run only every X minutes"?

**Comment by d7c0** [comment]
Please, make it so that we can have it run every X minutes. Is it possible? I wish for this feature every day. I AM ON MY HANDS AND KNEES, I BEG OF THEE, PLEASE MILORD

**Comment by reconman** [comment]
How is only running at full AP preventing AP waste?

**Comment by d7c0** [comment]
> How is only running at full AP preventing AP waste?

Just in that you can't generate any more.

It's more like I'm not sure when I'll be able to sit down and do the MSQ missions, so I try to keep as much AP in reserve as possible without wasting by it going beyond the cap. This means I have to run a mission every 200 minutes (40 AP) to prevent going over the cap and wasting AP.

I think it could be useful for when you're waiting for the next section of an event to release as well, and wish to have as much AP on hand as possible.

**Comment by reconman** [comment]
This feature is obsolete once the blue apples appear in NA, so it will not be added to FGA.

**Comment by d7c0** [comment]
I would still wish for a feature like that to be implemented so that you wouldn’t have to waste saplings.
So far, I’ve just been setting up a script in the emulator to run a mission after X minutes, but this tends to occasionally bug out when the computer is locked.

**Comment by d7c0** [comment]
> This feature is obsolete once the blue apples appear in NA, so it will not be added to FGA.

I would still wish for a feature like that to be implemented so that you wouldn’t have to waste saplings.
So far, I’ve just been setting up a script in the emulator to run a mission after X minutes, but this tends to occasionally bug out when the computer is locked.
