### ISSUE TITLE
Allow Preferred Friend Only

### ISSUE THREAD

**Issue by balthanon** [Fate-Grand-Automata/FGA#1761]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Now that preferred selection of a friend is combined with servants and CEs it isn't possible to select only a friend, even if you don't care about the Servant or CE because you know the friend will have the right options available with a selected CE.  I used this quite frequently for 'generic' scripts that I didn't want to modify each time for different Servants when Friend selection was separate.

Ideally, the pop up and error checking on preferred should be expanded to just having at least one of the three options filled out rather than specifically CE or Servant.

**Comment by reconman** [comment]
Rejected, friend supports can change anytime if your friends decide to, so requiring a specific servant and/or CE is better.

**Comment by SuperRiderTH** [comment]
> friend supports can change anytime if your friends decide to

In my opinion, this is why I used just friends for the selection. I only have a select few friends on my list, and I would rather use whatever they have prepared over a random servant. I came over to GitHub to see if this was an oversight, but if it is an intentional design decision then this is very disappointing.

**Comment by balthanon** [comment]
I'm not sure how common it is (though I have heard a fair number of people say they do it on various forums), but part of the reason that I want this is also because I have two accounts.  So I and others in that situation can be guaranteed that the support in question isn't going to change unless we want it too.  And even if that isn't the case, people who are actually friends could likely get a heads up from that friend if they're using this functionality and they're going to change their Servants.

It's not the end of the world if it isn't supported, but I guess I don't see the benefit to restricting it to requiring those two other than maybe avoiding user confusion for someone who's not familiar with FGA.  (And not spending time updating the app, of course.)  Disabling the friend only option means that users need to create additional support images for Servants/CEs that might otherwise not be needed.  And scripts may still end up messed up with preferred Servants if a friend changes the ascension level of their Servants and you don't have that image in your FGA too, so you have similar downsides with that option as well.
