### ISSUE TITLE
FGA clicks 'close' button instead of 'repeat' button after finishing free quest(KR server, Galaxy tab S7+) 

### ISSUE THREAD

**Issue by Apollyon0815** [Fate-Grand-Automata/FGA#1763]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

KR

### FGA build number

2469

### Describe the bug

I have Galaxy S23 and Galaxy S7+, and I tested both to check this.

Before FGO KR server update in January 31, both S23 and S7+ worked normally.
FGA clicks 'repeat' button to continue farming when it finishes free quest.

Since the update, there has been a problem with FGA on S7+.

On S7+, FGA clicks the 'close' button, select the free quest again, and then use the apple.(if it has to)

On the other hand, S23 uses the apple immediately after pressing the 'repeat' button normally.

This occurs regardless of the type of apple.(Gold, silver, bronze, blue)

I reinstalled the FGA of the S7+, but the same problem occurred.

I know this is not game breaking thing, but it takes more time when farming.
If this is a bug, I want to know if it is a fixable problem.

### Video

none, android 13

### Device model

Galaxy tab S7+

### Android version

13

### Screen size

2800x1752

### RAM

12GB

**Comment by reconman** [comment]
I'll need a video with debug mode to be able to find the issue.

Here's a guide on how to record FGA on Android 13 with a PC: https://youtu.be/iIjZPjDcZeM
