### ISSUE TITLE
Rearrange Cards Option

### ISSUE THREAD

**Issue by Dimastico** [Fate-Grand-Automata/FGA#1771]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Maybe it's obvious but what exactly does/what is the rearrange cards option for?
I searched the various sections of the site for an explanation but I couldn't find anything, maybe I didn't search well or I'm blind.

![Screenshot_20240224-004707](https://github.com/Fate-Grand-Automata/FGA/assets/49933780/105637f6-40d1-48ce-b9fb-a141b8fef7e2)

**Comment by d7c0** [comment]
AFAIK It's to do High Priority, Medium Priority, High Priority, instead of High Priority, High Priority, Medium Priority.
Like BAB instead of BBA if you have the Default Card Priority.

**Comment by Dimastico** [comment]
> AFAIK It's to do High Priority, Medium Priority, High Priority, instead of High Priority, High Priority, Medium Priority. Like BAB instead of BBA if you have the Default Card Priority.

Oh I understand, thanks

**Comment by reconman** [comment]
Btw, it's documented here: https://github.com/Fate-Grand-Automata/FGA/wiki/Battle#rearrange-cards

**Comment by Dimastico** [comment]
> Btw, it's documented here: https://github.com/Fate-Grand-Automata/FGA/wiki/Battle#rearrange-cards

Oh, not being accustomed to using GitHub, I couldn't see the wiki section on my mobile phone but now I understand how to see it, thank you very much.

**Comment by danilaml** [comment]
@reconman is there a typo in the wiki or is it just worded confusingly? It says
>The Rearrange Cards feature orders the 3 strongest cards so the 2nd strongest is used last.

But in the example of the "default" priority (i.e. rearrange disabled), 2nd stronges is already used last:

>If default card priority is used, FGA will pick these 3 cards:
>
>Jeanne Archer Buster (strongest card)
Castoria Buster (3rd strongest card)
Jeanne Archer Arts (2nd strongest card)

**Comment by reconman** [comment]
@danilaml "Default" in this case refers to WB WA WQ B A Q ..., not to Rearrange Cards being off.

**Comment by danilaml** [comment]
@reconman so without rearrange, it'd be
>- Jeanne Archer Buster (strongest card)
>- Jeanne Archer Arts (2nd strongest card)
>- Castoria Buster (3rd strongest card)

correct?
