### ISSUE TITLE
The newest version forced stop

### ISSUE THREAD

**Issue by Trungbuiap** [Fate-Grand-Automata/FGA#1827]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA, JP

### FGA build number

2687

### Describe the bug

I installed the newest version but the app doesn't run. When I click the app, it flashes and does nothing, I can't enter the app.

### Video

https://github.com/Fate-Grand-Automata/FGA/assets/90678953/ae43b34c-e2c7-44d8-84b6-1fe173ddb18f

### Device model

Samsung Galaxy S8 Plus

### Android version

9

### RAM

4GB

**Comment by reconman** [comment]
2687 isn't the latest, update went live a few minutes ago.

**Comment by Trungbuiap** [comment]
Thanks for your respond

Vào 10:43 Th 7, 25 thg 5, 2024 reconman ***@***.***> đã viết:
