### ISSUE TITLE
Party Selection Screen is broken after anniversary update 

### ISSUE THREAD

**Issue by vybze** [Fate-Grand-Automata/FGA#1867]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

2740

### Describe the bug

Anniversary increase the amount of parties you can have up to 15 now which broke fga ability to change to the present party in a battle script 

### Video

![Screenshot_20240804-040651_FateGO JP](https://github.com/user-attachments/assets/84e4d663-e032-48a5-a75d-efe266ed1516)
![Screenshot_20240804-060503_FateGO JP](https://github.com/user-attachments/assets/368d42b2-ae8e-4e2a-bdaa-1a47ba2684ff)

### Device model

Galaxy s10

### Android version

12

**Comment by nnnphu269** [comment]
+1

It's auto change the party and stuck there.

**Comment by AsdAsdAsd001** [comment]
Bump

This can be circumvented on the player's end by selecting the team, then once you're in the fight itself, then turn on the script, but should still be fixed if possible on FGA's side. Thanks <3

**Comment by EquinoxPhoenix** [comment]
Yeah it's cause they added 5 new teams I think so should be easily fixable on FGA's end
