### ISSUE TITLE
Service crashes once after phone restart

### ISSUE THREAD

**Issue by Squork** [Fate-Grand-Automata/FGA#1881]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2834

### Describe the bug

(not critical)
At first start (after phone reboot) service crashes. 
After second start (even after force app stop) all works normal.
(Recorded a normal video after about a dozen tries. Repeats after each restart, but only once.) 

### Video

https://github.com/user-attachments/assets/b534f9c7-5f11-4c05-a373-672114fe9fa8

### Device model

Oneplus 9R

### Android version

14

### Screen size

1080x2400

### RAM

12gb

**Comment by reconman** [comment]
Can reproduce on my phone, currently debugging potential solutions.

I'll report back when I've found one.

**Comment by reconman** [comment]
Fix will be available from the play store in 1-3 hours.
