### ISSUE TITLE
JP Server not working on Sony Xperia 10

### ISSUE THREAD

**Issue by itscakebuffet** [Fate-Grand-Automata/FGA#269]
**Describe the bug**
Cannot get the app to function correctly on JP server.  Works no problem on NA.  I have to believe it's related to the odd resolution/size of the phone.

**Screenshots**
See video

**Video**
https://streamable.com/k6pvlx
https://streamable.com/vmy202

**Device Info (please fill atleast 'Device model'):**
 - Device model: Sony Xperia 10
 - Screen size: 1080x2560
 - Android Version: Android 10
 - RAM: 3GB

Started using the application around version 15, was always an issue but never filed a report until now.  Have tried this with and without notch calculation too.  As stated works great on NA and I'm very thankful for the app and your work!  Please let me know if there is any more information I can provide.  Thanks

**Comment by reconman** [comment]
The black bars on both sides seem like the source of the problem. One comes from the notch, where does the other one come from?

Maybe there's a setting somewhere to activate something like Samsung's fullscreen mode. so only the notch stays black. I can't find any similar setting on the internet for Xperia 10 phones.

**Comment by itscakebuffet** [comment]
Agreed the black bars just seem to be present on the JP version.  The app apk itself is sideloaded, that's the only difference I can account for between the two setups.  Suppose I can try clearing cache or reinstalling JP app?

**Comment by MathewSachin** [comment]
Someone on Gamepress reported that their Xperia 1 ii has the same issue.

https://community.gamepress.gg/t/automatic-farming-app-fate-grand-automata/72155/950?u=mathewsachin

> Suppose I can try clearing cache or reinstalling JP app

I don't think that would make much difference. There should be some setting on your phone, but I can't find anything by googling.

**Comment by itscakebuffet** [comment]
Confirmed reinstall does nothing.  Appreciate the link, glad to know this isn't an isolated incident.  Can probably close this out then as it is not related to your app.  Thanks again!

**Comment by MathewSachin** [comment]
I'll leave this open so that other Xperia users can know.

PS: Maybe we could find some way to detect the region taken by the game (even if it is not centred) in the future.

**Comment by itscakebuffet** [comment]
Data point regarding the new JP UI update.  Battle sequence seems to work fine.  Everything post battle continues to fail though for what I suspect are the actual changes in the UI layout.

**Comment by reconman** [comment]
First, FGA needs to be adapted to the new JP UI once DW fixes the layout problems (#571) and then it may also work on the Sony Xperia 10. But there's no guarantee.

**Comment by MathewSachin** [comment]
I believe the situation is the same for Sony Xperia 10 and for every other non-16:9 phone after the JP update, so we can merge this into #571.
