### ISSUE TITLE
Not Searching Support

### ISSUE THREAD

**Issue by welknair** [Fate-Grand-Automata/FGA#283]
Device Info:
- Device model: Google Pixel 3a XL
- Screen size: 2,220 × 1,080
- Android Version: Android 10
- RAM: 4 GB

Downloaded app earlier today, been experimenting with it. I made a basic setup to farm aurora steel and it was working fine, but when I went to use it later in the day I noticed it was no longer scrolling through my friends list to find a suitable support (Caster, MLB Lunchtime Waver 10/10/10, Friends Only) as it had been previously. Instead it correctly navigates to the Caster lineup, but then just sits there for a few seconds (instead of slowly scrolling) until it hits the refresh button, then sits again, repeating a few times until it just gives up and goes to the fallback (set to manual). 

Edit: I have no other recorders or overlays that would be interfering, that I'm aware of.

**Comment by reconman** [comment]
@welknair Seems like the template doesn't work if you're not logged in from the start.

new issue -> log in -> no template
log in -> new issue -> selection -> template
