### ISSUE TITLE
App doesn't work on Huawei p 30 Pro 

### ISSUE THREAD

**Issue by mg137b** [Fate-Grand-Automata/FGA#384]
The app won't work during battle or farming stages but it work when selecting support servants.  I try to make sure my phone setting is on and on the debug but still it won't work during battle. 

Device model:Huawei P30 Pro 
Screen size: 2400 x 1176 
Android versioj:10 
RaM: 8.0 GB

@MathewSachin 

<img height="500px" src="https://user-images.githubusercontent.com/71218710/93019203-c80d4580-f5ff-11ea-8dc6-bcc2e6f3d2de.jpg" /> <img height="500px" src="https://user-images.githubusercontent.com/71218710/93019206-c93e7280-f5ff-11ea-8a9c-5302fdf53ec5.jpg" /> <img height="500px" src="https://user-images.githubusercontent.com/71218710/93019208-ca6f9f80-f5ff-11ea-9611-6d31d91fa106.jpg" />

I can't for some reason upload video so I will try my best to screenshot if you nerd further info to screenshot I will gladly provide more. 
<img height="500px" src="https://user-images.githubusercontent.com/71218710/93019294-55e93080-f600-11ea-822e-0fd2a9b2726d.jpg" />

**Comment by reconman** [comment]
Please enable "Record Screen", which is visible in the last screenshot. "Debug mode" should still be enabled. Then open FGO and click on the play button while you're in battle. After a few seconds you can stop FGA.

Then go to the Fate-Grand-Automata folder in your file system. You will see a `record.mp4` file. Upload that to streamable.com or youtube.com, then post a link here.

Only then we will be able to find out the source of the error.

**Comment by mg137b** [comment]
https://youtu.be/lN2JFlCcBF4
https://youtu.be/Qbc2srRu0F4
https://youtu.be/2TV5m6Xj4EY

@MathewSachin these are the YouTube link. Hope this video recording help solving the problem.

**Comment by mg137b** [comment]
![Screenshot_20200913_210747_com mathewsachin fategrandautomata](https://user-images.githubusercontent.com/71218710/93020040-330d4b00-f605-11ea-94a3-c228d1e96df2.jpg)

**Comment by MathewSachin** [comment]
There are black strips on top and bottom of FGO. Get rid of them and FGA will work properly.
Someone had some gestures ON which caused those black bars.

This is also present in the Troubleshooting Guide BTW: https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Game-Area-detection#case-3-your-phone-has-borders-around-fgo-even-at-the-bottom-of-screen, but its specific to your phone, so I can't tell you how to get rid of them.

**Comment by reconman** [comment]
You could also try playing with this setting for FGO and FGA: https://consumer.huawei.com/en/support/content/en-us00423269/

**Comment by mg137b** [comment]
> You could also try playing with this setting for FGO and FGA: https://consumer.huawei.com/en/support/content/en-us00423269/

I have turn off the notch or hide notch in the setting but it still won't play. Worst now the problem is it won't automatically select support like it initially does. 
![Screenshot_20200913_215257_com aniplex fategrandorder en](https://user-images.githubusercontent.com/71218710/93021179-90a49600-f60b-11ea-86d4-431f83024e75.jpg)
![Screenshot_20200913_215319_com android settings](https://user-images.githubusercontent.com/71218710/93021183-94381d00-f60b-11ea-950b-e6ac20aef797.jpg)

**Comment by reconman** [comment]
There's still something that causes black bars to be at the top and bottom. Your screenshots are 1128 pixels high, but your actual screen resolution is 1176 pixels. Do you see something at the top and bottom or is it just black?

**Comment by mg137b** [comment]
> There's still something that causes black bars to be at the top and bottom. Your screenshots are 1128 pixels high, but your actual screen resolution is 1176 pixels. Do you see something at the top and bottom or is it just black?

For me it is just black and it hide the notch or cut out should solve the black thing right... But it seems nothing different.

**Comment by reconman** [comment]
No, I said you could try the notch option, not that it solves the issue. The notch option only affects the left black bar, it seems, not the thin top and bottom ones.

We can't tell you which exact settings need to be changed since neither of us owns that phone.

**Comment by mg137b** [comment]
> No, I said you could try the notch option, not that it definitely solves the issue. The notch option only affects the left black bar, it seems, not the thin top and bottom ones.
> 
> We can't tell you which exact settings need to be changed since neither of us owns that phone.

I see... It is strange that it work during support selection but the farming are not working... Is there anymore settings I can try to change?

**Comment by reconman** [comment]
> It is strange that it work during support selection but the farming are not working

It's just that some images can be matched even with the black bars, but others like the attack button cannot be matched.

You will have to look through your phone settings yourself and try different settings, we can't know which settings exist in Huawei P30 Pro.

**Comment by Wrathach** [comment]
@mg137b I'm a P20 Pro user, very similar to P30 Pro. Please make sure you : 
Under display settings :
- disable "Smart Resolution"
- use FHD+ resolution
- don't use "Full-screen display" for FGO
- use default notch setting
on Automata : 
- go to "more options" menu make sure "Ignore notch calculation" is turned on.

Has been working like a charm here for the past month, even after updating to the last version.

**Comment by mg137b** [comment]
> @mg137b I'm a P20 Pro user, very similar to P30 Pro. Please make sure you :
> Under display settings :
> 
> * disable "Smart Resolution"
> * use FHD+ resolution
> * don't use "Full-screen display" for FGO (or you can try enabling it, that's the one thing I'm not entirely sure about on the P30)
> * use default notch setting
>   on Automata :
> * go to "more options" menu make sure "Ignore notch calculation" is turned on.
> 
> Has been working like a charm here for the past month, even after updating to the last version.

How do u find FHD+resolution? Also how do u not make fgo full screen display? I hv trouble finding that setting?



Because this is mine full screen display setting look like 
![Screenshot_20200916_093335_com android settings](https://user-images.githubusercontent.com/71218710/93285780-e04bb300-f7ff-11ea-8395-16b8e8b2e3c6.jpg)

**Comment by mg137b** [comment]
> @mg137b I'm a P20 Pro user, very similar to P30 Pro. Please make sure you :
> Under display settings :
> 
> * disable "Smart Resolution"
> * use FHD+ resolution
> * don't use "Full-screen display" for FGO (or you can try enabling it, that's the one thing I'm not entirely sure about on the P30)
> * use default notch setting
>   on Automata :
> * go to "more options" menu make sure "Ignore notch calculation" is turned on.
> 
> Has been working like a charm here for the past month, even after updating to the last version.

Should I do default setting on fgo as well or choose hide cutout? 
![Screenshot_20200916_093723_com android settings](https://user-images.githubusercontent.com/71218710/93285992-53edc000-f800-11ea-9e1d-38b3852797f7.jpg)
![Screenshot_20200916_093739_com android settings](https://user-images.githubusercontent.com/71218710/93285998-56501a00-f800-11ea-834a-c74e1e3be547.jpg)
![Screenshot_20200916_093745_com android settings](https://user-images.githubusercontent.com/71218710/93286002-57814700-f800-11ea-954b-d71a890d709a.jpg)

**Comment by Wrathach** [comment]
If it's like P20 Pro then no need to bother with Full-screen display settings, it's probably already good if it's not in there. 
Use default cutout on FGO and "Show cutout" in the custom options. Make sure you use "Ignore notch calculation in the Automata App". 

Here are my own settings : 

![Screenshot_20200916_115031_com android settings](https://user-images.githubusercontent.com/668237/93322412-940a6e00-f813-11ea-9642-fc37383e46ea.jpg)
![Screenshot_20200916_115049_com android settings](https://user-images.githubusercontent.com/668237/93322420-966cc800-f813-11ea-8532-4664168e35ed.jpg)
![Screenshot_20200916_115137_com android settings](https://user-images.githubusercontent.com/668237/93322427-98cf2200-f813-11ea-9044-31579f70a9fd.jpg)
Game should look like this : 
![Screenshot_20200916_114734_com aniplex fategrandorder en](https://user-images.githubusercontent.com/668237/93322440-9a98e580-f813-11ea-9d09-3a5d80be28cc.jpg)
FGA settings : 
![Screenshot_20200916_114800_com mathewsachin fategrandautomata](https://user-images.githubusercontent.com/668237/93322521-b00e0f80-f813-11ea-8fc2-4a9e7163bd01.png)

**Comment by mg137b** [comment]
I have try 

> If it's like P20 Pro then no need to bother with Full-screen display settings, it's probably already good if it's not in there.
> Use default cutout on FGO and "Show cutout" in the custom options. Make sure you use "Ignore notch calculation in the Automata App".
> 
> Here are my own settings :
> 
> ![Screenshot_20200916_115031_com android settings](https://user-images.githubusercontent.com/668237/93322412-940a6e00-f813-11ea-9642-fc37383e46ea.jpg)
> ![Screenshot_20200916_115049_com android settings](https://user-images.githubusercontent.com/668237/93322420-966cc800-f813-11ea-8532-4664168e35ed.jpg)
> ![Screenshot_20200916_115137_com android settings](https://user-images.githubusercontent.com/668237/93322427-98cf2200-f813-11ea-9044-31579f70a9fd.jpg)
> Game should look like this :
> ![Screenshot_20200916_114734_com aniplex fategrandorder en](https://user-images.githubusercontent.com/668237/93322440-9a98e580-f813-11ea-9d09-3a5d80be28cc.jpg)
> FGA settings :
> ![Screenshot_20200916_114800_com mathewsachin fategrandautomata](https://user-images.githubusercontent.com/668237/93322521-b00e0f80-f813-11ea-8fc2-4a9e7163bd01.png)

I have try your setting but now it won't even automatically select support by its own. I suspect it is  because I can't toogle off or on in the full screen resn display for app.

**Comment by mg137b** [comment]
![Screenshot_20200916_171144_com aniplex fategrandorder en](https://user-images.githubusercontent.com/71218710/93324481-288ac580-f840-11ea-9520-cfc2984a856e.jpg)

I have manage to get rid off the black bars or around the game by show notch like the setting you did but now it won't even automatically select support as well @Wrathach

**Comment by Wrathach** [comment]
https://youtu.be/DqODrKpia3U
Here's a demo with debug to show it works. 

Are you sure "Ignore Notch calculation" is ON in FGAutomata ?
I have the same issues you describe if I turn it OFF.

**Comment by mg137b** [comment]
![Screenshot_20200916_172214_com mathewsachin fategrandautomata](https://user-images.githubusercontent.com/71218710/93325225-2e34db00-f841-11ea-9e90-3808cc3ef809.jpg)
Yes it is on. U know what is weird for me before I  choose show notch  option the support selection is possible and that is also when I turn off ignore notch calculation and debug highlight in FGA app.

**Comment by MathewSachin** [comment]
@Wrathach Thanks for the help!
FGO definitely looks right now (Ignore Notch should be ON like you said).
@mg137b Can you restart your phone once? It might just be the Huawei battery saver issue now.
https://github.com/MathewSachin/Fate-Grand-Automata/issues/354#issuecomment-687152298

**Comment by mg137b** [comment]
> @Wrathach Thanks for the help!
> FGO definitely looks right now (Ignore Notch should be ON like you said).
> @mg137b Can you restart your phone once? It might just be the Huawei battery saver issue now.
> [#354 (comment)](https://github.com/MathewSachin/Fate-Grand-Automata/issues/354#issuecomment-687152298)

I already reset setting but it still won't let me use FGA and the full screen display in more display setting still won't show list of apps to toggle off on I suspect is that one.

**Comment by MathewSachin** [comment]
Not reset, I meant restart (turn OFF and turn ON your phone). FGO looks fine now.
Turn ON Ignore notch calculation. Do the battery optimization steps in the issue I linked and just RESTART your phone.

**Comment by mg137b** [comment]
> Not reset, I meant restart (turn OFF and turn ON your phone). FGO looks fine now.
> Turn ON Ignore notch calculation. Do the battery optimization steps in the issue I linked and just RESTART your phone.

Oh if restart phone I have done it numerous time but let me check the battery part

**Comment by mg137b** [comment]
@MathewSachin  I'm sorry but I can't find the issue page about battery

**Comment by MathewSachin** [comment]
I linked that in the above comment

**Comment by Wrathach** [comment]
You can find those settings in Settings -> Battery -> Battery usage ->Select FGA, then App Launch settings. Set it to manual, allow it to run in the background. Do the same for FGO.
Also make sure you're not in Power Saving mode or Ultra Power Saving mode.

Screens : 
![image](https://user-images.githubusercontent.com/668237/93327416-94f2ce00-f81a-11ea-957d-8f64f4e97e0c.png)
![image](https://user-images.githubusercontent.com/668237/93327426-99b78200-f81a-11ea-931f-3949693430d9.png)

**Comment by mg137b** [comment]
@MathewSachin so I hv choose manual for the battery part like the link u sent me for fgo apps and FGA but it is still not working still doesn't choose support automatically

**Comment by MathewSachin** [comment]
Since things have changed this much, mind posting a new Debug mode video?

**Comment by mg137b** [comment]
https://youtu.be/I2MoHRi0oxk

Here is the new video

**Comment by MathewSachin** [comment]
I still see black strips above and below FGO? Are they always there or added by your screen recorder or something?
As long as they're there, FGA absolutely won't work.

BTW, you should use the 'Record Screen' option to record videos for reporting bugs and Debug Mode should be ON.
See @reconman's first comment on this issue if you don't recall how to.

**Comment by mg137b** [comment]
![Screenshot_20200916_181450_com aniplex fategrandorder en](https://user-images.githubusercontent.com/71218710/93330237-b10d6400-f848-11ea-891f-4b80c241abc7.jpg)

I just screenshot this I think it is just from my recording because from my phone there is no black screen anymore

**Comment by mg137b** [comment]
I on the debug mode and it still doesn't work. It is always been like that from the beginning.

**Comment by MathewSachin** [comment]
Debug mode ON WON'T solve your problems.
It is for me to see what is happening.

**Comment by mg137b** [comment]
> Debug mode ON WON'T solve your problems.
> It is for me to see what is happening.

OK I will on the debug mode and do another recording of fgo and I on the record screen on FGA as  well. I will post the link in a moment.

**Comment by mg137b** [comment]
https://youtu.be/kBf4OvJF5Fk

@MathewSachin

**Comment by MathewSachin** [comment]
You know you have to start the script after you're over FGO and not just on the app? Try that.

**Comment by MathewSachin** [comment]
Get me a new video where you start the script when you're over FGO.
The regions are wrong because you started in portrait mode 🤦

**Comment by mg137b** [comment]
> You know you have to start the script after you're over FGO and not just on the app? Try that.

I am sorry what do you mean by have to start the script after you're over FGO?

**Comment by MathewSachin** [comment]
You have to start the script after you've opened FGO and FGO is in the foreground.
Or atleast your phone should be in Landscape orientation and not portrait.
Makes sense?

**Comment by mg137b** [comment]
> You have to start the script after you've opened FGO and FGO is in the foreground.
> Or atleast your phone should be in Landscape orientation and not portrait.
> Makes sense?

Then I hv to use my phone recording for this I will make another video using my phone record..

**Comment by MathewSachin** [comment]
I just want to see Debug mode over FGO that's it. I've already seen FGA settings.
Don't use other recorders pls.

**Comment by mg137b** [comment]
> I just want to see Debug mode over FGO that's it. I've already seen FGA settings.
> Don't use other recorders pls.

The last video shows  the debug mode over FGO. If I don't use my phone recording it won't show " select auto skill config confirm" and choose the set up.

**Comment by MathewSachin** [comment]
Damn it. I said last video showed Debug mode regions wrong.
If you don't do what I ask, how can I help you?

**Comment by mg137b** [comment]
@MathewSachin 
https://youtu.be/Zc0r34ohdJs

Here you go and if there black box or bar I think it is from the phone because I already hide the notch on my phone settings.

**Comment by MathewSachin** [comment]
> if there black box or bar I think it is from the phone

Like I said earlier, those black borders prevent FGA from working. There's no way around that right now. FGA won't work unless you get rid of those black bars/borders.

**Comment by mg137b** [comment]
> > if there black box or bar I think it is from the phone
> 
> Like I said earlier, those black borders prevent FGA from working. There's no way around that right now. FGA won't work unless you get rid of those black bars/borders.

I guess nothing I can do  then :( I can't do nothing about this since it is from phone

@Wrathach do u also have black box or bar in ur phone?

**Comment by Wrathach** [comment]
no I don't. I used to, but I managed to remove them in the past and don't really remember how I did it. I'm currently searching for this and will let you know what I find

**Comment by Wrathach** [comment]
@mg137b do you have any way to share your screen (I.E. Airserver or whatever) ?
If so we can schedule a Discord call and we can try to work around your issue.

**Comment by mg137b** [comment]
> @mg137b do you have any way to share your screen (I.E. Airserver or whatever) ?
> If so we can schedule a Discord call and we can try to work around your issue.

Is there an app to do that? Or phone setting?

**Comment by Wrathach** [comment]
If you have Discord DM me @ LeDrain#1267. If not send me an email on wrathach@gmail.com. If only github DMs were a thing

**Comment by mg137b** [comment]
> If you have Discord DM me @ LeDrain#1267. If not send me an email on [wrathach@gmail.com](mailto:wrathach@gmail.com). If only github DMs were a thing

How do I add u in discord?

**Comment by Wrathach** [comment]
send a friend request so you can DM

**Comment by mg137b** [comment]
> send a friend request so you can DM

Can u add me? For some reason I cannot find ur Id 

Mine is mg137b#4733

**Comment by Wrathach** [comment]
@MathewSachin I have been able to reproduce a phone state where FGA behaves the same as on @mg137b 's phone. 
What I did to "break" my working configuration : change the notch settings of FGA. Whatever setting I pick, FGA will no longer work once I start it, debug will show all the red boxes as per the previously shared video.

Changing the setting again doesn't affect FGA, I suspect it's too low level to be affected by the settings change without a restart.

What I did to fix it : 

Option 1 : 
Display -> More Display Settings -> Notch -> 
Fate/GO : Show notch/cutout
Fate/Grand Automata : Hide notch/cutout
RESTART YOUR DEVICE!

Start FGA (with ignore notch option activated) and toggle the service on.
Start FGO, FGA works

Option 2 : 
You can also run FGA with FGO this way : 
Display -> More Display Settings -> Notch -> 
Fate/GO : Hide notch/cutout
Fate/Grand Automata : Hide notch/cutout
RESTART YOUR DEVICE!

Start FGA (with ignore notch option deactivated) and toggle the service on.
Start FGO, FGA works


It is still not working for mg137b but this troubleshooting can still be helpful.

**Comment by MathewSachin** [comment]
mg137b's case is different in that there's those black bars above and below which I don't know why.
Another user had told me it was because of Android Gestures and I had told them that. But, might be something else.
I really can't do anything with those black bars in the way.

I tried to write up a way to automatically detect such black bars, but the code is so messy, I don't feel like taking it forward either
#360

**Comment by mg137b** [comment]
> mg137b's case is different in that there's those black bars above and below which I don't know why.
> Another user had told me it was because of Android Gestures and I had told them that. But, might be something else.
> I really can't do anything with those black bars in the way.
> 
> I tried to write up a way to automatically detect such black bars, but the code is so messy, I don't feel like taking it forward either
> #360

It could be I update my phone software so that could be a reason why FGA doesn't work properly on my phone. Or android 10 doesn't work with a lot of 3rd party apps.

**Comment by MathewSachin** [comment]
Most of the FGA users have Android 10 including me and it works just fine. It something really specific to your phone.

**Comment by mg137b** [comment]
Hello i want to ask if FGA app is compatible with these devices? 

Device model:Samsung Galaxy Tab s4 10.5
Screen size: 1600x2560 pixels 
Android version: Android 8.1 (Oreo) upgradable to Android 10
RaM: 4GB or 6GB RAM. 
link:https://m.gsmarena.com/samsung_galaxy_tab_s4_10_5-9262.php

Device Model: Samsing Galaxy Tab s6 Lite 
Screen Size:  1200 x 2000
Android Version: 10
RAM: 4GB
link:https://www.gsmarena.com/samsung_galaxy_tab_s6_lite-10158.php

**Comment by reconman** [comment]
@mg137b We can't guarantee it but I think it should work as long as you follow the troubleshooting guide.

**Comment by mg137b** [comment]
Hello I try using FGA and FGO on samsung tab s6 lite. It is able to pick support and select the servant skills during battle but the strange thing it doesn't increase the servant np. I am using summer jeanne and castoria team set. I will provide video but because this is my phone record it so i will use youtube again. I try tl record on the tablet but cant find the file even tho i already on Record Screen setting on FGA. 

I have on Ignore Notch Calculation and Debug Mode too. 

Device Model: Samsing Galaxy Tab s6 Lite
Screen Size: 1200 x 2000
Android Version: 10
RAM: 4GB

YouTube: https://youtu.be/PhV-azk2xyE

**Comment by MathewSachin** [comment]
Skill confirmation is ON in FGO, but OFF in FGA

**Comment by mg137b** [comment]
> Skill confirmation is ON in FGO, but OFF in FGA

Oh i didnt realize it must been reset because i move the game to tablet device. It works now thank you!
