### ISSUE TITLE
FGA doesn't do anything on Nokia 8.1

### ISSUE THREAD

**Issue by myllack** [Fate-Grand-Automata/FGA#387]
Nothing happens in support selection or in battle after choosing AutoSkill Config. I have tried tweaking screen size, notch settings and such but no luck. Script mode is set to battle, Game Server to NA (which is where I play). Services and permissions are OK. Didn't manage to find any menu where to configure app full screen options on this phone, even with some research and trying external apps to modify the notch area too.

Is there still something I could try? I can provide screenshots or more information.

Video with debug on:
https://streamable.com/kpktd3

Device model: Nokia 8.1
2246x1080
Android 10
4 GB RAM

**Comment by MathewSachin** [comment]
FGO looks fine on your phone. Since your phone has a notch, that's how it should look.
You shouldn't have to turn ON Ignore notch calculation either.
But, the regions detected by FGA are definitely wrong and I'm not sure why.

Can you post a screenshot of FGA itself? I want to see if it's due to navigation buttons or something.

**Comment by myllack** [comment]
Here's screenshots of FGA in landscape and portrait modes.

![Screenshot_20200913-210711](https://user-images.githubusercontent.com/67283427/93025309-9dbe8680-f605-11ea-9445-4ad7baf23321.png)
![Screenshot_20200913-210720](https://user-images.githubusercontent.com/67283427/93025310-a020e080-f605-11ea-99d1-5f9b85e4daf0.png)

**Comment by reconman** [comment]
Very interesting, your screenshots are 2246x1080, not 2280x1080. That seems to be the source of the problem.

**Comment by myllack** [comment]
Ah, my bad, I googled the specs and apparently the site I ended up copying the resolution from seemed to have it wrong. Several other sources claim that Nokia 8.1 resolution is indeed 2246x1080. I'll update the main post too.

**Comment by MathewSachin** [comment]
Seems like there is a `Full Bezel` option in Nokia 8.1.
Did you turn it ON by any chance?

**Comment by myllack** [comment]
> 
> 
> Seems like there is a `Full Bezel` option in Nokia 8.1.
> Did you turn it ON by any chance?

I tried it yes, combinations of Full Bezel option and Notch option in FGA. None worked sadly, and the Full Bezel didn't even seem to have any effect on FGO.

**Comment by reconman** [comment]
Doesn't look like we can help you any further then, maybe the future update of FGA with automatic black area detection will work.

**Comment by myllack** [comment]
> 
> 
> Doesn't look like we can help you any further then, maybe the future update of FGA with automatic black area detection will work.

Alright, thanks anyways. I'll give it a try later on, when this feature is implemented. Any idea if that'll happen soon?

**Comment by tosamyng** [comment]
I think I have a similar problem. I use nox emulator and couldn't find any force full screen, I tried to manually change the resolution to 2280x1080, but it didnt work either. Any advice?

**Comment by reconman** [comment]
@tosamyng Yours is a completely different issue. See https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Running-on-Emulators

**Comment by tosamyng** [comment]
> @tosamyng Yours is a completely different issue. See https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Running-on-Emulators

Omg now it works. I didnt notice I needed to root because it said no root needed on the page I saw from google.

**Comment by reihunter360** [comment]
Not sure if i should make a new thread, but i've got a similar problem on my Nokia 5. (I did everything, set permissions and start the service)
If the game is on Battle script, it does nothing at all.
I've tested on NA.
The lottery script and friend summon script works. The Friend List Image Maker doesnt seem to work either.

I've turned on debugging options, when i run the battlescript, it just highlights areas, then poofs, then blinks again, then poofs, on repeat. 

Currently trying to test on JP if it works there... possibly not.

Device Model : Nokia 5
720x1280 (Normally it is like this, but i've set it to 670x1190 due my screen being cracked.)
^ I did try with default size, but it battlescript+supportimagemaker doesnt work.
Android 8.1
2GB RAM

**Comment by MathewSachin** [comment]
> but i've set it to 670x1190 due my screen being cracked.

Tried setting back to 720x1280?

**Comment by reihunter360** [comment]
> 
> 
> > but i've set it to 670x1190 due my screen being cracked.
> 
> Tried setting back to 720x1280?

i did say i tried it with default size. Same deal, doesnt start or work.
The Supportimagemaker just throws me an error "You on your support screen or friend list?" despite i clearly am.

**Comment by MathewSachin** [comment]
See how the original issue was reported with a debug mode video.
Post similar video of it not working, so I can see what is happening.
Debug mode is not for fun, it's for me to see what is happening 😆

**Comment by reihunter360** [comment]
https://youtu.be/jNkeCQactM0 (For FateGONA)
(Hopefully i uploads overnight. Sheesh; just when i wanna upload stuff, it slows down to a crawl.)

If it doesnt work out, i'll use it as a Lottery Roller. Although i dont think it can like clear boxes without additional help. (Like me pressing the Next Lottery Box)

Guess i'm back to Repetitouch for Semi-Auto Macro @_@... for now.

**Comment by MathewSachin** [comment]
> i did say i tried it with default size. Same deal, doesnt start or work.

Show me the default resolution. These kinds of resolutions are not supported by us.
See this part of Troubleshooting guide: https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Game-Area-detection

**Comment by reihunter360** [comment]
I think it works now prevents me from clicking stuff in battle. 
Guess its finetuning for me huh?

But damnit, i can't see their NP and HP at this rate ;-; (The bottom of my screen is cracked, that's why i had it at a custom resolution)

**Comment by MathewSachin** [comment]
> > Tried setting back to 720x1280?

> i did say i tried it with default size. Same deal, doesnt start or work.

If only you'd have listened to me earlier.

> It kinda gets bugged and prevents me from clicking stuff in battle. So i shouldn't interrupt it too much.

You shouldn't anyway. What's the point of automation if you click in middle 🤔

**Comment by reihunter360** [comment]
Hmm, must've been the update to FGA that i grabbed from playstore.
Oh wells its working now @_@
The Targetted Skills are kinda slow though.

**Comment by MathewSachin** [comment]
@reihunter360 You know this is why I'm getting mad at people.
This wasn't even an issue with the app. Troubleshooting guide clearly stated stuff.
And, I'm flooded with things like this from people everywhere.
People don't listen to what I tell them to even.

You added clutter to a real issue for no reason.

**Comment by reihunter360** [comment]
I really did test it with default resolution and it didnt pick up anything from node selection/support screen before the update.
