### ISSUE TITLE
Overlay randomly turns off on LDPlayer

### ISSUE THREAD

**Issue by Sunspawn** [Fate-Grand-Automata/FGA#404]
Sometimes, when starting a quest, the overlay (the play/stop button) just disappears and the script does not happen. Had that happen twice today after it was on overnight - after setting it to a different refill number and starting it from the start, at some point during the day (I was away at work) it turned off. The second time was similar, sometime after I started, it just went away.

**Device Info (please fill atleast 'Device model'):**
LDplayer emulator with the following settings:
 - Device model: samsung SM-G975N
 - Screen size: 960x540
 - Android Version: Android 7.1
 - RAM: 4gb

**Comment by reconman** [comment]
I think it's energy saving mode of Samsung, check out https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting#worked-before-doesnt-work-now

**Comment by Sunspawn** [comment]
I don't know if the emulator goes that far in replicating phone behavior. Is that a thing with emulators?

**Comment by reconman** [comment]
Oooh, I missed the LDPlayer info. Could be. It could also be that the app crashes for some reason.

**Comment by Sunspawn** [comment]
I'll do some more testing to see if it is a recurring issue and reply later.

**Comment by MathewSachin** [comment]
Hey, did you have to take any extra steps to get it running on LDPlayer? I've not confirmed from anyone if it even works on LDPlayer yet.
Like on Nox, you need Root and on BlueStacks you have to turn ON Compatibility mode. Does LDPlayer work as it is with the app?

**Comment by Sunspawn** [comment]
I just installed it and it worked. Had to fumble in the settings because I forgot android has a back button, but other than that works fine out of the box, so to say.

**Comment by vybze** [comment]
The same thing happened to me too

**Comment by ScathachSkadi** [comment]
I just had the same issue with the 64bit version of LDPlayer. But, the 32bit version worked fine.
