### ISSUE TITLE
KR also has gift box x1 issue

### ISSUE THREAD

**Issue by sleeping-player** [Fate-Grand-Automata/FGA#444]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
I finally run a small gift box test on my secondary phone. And I was surprised this is failed.
This is similar issue on yesterday, now KR also has this problem.
Besides, somebody is even telling me that the JP gift box problem was not resolved in the last ci build.
Back in my case, interestingly, this phenomenon doesn't happen on my primary device.  From there, everything from 1 to 4 works.
<s>I think this is screen resolution problem, so I'll get another my gifts screenshot.</s>oh these screenshots are HiRes, so screenshot will not be problem...
And this <s>also</s> can be problem where red box must be in...

**Screenshots**
Video uploaded

**Video**
https://youtu.be/EcchzfkcPA4 this is for Redmi 7.
I'll upload working galaxy s10+ video shortly.

**Device Info (please fill at-least 'Device model'):**
 - Device model: Xiaomi Redmi 7
 - Screen size: 1520x720
 - Android Version: Android 9
 - RAM: 3GB

**Comment by MathewSachin** [comment]
Have you changed fine-tune settings for scrolling?
Looks like its scrolling too fast on your phone.

**Comment by sleeping-player** [comment]
All default value.
But I'll check it again.

**Comment by sleeping-player** [comment]
Yeah not working even though all are default values

**Comment by MathewSachin** [comment]
So, only lower resolution phones seem to be having this problem. And, I think it's because they scroll more for the same amount of swiping.

Can you see if increasing `Swipe duration (ms)` and `Wait after swiping (ms)` in fine-tune settings helps?

**Comment by sleeping-player** [comment]
Thats are 스와이프 후 딜레이, 스와이프 지속 시간 in KR. (for another readers)
All doesn't work.

And I forgot to tell it gathers silvers well.

**Comment by sleeping-player** [comment]
Second link.
https://youtu.be/P_HD6u2MOqE
This again Redmi 7. working 2 to 4 and silvers.

**Comment by MathewSachin** [comment]
I feel detection for 2 isn't working perfectly either. A new 2 scrolled into view at 0:14 but was only clicked after scrolling further at 0:18.

**Comment by sleeping-player** [comment]
https://youtu.be/uoHF-5JCBbs
This is from galaxy s10 plus. Just working.

**Comment by sleeping-player** [comment]
> I feel detection for 2 isn't working perfectly either. A new 2 scrolled into view at 0:14 but was only clicked after scrolling further at 0:18.

It seems like this is a more complicated problem than I thought.

**Comment by MathewSachin** [comment]
Well, yeah, it is complicated. We're using images to match numbers.
