### ISSUE TITLE
Scripts not functioning in battle (Nox)

### ISSUE THREAD

**Issue by qOnyx** [Fate-Grand-Automata/FGA#474]
**Describe the bug**
Scripts simply dont read or press any buttons once in a battle, battle script works up until that point and other modes work fine, yet as soon as it actually enters a battle the autoskill does nothing

**Video**
Video with debug
https://streamable.com/dsb6z4

**Device Info (please fill at-least 'Device model'):**
I'm not sure what I should put here since its Nox, the instance is Android 7 and the resolution in Nox's settings is 1920x1080 but was not working at 1600x900 as well

I've read through the troubleshooting and the emulator page, and the only similar issues I've seen have been on real phones and not Nox. The autoskill was also working fine a few days ago before not working suddenly last night

**Comment by MathewSachin** [comment]
You didn't mention about Root, so maybe that got turned OFF.

**Comment by qOnyx** [comment]
I thought I did mention that, I guess I forgot. I double checked both root settings in the app and in nox's settings and even turned them off and back on again and it didn't fix the issue

**Comment by MathewSachin** [comment]
Closing since #743 is a bigger problem now.
