### ISSUE TITLE
Unexpected error after clicking play on MEmu

### ISSUE THREAD

**Issue by namv22** [Fate-Grand-Automata/FGA#547]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
I set some auto skill with name base on classes of servants I want, selection mode at First
When I got into the game and hit the play button, an error popups.

I recently update to using Memu 64bit, when I was using the old Memu 32bit, it was running normally

> Unexpected Error: The producer output buffer format 0x2 doesn't match the ImageReader's configured buffer format 0x1.
> 
> 0 refills used out of 100
> Time: 00:00
> 
> java.lang.Exception: Unexpected Error: The producer output buffer format 0x2 doesn't match the ImageReader's configured buffer format 0x1.
> 
> 0 refills used out of 100
> Time: 00:00
> 	at c.a.a.c.b.a.w(AutoBattle.kt:35)
> 	at c.a.b.b.c(EntryPoint.kt:2)
> 	at l.n.a.run(Thread.kt:1)
> Caused by: java.lang.UnsupportedOperationException: The producer output buffer format 0x2 doesn't match the ImageReader's configured buffer format 0x1.
> 	at android.media.ImageReader.nativeImageSetup(Native Method)
> 	at android.media.ImageReader.acquireNextSurfaceImage(ImageReader.java:340)
> 	at android.media.ImageReader.acquireNextImage(ImageReader.java:394)
> 	at android.media.ImageReader.acquireLatestImage(ImageReader.java:287)
> 	at c.a.a.j.e.q(MediaProjectionScreenshotService.kt:1)
> 	at c.a.b.u.a(ScreenshotManager.kt:1)
> 	at c.a.b.u.c(ScreenshotManager.kt:1)
> 	at c.a.a.c.b.a.y(AutoBattle.kt:28)
> 	at c.a.a.c.b.a.w(AutoBattle.kt:34)
> 	... 2 more

**Screenshots**
![20201104_214656](https://user-images.githubusercontent.com/13979900/98125716-59ee4c00-1ee7-11eb-9a3e-a12d409a9a13.jpg)

**Device Info (please fill at-least 'Device model'):**
 - Device model: it is set as Samsung Galaxy S7 Edge
 - Screen size: 1280x720 240dpi
 - Android Version: Android 7.1 64bit
 - RAM: 3GB
 - Render mode: DirectX

**Comment by geekapp2019** [comment]
if (isDirectX){//逍遥模拟器必须用这个
            //mImageReader = ImageReader.newInstance(mScreenWidth, mScreenHeight, 0x2, 2);
            mImageReader = ImageReader.newInstance(mScreenWidth, mScreenHeight, PixelFormat.RGBX_8888, 2);
        }else {
            mImageReader = ImageReader.newInstance(mScreenWidth, mScreenHeight, PixelFormat.RGBA_8888, 2);
            //mImageReader = ImageReader.newInstance(mScreenWidth, mScreenHeight, PixelFormat.RGB_565, 2);
        }

**Comment by MathewSachin** [comment]
We're already having a hard time with Bluestacks and Nox. Can't support other emulators.
