### ISSUE TITLE
Problem with recognizing actions with LG K22+ phone screen

### ISSUE THREAD

**Issue by ECLL45** [Fate-Grand-Automata/FGA#548]
Before opening an issue:
- [ O ] I tested the latest release
- [ O ] I looked at other issues (even the closed ones)
- [ O ] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [ O ] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
FGA is unable to work properly during the support selection screen, the program attempts to slide the screen but is unable to do it, even with applying the ignore notch the program keep getting in a loop when scanning the screen for a match, this issue is in both NA and JP servers.

**Screenshots**
It is recommended that you at-least add one screenshot of FGO running on your device.

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON
Recording functionality is available within the app in `More options`.

Support Select Issue without "ignore notch": https://streamable.com/kyfg9z
Support Select Issue with "ignore notch": https://streamable.com/vpy704

**Device Info (please fill at-least 'Device model'):**
 - Device model: LG K22+
 - Screen size: 1080 x 2460
 - Android Version: Android 10
 - RAM: 3GB

**Comment by MathewSachin** [comment]
Sorry, this issue went unnoticed. IIRC there was a huge influx of issues at that time.
I'm pretty sure I've covered all cases (that I know of) in the troubleshooting guide.
Since, the videos on streamable are no longer available, I'm closing this issue.
