### ISSUE TITLE
CN Gift Box script

### ISSUE THREAD

**Issue by ddcxxx** [Fate-Grand-Automata/FGA#580]
The Gift Box script did not work on the CN server,can you add it? Thanks a lot.
The ember for x1, x2, x3, x4 are included in the picture
![Screenshot_2020-12-02-15-29-17-337_com bilibili fatego](https://user-images.githubusercontent.com/41536081/100842229-7c0dc680-34b3-11eb-806a-b0e41154b6a9.jpg)
![Screenshot_2020-12-02-15-30-35-963_com bilibili fatego](https://user-images.githubusercontent.com/41536081/100842239-7f08b700-34b3-11eb-8aa3-6e35f9360183.jpg)

**Comment by reconman** [comment]
@ddcxxx @Lineeee217 Can you check whether [this apk](https://github.com/Fate-Grand-Automata/FGA/suites/1746406617/artifacts/33182009) fixes the gift box on CN?

**Comment by Lineeee217** [comment]
@reconman CN server is under maintenance now，I'll try after maintenance.

**Comment by Lineeee217** [comment]
@reconman It still doesn't work.![Screenshot_20201231-195829_-.jpg](https://user-images.githubusercontent.com/42966576/103410527-9ddb9580-4ba6-11eb-8372-0ee44bde7dcc.jpg)
But if I change FGA server to JP, it will work on CN server.

**Comment by reconman** [comment]
Try again with this one: https://github.com/Fate-Grand-Automata/FGA/suites/1748381881/artifacts/33223599

**Comment by Lineeee217** [comment]
It can work now.
