### ISSUE TITLE
Question about skill use and facecards

### ISSUE THREAD

**Issue by runelt99** [Fate-Grand-Automata/FGA#601]
Before opening an issue:
- [x] My question isn't answered in any other issues (even the closed ones)
searched 'face card' 'skill' didn't find any
- [x] I'm not reporting a bug/error

> If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

1. Is there a way to make F/GA automatically use skills, like it does NPs? I have a strategy to facecard some events but it would suck if it never used skills like def up, attack up or np battery.

2. Face cards. I know that i can make F/GA prioritize very effective, not effective and neutral and then types of face cards, but i would prefer to choose a single servant to prioritize. I currently use double skaldi dantes setup and i would like it much more if  i could use his attacks over the skaldis, especially if after np i still have 2 dantes.

3. Edit: also is there a way to tell the game to use mystic code when any servant has 100 np charge, like ruler quetzacoatl 3rd skill gives buster that's perfect to use before np.

**Comment by Rajvir8** [comment]
Just turn on Auto Skill for 1, then it will use the skills you have previously used when there timer is done assuming that you've finished using all of your typed in skills.

2 isn't possible right now as you'd need to screenshot every single one of your servants cards

3 isn't either because FGA doesn't even know when you get to 100%, you just tell it when to use NP's or if you want to try to use them every turn.

**Comment by reconman** [comment]
Correction on 2: Under `Card Priority` in the `Battle Config` you can set `Brave Chains` to `With NP`. Everyone requested that feature for Dantes teams.

**Comment by reconman** [comment]
The rest of Rajvir8's answers are correct.

**Comment by runelt99** [comment]
questions 2 and 3 are answered.

Question 1 does require more elaboration. Do you mean that 'maker' that specifically follows wave start? I sometimes come into problem when my face carding is able to kill enemies too fast and so skill has not gone off cooldown so FGA sometimes get stuck on a screen that shows from clicking again on used skill. As otherwise skills are not used a second time.

**Comment by reconman** [comment]
@runelt99 If you turn on `Skill Spam` in the Battle Config, it will reuse any skills you've used after their cooldown.

See #510 for a detailed feature discussion.

**Comment by runelt99** [comment]
@reconman closest thing i see is 'skill confirmation'... The #510 build mentioned something about link to build but i have no idea what to do with apk.

Didnt notice the email about being written back.

**Comment by reconman** [comment]
![Screenshot_20201227-203224](https://user-images.githubusercontent.com/12360257/103178388-aa987a80-4882-11eb-8482-25a979d6298b.jpg)

**Comment by runelt99** [comment]
Aaah, i only now realised that FGA is not in google play store. I am playing on an outdated version 
![Screenshot_20201227_213841_com mathewsachin fategrandautomata](https://user-images.githubusercontent.com/48949150/103178597-d91b5300-488c-11eb-832b-403e6b4dcdc4.jpg)

Is there some way to update it without losing my data?

**Comment by reconman** [comment]
If you install it via the downloaded APK at https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary, it will install another version with a Quick Card icon. The playstore version with the Buster Card icon will still be there.

**Comment by runelt99** [comment]
On second thought, I installed the quick version but it has no data. I tried to click import but seems like it created "phone/Grand Automata/support/support", trying to manually import settings just gives me 'failed to import 1 item'. I can't even find where buster saved battle configs.

**Comment by reconman** [comment]
To use the same data, you will have to select the phone/Grand Automata folder, not the support one. You can change that in More Options -> `Change folder used for Support images....`

Battle Configs can be exported over `...` -> `Export All` in the top right corner of the battle config list.
