### ISSUE TITLE
FGA has stop working on Nox (Root)

### ISSUE THREAD

**Issue by GilangAlRusliadi** [Fate-Grand-Automata/FGA#603]
Hey, I am using Nox (Android 7 Root) and I've read Troubleshooting about Emulator in there
https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting

My problem is, even though I did what Mathew wrote there, my FGA still stopped working (Force Close) whenever I press toggle service button.

So... you guys have ny solution?
![Screenshot (26)](https://user-images.githubusercontent.com/39462661/102016101-b3bd1e00-3d91-11eb-8188-7f3ffa5842ef.png)

**Comment by WVVWVWVVW** [comment]
I have the same issue. Tried following the troubleshooting guide as well.
