### ISSUE TITLE
Support bundling custom CE/servant image in the AutoSkill export

### ISSUE THREAD

**Issue by minhducsun2002** [Fate-Grand-Automata/FGA#604]
Before opening an issue:
- [x] No one has asked for this feature before in other issues (even the closed ones)
  People only asked for exporting functions. Proof : 
![image](https://user-images.githubusercontent.com/32769878/102030871-e0e7eb80-3de6-11eb-82de-963ed7f1e27c.png)

In case I export an AutoSkill configuration with a custom support/CE image, the configuration still contains the value for that CE, but the image isn't there. (This seems to be a bug? Feel free to make a new issue to track.)

It `:wouldBeniCE:` to have them exported too. Probably as a zip or something easily editable, although I am completely fine if you make a new binary format out of it.

**Comment by alextruong** [comment]
For what it's worth, in the (admittedly narrow) case where I had (or rather, currently have) both the Play Store version and the canary build installed on the same device (BlueStacks in my case), if the screenshot/data folder where the support stuff lives is set to be the same for both apps, I have no issues with the canary build taking config exports from the play store version that use non-default CEs and such. All the options show up in the correct places, and seem to detect correctly when running.

Obviously, this is far more useful in general, especially if you want to switch devices entirely, but for people that had this same question and are in the same situation I'm in, hopefully that helps a little.
