### ISSUE TITLE
Not Picking Support

### ISSUE THREAD

**Issue by generamirez** [Fate-Grand-Automata/FGA#607]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

**Describe the bug**
script runs fine up until it gets to the select support screen.
I've already tried using the notch calculation in the app and my game has been running full screen since it was available

Attached are the screenshots of my config

**Screenshots*
![131307118_208677317413160_2648224818640943750_n](https://user-images.githubusercontent.com/37094854/102108850-62369100-3e6e-11eb-9869-1d589cb95bc8.jpg)
![131388011_441055223744037_5143381756187133087_n](https://user-images.githubusercontent.com/37094854/102108855-64005480-3e6e-11eb-9ea6-48e6f2c42cf3.jpg)
![131395588_756018778338869_7990091541787807574_n (1)](https://user-images.githubusercontent.com/37094854/102108858-6498eb00-3e6e-11eb-9bd0-606b8e7a9060.jpg)
![131395588_756018778338869_7990091541787807574_n](https://user-images.githubusercontent.com/37094854/102108861-65318180-3e6e-11eb-941b-02528d7409f6.jpg)
![131406487_144177933854001_5880648247918232781_n](https://user-images.githubusercontent.com/37094854/102108865-65318180-3e6e-11eb-9345-21f1e05ecfbd.jpg)
![131419100_134296601653925_1528215177743226700_n](https://user-images.githubusercontent.com/37094854/102108867-65ca1800-3e6e-11eb-8f5f-e54d60b02d4a.jpg)
![131471557_439151543754475_1596617644886385774_n](https://user-images.githubusercontent.com/37094854/102108870-6662ae80-3e6e-11eb-96cb-a44175438d10.jpg)

**Video**
Couldnt find where the app's recordings were but here's a recording of what the support list looks like after finishing a node
https://streamable.com/9emk3n

**Device Info (please fill at-least 'Device model'):**
Device: Samsung S20+
Resolution: 1440 x 3200 pixels
OS: Android 10, OneUI 2.5
RAM: 8GB

Hoping anyone can help

**Comment by MathewSachin** [comment]
You don't have to turn ON that Ignore notch option since FGO isn't not extending into the Notch area.
Try turning it off.

**Comment by matter18** [comment]
I'm having the same problem,and my notch calculation are off

**Comment by matter18** [comment]
> You don't have to turn ON that Ignore notch option since FGO isn't not extending into the Notch area.
> Try turning it off.

I am having the same problem and my notch calculation are off

**Comment by mg137b** [comment]
> You don't have to turn ON that Ignore notch option since FGO isn't not extending into the Notch area.
> Try turning it off.

i try this and it still wont choose support. Before my debug mode and ignore notch calculations are on and it works fine i can farm last 2 days continously. Today it works fine as well but suddenly at night i cannot use it. From the menu free quest it can choose the free quest but it stops there and wont choose support list. 

Device Info (please fill at-least 'Device model'):
Device: Galazy Tab s6 Lite 
Resolution: 2000 x 1200 
(OS: Android 10, OneUI 2.1
RAM: 4 GB (too small?)

Hoping anyone can help

**Comment by Nyan61192** [comment]
>i try this and it still wont choose support. Before my debug mode and ignore notch calculations are on and it works fine i can farm last 2 days continously. Today it works fine as well but suddenly at night i cannot use it. From the menu free quest it can choose the free quest but it stops there and wont choose support list.

I think I have an idea

I initially had the same issue on a Samsung S10+. I was also using  Ignore notch option. I was able to get it to work by flipping my phone around. The top and bottom part of the S10+ are not even so when the Top Part (The part with the Camera see image with circle https://imgur.com/a/dbPkieu) is on the left side (Close to where the enemy class is) it wont work and gets stuck in the Support screen. However when the Top part is on the right side of the screen close to where the command cards and atk button are it works properly.
