### ISSUE TITLE
Crash when setting Refill Repetitions to blank/empty.

### ISSUE THREAD

**Issue by DeltaCreeper** [Fate-Grand-Automata/FGA#618]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
1) Go to the Refill menu.
2) Select Enable Refill (if not enabled).
3) Select Repetitions.
4) Remove everything, leaving the input field blank/empty and then press Ok.

The application will crash once.
After a Force Stop, the application is working fine, but if the same steps (1-4) are repeated, the app will crash and not recover, even after a Force Stop.
I had to reinstall it in order to use it again.
I haven't tested this issue on other input fields, but it might give the same result.

**Device Info (please fill at-least 'Device model'):**
 - Device model: Pixel 2 (Don't think this matters)

**Comment by the3dsandwich** [comment]
I'm on Pixel 2 XL and don't have a problem with this. Have you tested the latest release (that are updated in these couple days)?

**Comment by MathewSachin** [comment]
This was fixed very early, even in the latest PlayStore version. This is why the issue template asks to test on the latest release 🤦 .
