### ISSUE TITLE
Crash on Bluestacks 64-bit

### ISSUE THREAD

**Issue by thai-ng** [Fate-Grand-Automata/FGA#623]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

**Describe the bug**
FGA crashes on Bluestacks 64-bit

**Screenshots**
![image](https://user-images.githubusercontent.com/11691629/102733494-50337300-42f2-11eb-9b08-c1e925058e03.png)

The issue here seems to bit libhoudini (ARM to x86/64 translation) isn't working well with the app.

Proposed solution is to add x86 and x86_64 to the ndk > abiFilters section in gradle. I have tested and confirmed it's working.

**Device Info (please fill at-least 'Device model'):**
 - Device model: Bluestacks 64-bit

**Comment by thai-ng** [comment]
Added a simple PR to fix. Tested working on my Bluestacks

**Comment by GeneralK** [comment]
I dont want to open a new issue post, because I dont think it's a problem that affects everyone. Probably just me.
So I'm going to post it here instead. I apologize for hijacking your post @thai-ng. I will post this comment as a separate issue if you find this comment troublesome.
I'm using Bluestacks 32-bit, build: v4.250.0.1070
When I was using the Canary build, and granted the .apk/app permission to overlay, it simply freezes when starting service.
It does not show a button for me.
Same problem occurs with older builds, as far back as April 2020. I dont know if it's a compatibility issue or not. 
Lastly, I want to ask where is the Support Image Maker script / section in the latest Canary build?

**Comment by reconman** [comment]
Image maker was moved to the very first option in the battle config list when you press play.

**Comment by MathewSachin** [comment]
> I had the same thing happen to me! I found a way to work around the issue though. In Settings, go to the Engine tab and set the Graphics engine to Compatibility. Once I did that, everything started working.

This is written in the Troubleshooting Guide, which every Issue template asks you to check first, under the Emulator section.

**Comment by GeneralK** [comment]
It's hard to spot that when I was tunneling visioning, trying to debloat bluestacks, while simultaneously trying to get the app working with a 24 hour limit left on the lottery. 

Also, this was under the windows section. Adding a copy and paste text into the blue stacks will help people like me in the future. 
![image](https://user-images.githubusercontent.com/7538710/103154576-349ef100-4766-11eb-8089-e2bca59f74db.png)

The app works great btw. Really sophisticated, elegant and easy to use.

**Comment by Ansem93** [comment]
Since bluestack released a new version I tried it, but still FGA doesn't work and the emulator will crash as soon as I start the service :( 
My versione is 5.3.10.1001 N32

**Comment by reconman** [comment]
@Ansem93 Your issue sounds like you didn't set the display to compatibility mode.

**Comment by Ansem93** [comment]
It now "works".
FGA Build 1589 
Bluestack 5.4.100.12026 N32
I Enabled "use Root for screenshots" in the advanced options.

The issue is that if I click on the play button nothing happen :(

**Comment by reconman** [comment]
I may have been wrong about root working, have to check later.

**Comment by Ansem93** [comment]
Double checked now:
Root disabled -> the service crash istantly but FGA isn't blocked anymore compared to before
Root enabled -> The service is correctly running, but the play button is not working. Not sure if I should open a new ticket for that :(

**Comment by reconman** [comment]
For now just switch to 32 bit.

**Comment by Ansem93** [comment]
My bad, I didn't see the update in the FAQ :( I tried everything:
-> I left the engine in performance mode and it works
-> After editing the bluestack file the play button now respond when clicked!
-> Root still need to be enabled

To me this case is closed :D
