### ISSUE TITLE
Failing to Determine Arts Cards

### ISSUE THREAD

**Issue by the3dsandwich** [Fate-Grand-Automata/FGA#627]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
When in battle phase, FGA failed to determine the Arts Cards. Buster and Quick are both correctly detected, just not for Arts. The similarity % is the default 80%. Could it be because the Arts image is significantly smaller than Buster and Quick?

**Screenshots**

<img width="1920" alt="Screenshot 2020-12-21 210318" src="https://user-images.githubusercontent.com/32169552/102779914-fc975700-43cf-11eb-9770-1ee8c90f76b1.png">

**Video**
[video link](https://youtu.be/QRoywUlSAmo)

**Device Info (please fill at-least 'Device model'):**
 - Device model: [Pixel 2 XL]
 - Screen size: [1440 x 2880]
 - Android Version: [Android 11]
 - RAM: [4GB]

**Comment by reconman** [comment]
Which FGO server is that?

**Comment by the3dsandwich** [comment]
TW

**Comment by reconman** [comment]
Please provide a direct screenshot of the face cards without the message. I need it to check the image matching.

**Comment by the3dsandwich** [comment]
<img width="1920" alt="Screenshot 2020-12-22 121329" src="https://user-images.githubusercontent.com/32169552/102848174-20e64880-444f-11eb-8762-aef5a4c1a1bb.png">

Here, sorry for being late. I screenshotted the part without the message from the video above, is this the one you want?

**Comment by reconman** [comment]
I don't want a screenshot taken from your video player, but one on the device.

But this screenshot from your video seems very weird. I'll have to take a closer look at the rectangle positions on my device later today.

**Comment by the3dsandwich** [comment]
I can try screenshotting directly, but given how fast everything runs it is difficult to time the screenshot. I'll do my best.

**Comment by the3dsandwich** [comment]
![Screenshot_20201222-171049](https://user-images.githubusercontent.com/32169552/102871198-18a30300-4479-11eb-9462-bbde35c7bb64.png)

@reconman Is this screenshot enough? Timing the screenshot is really hard...

**Comment by reconman** [comment]
Yes, I think it's something I can work with.

**Comment by reconman** [comment]
Okay, I found out that the A in Arts is a bit bigger in the TW version. Now I need one more screenshot from you without the red rectangles. We need a clean image of the Arts text.

So just start a quest manually, click on Attack and then take a screenshot if you see an Arts card.

**Comment by the3dsandwich** [comment]
![Screenshot_20201222-170457](https://user-images.githubusercontent.com/32169552/102953364-11790500-450c-11eb-85da-64add5f3662b.png)

Huh. Never thought TW will alter the Arts image. Thanks!

**Comment by reconman** [comment]
Can you please test the latest release?

**Comment by the3dsandwich** [comment]
Hi @reconman thanks for fixing the issue! Just tested the latest commit (from master) and it's working fine now. Thanks again!
