### ISSUE TITLE
Optional Play/Pause Button Size Override

### ISSUE THREAD

**Issue by chairmanxyz** [Fate-Grand-Automata/FGA#632]
Would it be possible to add a new setting in fine tune that overrides the auto scaling of the pause play button? I'd like to keep mine small regardless of resolution so that I can keep it in the bottom left corner without the script mistakenly clicking on it. Maybe a slider with small, medium, large? Something to that effect?

Thank you for considering!

**Comment by OmniStef94** [comment]
Would be nice if the option was there, but for now the most optimal thing is to just leave the button in the bottom left corner.

**Comment by reconman** [comment]
I don't see any config option for this?

**Comment by MathewSachin** [comment]
The problem was that button size varied depending on device dpi. In the compose version, it doesn't, so I think the option isn't needed either.
