### ISSUE TITLE
Not selecting skills after first wave

### ISSUE THREAD

**Issue by VichoH-32** [Fate-Grand-Automata/FGA#640]
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

**Describe the bug**
On JP after the UI update and version from playstore the app works normal selecting skills on first wave, but on second wave it goes strait into battle without selecting the skills indicated in the battle script. After reading Troubleshooting Guide and other issues reported i tried some canary version and in 1215 the character selection started working again but the bug from second wave is still present. One thing i tried is deleting the battle script and making it again but didn't work. The app works fine on NA.

**Screenshots**

![Screenshot_20201227-043331_FGA (CI)](https://user-images.githubusercontent.com/26494498/103166000-2f40b580-47fd-11eb-94f7-9508a0220e4f.jpg)

**Video**

https://user-images.githubusercontent.com/26494498/103166426-b17ea900-4800-11eb-8eb3-2b8feb0928b5.mp4

**Device Info:**
 - Device model: Galaxy s10e
 - Screen size: 1080 x 2280
 - Android Version: Android 10
 - RAM: 6GB

**Comment by MathewSachin** [comment]
Your phone is not 16:9. Other resolutions won't necessarily work correctly right now.
That's what the other issues and Troubleshooting Guide say.
