### ISSUE TITLE
Stop on node completion (first time clear)

### ISSUE THREAD

**Issue by runelt99** [Fate-Grand-Automata/FGA#644]
Before opening an issue:
- [x] No one has asked for this feature before in other issues (even the closed ones)

- searched 'first clear ' and 'node completion'

> If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

It can be accomplished by having it look at screen for the saint quartz from node completion.

Right now im trying to substitute that by just having it do '3' runs, but it gets messed up if i have to stop the script, meaning i have to go back to change amount of runs or risk not paying enough attention and having it waste AP by repeating a node (especially if first clear has lower AP usage.)

**Comment by MathewSachin** [comment]
So, a new 'Stop on First-clear rewards' similar to 'Stop on CE GET'.
Should be a really useful but pretty simple thing to add, so I'll leave it open for contributions.
