### ISSUE TITLE
JP FP gacha won't advance to the next 10 roll

### ISSUE THREAD

**Issue by ArikTsuka** [Fate-Grand-Automata/FGA#654]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
JP FP gacha won't advance to the next 10 roll even though debugger knows where it needs to press to advance. Tested this on NA and it works fine

**Screenshots**
![Screenshot_20210101-230725](https://user-images.githubusercontent.com/29684635/103450761-b7550e00-4c88-11eb-895b-74edadf8dc9f.png)

**Device Info (please fill at-least 'Device model'):**
 - Device model: Google Pixel 3 xL
 - Screen size: 1920×1080
 - Android Version: 9
 - RAM: 4GB

**Comment by ArikTsuka** [comment]
Using FGA canary-1263 btw

**Comment by metapone** [comment]
@ArikTsuka this isn't related to your problem, but how did you activate the FP mode? I'm on NA and when I start the script in that exact screen as your screenshot, it doesn't do anything. If I then do a 10x FGA will tap repeatedly to skip the individual result animations, then get right back to the result summary page above and hang again.

**Comment by ArikTsuka** [comment]
@metapone are you on the latest FGA canary? I got FP mode to start in the exact screen as my screenshot on NA and it kept going

**Comment by metapone** [comment]
@ArikTsuka huh, I tried turning on FGA's video recorder just now and the FP mode worked again. Disable Record Screen and it's back to being busted. This is amusing.

**Comment by MathewSachin** [comment]
@metapone works when recording can be due to either of the following:
1. Phone is weak to run both FGO and FGA at the same time. So, Android reduces the priority of FGA since it is a background process. 
2. Your Battery optimization settings limit background processes like FGA.

When the app is recording, Android retains its priority and hence it continues to work well, is what I believe, since I haven't experienced this myself.

> even though debugger knows where it needs to press to advance

@ArikTsuka It's looking for that button there but not finding it on your device for some reason.
That's why the rectangle is RED. If it matches it shows up as GREEN.
I confirmed that the FP script is working on my phone for both JP and NA.

Post a screenshot of your `More options` settings.

**Comment by ArikTsuka** [comment]
@MathewSachin 
![Screenshot_20210102-132435](https://user-images.githubusercontent.com/29684635/103463964-494b2e00-4cfe-11eb-9295-9593f5170e50.png)
![Screenshot_20210102-132546](https://user-images.githubusercontent.com/29684635/103463968-5405c300-4cfe-11eb-9c95-3217541d081a.png)

**Fine Tune menu**
![Screenshot_20210102-132512](https://user-images.githubusercontent.com/29684635/103463986-7b5c9000-4cfe-11eb-9d15-edf63dd37e41.png)
![Screenshot_20210102-132524](https://user-images.githubusercontent.com/29684635/103463989-82839e00-4cfe-11eb-97bb-e3c787aa9478.png)
![Screenshot_20210102-132534](https://user-images.githubusercontent.com/29684635/103464006-acd55b80-4cfe-11eb-8117-54d195dfb5c8.png)

**Comment by reconman** [comment]
@MathewSachin Is the stage counter similarity set to 100 necessary? Shouldn't it be fixed as part of the JP UI fixes?

@ArikTsuka I just replaced the fp_continue image with a higher quality one from your screenshot. Please test with Canary 1264, which will be available in a few minutes.

**Comment by ArikTsuka** [comment]
@reconman works now! =) thank you very much
