### ISSUE TITLE
FP gacha not working in KR

### ISSUE THREAD

**Issue by ScathachSkadi** [Fate-Grand-Automata/FGA#655]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
FP gacha does not work in KR. I tried on my S7, S8, and on Bluestacks. JP seems to work on Bluestacks so I think it's an image problem? I am not sure if KR changed the font of the button but here is the vid and the screenshot. 

**Screenshots**
![Screenshot_20210103-093421_FateGO](https://user-images.githubusercontent.com/70437676/103469396-9931ff80-4da7-11eb-966a-f3d43bca63c0.jpg)

**Video**
https://drive.google.com/file/d/1-6Icfo8vuApB5hBAiJ9pR-ohc8eN1HqB/view?usp=sharing

**Device Info (please fill at-least 'Device model'):**
 - Device model: S7, S8, Blustacks 4
 - Screen size: 16:9 and 18:9 in 1920x1080
 - Android Version: Unrelated
 - RAM: Unrelated

**Comment by reconman** [comment]
Hmm, strange. I don't see any custom similarity value in the source code and the picture isn't that different compared to your screenshot.

I also replaced the KR fp_continue with an image from your screenshot. Try out Canary 1265.

**Comment by ScathachSkadi** [comment]
@reconman the screenshot is from my S7 and it tried the latest canary on Bluestacks and it works now. I think it was an image problem. Thanks for fixing it so quickly!
