### ISSUE TITLE
[Question] When a Servant dies and is replaced by the next, it does not apply the skills

### ISSUE THREAD

**Issue by MakuSensei** [Fate-Grand-Automata/FGA#656]
Before opening an issue:
- [ ] My question isn't answered in any other issues (even the closed ones)
- [ ] I'm not reporting a bug/error

> If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

Hello and greetings from Argentina, sorry if my question is not understood since I use google translator
My question is how do I get the next Servant to execute their skills.
at this NA server New Years event. I have set up farming scripts not 3 shifts.
I have configured so that each servant, including the support, execute their skills themselves, in addition to being active "skill spam" so that it is repeated. up there no problems
But when a Servant dies (not always) and is replaced, the next Servant does not apply their skills where they are. I kept applying the skills of others.
I hope you can understand what I say.
Sorry for the inconvenience

**Comment by reconman** [comment]
Skill spam makes screenshots of the used skills and only clicks on skills it used before.

**Comment by MakuSensei** [comment]
> Skill spam makes screenshots of the used skills and only clicks on skills it used before.

Thanks for responding, and what could I do to make him execute the next Servant's skills.

**Comment by reconman** [comment]
That's too complicated to implement and requires human intervention. FGA's main focus is on handling consistent battles where you can predict most of the fight.
