### ISSUE TITLE
I cannot get Support Image Maker to work

### ISSUE THREAD

**Issue by UchiLazuli** [Fate-Grand-Automata/FGA#658]
Before opening an issue:
- [x] I tested the latest release
- [X] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
I have been trying to get the image maker to work but couldn't. The issue seems to be Android automatically puts .png at the end of an image while FGA also puts .png at the end of its images, resulting in the file name being image.png.png and that breaks the image.

**Screenshots**
It is recommended that you at-least add one screenshot of FGO running on your device.

**Video**
https://youtu.be/ETO3JTLzssk

**Device Info (please fill at-least 'Device model'):**
 - Device model: [Samsung Galaxy S20]
 - Screen size: [1440 x 3200]
 - Android Version: [Android 10]
 - RAM: [10 GB]

**Comment by reconman** [comment]
Since you made the effort to create an issue on Github, after I told you so on Youtube, I'll help you a bit.

When you create a bug report, you will see lots of text already there. That's the template.

Don't delete everything but instead replace the hints.

Please take a look at other pre-existing bug reports to see how it should look. For example #655.

**Comment by UchiLazuli** [comment]
> Since you made the effort to create an issue on Github, after I told you so on Youtube, I'll help you a bit.
> 
> When you create a bug report, you will see lots of text already there. That's the template.
> 
> Don't delete everything but instead replace the hints.
> 
> Please take a look at other pre-existing bug reports to see how it should look. For example #655.

Yeah, my bad. I fixed it with the template.

**Comment by MathewSachin** [comment]
We weren't able to reproduce this error yet and no one else using Samsung phones seems to have this issue either.
Can't do much about an issue we can't reproduce.
