### ISSUE TITLE
select skill doesn't work

### ISSUE THREAD

**Issue by Lilith97** [Fate-Grand-Automata/FGA#660]
hi, when i run the bot, select the skill but not confirm them, why?

**Comment by reconman** [comment]
See https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+%22skill+confirmation%22+is%3Aclosed+

**Comment by reconman** [comment]
Also see https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting#uses-skills-on-wrong-servant-or-doesnt-use-skills-at-all
