### ISSUE TITLE
Couldn't access support images

### ISSUE THREAD

**Issue by CoalMountain** [Fate-Grand-Automata/FGA#668]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

https://user-images.githubusercontent.com/77419752/104791523-fa10fd00-57d5-11eb-9fd7-8bf6f835c981.mp4

] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
I couldn't use the support image maker. Also, the save file cannot be accessed(i have given access when creating the folder). I have given both the access required when starting the application on first launch.
I used screen recorder because the app couldn't record even with the record function activated.

**Screenshots**
It is recommended that you at-least add one screenshot of FGO running on your device.

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON
Recording functionality is available within the app in `More options`.

**Device Info (please fill at-least 'Device model'):**
 - Device model: Huawei Nova 5T
 - Screen size: 6.26 inches, 96.2 cm2
 - Android Version: Android 10
 - RAM: 8.0 GB

**Comment by MathewSachin** [comment]
I believe this was fixed by 5a5d99bb0a540ff7626011754cf9c4944c86c135. If updating to the latest version still doesn't work, try clearing app data and setting it up again. Be sure to export any battle configs you want to keep.
