### ISSUE TITLE
Change between-skill click location

### ISSUE THREAD

**Issue by masterjuggler** [Fate-Grand-Automata/FGA#669]
I didn't see this mentioned in other issues, but I may have missed it. When running a battle script, I see clicks in the upper right of the screen between skill uses, presumably to speed things up (though I'm fairly sure it does not). The problem is it always clicks on any heads up notifications I get, which can really screw things up both for the battle and for the app it opens.

Could we have either a way to disable that click, or to change the location? If it was at the far left or right of the screen's center, it would be much less likely to click on a notification.

**Comment by potchy** [comment]
This upper right click is there to close the unwanted dialogues that pop up sometimes, like the enemy summary, stun warning or cooldown warning. 

Just turn on the "do not disturb" setting on your phone. It will disable notifications.
