### ISSUE TITLE
How does Skill Spam work?

### ISSUE THREAD

**Issue by mikey4realz** [Fate-Grand-Automata/FGA#674]
Before opening an issue:
- [x] My question isn't answered in any other issues (even the closed ones)
- [x] I'm not reporting a bug/error

> If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

I'm struggling on getting Skill Spam to work. I have it set to Spam but it never uses a skill. NP Spam works just fine.
Am I missing an extra step to set this up?

Thank you!

**Comment by the3dsandwich** [comment]
I believe this was asked somewhere in other issues, but the tldr is that skill spam **re-applies skills that finished recharging**. If you don't set it to use a skill the first time, it's not going to spam that skill.

So go ahead and script your battle config **with the timing to use a skill for the first time", then see if it works after.

**Comment by reconman** [comment]
Yeah, I recently answered in https://github.com/Fate-Grand-Automata/FGA/issues/659#issuecomment-755332653
