### ISSUE TITLE
can't choose folders to store images, shows the home screen instead

### ISSUE THREAD

**Issue by YuunaRenata** [Fate-Grand-Automata/FGA#677]
Before opening an issue:
- [Y es] My question isn't answered in any other issues (even the closed ones) 
at least i don't think so, i might miss a few threats. 
- [Y es] I'm not reporting a bug/error

> If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

When opening battle config, a pop up will appear, telling to choose a folder, however whenever i press the choose button, it'll go to the homescreen. Anyone have any idea what the issue is? ><

-can't record using debug mode, so i used a screen recorder
-phone is not rooted

![521689](https://user-images.githubusercontent.com/58941850/106353224-89acc480-631b-11eb-8671-92b6775dac10.jpg)

https://user-images.githubusercontent.com/58941850/106353227-8addf180-631b-11eb-966d-dc11c6bb48ed.mp4

Device : realme i5
Screen resolution : 720x1600
Android version: 9
Ram 4 gig

**Comment by TheRealPlagiariser** [comment]
What the app is trying to do currently is it will trigger-open your default file explorer. Could you change the default file explorer app to another (by downloading another one and setting as default) and see if it still fails?

**Comment by YuunaRenata** [comment]
Ah, i cant seem tk find a way to change the default storage ><. I think the problem is with the device since when i tried with the emulator it works just fine 👌
