### ISSUE TITLE
Skill option not working

### ISSUE THREAD

**Issue by thumthuma** [Fate-Grand-Automata/FGA#678]
Before opening an issue:
- [ /] I tested the latest release
- [ /] I looked at other issues (even the closed ones)
- [ /] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [ /] I'll fill this template properly

Device model:Huawei P30 Pro
Screen size: 1080 x 2340
Android version:10
RaM: 8.0 GB

My skill option (spam/danger) not working but np (spam/danger) work perfectly 
I had checked skill confirmation and notch as well
and others option like command or apple refill work normally so I think it not about screen size

I don't know that miss some thing else please help me
sorry for my bad English thankyou

I try to record screen while automata playing but it seem like it cut the record off when I switch from overlay automata app to fgo and continue record when I switch back to automata app I don't know that can't have 2 overlay app or something

**Comment by MathewSachin** [comment]
> I looked at other issues (even the closed ones)

No, you didn't look at closed issues. Please do. There were very recent ones regarding this.
