### ISSUE TITLE
Add Friends Only option to First

### ISSUE THREAD

**Issue by Cascadess** [Fate-Grand-Automata/FGA#679]
Revisiting this again with Illya event.

A weak NPC support will be selected as first everytime. Do not want.

Therefore, copying the "Friends Only" option to "First" will prevent this from happening in future.

Thank you.

**Comment by MathewSachin** [comment]
You already have another issue open for this. Please don't spam.
And, `Friends Only` treats NPCs and Followed as Friends, so there's no change in this case.
