### ISSUE TITLE
[Question] How to create a script that detects that an NP is available.

### ISSUE THREAD

**Issue by MakuSensei** [Fate-Grand-Automata/FGA#681]
Before opening an issue:
- [✓] My question isn't answered in any other issues (even the closed ones)
- [✓] I'm not reporting a bug/error

> If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

Hello and sorry if my question is very stupid.

First I have tried to create a script that tries to launch the NP as soon as it is available. But so far I haven't gotten it to work.Although NP spam is activated, it does not launch them.

An example of the team I'm using for the NA server Valentine's event: I have everyone with the point drop CEs. Support waver, sieg, Arash, kuro. Kuro with the CEs currently mlb, while the others with the initial charge of 30%. First turn. I use waver skills, then I use Arash. 2nd turn, he launched the kuro np at the enemy with the most life. After this in the same round if you get to load their bar again or if sieg and waver have it. The script doesn't recognize it and lets it pass. Then in the 3rd round that should launch the available np it does not do it even though it is programmed there.

I do not know if something is wrong with what I am doing or it is an error of the AI ​​of the application.

Well I apologize again if it becomes a nuisance. And excuse me for my English. I use the Gboard translator

**Comment by reconman** [comment]
How does your command look like?

**Comment by MathewSachin** [comment]
> github-actions bot locked and limited conversation to collaborators on 14 Feb

@reconman waiting for reply🤣

**Comment by reconman** [comment]
Oh, didn't notice.
