### ISSUE TITLE
First support entry being ignored when using Preferred?

### ISSUE THREAD

**Issue by alextruong** [Fate-Grand-Automata/FGA#682]
- [X] My question isn't answered in any other issues (even the closed ones)
- [x] I'm not reporting a bug/error

Didn't find any other issues for this, but I'm not sure if it's a bug or not, so just opened a question for now. I've noticed that the script has been ignoring the first support entry in the list, even when it's a match for the criteria I specified in the config. It's done stuff like swipe repeatedly, even when the matching first entry is the ONLY entry on the list, then refreshes the list, completely ignoring it.

I'm not sure which version I'm running unfortunately, only that it's a canary build (though not necessarily the one currently labeled). Is there somewhere in the app where the version string will print? I didn't find anything like that. But if my issue is fixed in some later version than 0.20.0, I can try pulling that down and testing.

**Comment by reconman** [comment]
On my phone you can find the version here:
Settings -> Apps -> FGA (CI) -> Click on Advanced -> Says `Version 1263` at the bottom

The version number is the build number from https://github.com/Fate-Grand-Automata/FGA/actions?query=workflow%3ACI+branch%3Amaster

The latest run is "CI #1288", so that's the latest version.

But anyways, your problem is probably related to your screen settings such as the missing full-screen mode for Samsung, since there wasn't any major screen detection change in the past few months.

Please look through https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting and open a Bug report if nothing helped.

Also try searching for closed issues related to your phone model.

**Comment by alextruong** [comment]
Just found an instance where it was ignoring the second element entry as well.

I'm on Bluestacks, so I don't think it's a display/Samsung thing...Bluestacks also unfortunately doesn't have the version string available for sideloaded apps, it appears...

![com bluestacks settings_Screenshot_2021 02 15_03 51 22](https://user-images.githubusercontent.com/10948145/107924553-20df6200-6f41-11eb-8ac4-955dcf0fa738.jpeg)

I noticed 907d205a2f7376a76b174c0e243bbd2e003ce64b was possibly relevant; maybe this possibly fixes it (I'm currently asking for MLB, but I guess I could toggle that to test)?

**Comment by reconman** [comment]
For me, the app version is displayed right under `App details`.

You can try updating the app and as you said disable MLB and see if anything helps.

**Comment by MathewSachin** [comment]
Also, take a look at `More-options / Fine-tune / MLB similarity`. Reduce that to 70 or a bit below and see if that works.

**Comment by jesaes** [comment]
Hello, not sure if I should create another issue or something but whenever I finish a node it just stops on quest drop (this is on valentines event in jp btw also in FGA canary using the latest version) the script is still working but it just stop there. Am I doing something wrong?

**Comment by reconman** [comment]
@jesaes we need a bug report with a video in debug mode, otherwise we can't determine anything.

**Comment by jesaes** [comment]
Okay, I'll be recording in a bit

**Comment by alextruong** [comment]
Oh, I forgot to follow up on this because of my tendency to procrastinate on events; I ended up just increasing the amount of times to refresh supports. Kind of an inelegant workaround, but probably not worth the effort to debug if it seems like I'm the only one with this problem.
