### ISSUE TITLE
Stops at point rewards

### ISSUE THREAD

**Issue by jesaes** [Fate-Grand-Automata/FGA#684]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

It took a while for it to actually click the continue on quest drops however on the point rewards, it just stop there (not sure if it would also continue after a while).

Device Info:
 - Device model: Realme 5 Pro
 - Screen size: 1080 x 2340
 - Android Version: 10
 - RAM: 8 GB

**Comment by jesaes** [comment]
I'll be uploading the video, I think the file size is too big

**Comment by jesaes** [comment]
https://user-images.githubusercontent.com/71634408/108038377-b8de6800-7075-11eb-9285-c87605a405d2.mp4

I also forgot to add that I'm playing on JP server.

**Comment by reconman** [comment]
@jesaes People usually upload to Youtube or Streamable.

**Comment by jesaes** [comment]
@reconman welp I made it work so there's that I guess..

**Comment by MathewSachin** [comment]
Does this happen when Debug mode is OFF?
Too many boxes around that text might be messing with image matching. 🤔

**Comment by jesaes** [comment]
Haven't really tried that yet, will do

**Comment by jesaes** [comment]
Turned off the debug mode and it now works properly. Thank you very much!

**Comment by MathewSachin** [comment]
I'll push a proper fix for this in a few hours.
