### ISSUE TITLE
Continuing to Skill Spam with new Servants coming in

### ISSUE THREAD

**Issue by Rajvir8** [Fate-Grand-Automata/FGA#686]
Before opening an issue:
- [X] No one has asked for this feature before in other issues (even the closed ones)

I wanted to ask if it would be possible to add an option for skill spam where after one of the first three Servants die, the remaining servant continues to skill spam.

I am aware that if any skill needs to be targeted it may fail, and/or if a Servant who normally needs to target it might select the servant instead.

That said it'd still overall be more useful than the current approach of new Servants not using there skills at all.

**Comment by the3dsandwich** [comment]
I remember the problem/difficulty with this approach is that they'll have to store every single skill icon, in order for image matching to work (to check whether a skill can be used). This is impractical at the moment, so it's not implemented.

That being said, if the remaining servant has a skill with the same icon at the same skill icon slot (hope you understand what I mean by this), then that servant's skill will still be used.

If you have an idea on how skill spam can be implemented, I'm sure you're welcome to experiment with different approaches.

**Comment by Rajvir8** [comment]
That's completely understandable, I'll have to experiment but your right in that every single skill icon being stored is impracticable.  I'll have to look into it and see if there's any better way.  

Thanks for the info.

**Comment by reconman** [comment]
Using images before clicking on skills is not necessary, but intended. There are quite a few skills which do more harm than good and lots of them require a target.

How should FGA decide the target of a skill that's normally not used, especially if it could have negative effects? For example, Emiya (Assassin)'s targeting skill.

Mori Nagayoshi's first skill turns all other skills to pure debuffs if they're used afterwards. Elizabeth (Brave)'s 3rd skill drains her NP gauge from 100 % to 0.

I personally wouldn't want FGA to behave like you're suggesting.

**Comment by MathewSachin** [comment]
I kind of have something similar I'm working on the side. This is making use of Jetpack Compose which is still in alpha.
I probably won't merge into `master` branch till compose is supported in regular Android Studio.

This essentially allows specifying spam settings for all 6 servants individually. Part of the code is up in #675. I haven't finished it yet.

![Screenshot_2021-02-16-11-18-32-20](https://user-images.githubusercontent.com/10654537/108407319-9a30ca80-7249-11eb-8a5c-a998aaa2891b.jpg)
