### ISSUE TITLE
system not doing anything when activated

### ISSUE THREAD

**Issue by ojojostar** [Fate-Grand-Automata/FGA#698]
Before opening an issue:
- [x ] I tested the latest release
- [x ] I looked at other issues (even the closed ones)
- [ x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x ] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
I swear that I set everything up properly the program, nothing happens in the menu, support selection, nor battle. Additionally, if I try to limit the number of runs, my phone keeps on flashing Ran 0 out of X time(s).

**Screenshots**
I have videos so i wont include any screenshots unless anyone wants anymore

**Video**

https://user-images.githubusercontent.com/81982489/113765274-0aa48580-96ea-11eb-8dc7-1886340925d4.mp4

https://user-images.githubusercontent.com/81982489/113765833-c6fe4b80-96ea-11eb-8581-ec2c3ad9354e.mp4

**Device Info (please fill at-least 'Device model'):**
 - Device model: [HUAWEI Mate SE BND-L34]
 - Screen size: [2160 x 1080]
 - Android Version: [8.0.0]
 - RAM: [4.0 GB]

**Comment by reconman** [comment]
I know that icon, that screen recorder breaks FGA because both want to see the capture the screen output.

Stop the video recording app, restart the phone to make sure, then test FGA again. If it doesn't work, record the video using FGA's built in recorder. (More Options -> Record Screen)

**Comment by ojojostar** [comment]
uh it randomly started working now thx
