### ISSUE TITLE
Pixel3 xl

### ISSUE THREAD

**Issue by farzor520** [Fate-Grand-Automata/FGA#700]
![Screenshot_20210407-005838](https://user-images.githubusercontent.com/43706651/113813943-d7401600-973e-11eb-9d2e-a080e1791aba.png)

I did all the actions in the photo the action in the script was use the NP 

Doesn't start the script , doesn't click in the screen

An old version used to click in wrong places

Last Version. 1327

**Device Info 

 - Device model: [Pixel3 xl]
 - Screen size: [1440x2960]
 - Android Version: [ Android 11] 
 - RAM: [4GB]

**Comment by MathewSachin** [comment]
The troubleshooting Guide pretty clearly mentions that FGO should take up the whole screen for FGA to work. There should be no black areas except a notch. There's a black region on the right side of the image you provided. Unless you get rid of that, FGA won't work properly.
