### ISSUE TITLE
system not doing anything when activated again

### ISSUE THREAD

**Issue by ojojostar** [Fate-Grand-Automata/FGA#701]
Before opening an issue:
- [ x] I tested the latest release
- [x ] I looked at other issues (even the closed ones)
- [x ] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [ x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
the program isnt running and i think the same thing that happened last time is occurring again

**Screenshots**
have video already

**Video**
https://user-images.githubusercontent.com/81982489/114111192-65cfa700-98a7-11eb-8097-44ba52e1e4ee.mp4

**Device Info (please fill at-least 'Device model'):**
Device model: [HUAWEI Mate SE BND-L34]
Screen size: [2160 x 1080]
Android Version: [8.0.0]
RAM: [4.0 GB]

**Comment by w-san** [comment]
not sure if you phone has this or not just throwing some suggestion if you phone display settings has a fullscreen mode for app check fgo has it on.

I decided to check what my Xiaomi 10T lite display ratio was and i saw this setting turn it on for FGO and now FGA works properly for my JP fgo. Not sure if Huawei has something similar

**Comment by MathewSachin** [comment]
It seems to me like Huawei's battery saver causing problems.
https://github.com/Fate-Grand-Automata/FGA/issues/354#issuecomment-687134894 was a similar issue.

**Comment by ojojostar** [comment]
> It seems to me like Huawei's battery saver causing problems.
> [#354 (comment)](https://github.com/Fate-Grand-Automata/FGA/issues/354#issuecomment-687134894) was a similar issue.

Thanks this fixed it!
