### ISSUE TITLE
The app doesn't work

### ISSUE THREAD

**Issue by Zero089** [Fate-Grand-Automata/FGA#704]
Before opening an issue:
- [ ✓ ] I tested the latest release
- [ ✓ ] I looked at other issues (even the closed ones)
- [✓  ] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [✓  ] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
I start the application and nothing happens.  It does not select support, it does not activate skills, it does not initiate attack and it does not select an NP either.

I have used the app in the past so I know how to organize it without problems, but this time it just doesn't work...

**Screenshots**
It is recommended that you at-least add one screenshot of FGO running on your device.

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON
Recording functionality is available within the app in `More options`.

https://user-images.githubusercontent.com/76478209/114786006-14aa3200-9d43-11eb-914a-814161826a4d.mp4
(Video Debug mode on)

**Device Info (please fill at-least 'Device model'):**
 - Device model: [e.g. Motorola One Macro]
 - Screen size: [e.g. 1280x720] [16:9]
 - Android Version: [e.g. Android 10]
 - RAM: [e.g. 4GB]

**Comment by w-san** [comment]
Not sure if Huawei phone has something similar

I'm using a Xiaomi MI 10t lite and i managed to finally get fga to work now,

If Huawei has something similar then try this maybe.

Go to display if there is a fullscreen mode setting in display or in the settings that allows apps to work in fullscreen mode check if fgo has permission to use it.

I turned mine on for FGO and now FGA can work properly on my JP account.

Not sure if it works but i'm just throwing you some ideas.

**Comment by Zero089** [comment]
I did what you said and it appeared that "full screen mode was off".  I
thought that my problem would be solved that way but the application does
not choose the support or activate the first or second skill of the first
party member.  It's weird, like I'm avoiding it.

**Comment by MathewSachin** [comment]
It's kinda hard to see from the video, but, your phone seems to have black bars on the bottom and both sides.

The troubleshooting guide does mention that FGA won't work in such a case. You've to get rid of those black bars which is usually due to gesture navigation.

https://github.com/Fate-Grand-Automata/FGA/wiki/Game-Area-detection#case-3-your-phone-has-borders-around-fgo-even-at-the-bottom-of-screen
