### ISSUE TITLE
FGA freezes when theres no support friend in JP.

### ISSUE THREAD

**Issue by Skyjersey** [Fate-Grand-Automata/FGA#710]
Before opening an issue:
- [✓] I tested the latest release
- [✓] I looked at other issues (even the closed ones)
- [✓] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [✓] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
FGA freezes on the support list when there's no friends present on the list and does not swipe or update. I have set the in-game CE filter to only show MLB gold currency event CE which is rare. Class is Mix and selection mode is First. I have tried fullscreen apps on and off in samsung settings.

This bug does not happen on 16:9 a phone playing FGO JP.

**Screenshots**
It is recommended that you at-least add one screenshot of FGO running on your device.

**Video**
https://user-images.githubusercontent.com/10911891/116513608-70a4b700-a8fc-11eb-831a-736bff24ae52.mp4

**Device Info (please fill at-least 'Device model'):**
 - Device model: [Samsung Galaxy A70]
 - Screen size: [2400x1080]
 - Android Version: [Android 11]
 - RAM: [6GB]

**Comment by MathewSachin** [comment]
So, the detection for 'No matching supports' is off by a bit on JP. Making that region wider should work I guess.

![image](https://user-images.githubusercontent.com/10654537/118003563-517b4000-b366-11eb-9c65-457d8bd92044.png)
