### ISSUE TITLE
Script not detecting/picking skills and NP only on the 2nd wave of some stages, works in other nodes fine. 

### ISSUE THREAD

**Issue by jensendong141** [Fate-Grand-Automata/FGA#714]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
The script would run on most nodes perfectly fine. However on some nodes, the script doesn't detect skills and NP cards, and it would go straight into command cards selection and only picking normal cards when NP cards are available. It gets stuck on picking normal cards from that point on. I have all Nox recommended settings turned on and I have tried tuning the parameters in fine tune. The same problems still happen. 

**Device Info (please fill at-least 'Device model'):**
 - Device model: NoxPlayer 7.0.0.8
 - Screen size: 1600x900
 - Android Version: Android 7
 - RAM: 4GB

**Comment by basturmater** [comment]
I have been getting the same issue as well recently and I am using BlueStacks

**Comment by reconman** [comment]
Can you identify the nodes where it doesn't work?

**Comment by basturmater** [comment]
> 
> 
> Can you identify the nodes where it doesn't work?

I am playing on FGO JP and so far it has been occurring on all the event node free quests for the current event

**Comment by reconman** [comment]
Can you provide a video using FGA's built in recorder?

**Comment by basturmater** [comment]
The file size is too big to attach directly on here so I uploaded it to streamable here: [](https://streamable.com/bv0mg9)

I also attached a screenshot of the commands I have for this specific team. Musashi berserker, double Caster Artoria and Tamamo with the plugsuit.
![com mathewsachin fategrandauto_Screenshot_2021 05 02_14 25 09](https://user-images.githubusercontent.com/28666765/116828301-a642dd80-ab52-11eb-818c-8c199d19ee0f.png)

**Comment by reconman** [comment]
Try lowering the stage similarity % in the settings.

**Comment by jensendong141** [comment]
> Can you identify the nodes where it doesn't work?

for me it's the idol event this time, 2nd lv90 node, フォーメーションリハーサル. I switched to the CI build from GitHub and now similar problem is appearing again but for the 3rd wave. In the screenshot below, g skill from the right servant in turn 3 is not being pressed, and the script goes straight into command cards. 
![image](https://user-images.githubusercontent.com/43710472/116837046-b91ed780-ab7d-11eb-9d80-cf481ef372d5.png)

**Comment by jensendong141** [comment]
> Try lowering the stage similarity % in the settings.

I tried lower the stage similarity % by 10%, same problem still happening. The first and third lv90 node work fine.

**Comment by jensendong141** [comment]
> Can you provide a video using FGA's built in recorder?

The built-in recorder is greyed out after I turned on the Nox specific setting, so I have a video recorded using Nox itself with FGA debug mode on. 

https://streamable.com/jxqfqi

**Comment by yiqunl2-1863642** [comment]
I am having the same issue, but switching to Cl(version 1270) solves the issue for me.

**Comment by byzzz** [comment]
> I am having the same issue, but switching to Cl(version 1270) solves the issue for me.

How do I switch to that version? I'm having similar problems as well

**Comment by the3dsandwich** [comment]
You will want to look at https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary to find the latest canary release. You can find the above link from [the FGA website](https://fate-grand-automata.github.io/), which is linked at the start of this repo.

**Comment by MathewSachin** [comment]
The region for matching the wave number is out of place.

![image](https://user-images.githubusercontent.com/10654537/118008176-78d40c00-b36a-11eb-9480-5bd5f0ec7d03.png)

@jensendong141 Are you on the latest canary version? I recall changing this region for JP quite a few times, so older versions might have incorrect regions. Or, it could be that DW updated the UI to align things better.

**Comment by jensendong141** [comment]
> The region for matching the wave number is out of place.
> 
> ![image](https://user-images.githubusercontent.com/10654537/118008176-78d40c00-b36a-11eb-9480-5bd5f0ec7d03.png)
> 
> @jensendong141 Are you on the latest canary version? I recall changing this region for JP quite a few times, so older versions might have incorrect regions. Or, it could be that DW updated the UI to align things better.

Yea I am currently. The problem on wave 2 was solved after switching from store version to the canary version, but the same problem started to happen on wave 3 instead of wave 2. Lowering the stage similarity by 5% solved the issue on one of the event nodes iirc but not all the problematic ones.

**Comment by yunamon** [comment]
> > The region for matching the wave number is out of place.
> > ![image](https://user-images.githubusercontent.com/10654537/118008176-78d40c00-b36a-11eb-9480-5bd5f0ec7d03.png)
> > @jensendong141 Are you on the latest canary version? I recall changing this region for JP quite a few times, so older versions might have incorrect regions. Or, it could be that DW updated the UI to align things better.
> 
> Yea I am currently. The problem on wave 2 was solved after switching from store version to the canary version, but the same problem started to happen on wave 3 instead of wave 2. Lowering the stage similarity by 5% solved the issue on one of the event nodes iirc but not all the problematic ones.

Your problem seems similar to mine (https://github.com/Fate-Grand-Automata/FGA/issues/709) , but instead of not picking cards it opened up the status box and thus stopping any script after that. I noticed it only happens last event and only if I enable auto target.

**Comment by MathewSachin** [comment]
Use thresholded stage counter detection from more options/advanced.
I'll make it default eventually.
