### ISSUE TITLE
Failed to determine Card type Arts in TW

### ISSUE THREAD

**Issue by ShibaShika** [Fate-Grand-Automata/FGA#720]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

**Describe the bug**
FGA can't determine Arts in TW server, but works fine on other types.

**Screenshots**
![B1](https://user-images.githubusercontent.com/40266069/118384127-3ba39e80-b636-11eb-924e-0d6d68e3d984.png)
![B2](https://user-images.githubusercontent.com/40266069/118384130-3e9e8f00-b636-11eb-87ba-c41bb58946df.png)
![B3](https://user-images.githubusercontent.com/40266069/118384133-40685280-b636-11eb-925c-bd3dbb1a9399.png)

**Device Info:**
 - Device model: NoxPlayer
 - Screen size: 1920x1080
 - Android Version: Android 7.1.2
 - RAM: 3GB

**Comment by the3dsandwich** [comment]
I'm on TW too and this is a problem for me as well. I think the problem in #627 happened again. Did TW change the font back? Let me go make some screenshots and see if we can fix this.

**Comment by the3dsandwich** [comment]
@ShibaShika would you mind double-checking if #721 works for you?

**Comment by reconman** [comment]
FYI, it will take a while for the fix to be built, Github Actions is not working right now: https://www.githubstatus.com/

**Comment by ShibaShika** [comment]
@the3dsandwich
Works good, thank you.
