### ISSUE TITLE
App chooses wrong servant position to cast a skill on

### ISSUE THREAD

**Issue by ARFearKubrick** [Fate-Grand-Automata/FGA#722]
I have a 3 turn farming set up with waver, a clasic one, but not only waver 1st skill but also suit NP up skill is casted onto the servant on the 3rd possition when is supposed to be casted onto the servant on 2nd possition.

I'm using a samgsung galaxy A42 5G

**Comment by reconman** [comment]
https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting#uses-skills-on-wrong-servant-or-doesnt-use-skills-at-all
