### ISSUE TITLE
App chooses wrong servant position to cast a skill on

### ISSUE THREAD

**Issue by ARFearKubrick** [Fate-Grand-Automata/FGA#723]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
I have a 3 turn farming set up with waver, a clasic one, but not only waver 1st skill but also suit NP up skill is casted onto the servant on the 3rd possition when is supposed to be casted onto the servant on 2nd possition.

**Screenshots**
It is recommended that you at-least add one screenshot of FGO running on your device.

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON
Recording functionality is available within the app in `More options`.

**Device Info (please fill at-least 'Device model'):**
 - Device model: Samsung galaxy A42 5G
 - Screen size: diagonally 6,6" (I do not have a ruler)
 - Android Version: Android 11
 - RAM: 4GB

**Comment by reconman** [comment]
You **didn't read** the troubleshooting guide: https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting#uses-skills-on-wrong-servant-or-doesnt-use-skills-at-all
