### ISSUE TITLE
System dying after use & few other things

### ISSUE THREAD

**Issue by ojojostar** [Fate-Grand-Automata/FGA#724]
Before opening an issue:
- [x ] I tested the latest release
- [x ] I looked at other issues (even the closed ones)
- [ x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [ x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
This is post has a variation of the problem (will scan stuff but do nothing but now after a while it just completely dies) of my first few posts along with some new ones.
First of all, the bug was somehow only fixed for one or two uses before it reverted back to its previous state, even though i tried the battery saver thing again. 
additionally, there are two more other bugs that I am even more confused about.

1.  I don't have video evidence for this one but I when I tried stopping the recording of FGO, the red square turned into a lighter shade and kinda froze. i then manually stopped FGA, and looked at the video that got recorded. It was corrupted and couldn't be opened. I tried it again and again, and finally worked properly on my third attempt, which is the recording that is attached. The recording was from a previous version since i forgot to check for updates, but after updating, the same bugs still happened so i didnt bother rerecording in the new version since I saw no difference.

2. the fga button thing appeared outside of FGO, but only appeared in landscape mode. I have no idea how this happened as all i did was exit out of FGO, but i took a picture of it. it appears that i can still click on it to activate the code, but i didn't run it. it is the screenshot.

**Screenshots**
![Screenshot_20210520-194616](https://user-images.githubusercontent.com/81982489/119064367-3aad9c80-b9a9-11eb-91dd-1f2217671278.jpg)

**Video**
https://user-images.githubusercontent.com/81982489/119064316-19e54700-b9a9-11eb-9a91-34fa70c7070e.mp4
sry for bad quality it was too big so had to shrink it  a bit

**Device Info (please fill at-least 'Device model'):**
Device model: [HUAWEI Mate SE BND-L34]
Screen size: [2160 x 1080]
Android Version: [8.0.0]
RAM: [4.0 GB]

**Comment by reconman** [comment]
2nd one has a history:

First the button was always there, no matter the orientation. Then I suggested to hide it in vertical mode since FGO always forces landscape and I'm too lazy to stop FGA every time.

If we would only show it when FGO is detected, then it's unusable for people where FGA can't detect that FGO is open.

Just stop FGA through the notification when you don't want to see the button while watching videos.

**Comment by MathewSachin** [comment]
"System dying after use" is related to Huawei battery optimisation. No solution from our end.
