### ISSUE TITLE
Add missing materials

### ISSUE THREAD

**Issue by MathewSachin** [Fate-Grand-Automata/FGA#727]
Some of the new NA mats and the JP only ones are missing from the app and were requested on Gamepress.

Here are their rough names:

- Ancient Bell of Tranquility
- Arrowhead
- Crown of Radiant Silver
- Divine Spiricle Vein
- Rainbow yarn
- Dawn light Reactor Core
- Tsukmo Mirror
- Genesis Egg
- Comet Shard
- Fruit of Longevity
- Demonic Flame Hōzuki

The images for the mats need to be cropped from screenshots of the drop screen (resize the original screen to 720p first) to be of the correct size.

I'm kinda not interested in the new mats and don't feel like switching back to `master` branch as I'm currently working on #675.
It would really help if someone could take this up. Don't worry about merge conflicts with `compose` branch.

Some images I have available (provided by @Skitts on Gamepress):

![image](https://user-images.githubusercontent.com/10654537/121034221-7bd7e600-c7ca-11eb-8ad5-4ffd46b613a8.png)

![image](https://user-images.githubusercontent.com/10654537/121034275-86927b00-c7ca-11eb-8c1b-1400bbfeab32.png)

**Comment by reconman** [comment]
https://docs.google.com/spreadsheets/d/1_SlTjrVRTgHgfS7sRqx4CeJMqlz687HdSlYqiW-JvQA/htmlview# should help both with item names and images.

**Comment by reconman** [comment]
> Don't worry about merge conflicts with compose branch.

Merge conflicts? Is there something I missed that makes it more complicated to merge into the compose branch?

**Comment by MathewSachin** [comment]
LB6 added 2 new mats 🙃 

https://community.gamepress.gg/t/automatic-farming-app-fate-grand-automata/72155/2701?u=mathewsachin
