### ISSUE TITLE
Can't enter Quests for some reason on CN server on Chaldea quest/ Free Quests Interface.

### ISSUE THREAD

**Issue by Kyonyuu** [Fate-Grand-Automata/FGA#729]
Before opening an issue:
- [x ] I tested the latest release
- [x ] I looked at other issues (even the closed ones)
- [x ] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [ x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
I can loop free quests with no problem, but only if i already had entered the quest but the quest needs to have "loop" activated... quests like Chaldea Gate for the first time i won't enter automatically on the quest, and if i don't reset FGA, it won't use any skills.

**Screenshots**
![image](https://user-images.githubusercontent.com/55859937/121113391-5f4aa680-c7e8-11eb-85e8-183df161de3d.png)
![image](https://user-images.githubusercontent.com/55859937/121113404-640f5a80-c7e8-11eb-9bd1-5e659d5923dd.png)

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON
Recording functionality is available within the app in `More options`.

**Device Info (please fill at-least 'Device model'):**
 - Device model: LG K10 2017
 - Screen size: [e.g. 1280x720]
 - Android Version: [e.g. Android 7.1]
 - RAM: [e.g. 3GB]

**Comment by reconman** [comment]
Menu was previously another image, that's why the menu button detection doesn't work anymore.

Check the apk at https://github.com/Fate-Grand-Automata/FGA/suites/3014534889/artifacts/68254369 for a potential fix. Please report whether it works or not.

**Comment by Kyonyuu** [comment]
it did work, thank you!
