### ISSUE TITLE
Android 12 does not allow FGA(or user) to register inputs.

### ISSUE THREAD

**Issue by sixtht** [Fate-Grand-Automata/FGA#734]
- [X] I tested the latest release
- [X] I looked at other issues (even the closed ones)
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] I'll fill this template properly

**Describe the bug**

Self-explanatory, Android 12 does not allow FGA(or user) to register inputs. You can start the app and if you activate debug mode you can tell it IS recognizing areas of the screen but it no input occurs, the screen stay unresponsive to touch until you turn FGA off.
I obviously know that this is a low-priority issue, and honestly it's probably on Google's side but it's nice to let everyone know it happens since some folks might want to try the beta out.
Upon further look I'm unsure if FGO even manages to recognize the screen. 

**Video**

[YouTube](https://youtu.be/GEPgW8eJAGc)
(notice that screen taps are on, so you can see me tapping everywhere to no effect)

**Device Info:**
 - Device model: Pixel 4 XL
 - Screen size: 1440 x 3040
 - Android Version: 12 Beta 2 - Clean Flash
 - RAM: 6GB

Thank you for your hard work programming this extremely useful app.

**Comment by MathewSachin** [comment]
Android 12 will generally block application overlays. See https://developer.android.com/about/versions/12/behavior-changes-all#untrusted-touch-events

**Comment by sixtht** [comment]
are you aware if it could be bypassed with root?

**Comment by MathewSachin** [comment]
The page I linked above has an option to bypass this with ADB.

See https://developer.android.com/about/versions/12/behavior-changes-all#test-untrusted-touch-events

**Comment by sixtht** [comment]
I apologize, I've only tried the first one and it failed but now that I allowed all apps it works.
> adb shell am compat disable BLOCK_UNTRUSTED_TOUCHES com.mathewsachin.fategrandautomata.debug

Returns:
>Cannot override a change on a non-debuggable app and user build.

But
>adb shell settings put global block_untrusted_touches 0
Works perfectly

Thank you.

**Comment by Kobata** [comment]
After reading the documentation on what causes the touch blocking, and a quick local test:
https://github.com/Fate-Grand-Automata/FGA/blob/master/app/src/main/java/com/mathewsachin/fategrandautomata/accessibility/ScriptRunnerUserInterface.kt#L92-L102

The highlight overlay is the part that causes it, as the button doesn't have the no-touch flag for obvious reasons. (It appears to always be added even if it's not being used)

This can be avoided by setting `alpha` sufficiently low in that layout: the default maximum is apparently `0.8f`, but it's configurable by the OEM so `InputManager.getMaximumObscuringOpacityForTouch()` also exists.

**Comment by chaoticnote** [comment]
I'm going to need a tutorial on how to use ADB. I've gotten to the point where I've downloaded Android Studio and now I'm stuck.

**Comment by gakiloroth** [comment]
I followed this and it worked for me:

https://www.howtogeek.com/125769/how-to-install-and-use-abd-the-android-debug-bridge-utility/

I didn't have to download android studio, just the sdk tools zip

**Comment by chaoticnote** [comment]
Thank you, gakiloroth. I'll use this when I try again later.

**Comment by decentblack** [comment]
I used this video guide

https://www.youtube.com/watch?v=vr0GLIufzkM

Pretty simple, took me 15 minutes. After I set it up I ran the command sixtht posted above and FGA works now. (I did have to write the command as ".\adb shell settings put global block_untrusted_touches 0" because maybe Windows Powershell is different somehow.

**Comment by chaoticnote** [comment]
Thank you, decentblack. Both the video and that article helped immensely!

**Comment by StateRoute67** [comment]
...I did everything in those guides, where the hell do I put the command in lol? I put it into the command prompt and now I don't even see the usual FGA play button on the lower left when running the app + FGO.

**Comment by decentblack** [comment]
It sounds like you put the command in the right place, I don't know why the play button disappeared.

**Comment by StateRoute67** [comment]
No clue why it happened, I updated FGA and then it worked!

**Comment by Pendalton** [comment]
I've downloaded ADB, used both commands :
`adb shell am compat disable BLOCK_UNTRUSTED_TOUCHES com.example.app` 
and
`adb shell settings put global block_untrusted_touches 0`
and now, I can use my phone while FGA is running, nice. BUT : whenever I try to start a script, the icon turns red, and it does nothing. Using the debug mode, i can see that the app only recognizes the bottom left corner, the Master AP/XP bar and stuff.

What does the red icon mean? How can I fix it?

**Comment by MathewSachin** [comment]
> After reading the documentation on what causes the touch blocking, and a quick local test: https://github.com/Fate-Grand-Automata/FGA/blob/master/app/src/main/java/com/mathewsachin/fategrandautomata/accessibility/ScriptRunnerUserInterface.kt#L92-L102
> 
> The highlight overlay is the part that causes it, as the button doesn't have the no-touch flag for obvious reasons. (It appears to always be added even if it's not being used)
> 
> This can be avoided by setting `alpha` sufficiently low in that layout: the default maximum is apparently `0.8f`, but it's configurable by the OEM so `InputManager.getMaximumObscuringOpacityForTouch()` also exists.

As per the documentation, `TYPE_ACCESSIBILITY_OVERLAY` windows shouldn't have this problem. Try changing highlight overlay type to this.
I ~~luckily~~ don't have Android 12 yet to try this out.

**Comment by Kobata** [comment]
`TYPE_ACCESSIBILITY_OVERLAY` causes the app to crash with
```
     Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:1159)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:399)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:133)
        at com.mathewsachin.fategrandautomata.accessibility.ScriptRunnerUserInterface.show(ScriptRunnerUserInterface.kt:160)
        at com.mathewsachin.fategrandautomata.accessibility.ScriptRunnerService.onCreate(ScriptRunnerService.kt:198)
```

I *think* to make it work the whole UI would have to be moved into the actual `AccessibilityService` (i.e., `TapperService`), plus maybe some messing with contexts. That's a bit of a giant mess to attempt to test, however.

**Comment by MathewSachin** [comment]
@Kobata you won't really need to move the whole UI. Try passing TapperService instance instead of application context to the highlight view.

https://github.com/Fate-Grand-Automata/FGA/blob/66437a641e5dc14e273917b16dddd858baffd3c6/app/src/main/java/com/mathewsachin/fategrandautomata/ui/highlight/HighlightManager.kt#L17

Considering how messy the accessibility code I've written already is, I don't think this is as bad.

I think this should work.
FGA used to have accessibility overlays when it was first written, then moved to application overlay since accessibility overlays show up even on the lock screen. Highlight view won't show up on lockscreen anyway so should be fine.

**Comment by Kobata** [comment]
Alright I'm gonna have to give up on trying to get that to work for now, it's either complaining `TapperService.instance` is null or, if I get it into a debugger and it goes slow enough to not get that, the same token thing.

**Comment by MathewSachin** [comment]
@Kobata For the Accessibility service being null, the DI scope for HighlightView needs to be changed from Singleton to ServiceScoped.
For the token error, the window manager should be made using the Accessibility service context.

I went ahead and made the changes. PR: #939
It works fine on Android 11, can you verify if this works on 12?
