### ISSUE TITLE
Doesn't work on Bluestacks and Nox

### ISSUE THREAD

**Issue by DekaSama** [Fate-Grand-Automata/FGA#740]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
So. This is sort of a weird situation. 

First off, on mobile I was able to install the apk perfectly fine with no issues. However . . . This time for some reason I couldn't find the play button or any other way to start the farm like I normally would. FGA has never given me issues before now, so I thought maybe I should just go back to using Nox. So . . . I did. 

But then things got worse. 

I tried to install the apk and got told it was "corrupt" and even tried to install it from the appstore (I saw it there with the old buster icon, but it wouldn't let me download it.) I tried sending the apk that I installed on my phone and it was apparently "Corrupt" too. 

This seriously sucks. I hope someone knows what's happening-

**Screenshots**
![ugh](https://user-images.githubusercontent.com/86207129/122688306-81312980-d1e9-11eb-9609-78f10056d7ae.PNG)

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON
Recording functionality is available within the app in `More options`.

I have no recordings, but if more info is needed then I can probably get it.

**Device Info (please fill at-least 'Device model'):**
PHONE:
 - Device model: [OnePlus 8 5G]
 - Screen size: [6.55"]
 - Android Version: [Android 11]
 - RAM: [8 GB]

And

NOX (PC)

(Not really sure what info you would need on my PC. It's a high range, pretty powerful gaming PC but besides that let me know what other info might be needed.)

**Comment by reconman** [comment]
From the Running on Emulators help page:

> Make sure you're using Android 7 version of these emulators

So on your phone you started the FGA service, went to FGO, but the play button is not shown?

**Comment by DekaSama** [comment]
So, I am running on Androif 7 with Nox. I've used FGA with it before even

**Comment by MathewSachin** [comment]
After seeing #748, I assume you had switched from 32-bit Nox to 64-bit Nox?

**Comment by DekaSama** [comment]
Funny enough, I just used the installer as normal! I wouldn't be shocked if it just installed a 64 bit version. Any idea how I can get the 32 bit one? I can't seem to see an option on the installer. 

> After seeing #748, I assume you had switched from 32-bit Nox to 64-bit Nox?

**Comment by MathewSachin** [comment]
How did you get it to install? Maybe that could give some hint.

**Comment by DekaSama** [comment]
> How did you get it to install? Maybe that could give some hint.

I simply went to the site and installed the installers as normal. It didn't give me any options as far as versions, and just in case, I went ahead and installed the older versions thinking that might help. 

But nerp— 

Here's a better question. Do you use FGA Canary on an Emulator? And if so, does it work for you?

**Comment by MathewSachin** [comment]
Yeah, it works on both Nox and Bluestacks. Though I haven't updated both Nox and Bluestacks in a while.

**Comment by MathewSachin** [comment]
> Funny enough the older version works just fine.

> just in case, I went ahead and installed the older versions thinking that might help

I'm kinda confused. Does older version work or not? If it did, can you tell the version number from Android's app info menu?

**Comment by DekaSama** [comment]
> Yeah, it works on both Nox and Bluestacks. Though I haven't updated both Nox and Bluestacks in a while.

Could you tell me what versions you use? I might be able to get it to work on em~!

**Comment by DekaSama** [comment]
> > Funny enough the older version works just fine.
> 
> > just in case, I went ahead and installed the older versions thinking that might help
> 
> I'm kinda confused. Does older version work or not? If it did, can you tell the version number from Android's app info menu?


The original issue was that it wouldn't install, but now for some reason I have no issues installing it on anything that isn't the most recent version of NOX. 

Now every time I do install it, pressing the play button makes the whole app crash. As far as the version numbers, that'll have to wait a few hours- (at work.)

**Comment by MathewSachin** [comment]
> installing it on anything that isn't the most recent version of NOX.

I updated to the latest version of Nox and yeah, it doesn't install now. 😞

> Now every time I do install it, pressing the play button makes the whole app crash.

Wait, this sounds familiar. Are you running Bluestacks on Windows? 

> Bluestacks on Windows needs extra steps
Change to Compatibility Graphics Engine:
>- Open Bluestack's settings
>- Go to Engine tab.
>- Set Graphics Engine to Compatibility.
>- Save settings and Restart Bluestacks.

Also, check that the Bluestacks instance is 32-bit. 64-bit instances don't work by default (#623).

**Comment by DekaSama** [comment]
> > installing it on anything that isn't the most recent version of NOX.
> 
> I updated to the latest version of Nox and yeah, it doesn't install now. 😞
> 
> > Now every time I do install it, pressing the play button makes the whole app crash.
> 
> Wait, this sounds familiar. Are you running Bluestacks on Windows?
> 
> > Bluestacks on Windows needs extra steps
> > Change to Compatibility Graphics Engine:
> > 
> > * Open Bluestack's settings
> > * Go to Engine tab.
> > * Set Graphics Engine to Compatibility.
> > * Save settings and Restart Bluestacks.
> 
> Also, check that the Bluestacks instance is 32-bit. 64-bit instances don't work by default (#623).

What version did you use that fga canary worked on? Also, I just double checked and I ran everything the way it said to. 

As far as version numbers, I tried using Bluestacks 5, Nox 7.0.1.2, 7.0.1.0, and 6.6.1.2. 

If it's not installation issues, It crashes when trying to use it. If it's not that, the older versions of Nox display nothing but a black screen when trying to run Android 7 Instances.

**Comment by DekaSama** [comment]
If anyone else has anything helpful to bring, that'll be great---

**Comment by MathewSachin** [comment]
I couldn't get canary to work on Bluestacks 5, but the UI update I'm working on right now works fine on it.
You can download that APK from this page: https://github.com/Fate-Grand-Automata/FGA/actions/runs/992780623

**Comment by DekaSama** [comment]
> I couldn't get canary to work on Bluestacks 5, but the UI update I'm working on right now works fine on it.
> You can download that APK from this page: https://github.com/Fate-Grand-Automata/FGA/actions/runs/992780623

Soooooooo

I installed the APK and gave it a few tests and the good news is it worked. 

Until I closed Bluestacks and opened it back again for more testing. 

Now for some reason, it crashes when I try to start the bot, not to mention the app will randomly "lose" accessibility even when it says it has it in the phone settings. Really weird stuff.

**Comment by MathewSachin** [comment]
64-bit Bluestacks didn't work before either. See #623.
I've confirmed that 32-bit works fine, at least with FGO NA.
Nox not working will be tracked in #748.
