### ISSUE TITLE
Script randomly skips waves

### ISSUE THREAD

**Issue by advancedorange** [Fate-Grand-Automata/FGA#741]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
A few days ago I switched to a new node to farm and created a new script, but this script does not what its supposed to do.
Most of the time the script for wave 3 gets activated on wave 2, sometimes the script even executes the steps for wave 2 on the second enemy on the first wave, followed by the steps for wave 3 on the third one (still wave 1). One time this was happening I think I noticed FGA trying to tap the skill for wave 2 right after it pressed the attack button for wave 1 (before the cards even popped up).
I previously tried to find a solution on the FGO reddit to this problem, but nobody could help me solve it.

Script: > i h g1 d ,#, f 5 ,#, g1 i h k1 c 4 ,#, 
Party: Summer Scathach, Yu Meiren, Waver 
Node: Fallen Babylon
Server: NA
Link to reddit: [Here](https://old.reddit.com/r/grandorder/comments/nyvt9g/help_and_question_thread_june_13_2021/h29ir3m/ )

**Screenshots**
x

**Video**
x

**Device Info (please fill at-least 'Device model'):**
 - Device model: [Honor 8]
 - Screen size: [1920x1080]
 - Android Version: [Android 8 (?)]
 - RAM: [4GB]

**Comment by MathewSachin** [comment]
There's a `Stage Counter SImilarity` option in `More-options/Fine-tune`.
Try reducing that to 75%.
