### ISSUE TITLE
Script not running on LG G7 

### ISSUE THREAD

**Issue by CapYuno** [Fate-Grand-Automata/FGA#745]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
No auto skill option. Defaulted at battle only with no option for auto summon etc. Script just doesn't run tried different combos installed reinstalled. Restarted phone. Went through troubleshooting turned of game mode. Nothing seems to get the script to run.

**Screenshots**
![Screenshot_20210623-120528](https://user-images.githubusercontent.com/86341130/123051566-5cbc9380-d41b-11eb-8091-4cb9060929b8.png)
![Screenshot_20210623-120306](https://user-images.githubusercontent.com/86341130/123051574-5f1eed80-d41b-11eb-965e-f1fc6ff828cc.png)
![Screenshot_20210623-120257](https://user-images.githubusercontent.com/86341130/123051575-5fb78400-d41b-11eb-9f58-a91e3d66fb2d.png)
![Screenshot_20210623-120253](https://user-images.githubusercontent.com/86341130/123051577-60501a80-d41b-11eb-8eec-4c3711f58c54.png)
![Screenshot_20210623-114635](https://user-images.githubusercontent.com/86341130/123051580-60e8b100-d41b-11eb-8790-a9e8804b7f7e.png)

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON
Recording functionality is available within the app in `More options`.

**Device Info (please fill at-least 'Device model'):**
 - Device model: [LG G7 ThinQ]
 - Screen size: [1560x720]
 - Android Version: [Android 10.0]
 - RAM: [4GB]

**Comment by MathewSachin** [comment]
I'm pretty sure it's the LG Game mode feature of `Disable alerts when in a game` preventing the app from opening the dialog before starting scripts.
I don't really see a case where this would happen otherwise. Check those settings again.
