### ISSUE TITLE
Script not working properly Card type issue etc.

### ISSUE THREAD

**Issue by CapYuno** [Fate-Grand-Automata/FGA#749]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**

Card Type issue, the script can't pick up on anything it just keeps running as shown in video links and screenshot links below. It happened out of nowhere after a nice 5hr farm. I tried reinstalling clearing checking if any battery saver is stopping but non of that so Idk what to do.
Playing on NA. Saw the TW card type issue and it seemed developers fixed that so I couldn't really take any fix from that repos 

**Screenshots**
http://imgur.com/gallery/NG3vx9K

**Video**
http://imgur.com/gallery/GQfhveQ
http://imgur.com/gallery/3UmAnv8
http://imgur.com/gallery/B2VD286

**Device Info**
 - Device model: LG G7 ThinQ
 - Screen size: 2340x1080
 - Android Version: 10.0
 - RAM: 4GB

**Comment by MathewSachin** [comment]
How did you get the script to work? i.e. how did you solve #745?
I'm not really sure, but could be related I guess.

**Comment by CapYuno** [comment]
> How did you get the script to work? i.e. how did you solve #745?
> I'm not really sure, but could be related I guess.

Turned out a game launcher had alerts turned so I turned off both the tools and launcher.

**Comment by CapYuno** [comment]
For future ppl who have the same issue. The solution I have found so far is too force stop the app. Once force stopped leave it for some time a hour at most or so. Open the app give it all permissions. Then delete the old presets for combat and then run the game again! Should be fine worked for me. Still problems occur sometimes but this fixes it for now. Also the script can't select start quest but other than that it's fine mostly.
