### ISSUE TITLE
Battle script stop behaving properly after 2nd wave and onward

### ISSUE THREAD

**Issue by CountDookie** [Fate-Grand-Automata/FGA#752]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
Hello, I've noticed that this is not a new bug, as there have been similar issues posted here before, however I cannot find a working solution for me. I have a script to use Melt against Rainbow Town in Shinjuku. However, the script falls out of place after wave 1 and would stop pressing NP and the required skills at all. I just downloaded FGA today so I'm confident that I have the latest build. Attached below is my detailed script along with my fine tune specification.

My party : Double Castoria, Melt Summer

Node : Rainbow Town (Shinjuku)

Server: JP

*UPDATE*: According to issue 579, I've tried cranking up Stage Counter Similarity to 100, which has resolved the NP issue, however Mystic Code skills are still not properly used (This is fine for this particular script, however some MC-dependent teams will pose problems so I think it's worth posting the issue). 

Here are the two issues that I would like to use as references.
https://github.com/Fate-Grand-Automata/FGA/issues/714
https://github.com/Fate-Grand-Automata/FGA/issues/579

**Screenshots**
![image](https://user-images.githubusercontent.com/43048825/123886894-a3aa0c00-d97a-11eb-8d51-0c5cbc5f9353.png)
![image](https://user-images.githubusercontent.com/43048825/123886919-b58baf00-d97a-11eb-99bd-cf5c579c6952.png)
**Video**
Here's a video of the script in run : 
https://streamable.com/jg5jbr

**Device Info (please fill at-least 'Device model'):**
 - Device model: Samsung Galaxy S8 (running on BlueStacks 5 Emulator)
 - Screen size: [e.g. 1600x900]
 - Android Version: Android 7.1
 - RAM: 4GB ?

**Comment by MathewSachin** [comment]
You've placed the PLAY button over the place that is used to detect the location of Master skills and Stage counter. ![image](https://user-images.githubusercontent.com/10654537/123915519-37d99a80-d99e-11eb-9846-111ec61433f1.png)
So, the script isn't able to detect wave changes and the location of master skills. Move the button to somewhere else.

Once you've done that, reset the Stage Counter Similarity setting. 100% forces you to use 3T setups.
