### ISSUE TITLE
FGA stops at support screen even though it can still choose the battle outside

### ISSUE THREAD

**Issue by creep1812** [Fate-Grand-Automata/FGA#755]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
Include steps to reproduce the error if required

**Screenshots**
It is recommended that you at-least add one screenshot of FGO running on your device.

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON
Recording functionality is available within the app in `More options`.

**Device Info (please fill at-least 'Device model'):**
 - Device model: [e.g. Xiaomi Redmi 4]
 - Screen size: [e.g. 1280x720]
 - Android Version: [e.g. Android 7.1]
 - RAM: [e.g. 3GB]
![Screenshot_20210630-183829](https://user-images.githubusercontent.com/75061348/123954336-7ab56580-d9d2-11eb-87e4-e4ed676c7adf.png)
Device: Joy4

**Comment by MathewSachin** [comment]
Tracking in #756
