### ISSUE TITLE
Friend Summon

### ISSUE THREAD

**Issue by Aghandor** [Fate-Grand-Automata/FGA#765]
Hi, since the update that changed the Interface of the app (and its icon from a buster card to a quick card), I can't seem to find the Friend Summon (and Lottery) mode for the script.

Where they removed ? If yes, would it be possible to implement those again ?

**Comment by ngtunganh123** [comment]
same question, friend summon also lotto open all gone
on top of that, nothing working at all. Is there a way to get older version ?

**Comment by reconman** [comment]
Just press the play button while you're on the summoning screen.

It will show up as option.
