### ISSUE TITLE
Play and Stop Button changes

### ISSUE THREAD

**Issue by Ashtonio** [Fate-Grand-Automata/FGA#768]
Hey there, liking the redesign that came with the new update, but was wondering if it was possible to have the play and stop button above one another like in the previous version instead of to the side, just that it triggers my autism that the play but obscures parts of the game, I've added a screenshot as an example. Thanks. 
![Screenshot_20210707-170710_FateGO](https://user-images.githubusercontent.com/38806485/124715049-df7a3e00-df45-11eb-8efc-5794722d82ff.png)

**Comment by MathewSachin** [comment]
> play but obscures parts of the game
Well, it only shows up when paused, so I don't feel like obscuring the game matters.

Instead, if it is was vertical, you literally cannot use it on JP (See #756).

**Comment by reconman** [comment]
I would personally also prefer if they were vertically stacked.

**Comment by MathewSachin** [comment]
I don't like vertical stacking. I eventually want to make it a horizontal button group.

Something like:
![image](https://user-images.githubusercontent.com/10654537/124747234-5a8c2600-df3f-11eb-9ab1-65203a27df18.png)

**Comment by MathewSachin** [comment]
#771 is what I wanted it to be.
