### ISSUE TITLE
App not selecting script correctly

### ISSUE THREAD

**Issue by arisinwonderland** [Fate-Grand-Automata/FGA#773]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

**Describe the bug**
App isn't recognizing which screen it's on and so isn't choosing the right script. When selecting the Play button on the FP Summon screen, the device still opens the combat script selection menu.

**Screenshots**
![2021-07-08 02_25](https://user-images.githubusercontent.com/16226401/124873002-ea5bbf80-df93-11eb-91a6-4c215222b148.png)

**Video**
https://youtu.be/brFEpJvwqr4

**Device Info (please fill at-least 'Device model'):**
 - Device model: LG Aristo 2 LM-X210MA
 - Screen size: 640x360
 - Android Version: Android 8.1.0
 - RAM: 2GB

**Comment by MathewSachin** [comment]
The device specs seem too low. Have you tried out if Battle scripts work fine?

**Comment by arisinwonderland** [comment]
Just checked. The script isn't running, but the debug zones look to be about in the right place. [Video here](https://youtu.be/z3lwCgOh7tA).

**Comment by reconman** [comment]
The debug areas do seem to be correctly placed but you're using something other than FGA to record the screen, which makes FGA only see a black screen.

A phone reboot made FGA work again in those cases.

The record function is also in the Advanced options.

**Comment by arisinwonderland** [comment]
Alright, well, I'm really not sure why that worked, especially since I restarted the phone before I did any of this and didn't even have the recording app installed until after I encountered the problem, but restarting my phone did fix both issues. I guess all's well that ends well. Thanks.
