### ISSUE TITLE
Run limit does not always update to user input value

### ISSUE THREAD

**Issue by reconman** [Fate-Grand-Automata/FGA#774]
If you set the Run limit to 2 and then start, it will show a toast of "Ran 0 out of 2 time(s)" when it selects the quest node.

If you stop the script, go back to the quest selection screen, press play and change the number to 1, it will also show a toast of "Ran 0 out of 2 time(s)".

If you then stop the script, it will say 0/2 in the Script Stopped screen and when you press the play button again, the run limit is set to 2 in the UI window.

Weirdly it only affects the Run limit but not the Mat limit.

**Comment by MathewSachin** [comment]
It seems to happen with Mat limit too and only for the value of 1 in both cases.
1 is the default value for both, so I think it's related to that.

**Comment by MathewSachin** [comment]
The problem happens at both values of 1 and 999. So, it's related to the value range of the stepper instead of the default value of the setting.
I don't think it's Compose's fault. The code for 'hold to continuously increment/decrement' is kind of complex and I'm not sure if I'm doing it right.

**Comment by MathewSachin** [comment]
Single presses are working fine, but, holding till the end of the value range doesn't update the value.
