### ISSUE TITLE
About endless bonus card pool

### ISSUE THREAD

**Issue by fuckgod123** [Fate-Grand-Automata/FGA#778]
The before version of the endless lottery ticket can be used until it is not available. Now this version can only draw 300 times and it stops, and the prize pool needs to be updated manually.

**Comment by reconman** [comment]
Sorry but your text is incomprehensible and should be a bug report.

**Comment by the3dsandwich** [comment]
I think you missed the "limit update" toggle. (forgot the name but it's the only toggle that's on by default)

Turn it on, then FGA won't update boxes. Turn it off, then FGA will draw lottery, update boxes until present box is full.
