### ISSUE TITLE
Xioami 10t Lite Battle Commands not working

### ISSUE THREAD

**Issue by w-san** [Fate-Grand-Automata/FGA#781]
Before opening an issue:
- [Y ] I tested the latest release
- [Y ] I looked at other issues (even the closed ones)
- [Y ] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [Y ] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
Battle Scripts not worrking or not recognising position? Was working with the previous version settings have tried in fullscreen mode no battery restrictions. and ignore notch calculation both on and off

**Screenshots**
https://imgur.com/a/8w7T3gI

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON
Recording functionality is available within the app in `More options`.

 - Device model: [Xiaomi mi 10T Lite 5G]
 - Screen size: [2400 x 1080 pixels]
 - Android Version: [11 RKQ1.200826.002]
 - RAM: [6GB]

**Comment by w-san** [comment]
im unsure if i filled the information in correctly i can make a video if needed

**Comment by MathewSachin** [comment]
That screenshot was sufficient. A new release will be up in a while with the fix.

**Comment by w-san** [comment]
> 
> 
> That screenshot was sufficient. A new release will be up in a while with the fix.

thank you for your hardwork.

**Comment by MathewSachin** [comment]
It's the same as the Accessibility problems Xiaomi phones have
See #314 for possible solutions from your side. Nothing can be done regarding it from our side.

**Comment by reconman** [comment]
Had a similar problem on OnePlus 9 and solved it by deactivating some battery saving options and locking FGA in the app switcher.

**Comment by w-san** [comment]
thank you
