### ISSUE TITLE
Problem when running on 20:9 phone

### ISSUE THREAD

**Issue by rizqee** [Fate-Grand-Automata/FGA#784]
Before opening an issue:
- [ v] I tested the latest release
- [ v] I looked at other issues (even the closed ones)
- [ v] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [ v] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
so there is a bug when i tried the current release(cannary-1398) when using my phone, a samsung galaxy s20 FE that has a screen ratio of 20:9. when using it on the na server it runs smoothly but when i was playing the jp server it doesn't even want to select the support servant.

**Screenshots**
It is recommended that you at-least add one screenshot of FGO running on your device.

**Video**
below is the video link of the bug in action
https://youtu.be/o3gwlqOSjc0

**Device Info (please fill at-least 'Device model'):**
 - Device model: samsung galaxy s20 FE
 - Screen size: 1080 x 2400 pixels, 20:9 ratio
 - Android Version: 11
 - RAM: 8GB

**Comment by MathewSachin** [comment]
After a recent update to FGO JP, it fills the entire screen including the notch (#756 shows that on another Samsung phone). The latest version of FGA is calibrated for that.
But, on your phone, there are black bars on both sides of the screen. The left one should be the notch and the other one might be for gestures. FGA would only work if you get rid of those black bars. Maybe try making FGO JP a fullscreen app.

![youtube-screenshot-fgabugon209phone](https://user-images.githubusercontent.com/10654537/125779162-bebb5e6e-9bdc-47bb-afdd-2ae2960adeb4.jpg)
