### ISSUE TITLE
App does not detect 'Next' Button after finishing battle (KR Server)

### ISSUE THREAD

**Issue by Yoshinyong** [Fate-Grand-Automata/FGA#785]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
I Play KR Server on an app-player. FGO KR recently had an update which included some decrease in delay and some minor changes in UI. Since the update the FGA had trouble making the scripts work properly which I could fix by tweaking the delays but I have no idea how I can fix the part where the app cannot find the 'Next' Button on the item-drop screen.  If I press on the 'Next' Button below myself the app normally continues looping the script but unless I don't its stuck in that screen forever. Using the debug mode, the app seems to know that the bond-level screen has appeared but I don't understand why it does not find the item-drop screen.

**Screenshots**
![Screenshot_20210725-110612](https://user-images.githubusercontent.com/76123418/126885457-02bac761-23c5-4c67-b42e-1418c1c1defd.png)

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON
Recording functionality is available within the app in `More options`.

**Device Info (please fill at-least 'Device model'):**
 - Device model: [LDPlayer]
 - Screen size: [1600x900]
 - Android Version: [Android 7.1.2]
 - RAM: [4GB]

**Comment by MathewSachin** [comment]
> some minor changes in UI

Nope. I've heard that it's the wide-screen update which came while ago to JP.
Since this issue only caters to 16:9 devices, I'm closing it and tracking this problem in #786 which is more general.

**Comment by Yoshinyong** [comment]
Understood.

**Comment by Yoshinyong** [comment]
> > some minor changes in UI
> 
> Nope. I've heard that it's the wide-screen update which came while ago to JP.
> Since this issue only caters to 16:9 devices, I'm closing it and tracking this problem in #786 which is more general.

Understood. Thanks.
