### ISSUE TITLE
Application problem due to UI change of Korean server

### ISSUE THREAD

**Issue by kbg0104** [Fate-Grand-Automata/FGA#786]
Before opening an issue:
- [ check ] I tested the latest release
- [ check ] I looked at other issues (even the closed ones)
- [ check ] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [ check ] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
First, I apologize for my poor English.
The application does not work properly as the Korean server's user interface becomes the same as the Japanese server.
There are problems such as the location of the touch and the inability to recognize it.

**Device Info (please fill at-least 'Device model'):**
 - Device model: [Most devices (Author is using Galaxy 21)]
 - Screen size: [Most display sizes (Author's device display is 2400x1080)]
 - Android Version: [Most Android versions (Author is using Android 11)]
 - RAM: [Most Capacity (Author is using 8GB)]
 - Most Korean server users are experiencing this problem.

**Comment by MathewSachin** [comment]
> Korean server's user interface becomes the same as the Japanese server.

There might be differences. I don't play on KR server, so please provide some screenshots so we can see what changed.

**Comment by kbg0104** [comment]
I'm attaching a video.
Please understand that I am forced to post a link to the Korean community.
https://gall.dcinside.com/mgallery/board/view/?id=mfgo&no=3315267&page=1
If you can't see two videos, I can send you the video myself.

The first video shows that the application does not come into the dungeon.

The second image shows that the macro originally woven with a double scadi system is not working properly.

**Comment by kbg0104** [comment]
Patches such as speed/UI applied on the 5th anniversary of the Japanese server have been applied to the Korean server.
In this process, the application seems to be a bug caused by mistake for UI of the existing Korean server.

**Comment by item4** [comment]
FGA build 1402
Galaxy Note20 Ultra 5G
Android 11
Accessibility Enabled
Set as Fullscreen mode app


https://user-images.githubusercontent.com/559952/126946944-3fd82b38-b4c0-4512-980b-d16fc6484e87.mp4


https://user-images.githubusercontent.com/559952/126946955-6b3c3ac1-8b33-4240-beb6-021a48a4237c.mp4


https://user-images.githubusercontent.com/559952/126946957-304efbe7-da1c-493a-af7d-ee6f6e623e0e.mp4

**Comment by item4** [comment]
FGA build 1402
Galaxy Note20 Ultra 5G
Android 11
Accessibility Enabled
Set as Fullscreen mode app
Flag on for ignore camera hole -> no effect
Set as JP server


https://user-images.githubusercontent.com/559952/126954505-dd5d366d-0cc3-45ee-b35b-cd58689b414b.mp4

I guess we might set flag on for KR server to NewUI (wide)

**Comment by item4** [comment]
@MathewSachin Can you check #787 ?

**Comment by Yoshinyong** [comment]
Btw as a temporary solution until this issue is fixed, setting stage counter similarity to 100% helps at least executing the script but it won't do auto-battle and only stick to the script. Also it doesn't know that the battle has finished so you kinda have to press on the 'Next' Button on the item-drop screen yourself to loop the script. This mostly helps EXP/QP farming scripts.

**Comment by MathewSachin** [comment]
@Yoshinyong that only applies to 16:9 devices. Things are different for other resolutions.

**Comment by Yoshinyong** [comment]
@MathewSachin Just in case since some ppl also run it on app-players which are mostly 16:9

**Comment by MathewSachin** [comment]
@Yoshinyong Ah, then that should be mentioned or others who're not using 16:9 would get confused.

**Comment by Yoshinyong** [comment]
@MathewSachin Ye you are right. Updated the context.
