### ISSUE TITLE
16:9 Screen Master Skills Click Miss

### ISSUE THREAD

**Issue by kbg0104** [Fate-Grand-Automata/FGA#789]
Before opening an issue:
- [ check ] I tested the latest release
- [ check ] I looked at other issues (even the closed ones)
- [ check ] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [ check ] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
On a 16:9 screen, all actions except the master skill are perfect. however, when using the master skill, the touch faces a strange place.

If the resolution was changed to 19:9 ratio or 20:9, it worked normally.

**Video**

https://user-images.githubusercontent.com/36321971/127199903-e5eb57e1-e907-4578-b05b-6eb9f5a96198.mp4

The video is the result of testing at 1920x1080.

**Device Info (please fill at-least 'Device model'):**
 - Device model: [Bluestacks 5 32bit]
 - Screen size: [1920x1080], [1520x720]
 - Android Version: [Android Nougat]
 - RAM: [4 GB]

**Comment by Munung** [comment]
https://youtu.be/_WFeS6AjRFc
When running at 1520x720 resolution

**Comment by MathewSachin** [comment]
Seems like the `battle_menu.png` image added yesterday is wrong. It works on non-16:9 devices just because the fallback value matched.

**Comment by Yoshinyong** [comment]
The Stage Counter also seems to be off aswell by far left. But I guess this will be fixed along this issue?
![Cap 2021-07-28 16-23-05-115](https://user-images.githubusercontent.com/76123418/127339307-2e3ef438-305d-4679-8179-697296aa731c.jpg)
