### ISSUE TITLE
Can't install on Samsung A51

### ISSUE THREAD

**Issue by ReikutsuNeko** [Fate-Grand-Automata/FGA#792]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
I downloaded the latest Canary build-1404 and trying to install on my Samsung A51, but the app not installed
and ofc I already allowed installation from non play store too 😥

**Screenshots**
![Screenshot_20210728-235028_Package_installer](https://user-images.githubusercontent.com/33795863/127367325-bdc8b04c-4bb2-40ef-a01e-38b1af7ff5b0.jpg)

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON
Recording functionality is available within the app in `More options`.

**Device Info (please fill at-least 'Device model'):**
 - Device model name: Samsung A51
 - Device model: SM-A515F/DSN
 - Screen size: 1080x2400
 - Android Version: Android 11
 - One UI Version: 3.1
 - RAM: 8GB

**Comment by ReikutsuNeko** [comment]
so, I just noticed that the internal storage is almost full, and it's already fixed...

**Comment by reconman** [comment]
I wish Android had a few more detailed error messages.

The same message appears when the APK signature is different.

**Comment by ReikutsuNeko** [comment]
yeah true, I was so confused at first and just realized that my internal storage almost full a sec after I post this issue > <
