### ISSUE TITLE
Only Card on first turn

### ISSUE THREAD

**Issue by chicoon** [Fate-Grand-Automata/FGA#794]
Is possible on 1 wave use only attack cards?

**Comment by the3dsandwich** [comment]
In the command editor UI, just select attack, next turn/wave then set your 2nd turn/wave skills

**Comment by chicoon** [comment]
Isnt working
![Screenshot_20210729-092222](https://user-images.githubusercontent.com/65822700/127491022-65768605-1964-46cc-baa1-13466344e8e5.png)
When i start nothing happens

**Comment by reconman** [comment]
Without a video recording using the FGA recording function, we can't tell what's wrong.
