### ISSUE TITLE
Append Skills from JP breaks the support picker

### ISSUE THREAD

**Issue by jcdeoferio** [Fate-Grand-Automata/FGA#796]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

**Describe the bug**
Support picker no longer working with the Append Skills released for JP's 6th anniversary

**Screenshots** / **Video**
https://imgur.com/a/CSdZv4P

**Device Info (please fill at-least 'Device model'):**
 - Device model: BlueStacks Hyper-V 4.280
 - Screen size: 1920x1080
 - Android Version: Android 7.1.1
 - RAM: 4GB

**Comment by reconman** [comment]
Can you explain how that new feature works?

**Comment by jcdeoferio** [comment]
They added new unlockable passive skills for servants, S1 and S2 are the same for everyone, S3 differs per servant. JP news article is in here: https://news.fate-go.jp/2021/6th_anniversary/#ttlb_4 (section 4)

Skill details are in here: https://apps.atlasacademy.io/db/JP/servant/106 (Append Skills section)

Since S2 also increases the starting battery, people might request for filtering on these values too, but the values doesn't seem to be shown in the picker, I have to check for samples/screenshots of servants that had unlocked append skills.

**Comment by sleeping-player** [comment]
Wow this must be in pinned issue

**Comment by damfir** [comment]
It happen to me too..J tried untick/unselect all the "max skill" and it works

**Comment by MathewSachin** [comment]
Yeah, looks like Max skills won't work for JP for now.

**Comment by jcdeoferio** [comment]
Checked my friend supports. The Append skill levels are only available in the servant profile or in the party setup screen (it switches display between the primary skill and the append skill numbers). It will need a new flow to check for append skill numbers if there's plans to make filters for it.

**Comment by reconman** [comment]
Looks like the font size is still the same as before, but the positions of the 2nd and 3rd "10"s were moved to the left.

Maybe moving the X positions to the left for JP is enough?

**Comment by reconman** [comment]
Could anyone provide a 720p or higher screenshot? The one in the original comment is 476p.

**Comment by jcdeoferio** [comment]
Sorry about that, I was using the windows snipping tool. Updated the album with a higher res image. Direct Link: https://imgur.com/0AxWanN

**Comment by reconman** [comment]
Can you test [my attempted fix](https://github.com/Fate-Grand-Automata/FGA/suites/3383203715/artifacts/79751707)?

I'm not 100 % sure it works. If it doesn't, I would appreciate a video with debug mode on.

**Comment by jcdeoferio** [comment]
Looks like the fix is working!

Tested on a Oneplus 6t (2340 x 1080), don't have access to my bluestacks machine right now. I'll try out other devices tomorrow.

**Comment by jcdeoferio** [comment]
On a related note, how does game server=auto-detect work?

I had to set it to JP for the adjusted margins to work.

**Comment by reconman** [comment]
> On a related note, how does game server=auto-detect work?

The app checks for the name of the app that's currently in the foreground. On some devices or emulators that doesn't work correctly.

**Comment by Zero089** [comment]
> ¿Puedes probar [mi intento de corrección](https://github.com/Fate-Grand-Automata/FGA/suites/3383203715/artifacts/79751707) ?
> 
> No estoy 100% seguro de que funcione. Si no es así, agradecería un video con el modo de depuración activado.

I am having the exact same problem as who started the post.  The FGA does not elect a supporter.  
I downloaded this file that you say fixes it but nothing happens.  I am somewhat clumsy with technology and I do not know how to solve the problem

**Comment by reconman** [comment]
@Zero089 If the problem is getting the APK out of the ZIP, read this: https://www.lifewire.com/unzip-files-on-android-4178981

**Comment by reconman** [comment]
How does the screen look like when you use this button?

![image](https://user-images.githubusercontent.com/12360257/127852264-1c8d9d3b-2ae3-473e-8b30-d17c1e9523ab.png)

**Comment by jcdeoferio** [comment]
@reconman it apparently shows the append skill levels. https://imgur.com/PPSqO0g

**Comment by MathewSachin** [comment]
![Screenshot_2021-08-02-16-39-01-29_13e7a6b1087387188a64bd1592e629e3](https://user-images.githubusercontent.com/10654537/127852586-a698bcda-b945-4723-a8ae-4234aa429184.jpg)

If you press again, it keeps switching between both skills and append skills.

**Comment by jcdeoferio** [comment]
So additional parsing for the text/image beneath the command codes is needed

**Comment by reconman** [comment]
For now I would say look for the blue text, press the button to switch, and then check the skill levels.

**Comment by jcdeoferio** [comment]
Do you want me to log a separate feature request for filtering on the append skill levels?

**Comment by reconman** [comment]
Yes please, also I wonder why they reduced the image size for the skills but then didn't put all 6 skills on the same screen.

**Comment by ggrn** [comment]
Same here.
Device model: Galaxy S20U
![Screenshot_20210802-203750_FateGO](https://user-images.githubusercontent.com/16633130/127856294-50ecd146-e729-476f-ae38-7d83e027430c.jpg)
![Screenshot_20210802-203742_FateGO](https://user-images.githubusercontent.com/16633130/127856314-aa0eecc1-644e-43e8-8ffc-66c938caa21b.jpg)

**Comment by replicat** [comment]
> Yes please, also I wonder why they reduced the image size for the skills but then didn't put all 6 skills on the same screen.

I think they reduced the size of the skills so that they could squeeze the "Active Skills"/"Append Skills" text above them, so it is more about vertical space and not the horizontal space. But they could have totally put all 6 skills on the same view given the current alignment, and it would have made much more sense than giving us a button to switch between them... unless they are planning to add more features so they needed to reserve the space.

**Comment by replicat** [comment]
> Can you test [my attempted fix](https://github.com/Fate-Grand-Automata/FGA/suites/3383203715/artifacts/79751707)?
> 
> I'm not 100 % sure it works. If it doesn't, I would appreciate a video with debug mode on.

I am testing this build on LD Player 4.0.53 (1920x1080) and doesn't seem to be working. Here is a screenshot with debug mode on.
![dnplayer_vzrZGKHat9](https://user-images.githubusercontent.com/1373853/127865699-90a5211e-ec2d-49da-9609-983667614f12.png)

The updated positions of the skills look fine but the match is unsuccessful. So either the similarity check is wacky or the positions are off by a few pixels.

**Comment by reconman** [comment]
The biggest problem right now is that the new button switches between 3 modes: normal, append, and mixed.

I can't come up with a good way that doesn't waste several seconds trying to figure which mode is active.

**Comment by MathewSachin** [comment]
I would suggest to just adjust your PR for 16:9 (see screenshot above) and merge.
We can think about supporting append skills later. For now, lets assume the user made sure they are on regular skills view.

**Comment by reconman** [comment]
@replicat How about this build: https://github.com/Fate-Grand-Automata/FGA/suites/3400807105/artifacts/80326039

Does that fix your issue? I made the boxes a bit bigger.

**Comment by replicat** [comment]
> @replicat How about this build: https://github.com/Fate-Grand-Automata/FGA/suites/3400807105/artifacts/80326039
> 
> Does that fix your issue? I made the boxes a bit bigger.

@reconman Unfortunately no. I can see that the regions are a bit wider but they are still not matching correctly.
![dnplayer_OrSGq7Vrtj](https://user-images.githubusercontent.com/1373853/128105941-3597a174-27f5-4bb2-8342-f3d2f9e2fd0a.png)

I think this could be related to scaling of the [image](https://github.com/Fate-Grand-Automata/FGA/blob/master/app/src/main/assets/En/skill_ten.png) used in matching as the skill level number is now smaller.
I am afraid this could be a device specific problem. I am going to test this in another device and see if it works.

**Device Info:**
 - Device model:  LD Player 4.0.53
 - Screen size: 1920x1080
 - Android Version: Android 7.1.2
 - RAM: 4GB

**Comment by RainehDaze** [comment]
@reconman Same issue--the alignment is slightly off and it doesn't match skill numbers.

![Screenshot_2021 08 04_04 11 35 849](https://user-images.githubusercontent.com/7266470/128116753-efc6e48d-c6d1-4c05-bab2-ecf17f2d7df0.png)

**Device Info:**

- Device model: Bluestacks 5.1.110.1005
- Screen size: 2560x1440, also tested at 2560x1080 and 1920x1080
- Android Version: Android 7.1.2
- RAM: 4GB

**Comment by reconman** [comment]
@replicat I double checked and the font is still the same size as before.

I did however just now replace the previous skill 10 image with a better quality one. Please check the latest canary build.

**Comment by RainehDaze** [comment]
<img width="897" alt="Screenshot_2021 08 04_17 42 16 957" src="https://user-images.githubusercontent.com/7266470/128220896-7ae5eb3d-a1f0-4922-aee1-eb4c8108cf65.png">

Latest build, same issue. Not sure why--it's not like the smaller skill icons should be causing enough noise to matter?

**Comment by reconman** [comment]
@RainehDaze Can you check at 720p?

The only thing that comes to mind as a possible solution right now is reducing the required similarity, which is already at 68 %.

**Comment by reconman** [comment]
Turns out transparent images barely worked in the canary version, so I made the situation worse by providing better images.

I was able to find the ancient bug that prevented us from using transparent images and got a working version for JP with a similarity value of 99 % for 720p and 95 % for 1080p!

I also discovered that the font size in JP is indeed smaller than NA, but I didn't notice because the old skill 10 image had a really low pixel count.

My version at https://github.com/Fate-Grand-Automata/FGA/suites/3415604807/artifacts/80783770 seems to work, although I had a small hiccup regarding the stage counter check.

I would appreciate some early testing feedback.

**Comment by RainehDaze** [comment]
Tested it quickly on 1440p; didn't seem to have any problems with matching this time.

**Comment by RainehDaze** [comment]
Do agree on further inspection, though; it seems to have caused the stage counter check to go off (amongst other things). I've had skills not being used at the beginning of a battle and it trying to use skills whilst still transitioning between stages (thus missing skills). 

@reconman

**Comment by Pshfrk** [comment]
The support picker is working for me, too. Good work on finding and fixing that old bug c: !

Though I think I also got some trouble with the battle counter, Maybe it thinks it's the 2nd wave when it's the first one? Sometimes it clicks on a servant's portrait and pauses there, maybe it's also trying to match stuff during the loading screen? I attached some videos, Excuse how stuttery and laggy it is, my old cpu is struggling. I included the whole loading screen on the first to see if any of the matching that happens there tells you anything of value.

**How it is: Build 1432**
https://www.youtube.com/watch?v=G1fEIXZbKos

**How it was: Build 1426**
https://www.youtube.com/watch?v=ibZQosVo1kc 



**Device Info:**

    Device model: Nox 6.6.1
    Screen size: 1920x1080
    Android Version: Android 7
    RAM: 6GB

P.S. Idk anything about coding

**Comment by reconman** [comment]
Here's a more stable version which worked perfectly for 2 quest runs for me: https://github.com/Fate-Grand-Automata/FGA/suites/3425317851/artifacts/81086804

I would appreciate some testing again.

**Comment by RainehDaze** [comment]
@reconman Yeah, I think this one fixes the previous problem. Detects skill levels appropriately; doesn't use skills during stage transitions/lose track of stage number--went through an AP bar without incident.

**Comment by replicat** [comment]
> Here's a more stable version which worked perfectly for 2 quest runs for me: https://github.com/Fate-Grand-Automata/FGA/suites/3425317851/artifacts/81086804
> 
> I would appreciate some testing again.

@reconman I have run this for ~hour and is perfectly fine. Good work.

**Comment by Pshfrk** [comment]
Tested for ~1 hour as well, seems to be working fine, all 3T. It seemed a bit slower, but I assume to maintain accuracy? Might be a placebo effect, tho c: Thanks!

**Comment by jcdeoferio** [comment]
Tested 2 runs on 1080p Bluestacks. Didn't notice any issues. Will try on a widescreen device later.

**Comment by ggrn** [comment]
@reconman Tested on V30(2880 x 1440). It works nice! Thanks!

However, it does not work on the widescreen device S20U (3200 x 1440). 
May I ask if this issue should be opened as a new issue?
![S20U](https://user-images.githubusercontent.com/16633130/128453865-b54f11af-bd6c-4fad-818f-cbb67fb62125.jpg)
![S20U_COMP1](https://user-images.githubusercontent.com/16633130/128454158-081b39f6-cb88-4331-8467-cd00a2d84a1a.png)

**Comment by jcdeoferio** [comment]
Yup. Also getting issues with widescreen. https://imgur.com/a/Da1ZApX

Oneplus 6t 1080x2340

**Comment by egzn** [comment]
> 
> 
> Here's a more stable version which worked perfectly for 2 quest runs for me: https://github.com/Fate-Grand-Automata/FGA/suites/3425317851/artifacts/81086804
> 
> I would appreciate some testing again.

Been running this for 6 hours or so (200 runs so far), no issues found on my Samsung Galaxy Tab S7+

**Comment by Alphacentariprime** [comment]
Having issues where the skills are being used on the wrong servant with the current version on the Samsung galaxy s10+

**Comment by sekir1488** [comment]
Still have this issue after patch. Samsung S10+

**Comment by reconman** [comment]
@sekir1488 I'm gonna need more info, at least a video with debug mode on.

**Comment by jcdeoferio** [comment]
@reconman was this incorrectly closed by the pull request? There were still widescreen issues from the pipeline build 1438 you've linked in https://github.com/Fate-Grand-Automata/FGA/issues/796#issuecomment-893866219

**Comment by MathewSachin** [comment]
@jcdeoferio I tested on wide screen. The commit that was merged works fine.

**Comment by jcdeoferio** [comment]
Alright! will try out 1447

**Comment by reconman** [comment]
@jcdeoferio Which device is the widescreen one? The rectangles are all shifted to the right.

If it's a Samsung, FGA also needs to run in Fullscreen mode.

**Comment by jcdeoferio** [comment]
@reconman details are in my comment yesterday, those are all recordings from the same widescreen device. https://github.com/Fate-Grand-Automata/FGA/issues/796#issuecomment-893988035

I'll try the latest canary in a bit and report back, will also check the fullscreen mode you've mentioned.

**Comment by MathewSachin** [comment]
Rectangles shift to the right after the recent JP update after which FGO JP covers the notch area.

Those rectangles don't enter the notch area and are shifted by that amount to the right.
We could fix this but thats a separate issue.

**Comment by sekir1488** [comment]
@reconman https://youtu.be/7xabfljBwVw

**Comment by jcdeoferio** [comment]
@MathewSachin is it just the rendering of the debug rectangles that are out of place? The calculations for detection is still correct?

**Comment by MathewSachin** [comment]
@sekir1488 you're using a separate recorder which messes with FGA. Restart your phone and try again.

@jcdeoferio yeah, it's just the rendering of the rectangles which doesn't really matter practically.
You don't need to force FGA to full-screen for the scripts to work. It's not that important issue honestly but feel free to open one.

**Comment by jcdeoferio** [comment]
Might be worth keeping a ticket as a reference in case other developers take a look into the app and wonder why their rectangles are out of place. I'll post a ticket :)

**Comment by sekir1488** [comment]
@MathewSachin still the same

**Comment by reconman** [comment]
@sekir1488 It seems like it thinks you're in lottery mode. It's not related to this bug ticket.

**Comment by sekir1488** [comment]
@reconman and what i need to do?

**Comment by reconman** [comment]
@sekir1488 I remembered this thing also happening to me in the past and it's because your preferred servant or CE image is gone.

If FGA can't find the image file in your support folder, it doesn't complain and instead searches for nothing.

**Comment by MathewSachin** [comment]
@reconman I guess we should throw a error for empty support servant folders.

**Comment by reconman** [comment]
@MathewSachin On it right now.

**Comment by MathewSachin** [comment]
Once you've pushed that, I'll add a new Exception type so we don't have to show it as Unexpected error.

**Comment by reconman** [comment]
Please report anything else in seperate bug issues. There are too many unrelated reports in this one.
