### ISSUE TITLE
Friend gacha auto detection failed after update

### ISSUE THREAD

**Issue by replicat** [Fate-Grand-Automata/FGA#799]
**Describe the bug**
Friend gacha script is not loaded even on friend gacha screen after the latest update in JP.
The detection region is shifted as JP added a banner scroll at the bottom of the gacha screen. 

**Screenshots**
![mpc-hc64_1FRdwI7O3c](https://user-images.githubusercontent.com/1373853/128005064-9d6779fd-aace-439d-a027-dd9c0826e131.jpg)

**Device Info (please fill at-least 'Device model'):**
 - Device model:  LD Player 4.0.53
 - Screen size: 1920x1080
 - Android Version: Android 7.1.2
 - RAM: 4GB

**Comment by egzn** [comment]
A temporal ""fix"" would be doing the first multi roll manually to enter the results screen
