### ISSUE TITLE
JP - Debug Rectangles are shifted due to the notch area

### ISSUE THREAD

**Issue by jcdeoferio** [Fate-Grand-Automata/FGA#809]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

**Describe the bug**
After the JP 6th Anniversary Update (2.36.0), FGO now renders into the notch area. But FGA doesn't, so the rendered rectangles for debugging are placed in the incorrect positions. This was noticed during testing of #796

**Screenshots / Video**
https://imgur.com/a/Da1ZApX

**Device Info (please fill at-least 'Device model'):**
 - Device model: Oneplus 6t
 - Screen size: 1080x2340
 - Android Version: Android 10

**Comment by sekir1488** [comment]
@reconman well i tried to change preffered servant, and all the same. I dont know why fga cant find images cuz i set the right folder
