### ISSUE TITLE
Script issue after Patch

### ISSUE THREAD

**Issue by Alphacentariprime** [Fate-Grand-Automata/FGA#816]
Before opening an issue:
- [y ] I tested the latest release
- [y ] I looked at other issues (even the closed ones)
- [y ] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [y ] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
Issue with script not working as intended will choose far right as opposed to any other options 

**Screenshots**
![Screenshot_20210807-180116_FGA (CI)](https://user-images.githubusercontent.com/83358830/128615324-dc88f836-b251-4e10-9634-f29cf1c50c07.jpg)

**Video**

https://youtu.be/L38713ZZtCs
**Device Info Samsung Galaxy S10):**
 - Device model: [e.g. Xiaomi Redmi 4]
 - Screen size: [e.g. 1280x720]
 - Android Version: [e.g. Android 7.1]
 - RAM: [e.g. 3GB]

**Comment by reconman** [comment]
Are you sure it's not because of skill confirm being enabled?

**Comment by MathewSachin** [comment]
Bombarded us with so many issues where you neither followed the template, nor read the Troubleshooting guide.
I'm temporarily blocking your from the repo.
It's this kind of behaviour that makes me not feel like helping with bug reports.
