### ISSUE TITLE
Ankulua type complete root support

### ISSUE THREAD

**Issue by tbektas0** [Fate-Grand-Automata/FGA#817]
If it is possible can you add complete root support for fga like ankulua does. It would be nice to have since we wont have to rely on accessibility and it would work as go without any problem. If it hard to do I would understand and I checked other issues. It wasnt requested before. Fgo supports root without problem now.

**Comment by reconman** [comment]
![Screenshot_20210809-131559](https://user-images.githubusercontent.com/12360257/128698280-c8531feb-4884-432d-bcb3-b4ef83cdcb0d.jpg)

**Comment by reconman** [comment]
Root for clicks and swipes is too different from Accessibility mode so we removed that. Can't maintain both easily.
