### ISSUE TITLE
FGA not working on Galaxy Note 8

### ISSUE THREAD

**Issue by tofu951753** [Fate-Grand-Automata/FGA#820]
Screenshot: https://imgur.com/a/BOm9QEY

**Describe the bug**
For some reason FGA seems to not work on my galaxy note 8. I tried chainging my screen resolution, checked full screen apps, enabled and disabled the notch setting on FGA, but it still doesn't seem to be findng the images correctly. 

Device: Samsung Galaxy Note 8
Screen size: Tried 2960 x 1440, 2220 x 1080, and 1480 x 720
Android version: Android 9

**Comment by reconman** [comment]
The template check is a bit strict.

Did you use some screen recorder recently?

**Comment by tofu951753** [comment]
No I did not. I tried it while streaming to friends who were helping me set it up as well as while I wasn't streaming and both yielded the same results.

**Comment by reconman** [comment]
I don't see any blue bars in your screenshot, did you enable fullscreen mode? https://github.com/Fate-Grand-Automata/FGA/wiki/Game-Area-detection#case-1-borders-around-fgo-are-black

If that still doesn't work, try restarting your device.

**Comment by tofu951753** [comment]
Both apps are in full screen mode. There isn't a setting for me to toggle in my full screen apps settings for those two apps since the phone automatically assumed they were optimized for full screen. The game displays similar to on my Note 10, which also doesn't have borders, but which FGA works perfectly for.

**Comment by tofu951753** [comment]
resolved, restarting phone worked. thanks!

**Comment by reconman** [comment]
That means you streaming probably messed with FGA's image detection.
