### ISSUE TITLE
Unable to hit play on FGA

### ISSUE THREAD

**Issue by nghipham513** [Fate-Grand-Automata/FGA#824]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
Trying out the 1438 build for FGA (CI). Play button does not work, even tho it will register me clicking the button as seen in video. Opening up the FGA app itself, I am unable to actually Stop Service by clicking on it, and have to manually stop it via the overlay permissions app 

**Video**
See attached please 

**Device Info (please fill at-least 'Device model'):**
 - Device model: Samsung Galaxy S8
 - Screen size: 1440x2960
 - Android Version: Android 9 
 - RAM: 4 GB

https://user-images.githubusercontent.com/55781810/129118379-6a6de268-8736-42bd-af4e-8d20fb55dfa8.mp4

![image](https://user-images.githubusercontent.com/55781810/129118402-8051e60a-a747-45da-90d2-999f0870d73a.png)

**Comment by reconman** [comment]
Try connecting via adb and doing `adb shell pm grant com.mathewsachin.fategrandautomata android.permission.SYSTEM_ALERT_WINDOW`.

That would fix a missing permission if it hasn't been granted for some unknown reason.

**Comment by MathewSachin** [comment]
> That would fix a missing permission if it hasn't been granted for some unknown reason.

PLAY button is already visible which means that permission is not the problem.

I suspect it is similar to LG phones where the game mode option prevents popups from other apps. I suspect something similar is happening here. That couldn't record game audio toast is a bit suspicious. GAME BOOSTER.... thats the same thing that happens on LG phones then.

**Comment by peroroch** [comment]
Same issue is happening to me on 64-bit Bluestack 5. Don't have the "can't record audio" though.

The instance is allocated 4 CPUs and 4GB of RAM.

**Comment by cpang6** [comment]
Had a similar issue a a moment ago on my OnePlus 6. Try to Force Quit the app and restart it all.

**Comment by PlsCallSyfs** [comment]
Hi there I am having the same problem on LDPlayer on FGA canary ver 1478. Fixed it by uninstalling and reinstalling a bunch of times but lost all of my skill configs and now it has happened again

**Comment by nghipham513** [comment]
> I suspect it is similar to LG phones where the game mode option prevents popups from other apps. I suspect something similar is happening here. That couldn't record game audio toast is a bit suspicious. GAME BOOSTER.... thats the same thing that happens on LG phones then.

tbh if it's game booster that would be super weird, as i've been using FGA w/o any issues until now
record game audio is only there b/c i never play w/ volume up LOL 

if anything i'll just reinstall FGA and see if anything changes.

**Comment by nghipham513** [comment]
i just deleted and reinstalled FGA Canary and it works!

i'm guessing my version was out of date as the newer version definitely looks newer and has more friendly UI stuff.
