### ISSUE TITLE
Skip Story doesn't work

### ISSUE THREAD

**Issue by Venomosh** [Fate-Grand-Automata/FGA#830]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1468

### Describe the bug

Playing on Bluestacks 5. In the Dubug Mode I can see that the program does detect the story skip button but just doesn't press it. I tried restarting, reinstalling, regiving the permissions.  

### Device model

OnePlus 3T

### Android version

Android 9

**Comment by MathewSachin** [comment]
Story Skip doesn't seem to be working in general.
@reconman I'm pretty sure this is related to the transparency change since story skip uses a transparent image.

**Comment by Venomosh** [comment]
Ok thank you so much for the quick response

**Comment by MathewSachin** [comment]
We could just change the story skip image to have black pixels instead of transparency to get back the old behaviour. 🤔

**Comment by PlsCallSyfs** [comment]
Hi there having this problem too

**Comment by VietNamVOV1** [comment]
Can't skip sir
