### ISSUE TITLE
Script keeps skipping over certain support servants

### ISSUE THREAD

**Issue by cpang6** [Fate-Grand-Automata/FGA#831]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1468

### Describe the bug

I set up the support filter on the script to search for Merlin and any MLB Mona Lisa or Belle Lisa. Then as the script run, I see a few that fall within the specification but it skips over them. It occasionally works. I also had an instance where it picked a Gilgamesh (Caster).

### Device model

OnePlus 6

### Android version

Android 10

### Screen size

1080x2280

### RAM

8GB

**Comment by DarkaXisX** [comment]
This also happen to me with Skadi, sometimes it pick one but most of time skip them.

**Comment by reconman** [comment]
I need a video with debug mode to diagnose the problem.

**Comment by MathewSachin** [comment]
@reconman Should we make video section mandatory. I don't feel like begging for info that is already asked in the template.

> It is recommended that you at-least add one screenshot of FGO running on your device.

I think we can get rid of the screenshots section if we're making video mandatory.

> ~~If relevant,~~ include a video of the script running on your device with Debug mode ON.

.

**Comment by starwolf256** [comment]
I am experiencing this issue in build 1469 with Merlin on my Samsung Note 9.  I have narrowed it down to his summer outfit specifically; my particular script is set to look for a 10/x/10 Merlin with no specific CE, and it will scroll past all Summer outfit Merlins until it finds a standard outfit one.

I recorded a debug video showing the issue; FGA scrolls past a summer Merlin at 0:10 and selects a standard Merlin at 0:16.

[youtube link](https://youtu.be/N2E6K4yTcHM)

**Comment by reconman** [comment]
@starwolf256 Is there an image called `merlin_c.png` in your support/servant/Merlin folder?

If not, you'll need to extract the default support images again under More Options -> Storage

**Comment by starwolf256** [comment]
@reconman Thanks for the reply.  Yes, my support/servant/Merlin folder has four PNGs: merlin_c, merlin1, merlin4, and merlin23, all dated August15th at 9:47PM, which I believe is when I extracted them last evening.

**Comment by MathewSachin** [comment]
Try replacing the merlin_c image with another one made with support image maker.
Default support images sometimes don't work for everyone depending on stuff like screen resolution.

**Comment by starwolf256** [comment]
@MathewSachin Thanks for the reply.  I used the Support Image Maker tool to create a new image and saved it to the Merlin folder.  It continued to fail matching until I rebooted my device, but it's working now.  Thanks for your help, and thanks for all the work you and all the others do on this app!  It makes the overall FGO experience so much more pleasant, I really appreciate it.

**Comment by MathewSachin** [comment]
TODO

- [ ] Check if Merlin costume image is bugged for everyone

**Comment by cpang6** [comment]
https://user-images.githubusercontent.com/14796503/129663895-77b938a8-9691-4257-888c-ef06468d39bc.mp4

As you can see here, it scrolls right past any Merlins with Bella Lisa

**Comment by reconman** [comment]
@cpang6 same problem as [above](https://github.com/Fate-Grand-Automata/FGA/issues/831#issuecomment-899508783)?

**Comment by cpang6** [comment]
@reconman I'll try it later. Cause I'm getting absolutely no Belle Lisas on my support list no matter how much I refresh

**Comment by reconman** [comment]
I fixed Merlin's image.

What you need to do:
1. Install latest canary
2. Delete merlin_c.png in your Merlin support folder
3. Go to FGA's More Options -> Storage and choose Extract default support images
4. Force close FGA and clear its cache

Then it should work.

**Comment by reconman** [comment]
Something is wrong, the new image seems more zoomed in but has the same width.

Does NA use a different image than JP?

**Comment by reconman** [comment]
Seems like the original committer used a 1080p screenshot and didn't downscale it to 720p.

The image taken on JP is the same as NA.

**Comment by reconman** [comment]
I've added it to the troubleshooting guide: https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting#merlins-costume-is-not-detected

**Comment by MathewSachin** [comment]
> Force close FGA and clear its cache

@reconman This isn't needed. Just Stop Service, then Start Service again would be enough. The image cache, including support images are cleared on Stop Service. It's not tied to the AccessibilityService.


https://github.com/Fate-Grand-Automata/FGA/blob/732a831739a54e37c7e1fa35366c4353eb2464e4/app/src/main/java/com/mathewsachin/fategrandautomata/accessibility/ScriptRunnerService.kt#L118
