### ISSUE TITLE
Incorrect script detection

### ISSUE THREAD

**Issue by RICHIEm8** [Fate-Grand-Automata/FGA#832]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1449

### Describe the bug

I mainly play on bluestacks but I've encountered this on my phone as well. Since the app now automatically detects what script is needed, when I try to start for example the battlescript it just constantly opens the Lottery Box script. After cancelling and trying to start it again the play button becomes unclickable and I have to end the service and start it up again. Then after restarting it twice it will disable my accessibility which makes me have to force end FGA app and turn off and on the accessibility again.

### Device model

Samsung Galaxy S8 Plus profile

### Android version

Android 7.1.2

### Screen size

1920 x 1080

### RAM

4GB

**Comment by reconman** [comment]
We need a video with debug on to diagnose.

**Comment by RICHIEm8** [comment]
I've tried enabling debug mode and record screen in the FGA settings but it would not record properly. I manually recorded the issue with OBS, not sure if that is good enough.

https://user-images.githubusercontent.com/48461113/129468272-c987a7ee-73bf-4fb2-ad03-87c5868b1364.mp4

**Comment by MathewSachin** [comment]
@reconman 1449 is 8 days old. We don't have any important change in this case, but asking for the Build number was the right choice.

@RICHIEm8 The video shows so much more than what you wrote. FGA is crashing when you hit the PLAY button.
I have a few questions:
1. Is the Bluestacks instance 32-bit or 64-bit? (You can check this in the multi-instance manager)
2. Have you turned ON Compatibility mode?

**Comment by RICHIEm8** [comment]
@MathewSachin 
1. Bluestack instance is Nougat 64 bit
2. Compatibility mode is ON

**Comment by MathewSachin** [comment]
From the Troubleshooting Guide:

![image](https://user-images.githubusercontent.com/10654537/129470705-68b4e981-fd34-429b-8826-545457f2429f.png)

**Comment by MathewSachin** [comment]
Create a new 32-bit instance and it should work.

**Comment by RICHIEm8** [comment]
Oh! I am very sorry I missed that. I will give it and go and report back.

**Comment by RICHIEm8** [comment]
Yep seems to be working fine now, again sorry for missing that in the troubleshooting guide. Thanks for the help,
