### ISSUE TITLE
script ends unexpectedly when selecting support

### ISSUE THREAD

**Issue by coolchulainn** [Fate-Grand-Automata/FGA#833]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1468

### Describe the bug

The script will end suddenly when trying to select a support. If I press play on the support select screen it will click to select the caster support list, but then end before trying to actually select one and gives this error:
![image](https://user-images.githubusercontent.com/56346314/129478003-51d6d1f9-f71e-40a6-a21a-ec8b44e1e1b5.png)
Starting the quest and then starting the script will have it select skills as normal, but it crashes when returning to the support select.

### Device model

Fairphone 3

### Android version

Android 10

**Comment by reconman** [comment]
Check the images of your preferred servant and CEs in the support folder. Are they corrupted?

**Comment by coolchulainn** [comment]
The images appear to be fine, but there was a non image file in the folder and deleting that resolved the issue. Thank you for the fast response :)
