### ISSUE TITLE
Quests without battles are not handled

### ISSUE THREAD

**Issue by kissLoveyou** [Fate-Grand-Automata/FGA#835]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1468

### Describe the bug

Unrecognized by image detection.
as follows.
![IMG_20210816_035343](https://user-images.githubusercontent.com/87466224/129490870-4e16105f-408b-4235-a2a5-6ee1dfebd20b.jpg)

### Video

https://user-images.githubusercontent.com/87466224/129491435-4726b398-0a28-424b-a15d-72639c2c621c.mp4

### Device model

xiaomi8

### Android version

10

**Comment by kissLoveyou** [comment]
pls

**Comment by reconman** [comment]
So far there are 2 situations FGA doesn't handle: pure story quests and quests where you have to choose the party after the story part.

For now you'll have to press OK yourself.

**Comment by kissLoveyou** [comment]
All right. XD
