### ISSUE TITLE
Can't repeat the stage

### ISSUE THREAD

**Issue by godarea** [Fate-Grand-Automata/FGA#836]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1474

### Describe the bug

Everything works fine, but can't repeat the stage after cleared, it just stucked 

### Video
https://youtu.be/LaC7SnqLInU
![Screenshot_20210819-002403322_1](https://user-images.githubusercontent.com/15869887/129937134-d75c4a09-29ae-4d6e-8ceb-1addaa74a042.jpg)

### Device model

Pixel XL (F1 VM)

### Android version

7.1.2

**Comment by reconman** [comment]
Please provide a video in debug mode, otherwise we can't help you.

**Comment by godarea** [comment]
https://youtu.be/LaC7SnqLInU

Ok, I can't recod at first, it's fine now.

**Comment by reconman** [comment]
Can you try this build? https://github.com/Fate-Grand-Automata/FGA/suites/3555453416/artifacts/85277682

**Comment by godarea** [comment]
> Can you try this build? https://github.com/Fate-Grand-Automata/FGA/suites/3555453416/artifacts/85277682

It works! Musch appreciated.
