### ISSUE TITLE
Game Screen Detect for 1080x2340

### ISSUE THREAD

**Issue by nhanlamtac** [Fate-Grand-Automata/FGA#840]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

The release last night didnt fix the problem of detecting on my phone (Honor Play).
In debug mode, the frame of the servant list was aside of the tap op FGA.
After a few tap, FGA decide to change sp list.
I dont know the reason why it cant tap right on a servant.
If I choose manually type cho choosing support, it will be bugged and cant do anything

**Comment by MathewSachin** [comment]
Bug report?

**Comment by MathewSachin** [comment]
My phone is 2400x1800 and it works fine.
Try looking at the Troubleshooting guide before opening bug report to see if anything works.
