### ISSUE TITLE
misclick buff

### ISSUE THREAD

**Issue by andrey35831222** [Fate-Grand-Automata/FGA#841]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1483

### Describe the bug

when using buffs, the target is incorrectly selected
settings selected:
Settings > System > Gestures > System Navigation.
Change to 3-button navigation.
![Screenshot_2021-08-21-20-32-13-86](https://user-images.githubusercontent.com/35026262/130323002-66534673-807d-4a3d-a6df-ad2e3d466c52.jpg)

### Video

[![video](https://i9.ytimg.com/vi/xVSjQus_b6Y/mq2.jpg?sqp=CNDxg4kG&rs=AOn4CLAUxmBmUqqpN6nce2L1tYTvsIO0Hg)](https://youtu.be/xVSjQus_b6Y)

### Device model

realme gt 5g 

### Android version

Android 11

### Screen size

2400x1080

### RAM

12Gb

**Comment by MathewSachin** [comment]
https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting#uses-skills-on-the-wrong-servant-or-doesnt-use-skills-at-all

>  I read the Troubleshooting Guide

pls
