### ISSUE TITLE
Overlay play button not appearing 

### ISSUE THREAD

**Issue by deveshm18** [Fate-Grand-Automata/FGA#842]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1483

### Describe the bug

![Screenshot_20210822-220202](https://user-images.githubusercontent.com/43674780/130362919-5613ef79-f85a-4e31-ab45-127276fb86c3.jpg)

When I click the start service no play button appears. I have tried clearing the cache, turning off and on again the enable overlay option and switched off battery optimization as well. 
I used to use the FGA(buster) app before and it used to work normally 

### Video

https://user-images.githubusercontent.com/43674780/130363006-547391fb-d80d-43e5-846e-63eb3d596547.mp4

### Device model

Oneplus 7T

### Android version

11

### Screen size

1080x2400

### RAM

6GB

**Comment by reconman** [comment]
You know that the play button only appears in landscape, right?

**Comment by deveshm18** [comment]
> You know that the play button only appears in landscape, right?

Hey! So it should work when I go into game right? Since the game runs landscape? It doesn't. However if I turn on auto rotate and then first get the play button and then go into game it works. Shouldn't it work directly when I go into the game (with auto rotate off too?)

**Comment by reconman** [comment]
> Shouldn't it work directly when I go into the game (with auto rotate off too?)

Yes, that should work, although sometimes the play button also doesn't appear for me after installing an update and I have to enable and disable Accessibility a few times and sometimes even force close the app to get it to work.

**Comment by deveshm18** [comment]
> Yes, that should work, although sometimes the play button also doesn't appear for me after installing an update and I have to enable and disable Accessibility a few times and sometimes even force close the app to get it to work.

Yep I guess there's a few steps involved (which probably is a bug) hence I posted this. Thanks for telling me a workaround tho. Works for the time being.
