### ISSUE TITLE
NA Getting UI changes up to October 2020 version of JP

### ISSUE THREAD

**Issue by jcdeoferio** [Fate-Grand-Automata/FGA#843]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Changes are going live on 25 August. ~~No mention of widescreen UI from the official news posts, but it might also be included. Widescreen was also part of the December 2020 update in JP.~~ Misread, looks like only the changes up to October 2020 are getting ported.

Changes that might have impact with FGA:
- Faster battle transitions
- Cooldown timer for refresh support list

https://fate-go.us/news/?category=MAINTENANCE&article=%2Fiframe%2F2021%2F0822_maintenance%2F
https://fate-go.us/news/?category=UPDATES&article=%2Fiframe%2F2021%2F0822_gameupdate_notice%2F

**Comment by MathewSachin** [comment]
I think there's nothing to change if wide screen update isn't coming.

Even for wide screen update, changes are pretty minor since we already support JP.

Thank you for reporting though!

**Comment by jcdeoferio** [comment]
Confirmed that the latest update is still not using widescreen. FGA still working :)
