### ISSUE TITLE
Repeat quest didn't pick support for a while

### ISSUE THREAD

**Issue by TA931525** [Fate-Grand-Automata/FGA#844]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA, JP

### FGA build number

1483

### Describe the bug

It usually happens when FGA tried to repeat the same quest, and when the screen changes to support selection it just does the thing in the video.

### Video

This is happening consecutively

https://user-images.githubusercontent.com/89583975/131235557-a5809859-c161-4a7b-b9ba-293af243a57c.mp4

### Device model

Redmi Note 4

### Android version

Android 7

**Comment by reconman** [comment]
Did you change any of the Fine-Tune settings?

**Comment by TA931525** [comment]
Nope, i did not

**Comment by DukeBurkoff** [comment]
Im having the same issue but i also found that rotating the phone causes FGA to restart the recognition process again wich exits the loop (i also havent changed anything in the settings) and that it also fixes itself after waiting for about 4 minutes inside the loop in at least in my case.

my own version of the post for reference:
FGO server
NA, JP

FGA build number
1488

Describe the bug
The exact same one as listed above.

Video
https://user-images.githubusercontent.com/81212715/132327445-8d03ae8e-5711-426b-833e-1bc6c5c30edb.mp4

Device model
Galaxy A12 (SM-A125M)

Android version
Android 10

Screen size
1600x720

RAM
4gb

**Comment by TA931525** [comment]
Hey, thanks for the temporary fix.
Also, do you just wait it out for 4 minutes each time you tried to farm something?

**Comment by MathewSachin** [comment]
Are the debug mode rectangles making the matching fail? I can only see that as the difference when you rotate the screen. 🤔

Debug mode rectangles interfering with matching has happened before on Quest rewards screens. I don't have the link to that issue though.

**Comment by TA931525** [comment]
It... worked? I swear it didn't worked before.

Anyway, thank you everyone for the help
