### ISSUE TITLE
Koyanskaya and Oberon in Preferred Servants

### ISSUE THREAD

**Issue by BllackeneD** [Fate-Grand-Automata/FGA#846]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

please, put Koyanskaya and Oberon in preferred Servants settings, thank you for the app

**Comment by reconman** [comment]
Koyanskaya is already part of FGA, you just need to use the Extract Default Support button.

For Oberon we still need images for all of his 4 ascensions. Can you provide them?

**Comment by BllackeneD** [comment]
> Koyanskaya is already part of FGA, you just need to use the Extract Default Support button.
> 
> For Oberon we still need images for all of his 4 ascensions. Can you provide them?

where is this button?

https://apps.atlasacademy.io/db/JP/servant/316/assets

**Comment by reconman** [comment]
We need the 4 images created by [Support Image Maker](https://github.com/Fate-Grand-Automata/FGA/wiki/Support-Image-Maker#how-to-use-support-image-maker)

> where is this button?

https://youtu.be/JOwupZ4W8AQ?t=1814

**Comment by BllackeneD** [comment]
oh ok

**Comment by BllackeneD** [comment]
> We need the 4 images created by [Support Image Maker](https://github.com/Fate-Grand-Automata/FGA/wiki/Support-Image-Maker#how-to-use-support-image-maker)
> 
> > where is this button?
> 
> https://youtu.be/JOwupZ4W8AQ?t=1814

https://imgur.com/a/zSZCy7f 

it's correct?

**Comment by reconman** [comment]
Available with build 1485.
