### ISSUE TITLE
FGA closes itself in Vivo phone

### ISSUE THREAD

**Issue by AxD99999** [Fate-Grand-Automata/FGA#847]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1483

### Describe the bug

The app gets killed during the first or second wave. The first video shows the app running just fine until FGA crashes abruptly. About 30 seconds after the app crashes, the play button returns but cant be clicked. I recorded the second video showing this.

I have done everything as mentioned in https://dontkillmyapp.com/vivo and checked the previous issues. The closest issue i found to my problem was #41 .

Edit: I should also mention that FGA was running perfectly well about 2 months ago. I had stopped playing and came back a few days ago. The above mentioned problem appeared. I realised that a new verson of FGA was released, since i had the previous verson of FGA installed (the verson fom 2 months ago). I installed the new verson but the problem still continues.

### Video

1st vid --> https://youtu.be/El8FziI97to
2nd vid --> https://youtu.be/F4faP25sM5w
<img height="500px" src="https://user-images.githubusercontent.com/57704669/131548573-8a6af77d-c425-480e-b1b9-b59dfbaf558d.jpg" />

### Device model

Vivo 1904

### Android version

Android 11

### Screen size

720 x 1544 pixels

### RAM

3GB

**Comment by reconman** [comment]
Since the old issue is about RAM usage, can you check this? https://fossbytes.com/check-ram-usage-android/

The crash reason could also be written in the logs. You can check them like this: https://github.com/Fate-Grand-Automata/FGA/issues/282#issuecomment-678614896

**Comment by AxD99999** [comment]
So, this is from the RAM usage :
![Screenshot_20210831_235209](https://user-images.githubusercontent.com/57704669/131558532-00900ba8-92c0-4eab-98c7-fbd9aafbf4f8.jpg)

And here's the log file:
[logcat.log](https://github.com/Fate-Grand-Automata/FGA/files/7086128/logcat.log)
I think the log of the time at which the video was recorded is at: 08-31 22:45:59.764 , although there are a lot of other instances at which i could find 'FGA' and 'fate' keywords when i searched.

**Comment by reconman** [comment]
There was a missing line in the source code which made the error log useless.

Can you please try again with build 1484 once it's released? (in a few minutes)

**Comment by AxD99999** [comment]
[logcat.log](https://github.com/Fate-Grand-Automata/FGA/files/7087775/logcat.log)
This is the log at build 1484.
The crash is at: 09-01 08:00:48.521

**Comment by MathewSachin** [comment]
@reconman The Null exceptions in the logs is expected on service start since media projection won't be initialised at that point. it's only logging that error, won't crash due to that.

**Comment by MathewSachin** [comment]
> I should also mention that FGA was running perfectly well about 2 months ago. I had stopped playing and came back a few days ago. The above mentioned problem appeared. I realised

That clearly indicates a battery saver/accessibility issue.
I assume you've tried restarting your phone or force stopping FGA after making those changes.

By any chance, did you suppress the ongoing notification that pops up when FGA runs scripts?

**Comment by AxD99999** [comment]
> > I should also mention that FGA was running perfectly well about 2 months ago. I had stopped playing and came back a few days ago. The above mentioned problem appeared. I realised
> 
> That clearly indicates a battery saver/accessibility issue.
> I assume you've tried restarting your phone or force stopping FGA after making those changes.
> 
> By any chance, did you suppress the ongoing notification that pops up when FGA runs scripts? 

No

**Comment by AxD99999** [comment]
So, I just restarted my device again and the app works fine now. It didn't work when i restarted twice yesterday so idk whats up with that.
Closing this issue now. Sorry to waste everyone's time and thankyou @MathewSachin and @reconman for the help.
