### ISSUE TITLE
Support: "Also check All" when selecting friends

### ISSUE THREAD

**Issue by biomagnet** [Fate-Grand-Automata/FGA#848]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Is there's a way to set support selection so that, once it's done all the downward swipes on the Preferred Class tab, it swaps to All to then swipe as many times down as before to check there for the same Servant?

I understand that Mix exists, but it is an amalgamation of all available Servants in _every_ Class and would take nine times as long to get to the "bottom" rather than merely doubling the time spent in checking two different tabs instead.

Considering the number of overlapping Caster Servants that people will split between "All" and "Caster," not to mention in JP there's now two Assassin support-types, and Extra being one big smorgasboard so that there are a lot of Oberons in All instead of Extra, I hope this idea might be implemented to overall cut down on time between runs instead of waiting for just the right support between all the different ways people implement their lists.

**Comment by jcdeoferio** [comment]
This might be needed in JP now. They allowed users to put up to 3 active support lists. So you see 3 servants per user when picking support and servants are all over the place.

**Comment by biomagnet** [comment]
I agree. This update alleviated the problem in a unique way, but there are still _five_ support Casters, so if someone happens to have all of them, two of them will still be in All to fit them into the lists. Oberon faces the same issue since Extra is always so packed, as well.

**Comment by MathewSachin** [comment]
Test build: https://github.com/Fate-Grand-Automata/FGA/actions/runs/1250947255

I've only tested for preferred selection mode. Feeling too lazy right now to test for every other mode 😴
