### ISSUE TITLE
Regarsing the Support Image Maker

### ISSUE THREAD

**Issue by EnglishPatchFanatic** [Fate-Grand-Automata/FGA#849]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

With the latest version of FGA, the means to make new images both craft essence as well as support servants can no longer be done.

Or if the feature itself is still can there can you put me in the right direction, thank you for the time reading this request.

**Comment by reconman** [comment]
https://youtu.be/JOwupZ4W8AQ?t=2135
