### ISSUE TITLE
Max-level support skills not being detected

### ISSUE THREAD

**Issue by minhducsun2002** [Fate-Grand-Automata/FGA#850]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1485

### Describe the bug

Detection of supports' max skills seem to be failing.

### Video

https://media.discordapp.net/attachments/755763097788088330/882964834948362250/record.mp4

### Device model

Bluestacks Hyper-V 4.280

### Android version

7

### Screen size

960x540

**Comment by MathewSachin** [comment]
Skadi's first skill isn't matching correctly. Maybe not enough similarity on scaling down the new transparent skill 10 image to 540p.

**Comment by reconman** [comment]
@minhducsun2002 @JusKIdding Can you try this build? https://github.com/Fate-Grand-Automata/FGA/suites/3683687739/artifacts/89738887

**Comment by JusKIdding** [comment]
> @minhducsun2002 @JusKIdding Can you try this build? https://github.com/Fate-Grand-Automata/FGA/suites/3683687739/artifacts/89738887

Hi, tested, the first skill is still not being detected correctly.

**Comment by JusKIdding** [comment]
Hi, created a new comment to pump up the thread with a recording for evidence.

[Build: 1489 - Issue #850 Record](https://youtu.be/AuRxrpAKfNM)

**Comment by MathewSachin** [comment]
@reconman can you switch to the old skill 10 image just for NA with black background to see if that works.

**Comment by reconman** [comment]
@JusKIdding It's really weird how we both have 1080p screens, yet your similarity is much lower than mine.

Can you post a screenshot of your support screen? I'm going to test out image detection some time this week. I'm currently a bit busy.

@MathewSachin Not only would the background be set to black, the min similarity would also need to be reduced again for all servers except for JP.

**Comment by MathewSachin** [comment]
> Not only would the background be set to black, the min similarity would also need to be reduced again for all servers except for JP.

Ok. I'll get a build ready in a few minutes for them to test.

**Comment by MathewSachin** [comment]
@JusKIdding try this one: https://github.com/Fate-Grand-Automata/FGA/suites/3703247669/artifacts/90394086

**Comment by minhducsun2002** [comment]
> @JusKIdding try this one: https://github.com/Fate-Grand-Automata/FGA/suites/3703247669/artifacts/90394086

This works for me.
![IMG_20210907_230029](https://user-images.githubusercontent.com/32769878/132376062-4deae16c-9257-436e-a545-716b596be06d.jpg)

**Comment by JusKIdding** [comment]
> @JusKIdding try this one: https://github.com/Fate-Grand-Automata/FGA/suites/3703247669/artifacts/90394086

Yeap it's working as intended. Sorry for late reply.
