### ISSUE TITLE
auto np

### ISSUE THREAD

**Issue by danieladi98** [Fate-Grand-Automata/FGA#856]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

i remember there use to have auto np menu but i dont find it in any option in this new ui. i try to use command but it seems it doesny always work. all i want is using np when there are np available.

**Comment by reconman** [comment]
![Uploading Screenshot_20210905-095128__01.jpg…]()

**Comment by reconman** [comment]
![Screenshot_20210905-095128__01](https://user-images.githubusercontent.com/12360257/132119702-b216b0f8-3f96-43bd-b0c5-f20dc90907f9.jpg)

**Comment by danieladi98** [comment]
thanks
