### ISSUE TITLE
Detection not working on Galaxy S21 Ultra

### ISSUE THREAD

**Issue by quinnjr** [Fate-Grand-Automata/FGA#857]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1488

### Describe the bug

The automation application no longer correctly detects the position of UI elements on the S21. 

The application was working in previous canary builds but seems to no longer detect the proper UI elements with the change to the newer Automata UI interface.

### Video

https://streamable.com/lb2r2b

### Device model

Samsung Galaxy S21 Ultra

### Android version

11

### Screen size

3200x1440

### RAM

12GB

**Comment by reconman** [comment]
How are you recording the screen? Not with FGA, I assume.

Recording the screen with anything other than FGA messes up the screen detection.

**Comment by quinnjr** [comment]
I was recording the screen using the built-in Samsung screen recorder. The detection boxes for FGA are the same with it or the built-in screen recorder for FGA, but FGA doesn't save a valid screen record that I can upload from my device.

**Comment by reconman** [comment]
What I'm saying is that once you use Samsung's recorder, FGA is broken from that point onward. You'll have to stop the FGA service and start it again to get another Media Projection token.

**Comment by quinnjr** [comment]
Sorry, didn't know about that.

Here is another video using only the FGA recorder: https://youtu.be/4TvN-RA254M

**Comment by MathewSachin** [comment]
Skill confirmation is mentioned in troubleshooting guide. 😞

**Comment by quinnjr** [comment]
Is skill confirmation now a new, required feature?

I should mention that I've been running FGA for a while now on this phone and this issue only cropped up with the recent update to the UI. This isn't a new phone.

I've been running with the same config from since when the application was on the play store and never needed to Skill Confirmation turned on. My config doesn't use skills and doesn't have skill spamming turned on. Prior to this latest Canary build, the application did not have the same issue with casting skills.

**Comment by reconman** [comment]
Skill confirmation is disabled in FGA by default for as long as I can remember. In FGO it's enabled by default.

No matter how we set the default value, people will still have problems misaligning both settings. That's why it's in the troubleshooting guide.

I can't tell you why it worked until recently.

**Comment by MathewSachin** [comment]
Am I blind, I clearly see it skill spamming in the beginning from the debug mode rectangles 🙈

**Comment by quinnjr** [comment]
> Am I blind, I clearly see it skill spamming in the beginning from the debug mode rectangles 🙈

Which is why I'm asking as I don't have spamming enabled in my settings.

**Comment by MathewSachin** [comment]
Post a screenshot?

**Comment by MathewSachin** [comment]
I think you turned OFF skill spam only for the first servant. It's spamming for 2nd and 3rd one.

**Comment by quinnjr** [comment]
Spamming is turned off for all servants in my config:

https://imgur.com/a/bhWOey6
https://imgur.com/a/QTC4M44

**Comment by MathewSachin** [comment]
Idk, it still thinks it has to spam 2nd and 3rd servant's skills.
The changes to Spam config are saved only after you leave the Spam screen (by pressing back). That could be a reason it is not updated. I can't really think of anything else.

I'm honestly more worried about how it closed the Servant Status dialog by clicking on the X instead of the top-right corner which led to a complete malfunction in the rest of the video. I think this shouldn't happen in any case.
