### ISSUE TITLE
Script launched but no action

### ISSUE THREAD

**Issue by unlimited-oof-works** [Fate-Grand-Automata/FGA#859]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1488

### Describe the bug

Upon launching my script, my screen's scanned but no click is made. Be it the Quest or the Support selection or battles, the App scans correctly but nothing's done. 

### Video

https://user-images.githubusercontent.com/78726430/132144483-93f6523a-1208-47bb-a541-c2e535634430.mp4

### Device model

Huawei P Smart

### Android version

9

### Screen size

2160*1080

### RAM

4GB

**Comment by reconman** [comment]
You are **not** recording using FGA, which messes up all image detection until you stop and start the FGA service again.

Also, your notch behaves weirdly. Change this system configuration: https://consumer.huawei.com/en/support/content/en-us00753709/
