### ISSUE TITLE
Detection area misaligned

### ISSUE THREAD

**Issue by kevinnaoko** [Fate-Grand-Automata/FGA#860]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1488

### Describe the bug

With debug mode on, I can see that the detection area is misaligned. For the most part, it works. But because of the misalignment, it can't detect the "NEXT" button after each quest ends, and the Extra Class button in the support servant selection menu. Due to these problems, the script is unable to repeat quests.

note: I've also tried the "ignore notch" setting but it didn't seem to change anything

### Video

I've read somewhere in the thread that recording a screen while the app is on may cause the detection area to misalign. Instead, here's some pictures where the area is clearly not placed correctly
![Screenshot_2021-09-06-17-56-32](https://user-images.githubusercontent.com/63304738/132208718-d5679e5e-72fa-4ec2-813e-6fd04e365769.png)
![Screenshot_2021-09-06-17-56-59](https://user-images.githubusercontent.com/63304738/132209085-24135171-375f-4664-9cea-5ed265b02a82.png)

### Device model

LG G7+

### Android version

8

### Screen size

1440x3120

### RAM

6GB

**Comment by reconman** [comment]
A search for LG G7 got me in past issues got me: https://github.com/Fate-Grand-Automata/FGA/issues/455#issuecomment-703218195

Get rid of the black notch area, then it works.
