### ISSUE TITLE
CN server UI  has changed after update

### ISSUE THREAD

**Issue by NepPure** [Fate-Grand-Automata/FGA#861]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

1488

### Describe the bug

CN server has been updated today, and the UI has changed.

### Video

Add later

### Device model

simulator

### Android version

7

### Screen size

1280x720

### RAM

4GB

**Comment by NepPure** [comment]
![image](https://user-images.githubusercontent.com/12379907/132466170-a9d674c1-aed6-4f06-ad63-4cfa99173572.png)


https://user-images.githubusercontent.com/12379907/132466321-a43bfd74-8416-4547-b382-e040562eb06e.mp4

**Comment by NepPure** [comment]
https://user-images.githubusercontent.com/12379907/132467253-da8c41b4-98d8-46b3-ad2a-a20f4c9d3122.mp4

**Comment by reconman** [comment]
Add info to the other issue.

**Comment by MathewSachin** [comment]
@reconman it is technically still insufficient info because what we need to see is a wide screen phone with a notch. We already know how it would behave on 16:9 devices.

**Comment by reconman** [comment]
Ah, didn't check.

**Comment by NepPure** [comment]
How about the emulator set to widescreen?

I only have iPhone with a notch.

**Comment by Kyonyuu** [comment]
by Notch you mean the older one which had blue pilla on both sides? i can ask a friend to record, he has one... he also play CN...

**Comment by PUNX1d** [comment]
https://streamable.com/0oilz7

**Comment by MathewSachin** [comment]
@Kyonyuu to put it simply, notch means a phone's front camera is in a hole on the screen. For example, Samsung S10 has a notch.

@PUNX1d what's your phone model?

**Comment by reconman** [comment]
@Kyonyuu This is a notch

![image](https://user-images.githubusercontent.com/12360257/132478562-b97ebbc1-6f6f-4381-902e-d3e0255b249e.png)

**Comment by PUNX1d** [comment]
@MathewSachin Xiaomi Redmi K20 Pro

**Comment by MathewSachin** [comment]
@PUNX1d Ah, this one doesn't have a notch. We still need a video on a phone with a notch.

**Comment by PUNX1d** [comment]
@MathewSachin But FGA can't work on my phone. Can you consider my situation first? If my request is rude and impolite, I apologise. 😰

**Comment by Kyonyuu** [comment]
i know what is a notch what i mean was if it had the blue pillar on both sides(on fgo) like that:
![image](https://user-images.githubusercontent.com/55859937/132481618-43cd8def-c5b0-4010-b2de-fb5ce7334299.png)

**Comment by reconman** [comment]
@Kyonyuu The blue pillars still appear on anything under a 18:9 screen ratio. We need both 18:9 or above and a notch.

**Comment by Kyonyuu** [comment]
i will try to find a friend with it, does he need to record battle script or everything else? like... drop screen the script just freeze here so he also needs to record that? and if he does, what is everything he needs to record?

**Comment by hycainth** [comment]
![Screenshot_20210908_175510_aea65f8d686cc6c065dfd97f67f4a929](https://user-images.githubusercontent.com/23132013/132488915-00113d08-e72d-40f2-ada2-f456c05152a7.jpg)
![Screenshot_20210908_175514_aea65f8d686cc6c065dfd97f67f4a929](https://user-images.githubusercontent.com/23132013/132488983-9e90c115-2476-41c9-a624-c912e7048acc.jpg)
like this？      ––vivo s6

**Comment by reconman** [comment]
@hycainth Yes, but we need a screenshot from a battle.

**Comment by hycainth** [comment]
https://youtu.be/HmfkG1JVj8Q

**Comment by ddcxxx** [comment]
> @hycainth Yes, but we need a screenshot from a battle.

![Screenshot_2021-09-08-18-08-35-415_com bilibili fatego](https://user-images.githubusercontent.com/41536081/132491248-c2dcb111-4c75-41f9-aed9-d989ad9ae8b6.jpg)
![Screenshot_2021-09-08-18-08-40-359_com bilibili fatego](https://user-images.githubusercontent.com/41536081/132491340-75f46f41-9f52-4e58-b494-18e2ae5ab8d3.jpg)
![Screenshot_2021-09-08-18-08-52-742_com bilibili fatego](https://user-images.githubusercontent.com/41536081/132491444-b6c42a6e-cf2b-4042-b91a-7be523323d83.jpg)
![Screenshot_2021-09-08-18-09-14-058_com bilibili fatego](https://user-images.githubusercontent.com/41536081/132491495-c7971d99-f628-46db-8171-04d030feb2ab.jpg)
![Screenshot_2021-09-08-18-09-20-475_com bilibili fatego](https://user-images.githubusercontent.com/41536081/132491681-a74eede8-c904-4979-ba0c-2551899f4091.jpg)
![Screenshot_2021-09-08-18-11-02-370_com bilibili fatego](https://user-images.githubusercontent.com/41536081/132491738-ff2eb600-1b37-4955-a377-3a7475dfe1b1.jpg)

**Comment by hycainth** [comment]
![Screenshot_20210908_182537_aea65f8d686cc6c065dfd97f67f4a929](https://user-images.githubusercontent.com/23132013/132493373-53b5a532-3db3-4d11-9b49-18907b62e568.jpg)
![Screenshot_20210908_182641_aea65f8d686cc6c065dfd97f67f4a929](https://user-images.githubusercontent.com/23132013/132493414-28f0dc1c-7629-459d-8632-3e2a8d763263.jpg)
friend gacha and order change

**Comment by MathewSachin** [comment]
Can you guys test the APK from: https://github.com/Fate-Grand-Automata/FGA/actions/runs/1213553854
Regardless of whether it works, upload debug mode videos of it doing a battle, so we can confirm it is working properly.
We don't have CN accounts to test it by ourselves.

---

> The blue pillars still appear on anything under a 18:9 screen ratio.

@reconman blue pillars don't really appear even under 18:9 after the update. They only appear for some story and NPs.

**Comment by NepPure** [comment]
Some problem detect

![image](https://user-images.githubusercontent.com/12379907/132525033-282ef521-a780-49b5-b050-fd917cf36324.png)

https://www.youtube.com/watch?v=NbI3S8WYWXY

**Comment by hycainth** [comment]
https://youtu.be/o99H0zWg5LQ  @MathewSachin

**Comment by MathewSachin** [comment]
got it. I have to update an image. I'll give you a new APK shortly.

**Comment by MathewSachin** [comment]
@hycainth In your case, FGA isn't able to see the screen due to the app you're using for recording.
After I post the new build, use the inbuilt recorder in FGA by turning it ON from `More options/Advanced/Record Screen`.

**Comment by NepPure** [comment]
https://pkg.biligame.com/games/fgo_v2.26.0_bili_952674.apk

lv120 CN account batch created by robot, feel free to use. Hope it can help a bit.

`p64763517`

`qwer0805`

![image](https://user-images.githubusercontent.com/12379907/132528859-24aa07b6-7558-4bb8-974c-4dc58d79a33e.png)

![image](https://user-images.githubusercontent.com/12379907/132528909-63288442-c700-4a81-8fe2-b84c354dc988.png)

**Comment by MathewSachin** [comment]
This should work: https://github.com/Fate-Grand-Automata/FGA/actions/runs/1213708122
@NepPure thanks, but I don't feel like installing FGO CN just for this 😅.

**Comment by NepPure** [comment]
![)M14SEALAJW$TP)X%O~E)~P](https://user-images.githubusercontent.com/12379907/132530391-03f5d86b-4b8f-41d5-baca-5bd0b80ce896.png)

**Comment by hycainth** [comment]
https://youtu.be/wsBDdHmDSfY
always failed to determine card type

**Comment by hycainth** [comment]
always failed to determine card type
https://youtu.be/wsBDdHmDSfY

**Comment by MathewSachin** [comment]
They've shifted all face cards up by a bit.
I would need much more time to do this properly, won't be able to until the weekend.

**Comment by MathewSachin** [comment]
Made some changes for detecting face cards.
Try this build: https://github.com/Fate-Grand-Automata/FGA/actions/runs/1223933973

**Comment by PUNX1d** [comment]
This build can detect the color of face cards on my Redmi K20 Pro.

**Comment by Sabersirius** [comment]
hello, I need help, the app doesn't select support, it doesn't do anything, I'm using the latest version posted @MathewSachin 
My phone is Xiaomi Mi 9T Pro
https://youtu.be/EPh-J6SIGbU

**Comment by reconman** [comment]
@Sabersirius Your video recorder is interfering with FGA. Stop and start the FGA service. Only record using FGA's feature in More Options.

If it still doesn't work, record a video with debug mode on using FGA, then share the video.

**Comment by Sabersirius** [comment]
@reconman The video recorder isn´t interfering with FGA, I didn't turn on debug mode, I´m sorry. Even without the video recorder activated, the same happens.
New video: https://youtu.be/hCYwXYbgLmY

**Comment by MathewSachin** [comment]
@Sabersirius Play button is at the place where FGA checks for support screen.
Move it to somewhere else, preferably bottom left corner of screen.

**Comment by luolikong1265446** [comment]
![44500B7C817E67388D7F6504291342B6](https://user-images.githubusercontent.com/90274651/132982651-be81be82-4bc3-43c1-a903-d4ff7bd64162.jpg)
![%FQXU81KHPE4US6U}N9TK9B](https://user-images.githubusercontent.com/90274651/132982737-ba46374d-12cb-454f-a9a7-7e0fbc66485f.png)
![O(5`$BG{H@ADS% W0_C2)(M](https://user-images.githubusercontent.com/90274651/132982796-73adf8ff-5ef0-44d5-880c-5bd5668a470d.png)


Mobile phones with a very wide screen have various exceptions

Helpers have no choice

There was no response after the battle

And the command card will not be selected

**Comment by reconman** [comment]
@luolikong1265446 Are you using version 1499?

**Comment by luolikong1265446** [comment]
> @luolikong1265446你用的是1499版本吗？

yes.  Not a very wide mobile phone can work normally

**Comment by MathewSachin** [comment]
@luolikong1265446 can you upload debug mode videos like everyone else did? We can't figure out what is happening from just screenshots.

**Comment by luolikong1265446** [comment]
sorry.

The video can't be uploaded here directly. I haven't used any other way. I'll try it

**Comment by MathewSachin** [comment]
Just upload to YouTube or streamable like others did

**Comment by luolikong1265446** [comment]
https://youtu.be/bGj4QavMB-A

**Comment by luolikong1265446** [comment]
https://www.youtube.com/watch?v=bGj4QavMB-A

**Comment by luolikong1265446** [comment]
https://www.youtube.com/watch?v=bGj4QavMB-A

https://www.youtube.com/watch?v=G-ia-hDwSvQ

**Comment by reconman** [comment]
@luolikong1265446 Both videos are private

**Comment by luolikong1265446** [comment]
@reconman 
It should be all right

**Comment by Sabersirius** [comment]
@MathewSachin ok, new video https://youtu.be/Cf1xnkkwNjM

**Comment by MathewSachin** [comment]
> The video recorder isn´t interfering with FGA

@Sabersirius How do you know it isn't? Force-stop FGA and try again with inbuilt recorder.

@luolikong1265446 You're using another screen recorder which is the first problem. What's your phone model? The first video you posted doesn't look like 1499 to me. Maybe because your phone has a notch but FGO still covers it.

**Comment by Sabersirius** [comment]
Oh, I didn't remember to do this, forced-stop. The forced-stop on FGA make it work. Problem solved. Thanks @MathewSachin

**Comment by luolikong1265446** [comment]
@MathewSachin
HAIWEIp30.
It's 1499
The recording screen will not affect FGA operation. My other equipment is also the recording screen, which is normal

**Comment by MathewSachin** [comment]
> The recording screen will not affect FGA operation.

I think it will affect FGA, but If you're sure it won't, then unfortunately I can't think of anything else you can try for now.

**Comment by reconman** [comment]
@luolikong1265446 Are you playing a modded FGO apk? Why are the animations so fast?

**Comment by luolikong1265446** [comment]
@MathewSachin @reconman 
https://youtu.be/XQ7nZ28HC8g
HAIWEI P40 Pro

**Comment by hycainth** [comment]
https://youtu.be/Eleon1_KgrA
I have this problem on my new phone too.
OnePlus 9R

**Comment by MathewSachin** [comment]
On Vivo S6,  FGO CN leaves notch black.
On OnePlus 9R, FGO CN covers notch too.

The behaviour isn't consistent unlike JP and KR 🤔 

I think I'll just leave it to the users to set `Ignore notch calculation` then.

**Comment by MathewSachin** [comment]
New build: https://github.com/Fate-Grand-Automata/FGA/actions/runs/1233449268

If FGO fills notch area, turn ON `More options/Advanced/Ignore notch calculation`

**Comment by hycainth** [comment]
It works.

**Comment by luolikong1265446** [comment]
I tested it. It can be used normally. Thank you

**Comment by NepPure** [comment]
![image](https://user-images.githubusercontent.com/12379907/133265229-3003e6b4-ad0a-471c-bdce-c023a414132c.png)

There is a problem with detecting danger.

16:9

**Comment by MathewSachin** [comment]
I don't see target_servant.png or target_danger.png images for CN. That should mean auto-targeting never worked on CN (unless they recently changed the font from English to Chinese).
You should open a different issue for that. I'm going to close this issue and do a canary release with CN wide screen support.
