### ISSUE TITLE
Arash  Stella

### ISSUE THREAD

**Issue by kissLoveyou** [Fate-Grand-Automata/FGA#868]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

1492

### Describe the bug

After Arash opens the treasure and dies, the next round, the script set in advance will be invalid。(cn update model is related to action？)
Do not release the set skills, directly select the card，
But the next Arash (same round) there will be no error, I don't know if it’s a translation error or a bug

### Video

NO

### Device model

xiaomi

### Android version

11

**Comment by reconman** [comment]
Sorry, but I can't understand your bug report. You will have to ask someone to translate.

And you didn't even provide a video.

**Comment by MathewSachin** [comment]
Duplicate of #861

**Comment by kissLoveyou** [comment]
This problem is not UI,
![IMG_20210910_144203](https://user-images.githubusercontent.com/87466224/132811319-ec44b421-a99a-40a5-9bb8-c312ec834f8c.jpg)
![IMG_20210910_144250](https://user-images.githubusercontent.com/87466224/132811322-dc491aa0-9f1c-4803-8a0e-bb7d4bde6de5.jpg)
Picture 1 is the script I set

Picture 2 chooses the first one, next time, after Alash uses Stella to die, the next person to replace Alash will not use skills

**Comment by kissLoveyou** [comment]
https://user-images.githubusercontent.com/87466224/132816445-f7198a8e-0043-4654-a295-7305fedcc822.mp4
