### ISSUE TITLE
Prevent attacks form chaining?

### ISSUE THREAD

**Issue by Sabagabu** [Fate-Grand-Automata/FGA#871]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Hello all, I am very greatful for the app, it works wonders. i wanted to ask if there's an option to prevent units from chaining attacks, especially when I go to lower level nodes, they often overkill a weaker monster instead of using different servant attack. hope i was clear enough, please let me know if you need me to explain further

**Comment by MathewSachin** [comment]
Look at avoid brave chains in card priority
