### ISSUE TITLE
app cant choose apples

### ISSUE THREAD

**Issue by DevilAngel123** [Fate-Grand-Automata/FGA#875]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1488

### Describe the bug

app cant choose ap to refill and keep saying "ran out of AP " 

### Video

https://youtu.be/9LfRr0wnCIE

### Device model

Poco x3 NFC

### Android version

12

### Screen size

1080x2400

### RAM

6GB

**Comment by MathewSachin** [comment]
How many apples did you set it to use?

**Comment by DevilAngel123** [comment]
I always set 100 apples as default
