### ISSUE TITLE
Allow checking the status of the current script when paused

### ISSUE THREAD

**Issue by The-Intelligent-One** [Fate-Grand-Automata/FGA#876]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

There's result summary screen that pops up once the script has run and exited, but I'd really like to be able to bring up a same kind of screen when pausing, so I could check how many refills it has used, how many runs it has done, was there a CE drop already, etc.

Currently if I want to do that I have to either wait until the end of the current run, stop it there to check it and then start the script again (I appreciate that the app decreases the run and refill limit now and I don't have to keep track of it anymore), or stop script to check it and then play the remainder of the battle manually to then be able to start the script again. I know this is not a hugely important feature because of this, but it would be very nice to have.

**Comment by reconman** [comment]
I support this feature, but I'm not too sure how to rewrite the code in order to implement it.

Currently the script modes throw an ExitException with all the details for the summary dialog, whereas pausing is currently handled independently of the script modes.

**Comment by MathewSachin** [comment]
Pretty much impossible without a rewrite from scratch. Pausing right now works by locking on a mutex, whereas the result screen is generated from exceptions. Can't throw exception at pause since that would terminate the script.

**Comment by MathewSachin** [comment]
I guess adding an abstract function on `EntrtPoint` which every script has to implement and return the ExitException at the current state could work. The UI could call this function and display dialog using the exception.
