### ISSUE TITLE
Chose Servants

### ISSUE THREAD

**Issue by ITzYxssxn** [Fate-Grand-Automata/FGA#877]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Hello, i was using Fate Grand Automata like 1 week and the first day, i get a some pictures from different servants, so i was doing some day i was doing some farm with Ishtar( i was choosing her manually) but i get a random download from a face picture from Isthar to can choose her automatically. 

Okey thats my question where i can get more pictures of different servants, to can choose them automatically

![is](https://user-images.githubusercontent.com/90447842/132963057-4569b234-135f-4b8f-8320-8a0a8e91ca0e.png)

**Comment by reconman** [comment]
https://youtu.be/JOwupZ4W8AQ?t=35m35s
