### ISSUE TITLE
Add Nero Bride as a preferred support

### ISSUE THREAD

**Issue by SafeguardSanakan** [Fate-Grand-Automata/FGA#878]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Nero Bride is a prime support candidate, and deserves to be a preferred support that the program can search for. Her synergy with the recently released Berserker Musashi is very high, and not being able to have the program automatically look for Nero Bride is a great downside to this program IMO.

**Comment by MathewSachin** [comment]
She was added long long ago.
Extract default support images again from more options/storage.

> great downside to this program IMO.

Support image maker exists, so not having a servant or 2 by default is not big deal.

**Comment by SafeguardSanakan** [comment]
> 
> 
> She was added long long ago.
> Extract default support images again from more options/storage.
> 
> > great downside to this program IMO.
> 
> Support image maker exists, so not having a servant or 2 by default is not a big deal.

My mistake, I was blind. 
Thanks for the input.
