### ISSUE TITLE
problem when launching the bot

### ISSUE THREAD

**Issue by damso93** [Fate-Grand-Automata/FGA#879]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

When I launch the bot "start device" on the bot page, the page starts to bug (frozen) and when I press the "start" button on the fgo page it bugs my fgo and fga page, but everything else works fine beside it. Do you know how to fix it?

**Comment by MathewSachin** [comment]
>  page starts to bug (frozen) 

bug report not question.
