### ISSUE TITLE
problem when launching the bot 

### ISSUE THREAD

**Issue by damso93** [Fate-Grand-Automata/FGA#880]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1498

### Describe the bug

When I launch the bot "start device" on the bot page, the page starts to bug (frozen) and when I press the "start" button on the fgo page it bugs my fgo and fga page, but everything else works fine beside it. Do you know how to fix it?

I'am on emulator ( Bluestacks 4 or 5 , I've tried both )

sorry for the quality of the video but if I reccord with my computer the video is too heavy

### Video

https://user-images.githubusercontent.com/90508205/132997991-7b039901-ca27-4c5b-91bd-94922007049f.mov

### Device model

blustacks on ONEPLUS 

### Android version

7

### RAM

4 GB

**Comment by MathewSachin** [comment]
>  I read the Troubleshooting Guide

freezing on Bluestacks? Solution is in the Troubleshooting guide, emulators section -_-
