### ISSUE TITLE
Problem with configuring commands.

### ISSUE THREAD

**Issue by RebellionBlack** [Fate-Grand-Automata/FGA#881]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1498

### Describe the bug

The buttons for the last two skills do not appear in the battle command configuration interface.
![Screenshot_20210913-124614](https://user-images.githubusercontent.com/89496489/133115946-5e76594b-1265-4a6f-a6e7-de5477df8109.png)

### Video

I believe it is not necessary in this case.

### Device model

Moto G5

### Android version

8

### Screen size

1080x1920

### RAM

2GB

**Comment by reconman** [comment]
Can you try playing around with your phone's accessibility settings? Specifically `Font size` and `Display size`.

We've never had a device with this problem before, even phones with similar pixel density.

**Comment by RebellionBlack** [comment]
Perfect. Solved problem! Thank you for the assistance.
