### ISSUE TITLE
It dosen't work at Galaxy Z Flip3

### ISSUE THREAD

**Issue by Whitenugget** [Fate-Grand-Automata/FGA#883]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1498

### Describe the bug

Hello, I'm a user who recently changed his cell phone to Galaxy Z Flip3.
I tried to use FGA at this summer event, but the script didn't work at all. (Case#1~#3)
I thought the screen ratio was not 16:9, so I changed it to the full screen. This time, some skills worked, but command input failed because some were not recognized. (Case#4)

All z flip series have a 6.7-inch ratio of 22:9 2640×1080. I don't think this screen size will change even if the next model comes out. I would appreciate it if you could help users who use the device.

### Video

Case#1 - Order change https://youtu.be/9nrzwcuSeJo
Case#2 - Space Ishtar https://youtu.be/KHDbc6p_Rl8
Case#3 - Amiya Archet https://youtu.be/IkC_U5MQDHc
(I did it manually to show you the skill selection screen.)

Case#4 - Full Screen https://youtu.be/jD1sg8md-i4
(It didn't work on the original screen. This is a situation where i filmed after turning the screen upside down.)

### Device model

Galaxy Z Flip 3

### Android version

11

### Screen size

6.7inch ratio 22:9 2640×1080

### RAM

8GB

**Comment by MathewSachin** [comment]
We could make CASE#4 work.
It looks like for screens wider than 21:9, blue borders appear on the sides. FGA should be able to work if we adjust for this.

**Comment by reconman** [comment]
Isn't everything above 18:9 supposed to be full screen without borders?

**Comment by MathewSachin** [comment]
That should be, but I think DW didn't plan for wider than 21:9 yet, similar to how less wider than 16:9 also gets blue borders above and below.

A potential way to confirm this would be to create a 21:9 emulator instance.

**Comment by ReanTong** [comment]
Hi, sorry for disturbing. I face a similar problem too. I am using Sony Xperia 1 which is with the ratio 21:9. After I run my battle config, FGA doesn't select any quests. 

[Video record](https://youtu.be/tMyAnQt_vFg)

**Comment by Whitenugget** [comment]
Thank you. I'm looking forward to the day when it's adjusted.

**Comment by MathewSachin** [comment]
Can you try the APK from this page for CASE#4: https://github.com/Fate-Grand-Automata/FGA/actions/runs/1246024929
and also post a debug mode video so I can confirm.

**Comment by Whitenugget** [comment]
Sorry for confusing. I scroll down and pressed the wrong button to close it, so I thought it would be okay if I opened it again. I needed to explain why the condition changed.
https://youtu.be/J6v2dJAUjIk

But sorry, I don't know how to proceed with the actions.

**Comment by reconman** [comment]
@Whitenugget at the bottom there's an APK link, triggering the download of a zip file containing the APK.

**Comment by Whitenugget** [comment]
https://youtu.be/kzgCtoehwB0

At first, fga couldn't choose a friend, so I was worried. But the battle went smoothly according to the input command, and when it continued, it seems to be okay considering that it made a good choice at once.
