### ISSUE TITLE
auto-targeting problem on CN

### ISSUE THREAD

**Issue by NepPure** [Fate-Grand-Automata/FGA#885]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

1501

### Describe the bug

see https://github.com/Fate-Grand-Automata/FGA/issues/861#issuecomment-919146804

![image](https://user-images.githubusercontent.com/12379907/133729308-c803d961-943d-4ccf-ad0b-35fa97ddc563.png)

 detecting danger failed

### Video

add lator

### Device model

Emulator

### Android version

7

**Comment by MathewSachin** [comment]
> Video
add lator

Video is not really needed for this, but, can you atleast post a full-screen screenshot of both servant and danger cases?

**Comment by NepPure** [comment]
https://b23.tv/96vwzi

sorry for late

Screenshot on the way

**Comment by NepPure** [comment]
![BABA2B4B-F380-4AF5-A7DF-B81669728A52](https://user-images.githubusercontent.com/12379907/133893717-6c9949dd-5726-4d39-9081-7db4fdd84fd9.png)
![176A85F6-B18B-4EFB-BF63-EC0A177C1AE0](https://user-images.githubusercontent.com/12379907/133893721-f7ab83cf-9477-4ff0-9477-645b7bcdd2d3.png)

**Comment by MathewSachin** [comment]
Can you give screenshots without the emulator border? I'm not able to precisely crop out the border sadly.
Your emulator should have an option to take screenshots in it.

I tried taking images from that video but the quality turned out lower that way.

**Comment by NepPure** [comment]
![image](https://user-images.githubusercontent.com/12379907/134107002-52bad8ed-da29-4980-9ff3-4f06f7e43998.png)

danger left 1

![image](https://user-images.githubusercontent.com/12379907/134107072-008ccf7a-70df-437c-a894-fa58b21f7d35.png)

all servant

**Comment by MathewSachin** [comment]
Try this build: https://github.com/Fate-Grand-Automata/FGA/actions/runs/1273027821

**Comment by NepPure** [comment]
Seems no problem
