### ISSUE TITLE
Having FGA accessibility enabled causing issues.

### ISSUE THREAD

**Issue by Bubbaz-Cellmate** [Fate-Grand-Automata/FGA#887]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1501

### Describe the bug

As I mentioned in the title. Chromium browsers lose access to grid view and tab Groups when the FGA accessibility is enabled. Video attached for demonstration.

### Video

https://youtu.be/OaPNm5-hMGA

### Device model

One Plus 9 Pro 5G

### Android version

11

### Screen size

3216x1440

### RAM

12GB

**Comment by jcdeoferio** [comment]
This isn't a bug for FGA.

https://support.google.com/chrome/thread/11460012/as-of-chrome-76-on-android-the-accessibility-tab-switcher-is-no-longer-available?hl=en

Settings > Accessibility > Simplified view for open tabs

**Comment by MathewSachin** [comment]
Yeah, well FGA shouldn't really affect Chrome but I was surprised when I saw this happen on my phone too.
But, yeah we can't do anything about it.
