### ISSUE TITLE
FGA hangs at the result screen

### ISSUE THREAD

**Issue by ArikTsuka** [Fate-Grand-Automata/FGA#891]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1505

### Describe the bug

FGA works all the way until the result screen and then hangs. Once user taps on the screen then FGA proceeds like normal and goes back to auto farming.

### Video

https://streamable.com/xozfli

### Device model

Google Pixel 3xL

### Android version

9

### Screen size

1440 x 2960

### RAM

4gb

**Comment by reconman** [comment]
Your play button overlaps the area used for detecting the bond screen. Move it somewhere else, preferably the bottom left.
