### ISSUE TITLE
FGA BUILD:1505 (CN server) not work on samsung s10+

### ISSUE THREAD

**Issue by OXERIS** [Fate-Grand-Automata/FGA#892]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

1505

### Describe the bug

it's not work,nothing happens after i startup the script

my phone‘s Screen Resolution is 2280*1080

![Screenshot_20210920-125233_-](https://user-images.githubusercontent.com/18722082/133958330-67d78196-4d42-4ec7-8dfc-126b1806d4a5.jpg)

![Screenshot_20210920-125921_-](https://user-images.githubusercontent.com/18722082/133958640-10171d31-cf28-4085-af4a-ccff75163435.jpg)

### Video

https://www.youtube.com/watch?v=kfTvGTVAhZg&t=2s

### Device model

samsung galaxy s10+ 

### Android version

11

### Screen size

2280*1080

### RAM

8GB

**Comment by reconman** [comment]
You're not recording with FGA but with the Android recorder. FGA will only see black.

Stop and Start the FGA service.

**Comment by OXERIS** [comment]
> You're not recording with FGA but with the Android recorder. FGA will only see black.
> 
> Stop and Start the FGA service.

you means i shoud record with fga，and then release the video，right？

**Comment by reconman** [comment]
Yes, also is full screen mode active? The black area should not be there.

**Comment by reconman** [comment]
Do you have ignore notch calculation enabled?

**Comment by OXERIS** [comment]
> Yes, also is full screen mode active? The black area should not be there.

i tried record with fga,but failed,it told me that screen recording cannot be turned on.
The black area always be there whether full screen mode is active.

**Comment by reconman** [comment]
You quoted my old comment, I edited it and posted another comment.

What do you mean with screen recording cannot be turned on? Share a screenshot.

**Comment by OXERIS** [comment]
![Screenshot_20210920-164228_FGA (CI)](https://user-images.githubusercontent.com/18722082/133976299-1d2ea9a8-98f6-40ed-aa9e-b9adda14e41a.jpg)
![Screenshot_20210920-164256_-](https://user-images.githubusercontent.com/18722082/133976304-b06ad9af-43aa-46bb-a233-7e0fb0dbb7d7.jpg)

**Comment by OXERIS** [comment]
![Screenshot_20210920-164256_-](https://user-images.githubusercontent.com/18722082/133976596-fbc144f8-031d-47a9-9504-a75e13312946.jpg)

**Comment by reconman** [comment]
Can you try force-closing FGA? If that doesn't help, the reason why it can't record can be found by doing this https://github.com/Fate-Grand-Automata/FGA/issues/282#issuecomment-678614896

**Comment by OXERIS** [comment]
i have just remembered that i installed an app which used to manage permissions，and "Display over other apps" was denied by the app automatically. 
now fga works,and the recorder of fga works now
thank you
