### ISSUE TITLE
Not working in CN server

### ISSUE THREAD

**Issue by applefruit88** [Fate-Grand-Automata/FGA#893]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

1511

### Describe the bug

It does not detecting the Support selection screen correctly, also after i manually start the battle, it does not clicking as intended as the script. Seems regarding the game area detecting problem, checked the troubleshooting guide didn't find solution for CN server. Please help.

### Video

Video: https://drive.google.com/file/d/1ziI60E_gOi22EHrAzz3BMSyPeRRGQpWD/view?usp=sharing

### Device model

Huawei P20 Pro

### Android version

10

### Screen size

2240x1080

### RAM

6

**Comment by reconman** [comment]
Can you try enabling Ignore Notch?
