### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by giverance** [Fate-Grand-Automata/FGA#894]
### Preparation

- [x] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [x] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP, KR

### FGA build number

1511

### Describe the bug

Does not support full screen on Redmi note 9 pro(It supports it, but not well.)

### Video

https://youtu.be/yqWk5YoQ9Ig

### Device model

Xiaomi redmi note 9 pro

### Android version

11

### Screen size

1080x2400

### RAM

6

**Comment by giverance** [comment]
Any settings in the app dont solve the problem

**Comment by MathewSachin** [comment]
I see 2 problems:
1. It's not clicking on top-right corner after using skills/NPs/auto-targetting which leaves some dialogs open.
2. Regions for skill spam are off in JP too (#874)

**Comment by giverance** [comment]
About the first, I have it works fine on the NA version, but already in Korea or China such an error. Here is about the second I also on NA more or less everything works, though sometimes there are dialogs, but it does not interfere with farming.

**Comment by MathewSachin** [comment]
Try the apk from this page: https://github.com/Fate-Grand-Automata/FGA/actions/runs/1275218518

Just shifted the click on top-right corner for closing dialogs a bit inwards. See if it closes dialogs now.

**Comment by giverance** [comment]
Didn't help, it doesn't close the dialogues either.
![Screenshot_2021-09-26-19-03-37-447_com aniplex fategrandorder](https://user-images.githubusercontent.com/68159352/134815332-d222ed22-96bb-44d4-b08a-08315c77797b.jpg)

**Comment by MathewSachin** [comment]
Just to be clear, it won't close a dialog if already open. It only closes if a dialog opens up when it clicks by itself on NP/enemy/skills.
I'm assuming you knew this.

So, on most phones an offset of 10 for the top-right corner click works. The build I gave you above had 20 offest which didn't work either.
Here's a 50 offest build: https://github.com/Fate-Grand-Automata/FGA/actions/runs/1275543433

If even this won't work, I'm not sure what you could try 😞

**Comment by Crimsonhime327** [comment]
it gets stucks on bluestacks too. when i click on Start Service it gets stucked

**Comment by giverance** [comment]
Now it's OK, at least now I can't see anything
