### ISSUE TITLE
Servant Card priority.

### ISSUE THREAD

**Issue by Arimil508** [Fate-Grand-Automata/FGA#895]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

While I love how you have card selection set up for the script. I had an idea that might help prevent run from failing due to a servant dying. When I set up a script I set up card priority based on my frontline but sometimes a servant dies which sometimes causes things to fall a part. I was would it be possible to set up a way to set card priority based on a given servant.  If a servant does not have a setup it would follow the priority the player sets for the script. but if it does it adjust that priority.

**Comment by MathewSachin** [comment]
Duplicate of #730
