### ISSUE TITLE
FGA is stuck in the selection of servant support

### ISSUE THREAD

**Issue by MakuSensei** [Fate-Grand-Automata/FGA#904]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1521

### Describe the bug

FGA is stuck in the selection of servant support
![Screenshot_2021 10 04_00 27 00 838](https://user-images.githubusercontent.com/16900914/135788837-fe998135-28ab-438c-9250-09a5f39eb1e1.png)

### Video

*

### Device model

Bluestack 5

### Android version

7

### Screen size

1280x720

### RAM

4G

**Comment by MathewSachin** [comment]
I think this could only happen when Debug mode is ON. Try turning it OFF.

**Comment by MakuSensei** [comment]
> I think this could only happen when Debug mode is ON. Try turning it OFF.

thanks, it was debug mode problem.
