### ISSUE TITLE
Script Repeatedly Taps Top Right Area of Screen on Samsung Galaxy S8

### ISSUE THREAD

**Issue by hibikikuze4dan** [Fate-Grand-Automata/FGA#907]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1518

### Describe the bug

When I start the automation, all that happens is that the top right of the screen is pressed repeatedly. The previous version of the app (when it was called FGA, not FGA (CI)) worked perfectly. I thought the issue might be the skills spam or notch settings, but after trying the recommended solutions in the troubleshooting guide for those I am still seeing the same behavior as shown in the video below. Any help would be appreciated.

### Video

https://www.youtube.com/watch?v=DfhwD374UZQ

### Device model

Samsung Galaxy S8

### Android version

9

### Screen size

1440 x 2960

### RAM

4GB

**Comment by jcdeoferio** [comment]
Does this happen all the time? I notice this happening to FGO sometimes when I'm using a generic autoclicker (not FGA) and switch apps or open the notification drop down or some game overlay that interrupted the clicks. 

FGO or Unity was probably interrupted during a click event and something made it stuck to always click on that specific coordinate. Switching to a different app then back to FGO usually solves the problem for me.

**Comment by hibikikuze4dan** [comment]
Yeah, it's happening all the time. It doesn't matter if I start the script outside of the node or once the fight starts. Once the servants show up, nothing else happens.
