### ISSUE TITLE
At the start of the battle the script opens the first 2 servants status and after that it progress normally

### ISSUE THREAD

**Issue by duradara** [Fate-Grand-Automata/FGA#911]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1530

### Describe the bug

At the start of the battle the script opens the firs 2 servants status and after that if proceed normally, it started happenig after I downloaded the 1530 build

### Video

https://user-images.githubusercontent.com/50158352/136814943-3b89bef2-9ae8-495b-a02b-19ac386f2ef4.mp4

The script that I was using:
![Screenshot_2021 10 11_12 45 28 515](https://user-images.githubusercontent.com/50158352/136818894-5369c4c2-b1f3-490b-ae29-043ee1b69e66.png)

### Device model

Bluestack 5 32 bit

### Android version

8

### Screen size

1280x720

### RAM

2

**Comment by MathewSachin** [comment]
This is expected behaviour going forward.
See #730
