### ISSUE TITLE
Brave chain "With NP" and servant priority not working and actually avoids the target cards.

### ISSUE THREAD

**Issue by Ryrin45** [Fate-Grand-Automata/FGA#913]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1532

### Describe the bug

Both "with NP" setting for brave chains and the servant priority feature seemed to be ignored. It actually entirely avoids the NP user's cards even when there are plenty to pick from. I'm not sure if I'm misunderstanding a feature or missing something. And no I did not accidently set it to "avoid"

https://files.catbox.moe/ytx7v7.jpg

### Video

https://files.catbox.moe/4l8rs0.mp4

### Device model

LDPlayer

### Android version

7

### Screen size

2560x1440

### RAM

6GB

**Comment by MathewSachin** [comment]
Interesting... So, from what I can see from the video, it is detecting Koyanskaya and the Support Koyanskaya just fine but fails to detect Space Ishtar cards.
I'm guessing it should be due to the buffs showing up on her face card.
Can you check if it works if you don't apply any buffs? Maybe try that on Fuyuki X-C (4AP).
If that's the case, I would adjust the face card image crop region and the detection region.

**Comment by AKSoo** [comment]
Confirming this happens with Build 1556 in NA. The problem also seems to be buffs on cards.

What is more frustrating is that this breaks the basic, non-priority (only avoid brave or with NP) card selection. I don't know how many users actually need full servant priority, but we need a release with this feature rolled back.

Going forward, this repo really needs 2 separate branches and releases:

* `stable` focusing on just making sure the existing features work
* `develop` with new features and enhancements

**Comment by reconman** [comment]
Should be fixed since build 1589, the Servant regions were moved.
