### ISSUE TITLE
Script crash after first Attack button press

### ISSUE THREAD

**Issue by tyler274** [Fate-Grand-Automata/FGA#915]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1534

### Describe the bug

Script crash after first Attack button press and scan of the command cards. 

```
null

c4.a$b
	at c4.a.a(AutoBattle.kt:3)
	at a5.c.q(EntryPoint.kt:3)
	at o5.a.run(Thread.kt:1)
```

### Video

https://user-images.githubusercontent.com/4147075/138022185-83bdeb34-3899-4d2d-8be8-86320d2371ab.mp4

### Device model

BlueStacks Hyper-V/Samsung Galaxy S8 Plus

### Android version

7

### Screen size

1920x1080

### RAM

8GB

**Comment by MathewSachin** [comment]
The crash is due to not being able to match servant face card I believe due to buff icons, similar to #913.
But, now the code was assuming something would match, and when nothing matched, it crashed.

ToDo for me: 
1. Add TeamSlot.Ghost for cases when servant cannot be matched.
2. Adjust the face card crop region to exclude buff icons to prevent matching failure.

**Comment by DAOWAce** [comment]
Just got this too, coincidentally after updating to the latest canary.

```
null

c4.a$b
	at c4.a.a(AutoBattle.kt:3)
	at a5.c.q(EntryPoint.kt:3)
	at o5.a.run(Thread.kt:1)
```

Is it just due to Space Ishtar?

**Comment by MathewSachin** [comment]
> lastest build 

1534 was latest until yesterday. Try 1536.

Accessibility issue is unrelated, there's a pinned issue. That's something you'll have to follow the steps to solve for yourself.
