### ISSUE TITLE
Failed to determine card type on super-buffed Lancelot on T3

### ISSUE THREAD

**Issue by KagomeKagome** [Fate-Grand-Automata/FGA#920]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1537

### Describe the bug

On turn 3, I'm getting "failed to determine card type" error on Lancelot. It works every other turn, but it always fails on turn 3. I've added a video of what happens in turn 3 when Lancelot face cards are there.

It's happened on every Saber Wars 2 nodes I've done since I updated last night. It also happens on non-event nodes, so it has nothing to do with the bonus damage buffs Lancelot has plus the CE.

Buff order for Lancelot goes
**T1:** Paracelsus Arts, Waver DEF, Waver ATK
**T2:** Paracelsus Guts, Paracelsus NP Gain, Waver Crit, Skadi Quick, Skadi Quick Crit, Lancelot NP Gain (_FALLS OFF START OF T3_), Crit Strength, Crit Star Drop, Crit Star Gather
**T3:** Command Code ATK buff

I saw similar issues with buffs messing with card matching, but I noticed they were said to be fixed. I don't know how fringe this case is, but it's still happening seemingly. Every setting is default as far as I remember.

Team looks as such:
![Screenshot_2021 10 26_07 39 05 987](https://user-images.githubusercontent.com/14761490/138890762-f915cf61-1479-4d59-b140-6b5aaee1f86f.png)

### Video

https://streamable.com/246c5d

### Device model

Bluestacks 5 Pie

### Android version

9

**Comment by nantukoprime** [comment]
Now seeing this issue regularly since the widescreen update on NA. Error crops up when selecting NP or cards, every turn.

Device:
Pixel 4 XL

Android version
12

FGA Build
1551

**Comment by DNLMow** [comment]
Seeing same issue with Arjuna Alter with Merlin buster buff. 

![image](https://user-images.githubusercontent.com/15274651/143947131-35d34fa6-ee9d-48fb-8f6c-7bda5d41ba94.png)
![image](https://user-images.githubusercontent.com/15274651/143947189-a4b07abd-f878-40b8-836c-cba2ad4ddc58.png)
![image](https://user-images.githubusercontent.com/15274651/143947220-45e68009-27c1-4e09-9871-b5025cfb3252.png)
![image](https://user-images.githubusercontent.com/15274651/143947358-5f6b50aa-88f1-4db5-b4a0-5a12bd579e8b.png)
![Untitled](https://user-images.githubusercontent.com/15274651/143947866-19872cc0-3287-4c77-b25a-d421b45602ca.png)

Server:
NA

Device:
Bluestack (S20 Ultra)
1920x1080 240 DPI

FGA Build
1558

RAM
4G

Android version
Bluestack 5.4.50.1009 N32

**Comment by sdarkpaladin** [comment]
Am getting this a lot when someone is super-buffed, usually with a single DPS double support Castoria team. Probably because the icons cover the top part of the card.

**Comment by Shadd1** [comment]
u have some help to fixed this bug!?

**Comment by Spiralem** [comment]
I'm running on FGA canary-1575, and on BlueStack 4, but it seems like the issue is still present.
Some additional image to help troubleshooting... First 2 pic is from the same turn, but different turn, while the 3rd(last) pic is the buffs that is on the servant before command card selection.
![bug](https://user-images.githubusercontent.com/26656490/146672028-5aecada3-ebf1-46b0-8e9f-1bbb6265476a.png)

**Comment by reconman** [comment]
Please try build 1578: https://github.com/Fate-Grand-Automata/FGA/suites/4705002646/artifacts/128879744

**Comment by justinbridouille** [comment]
> Please try build 1579: https://github.com/Fate-Grand-Automata/FGA/suites/4705166993/artifacts/128891252

![WhatsApp Image 2021-12-19 at 23 30 21](https://user-images.githubusercontent.com/44977945/146693174-1b8ca96e-9381-4a2a-8fc8-ccf23bd73aa2.jpeg)

the problem is not solved in build 1579

**Comment by atm153** [comment]
Also encountering the same issue with Dantes/Skadi/Skadi on build 1577 using Bluestacks 5/Android 9 on NA. Can't try 1579 as it looks like it was pulled.

I found a temporary workaround for my purposes at least, turning on "Skip servant face-card checks" prevents FGA from encountering the bug and lets it keep moving forward by just selecting the two leftmost cards.

**Comment by DNLMow** [comment]
Build 1579 fixed the arjuna issue I posted for me.

**Comment by mpetrovic** [comment]
Build 1579 fixed the issue for me as well. It is now selecting the buffed servant's cards and correctly setting up Brave chains.

**Comment by reconman** [comment]
@justinbridouille Try changing Lancelot to 3rd ascension, I bet it will work. His 1st ascension is currently too dark to detect properly.

I have a solution in mind for some better image matching strategy, but for now please test my suggestion.

**Comment by lolcatzidk** [comment]
> I'm running on FGA canary-1575, and on BlueStack 4, but it seems like the issue is still present. Some additional image to help troubleshooting... First 2 pic is from the same turn, but different turn, while the 3rd pic is the buffs that is on the servant before command card selection. Edit: From the 4th (last) pic, it seems that there is no issue detecting superbuffed Musashi... ![bug](https://user-images.githubusercontent.com/26656490/146672028-5aecada3-ebf1-46b0-8e9f-1bbb6265476a.png) ![bug](https://user-images.githubusercontent.com/26656490/146672110-72030262-a21f-45e9-b720-3888962108d1.png)

I am running the same comp as you, and I'm also having the same issues with cards not being detected.

**Comment by reconman** [comment]
@lolcatzidk Update FGA

**Comment by lolcatzidk** [comment]
> @lolcatzidk Update FGA

I downloaded it, but now my Bluestacks doesn't want to even open now..

**Comment by Hebelios** [comment]
Hey, I updated to 1597 and play on JP.
It still doesn't seem to work for me. I'm running via Nox-Player.

I am running a Melusiné team in the Beast-Raid right now.
Servant is in 1st sprite, cards are in 2nd sprite (now that I write it out that might be the problem?).

It worked for a while when adjusting the similarity-value but then stopped again.
![image](https://user-images.githubusercontent.com/74915897/147414141-72c55631-a209-4e9e-953b-f20b210f3dd8.png)

**Comment by reconman** [comment]
@Hebelios Using a different portrait or adjusting the similarity should have 0 effect. The servant detail screen is used for matching, which just contains the selected sprite.

And the Failed to Determine message should only appear if the similarity between the face cards and the detail sprite was below 50 %.

If something like this happens again, I'll need a video with debug rectangles, including the first round where the detail windows are opened.
