### ISSUE TITLE
Support selection: Refresh as soon as refresh is available

### ISSUE THREAD

**Issue by Hebelios** [Fate-Grand-Automata/FGA#922]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Add a (I suppose app-wide would be best) option to refresh support lists as soon as refresh becomes available.

During events it's quite easy and a lot faster to just pre-filter supports for your desired event-CE (even LB'd if you so desire). That reduces the pool of available support-entries by a huge number and you might need a refresh or three to get your favoured support.

The way support-selection works right now is that it scrolls a set number of times to look for a fitting servant before refreshing.
When the list of servants is ~4ish entries long it wastes a lot of time "scrolling" through a list of supports that shows on one screen. So I suggest a variant of support-selection where it just refreshes as soon as the refresh is available again.
Going for "friends only" is not a good workaround, as you increase your chances by a huge margin if you go for non-friends as well. 

For JP at least it should be quite easy to implement, as the refresh button is greyed out, when it's not available.

**Comment by MathewSachin** [comment]
You could just set `More options/fine tune/Support/swipes per update` to 0.

It will refresh after the required 10 seconds have passed.
I don't feel like adding another setting for this when it can be already achieved through existing ones.
