### ISSUE TITLE
CE selection: FP-Lots

### ISSUE THREAD

**Issue by Hebelios** [Fate-Grand-Automata/FGA#923]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

When selecting which CE is to be used with a script, may I ask for some of the FP-Point options?
JP added a few additional FP-CEs over the last couple of months, so it would be helpful to have them in as well.

[Beyond the Night Without the Snow Flower](https://fategrandorder.fandom.com/wiki/Beyond_the_Night_Without_the_Snow_Flower) and [Into the Ethereal Veil](https://fategrandorder.fandom.com/wiki/Into_the_Ethereal_Veil) are viable, the spiritrons are probably a pain in the ass to implement.

EDIT:
And [Beyond The Rain Cloud](https://fategrandorder.fandom.com/wiki/Beyond_The_Rain_Cloud) as well of course.
As the crypter-CEs would probably clutter the selection-screen maybe one can filter/organize the CEs in accordance to their effect? i.e. folders for QP, Bond, FP, Combat and the like?

**Comment by MathewSachin** [comment]
You can use `Support Image Maker` to add any servant/CE images you want.
We don't want to bundle too much stuff by default in the app, so you can DIY for what you need.

You could also just use a file manager to put the CE images in folders for QP, Bond, etc.
Making an in-app interface for this is not worth it.
