### ISSUE TITLE
Make FGA check the selected class when selecting supports even if there were no supports found after the filter

### ISSUE THREAD

**Issue by The-Intelligent-One** [Fate-Grand-Automata/FGA#924]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

This might fit better as a bug, but I'm not sure how intended it is, so I decided to write it as a suggestion. Currently, if the support list contains no servants (because the event filters filter out everyone on the currently selected class's list) the script immediately goes to refresh the support list, and repeat that until there's at least one result.

The problem is when the currently selected class list is not the one that the script is supposed to check. For example, let's say the script is set to get the first result of the caster support list, but the node is actually a lancer node, so the game defaults to displaying the saber support list at first. If the saber support list has no supports appearing, the script will keep refreshing the list until it gets a servant on the saber support list, as opposed switching to the caster support list, and _then_ checking if there are supports available or if it has to refresh.

**Comment by MathewSachin** [comment]
Like @the3dsandwich said, you have to turn that option OFF. it's been like than since forever.

**Comment by The-Intelligent-One** [comment]
Turning it off solves it mostly, but not 100% because the next time you want to run a different script with a different preferred class it happens again and needs to be fixed by forcibly choosing the class on the support screen.

Obviously this isn't a huge issue or anything, it just doesn't make sense to me that the first thing FGA does is try to refresh the support list instead of actually making sure that the correct class is selected and _that_ list is what's empty. That's why I wanted to bring it up
