### ISSUE TITLE
This error is making script stop

### ISSUE THREAD

**Issue by BhupenKDot** [Fate-Grand-Automata/FGA#930]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Device: s10+
Jp server 

[null

c4.a$b
![Screenshot_20211031-024010_FateGO](https://user-images.githubusercontent.com/26735354/139558461-b707b2ef-1c9d-4ec9-b97e-d4fa01880f64.png)

	at c4.a.b(AutoBattle.kt:3)
	at a5.c.q(EntryPoint.kt:3)
	at o5.a.run(Thread.kt:1)
]

**Comment by reconman** [comment]
Not a question, open again as a bug report.
