### ISSUE TITLE
Working for JP not for NA

### ISSUE THREAD

**Issue by w-san** [Fate-Grand-Automata/FGA#932]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA, JP

### FGA build number

1540

### Describe the bug

I can use FGA v1540 fine on JP but not on my NA.

I just have a video of NA

### Video

https://www.youtube.com/watch?v=rmAm7zXopTY

### Device model

Xiaomi Mi 10t lite 5G

### Android version

11

### Screen size

1080 x 2400

### RAM

8 gb

**Comment by MathewSachin** [comment]
> Video unavailable
This video is private.

**Comment by w-san** [comment]
Opps sorry fixed the link

**Comment by sdarkpaladin** [comment]
From the video you posted, I think it seems like it is trying to detect JP size.

Have you checked whether you (1) set the app up for JP only or (2) did you disable notch calculation?

**Comment by w-san** [comment]
i've tried a few one and since i have accessibility for it is should be able to auto detect. and i tried disable and enable notch calculation and i have gotten either the same not working or doing weird stuff.

**Comment by w-san** [comment]
Okay it works but it now targets the wrong target.

also it is meant to open the servant's status screens now on wave 1?

https://www.youtube.com/watch?v=U3f7E0wvmpA
