### ISSUE TITLE
Nothing is being clicked when the overlay is active

### ISSUE THREAD

**Issue by Halcyon15** [Fate-Grand-Automata/FGA#934]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1546

### Describe the bug

When the overlay is active, I am not able to press any buttons on the screen.
I tried running a script, but nothing is clicked. Seems like the overlay is not clicking anything or Android 12 is blocking it.
The only way to leave is to bring up the overlay menu and go back to the home screen.

### Video

I'm not able to screen record because any time I try to record it, the overlay won't let me record past the time I enable FGA. I know this isn't the best but I've even tried third party apps and they've all been stopped as the FGA service is started.

### Device model

Pixel 4 XL

### Android version

12

**Comment by MathewSachin** [comment]
See #734

**Comment by chaoticnote** [comment]
> See #734

I don't know how to use Android Studio, use ADB, or even how to open ADB.
