### ISSUE TITLE
Latest release no longer working (accidentally closed)

### ISSUE THREAD

**Issue by Marrionetta** [Fate-Grand-Automata/FGA#938]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1547

### Describe the bug

So I'm using a Samsung 20 Note Ultra (or something to that effect) and up until now every single build has worked flawlessly. I was always able to run fga straight out of the proverbial box without needing to alter any settings and I was able to leave the ignore notch calc unchecked.

After updating the app however, when loading into a fight and launching a script, it will click on a character image over and over again and not actually do what it's supposed to.

I tried enabling ignore notch even though the borders don't intersect the notch and for whatever reason, it started functioning as intended. Sorta.

The first turn would work, no matter what line up I used but would return an error when selecting cards.

It would perfectly select the cards for turn one but would return a "Failed to Determine Card Type: [1, 2, 3, 4, 5]".

The following turn, the script would ignore the rest of the command and immediately start mashing random face cards. 

I've seen similar issues in other threads but nothing that helped me. Is it possible to get the previous build? That one worked fine for me. 

The only thing I could think of is my screen dimmer overlay but I have it on all the time and used to be able to leave it on for 8 hours with the screen so heavily dimmed you could barely make out the characters.

### Video

https://streamable.com/bn134l

### Device model

Samsung Galaxy Note20 Ultra 5G

### Android version

11

### Screen size

2316x1080

### RAM

11GB

**Comment by reconman** [comment]
Can you disable Ignore Notch and record another video? The rectangles seem off to me in your existing video.

**Comment by Marrionetta** [comment]
Yeah. Here's what happens without it

https://streamable.com/rm0th4

**Comment by Marrionetta** [comment]
I guess there's nothing that can be done anymore?
I guess the wide screen update broke my phone's campatability due to my phone's native and unusual resolution...?

**Comment by reconman** [comment]
Other users with similar phones have it working.

I'm still seeing wrong rectangle positions, maybe restarting the FGA service will help?

Also don't place your play button in the top left, that's needed for Support selection. Keep it in the bottom left.

**Comment by Marrionetta** [comment]
> Other users with similar phones have it working.
> 
> I'm still seeing wrong rectangle positions, maybe restarting the FGA service will help?
> 
> Also don't place your play button in the top left, that's needed for Support selection. Keep it in the bottom left.

I've naturally restarted it many times in the 29 days since I've posted this problem. Nothing I do fixes this "wrong rectangle" problem.

**Comment by reconman** [comment]
Did you ever try disabling the dimmer?

I'm not even sure why you need it when you can turn down the screen brightness. That way, FGA can still see normal colors.

**Comment by Marrionetta** [comment]
> Did you ever try disabling the dimmer?
> 
> I'm not even sure why you need it when you can turn down the screen brightness. That way, FGA can still see normal colors.

Because some people are sensitive to light and the screen brightness won't lower past a certain point.

The dimmer has no effect on fga as I was able to make my screen pitch black, leave it on all night while I slept and fga was able to farm lotto effortlessly all night into the morning.

But naturally, during the day, I don't have it on. It still doesn't work.

**Comment by reconman** [comment]
Between the first and second video, you changed full screen settings for FGO, right?

Is FGA also set to full screen?

**Comment by Marrionetta** [comment]
> Between the first and second video, you changed full screen settings for FGO, right?
> 
> Is FGA also set to full screen?

No both fga and fgo don't have full screen enabled. I've never changed the settings for either of them. They were always disabled. I had actually hoped they were enabled so I could fix the problem but it didn't. I suppose I could try enabling full screen for fga tho and see what happens

**Comment by Marrionetta** [comment]
Nope nothing has any effect. Still does the exact same thing no matter what I do. Only enabling ignore notch calc changes its behavior
https://streamable.com/gft75l

**Comment by reconman** [comment]
The last video looks kinda correct. Is there something going wrong?

**Comment by Marrionetta** [comment]
> The last video looks kinda correct. Is there something going wrong?

What do you mean? Everything is going wrong. It's not even touching the skills. It's exclusively touching character portraits. Isn't that the very definition of something going wrong?

**Comment by reconman** [comment]
See the last question in the troubleshooting guide linked when you submitted the issue.

**Comment by Marrionetta** [comment]
Oh wat? Is that what that "skip servant face check" option is related to?

**Comment by Marrionetta** [comment]
Okay so I let it run thru the screen shorting and it does indeed work as intended and I'm no longer getting the read error message. I probably will be disabling it however unless there's a way to enable that setting on certain scripts since many of my scrips don't really care which cards are being punched but thanks for the help nonetheless!
