### ISSUE TITLE
the play button wont work even if everything is right in bluestacks

### ISSUE THREAD

**Issue by Auboreus** [Fate-Grand-Automata/FGA#941]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1551

### Describe the bug

i used to farm with a old version of fga, need to uninstall bluestacks and now even playing in 32 bits, configuring right and trying to uninstall and install again, it does not work, i tried searching and instaling older versions to see if works but cant find anyone to try.

### Video

https://www.youtube.com/watch?v=0M_ejw7cwrA

### Device model

One Plus 5

### Android version

7

### Screen size

1600x900

### RAM

4gb

**Comment by notfideh123** [comment]
yeah im also experiencing the same issues, when i click the play button the script window not showing like it did before

**Comment by MLeongQA** [comment]
Also experiencing this issue. Screensize 1280x720 for me though.

**Comment by reconman** [comment]
Use Bluestacks 5, follow the troubleshooting guide and https://github.com/Fate-Grand-Automata/FGA/issues/967#issuecomment-974652785
