### ISSUE TITLE
Nothing happened with Samsung S20 FE

### ISSUE THREAD

**Issue by Yokanime** [Fate-Grand-Automata/FGA#942]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1547

### Describe the bug

No matter where I am in-game, FGA isn't able to detect anything. I can't even record the screen but I took a screenshot of the debug mode: http://imgur.com/a/njA3Wr3 It's exactly the same thing whether I am in fight, selecting a servant, rolling FP, in my present box, etc. I tried activating/deactivating notch, selected the NA server, tried activating the full screen mode but nothing changed

### Video

Can't record with FGA, I have an error

### Device model

Samsung S20 FE

### Android version

11

### Screen size

2400 x 1080

### RAM

6 Go

**Comment by clse0190** [comment]
Same here. Xperia 1 III with android 11.

I think android 11 change something about accessibility so FGA can't get screen correctly.

**Comment by reconman** [comment]
@Yokanime Set FGO and FGA to full screen mode in your display settings and xou might need to activate Ignore Notch.

@clse0190 See #845 and #1000.

**Comment by Yokanime** [comment]
> @Yokanime Set FGO and FGA to full screen mode in your display settings and xou might need to activate Ignore Notch.

That's exactly my config and I already tested with and without Fullscreen for both applications and with and without notch https://imgur.com/a/5QRky3L

**Comment by reconman** [comment]
Okay, the rectangles look fine but what's your error that prevents you from recording your screen?

**Comment by Yokanime** [comment]
The application crashes as soon as I start a script https://imgur.com/a/c8z19U4

**Comment by reconman** [comment]
Maybe FGA can't create the video file? Which folder is selected in `More options` -> `Storage`?

**Comment by Yokanime** [comment]
It's in my SD Card  https://imgur.com/a/BLYHLgb And I thus discovered that a video file was created but it's 0MB so there is nothing

**Comment by reconman** [comment]
Can you try what happens if you move the folder to somewhere on the main device?

I think there's some issue with SD cards.

**Comment by Yokanime** [comment]
Move it to the phone memory 
![Screenshot_20211211-232437_Files](https://user-images.githubusercontent.com/93881757/145693452-08105501-9b90-4213-88ff-a2cf3823b80c.jpg)
 but same result :(
