### ISSUE TITLE
Widescreen support for NA

### ISSUE THREAD

**Issue by jcdeoferio** [Fate-Grand-Automata/FGA#948]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

https://fate-go.us/news/?category=UPDATES&article=%2Fiframe%2F2021%2F1114_gameupdate_notice%2F

NA rolled out the widescreen changes today

**Comment by AeroXV** [comment]
As a temporary fix, you can swap FGA's server setting to JP but you will have to manually start the node every time, including picking support. It will do the battle and nothing else, you have to advance the results screen as well.

**Comment by tateMode** [comment]
> As a temporary fix, you can swap FGA's server setting to JP but you will have to manually start the node and restart the script every run, including picking support. It will do the battle and nothing else, you have to advance the results screen as well.

For me, this workaround does not work. If I set the Game Server setting under "More options" to JP and start the script in battle like suggested, it will play the first wave properly (i.e., 1. tap each servant to check their NP cards then 2. follow inputs according to script), but from the second wave, it will just start selecting random face cards and finish the battle that way. It will then stall on the item drop screen.

If I set the Game Server setting to Auto or NA and start the script on the Support Select screen, it will select the proper support servant, start the battle, and complete the first wave as expected. However, it will also fail on the second wave like described above.

Google Pixel 2 XL
canary-1551

**Comment by AlexGama11** [comment]
> > As a temporary fix, you can swap FGA's server setting to JP but you will have to manually start the node and restart the script every run, including picking support. It will do the battle and nothing else, you have to advance the results screen as well.
> 
> For me, this workaround does not work. If I set the Game Server setting under "More options" to JP and start the script in battle like suggested, it will play the first wave properly (i.e., 1. tap each servant to check their NP cards then 2. follow inputs according to script), but from the second wave, it will just start selecting random face cards and finish the battle that way. It will then stall on the item drop screen.
> 
> If I set the Game Server setting to Auto or NA and start the script on the Support Select screen, it will select the proper support servant, start the battle, and complete the first wave as expected. However, it will also fail on the second wave like described above.
> 
> Google Pixel 2 XL canary-1551

I've also had script issues after the update, with the ai not spamming skills and nps as I asked. there have also been issues with selecting the right boxes. pictures below.

![Screenshot_20211116_122227_com aniplex fategrandorder en](https://user-images.githubusercontent.com/52133865/141984993-5b6d9b2c-7f71-4a0c-9e4b-f63d80c07bc4.jpg)
1116_122149_com.aniplex.fategrandorder.en.jpg…]()

![Screenshot_20211116_122155_com aniplex fategrandorder en](https://user-images.githubusercontent.com/52133865/141985060-cd90704a-2b14-4afa-940a-087718e683f5.jpg)

![Screenshot_20211116_121737_com mathewsachin fategrandautomata debug](https://user-images.githubusercontent.com/52133865/141985082-1752af79-6cab-4425-b24e-448da7729ccc.jpg)

![Screenshot_20211116_122149_com aniplex fategrandorder en](https://user-images.githubusercontent.com/52133865/141985193-bf8f44ed-8176-49b2-8bc7-35c8578ea707.jpg)

![Screenshot_20211116_121607_com aniplex fategrandorder en](https://user-images.githubusercontent.com/52133865/141985213-8c276c2b-e466-405a-ad23-4b85a4a04a0c.jpg)

![Screenshot_20211116_121640_com aniplex fategrandorder en (1)](https://user-images.githubusercontent.com/52133865/141985232-5c2b7c48-982a-44f9-84b5-9facbe08e805.jpg)

**Comment by Santicx** [comment]
So is there any solution yet. For my case they made the game even worse 
![Screenshot_20211116-151542931](https://user-images.githubusercontent.com/61398201/142001689-1a837c32-8b65-47cd-bc62-b1c68a4038b6.png)
![Screenshot_20211116-151534696](https://user-images.githubusercontent.com/61398201/142001702-e128caba-165d-4fb9-993b-f06ecacdf1d0.png)

The AI recognizes only when the battle is over
