### ISSUE TITLE
Question about older  canary builds. 

### ISSUE THREAD

**Issue by tyaty1** [Fate-Grand-Automata/FGA#952]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Could you rerelease the latest build which was designed for the JP 2.23's UI? 
Because it could work on the NA 2.23 version.

**Comment by reconman** [comment]
We're already working on a fix for NA. The old release won't work since there are some different button texts in JP and US.
