### ISSUE TITLE
Skills are not being used on second and third wave. 

### ISSUE THREAD

**Issue by TsubasaNoNai** [Fate-Grand-Automata/FGA#953]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1554

### Describe the bug

Skills are not being used on the second and third wave, and looking at the debug mode, it looks like it's not trying to match anything in the area for Waver's skills from the second turn onward, but I'm not sure how it's intended to behave there.  

Here's the command that I'm using for the battle config. 
<img width="236" alt="Screenshot 2021-11-16 at 19 09 19" src="https://user-images.githubusercontent.com/43218857/142041444-62016de0-9120-4173-83a3-a7c278cfc484.png">
 

### Video

https://streamable.com/ruhe1d

### Device model

Bluestacks 4 for Mac

### Android version

7

### Screen size

1280x720

### RAM

8GB allocated

**Comment by potchy** [comment]
I think it's only affecting 16:9 resolutions.
It's working perfectly on my phone (2246x1080), but not on Nox (960x540).
The battle counter region seems to be misaligned.

![image](https://user-images.githubusercontent.com/4316326/142049521-3d2f2704-b220-42bc-9068-7df21c6f0751.png)

**Comment by JoshStegmaier** [comment]
> Can you check if activating `More Options -> Advanced -> Thresholded state counter detection` helps?

I'm having this same issue. I enabled that setting, but unfortunately the issue remained.

**Comment by hieutieuho** [comment]
I got same issue with pixel 4, and np also did not work on wave 2 and 3

**Comment by TsubasaNoNai** [comment]
> Can you check if activating `More Options -> Advanced -> Thresholded state counter detection` helps?

Should've checked that beforehand, my apologies. It gives the same results. 

https://streamable.com/tsv0i7 is the (choppy, sorry) video if it helps.

**Comment by Rajvir8** [comment]
I'm having the same issue, also as a side note is their any easy way to downgrade back to Version 1551?

That version managed to run my skills properly, it just couldn't click next at the end, I'd rather just manually have to start a round again, than have it break, and I can always record another Macro advancing it, at least while I'm doing the same quest.

**Comment by reconman** [comment]
> I'm having the same issue, also as a side note is their any easy way to downgrade back to Version 1551?

You'll lose your settings because you have to deinstall FGA before you can install the old version again.

https://github.com/Fate-Grand-Automata/FGA/suites/4276603852/artifacts/111300908

**Comment by Rajvir8** [comment]
Thank you for the older version, I suppose I'll just have to Export my Auto's again.

And copy them back in.

**Comment by Tom3kk** [comment]
For me it for some reason taps on all 3 servants as if it wants to read the details and only then uses skills but doesn't use NP on wave 2, and refuses to go past the item drop screen after clearing..

**Comment by Djinnistorm** [comment]
> 
> 
> I think it's only affecting 16:9 resolutions. It's working perfectly on my phone (2246x1080), but not on Nox (960x540). The battle counter region seems to be misaligned.
> 
> ![image](https://user-images.githubusercontent.com/4316326/142049521-3d2f2704-b220-42bc-9068-7df21c6f0751.png)

Changing Bluestack's resolution to an ultrawide resolution, 2560x1080, **does** cause the script to behave normally. This is most likely the cause of the issue. Based on other issues popping up, it's likely not the only issue 16:9 resolutions are having atm.

**Comment by ChaoticVice777** [comment]
> > I think it's only affecting 16:9 resolutions. It's working perfectly on my phone (2246x1080), but not on Nox (960x540). The battle counter region seems to be misaligned.
> > ![image](https://user-images.githubusercontent.com/4316326/142049521-3d2f2704-b220-42bc-9068-7df21c6f0751.png)
> 
> Changing Bluestack's resolution to an ultrawide resolution, 2560x1080, **does** cause the script to behave normally. This is most likely the cause of the issue. Based on other issues popping up, it's likely not the only issue 16:9 resolutions are having atm.

I just tried your solution by upgrading from my original resolution of 1600 x 900 to an ultrawide resolution, 2400 x 1080. Finally, my scripts are running properly. I do hope the 16:9 resolution errors are resolved promptly.

**Comment by enfyrneaux** [comment]
> 
> 
> For me it for some reason taps on all 3 servants as if it wants to read the details and only then uses skills but doesn't use NP on wave 2, and refuses to go past the item drop screen after clearing.. Though interestingly, besides the tapping on each character before using skills - it works on my galaxy note 9.

I'm running into a similar issue with a Galaxy Tab S5e, tapping on servant portraits in wave 1 and it's not tapping any skills for wave 2.

**Comment by JusKIdding** [comment]
> > For me it for some reason taps on all 3 servants as if it wants to read the details and only then uses skills but doesn't use NP on wave 2, and refuses to go past the item drop screen after clearing.. Though interestingly, besides the tapping on each character before using skills - it works on my galaxy note 9.
> 
> I'm running into a similar issue with a Galaxy Tab S5e, tapping on servant portraits in wave 1 and it's not tapping any skills for wave 2.

Same issue for me too in Samsung Galaxy J7 Prime. Same problem as back in build 1551

**Comment by tateMode** [comment]
> > > For me it for some reason taps on all 3 servants as if it wants to read the details and only then uses skills but doesn't use NP on wave 2, and refuses to go past the item drop screen after clearing.. Though interestingly, besides the tapping on each character before using skills - it works on my galaxy note 9.
> > 
> > 
> > I'm running into a similar issue with a Galaxy Tab S5e, tapping on servant portraits in wave 1 and it's not tapping any skills for wave 2.
> 
> Same issue for me too in Samsung Galaxy J7 Prime. Same problem as back in build 1551.
> 
> Wave 1 tap portrait then use skill and NP, wave 2, tap portrait and nothing.

The tapping of portraits in wave 1 is expected behavior. It does this to check each servant's face cards once per run, for use with the servant priority feature, which was not present in the old app store build and earlier canary builds. See #730.

**Comment by MathewSachin** [comment]
Seems like this image: https://github.com/Fate-Grand-Automata/FGA/blob/6a035ff4037040a780d25fcd9c414daaefbb86b2/app/src/main/assets/En/battle_menu.png
isn't matching properly on 16:9. I think it needs to be cropped.
Location of stage counter and master skills depend on this image matching.

**Comment by chaoticnote** [comment]
Pixel 4a 5G user. Phone has resolution of 1080 x 2340 pixels, 19.5:9 ratio (~413 ppi density). FGA sometimes misclicks Servant Skills for me and instead taps on Servant Details/Status.

**Comment by chaoticnote** [comment]
> > > > For me it for some reason taps on all 3 servants as if it wants to read the details and only then uses skills but doesn't use NP on wave 2, and refuses to go past the item drop screen after clearing.. Though interestingly, besides the tapping on each character before using skills - it works on my galaxy note 9.
> > > 
> > > 
> > > I'm running into a similar issue with a Galaxy Tab S5e, tapping on servant portraits in wave 1 and it's not tapping any skills for wave 2.
> > 
> > 
> > Same issue for me too in Samsung Galaxy J7 Prime. Same problem as back in build 1551.
> > Wave 1 tap portrait then use skill and NP, wave 2, tap portrait and nothing.
> 
> The tapping of portraits in wave 1 is expected behavior. It does this to check each servant's face card once per run, for use with the servant priority feature, which was not present in the old app store build and earlier canary builds. See #730.

I see now. Although, I've encountered a new issue. I'm not certain if this is a Pixel 4a 5G unique issue or not because the phone has a god-awful front-facing camera in the screen's corner. In any case, when my phone's front-facing camera (or screen-side camera) is oriented on the bottom-side during horizontal mode, FGA has trouble detecting the second servant's portrait and then proceeds to activating the leftmost (first) Servant's skill 1 but fails. The skills of the second Servant's are activated, but then the portrait of the third servant is tapped on.

Overall, I think for the Pixel 4a 5G, FGA only works properly on one horizontal side. On the side it doesn't, it doesn't screen all the Servant portraits properly and then will fail to activate some Servant Skills on wave 1.

**Comment by potchy** [comment]
Please check if build 1555 solves this issue for you guys.

**Comment by JoshStegmaier** [comment]
> Please check if build 1555 solves this issue for you guys.

Works perfectly for me. Thanks!

**Comment by TsubasaNoNai** [comment]
> Please check if build 1555 solves this issue for you guys.

Fixed here as well. Thank you very much.

**Comment by Rajvir8** [comment]
Fixed here as well with version 1556, thanks for managing to work on the issue so fast.  I was more than prepared for it to take around a week potentially, as 1551 was good enough to handle this week of dead time.

But nice to remove any and all worry, although it does still mention failed to determine card type in wave 2.  I can't honestly say I mind, and it might because it's facing a wave of pure Berserkers.  It still picks Buster first to go with the NP so it's working perfectly as far as I'm concerned.

**Comment by JusKIdding** [comment]
> Please check if build 1555 solves this issue for you guys.

Did not manage to download 1555, but tried 1556, it works perfectly. 

Thank you devs for all your hard work (bow)

**Comment by enfyrneaux** [comment]
Can confirm fixed on 1556.  Thank you!
