### ISSUE TITLE
Mystic code skills not being tapped properly on 16:9 devices

### ISSUE THREAD

**Issue by Skyjersey** [Fate-Grand-Automata/FGA#956]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1554

### Describe the bug

The tapping is a bit off to the left and will not tap any of the mystic code skills. Order change also does not work.

### Video

Video shows Waver s2 and s3 then activating order change but fails to open the MC skills menu.

https://user-images.githubusercontent.com/10911891/142080159-009b8dea-c7c3-4857-a252-6c361463fd3f.mp4

### Device model

Xiaomi Mi Max 1 Prime

### Android version

11

### Screen size

1920x1080

### RAM

4GB

**Comment by tateMode** [comment]
Can confirm this also happens on my Pixel 2 XL, which has a 2880 x 1440 screen size and 18:9 aspect ratio. The taps for the Mystic Code appear shifted left of where they should be, maybe by the width of the "Skill" button used to open the MC drawer.

**Comment by chaoticnote** [comment]
Pixel 4a 5G user, a phone that has 1080 x 2340 pixels and 19.5:9 ratio. Android 12. For me, it's misclicking several Servant Skills.

**Comment by reconman** [comment]
Should be fixed by build 1556.
