### ISSUE TITLE
App doesnt work correctly with latest build 

### ISSUE THREAD

**Issue by jacknguyen0911** [Fate-Grand-Automata/FGA#957]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1554

### Describe the bug

The app cannot detect friend support, face cards, skills...

### Video

https://www.youtube.com/watch?v=il5J1bTBN-8

### Device model

Samsung Galaxy S20+ 5G

### Android version

11

### Screen size

1440 x 3200

**Comment by brightEcho** [comment]
I also have the same phone (samsung galaxy plus ultra, android 11), and I'm experiencing the same issues as well. This new update really broke something.

**Comment by Misterdark** [comment]
Samsung S20+ here. There is a partial fix for this, go to your phone setting and search for full screen apps. Toggle it for the game, it should work now although it is a little buggy (randomly selects servants and fails to determine card type).

**Comment by magmacane** [comment]
Whenever I run, it also randomly selects my first servant before using the skills

**Comment by decentblack** [comment]
Same issue
Can't select friend support, uses random skills if I choose a support and start it in battle

**Comment by AKSoo** [comment]
> Whenever I run, it also randomly selects my first servant before using the skills

This and the script pauses after every step, requiring manual restart. The latest update broke many things.

**Comment by reconman** [comment]
First of all, you're using a screen recorder and not FGA so at that point FGA can't see anything anymore.

It's only fixed by at least restarting the FGA service.
