### ISSUE TITLE
FGA can't start

### ISSUE THREAD

**Issue by SirRHellsing** [Fate-Grand-Automata/FGA#959]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1554

### Describe the bug

I just switched from 1540 to 1554 and now I have a problem when it said

FGA (Cl) will start capturing everything that is displayed on screen.

I can't press the start now button. I can import, add and do everything else just fine. It just won't start when I click the start serivce

This isn't a problem with the 1540 version. I have it on my PC as well so I tried both versions, the 1540 version has the problem of not clicking next when I'm on the drops screen which is why I tried updating but doesn't have the problem I mentioned above wit the 1554 version

### Video

https://youtu.be/_-Qq4MzIQ5o

### Device model

Lenovo T570

### Android version

11

### RAM

8GB

**Comment by SirRHellsing** [comment]
I just used the debugger on 1540 and the reason it is stuck on the drop screen is because now the drop screen is a popup so fga runs the same battle script as it didn't detect screen change

**Comment by chaoticnote** [comment]
Check to see if the app has unrestricted battery usage. The play button didn't pop up for me until I changed the setting to unrestricted.

**Comment by alteos98** [comment]
I have the exact same problem, I tried to jump to version 1554 this morning and now to 1556 coming from 1547. In version 1547 I could start FGA but it stays in the drops screen without clicking Next. In versions 1554 and forward I couldn't start FGA.

**Comment by SirRHellsing** [comment]
I got a fix from others just now, rotate your bluestacks and then you can start 1554+

**Comment by reconman** [comment]
@SirRHellsing Do you still have a problem?

**Comment by SirRHellsing** [comment]
nope
