### ISSUE TITLE
Has anyone been able to get 1554 release to work with Bluestack 5?

### ISSUE THREAD

**Issue by jacknguyen0911** [Fate-Grand-Automata/FGA#961]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

As title says, I got it to work on phone struggling on emulator. If anyone is able to help, thank you.

**Comment by reconman** [comment]
See #623 and #953
