### ISSUE TITLE
Context sensitivity don't work properly

### ISSUE THREAD

**Issue by tyaty1** [Fate-Grand-Automata/FGA#962]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1555

### Describe the bug

Context-sensitivity doesn't work anywhere.

### Video

https://youtu.be/vUL29jHQss0

### Device model

Huawei Mate 9

### Android version

9

### Screen size

1920*1080

### RAM

4GB

**Comment by reconman** [comment]
What is context sensitivity? Also your video is private.

**Comment by tyaty1** [comment]
The functionality where the program recognizes which cp ods scripts should it run.
Right now it can on run the auto-battle, regardless of where I start it.

**Comment by reconman** [comment]
First of all, you're recording your screen, so unless you use root mode for FGA, it can't see anything but a black screen.

**Comment by MathewSachin** [comment]
Using other recorders usually screws up FGA. This is stated around the top of troubleshooting guide.
Additionally, gift box script only works when there's embers on the screen.
And, Huawei phones have notorious battery optimization which we can't help with.
