### ISSUE TITLE
Troubleshooting on widescreen 

### ISSUE THREAD

**Issue by Np100ops** [Fate-Grand-Automata/FGA#963]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1556 

### Describe the bug

I have tested the last version on both servers NA and JP and I have the same problem with the troubleshooting of the skills, mystic code and nps on my phone. 

### Video

https://user-images.githubusercontent.com/94489293/142299320-5a79008e-930b-40d0-afd7-057b8d6ab93b.mp4

### Device model

Samsung S20 FE

### Android version

11

### Screen size

1080 x 2400 px

### RAM

6gb

**Comment by reconman** [comment]
Need to see a longer video where you're not in the face card selection screen.

**Comment by Np100ops** [comment]
> Need to see a longer video where you're not in the face card selection screen.

**Comment by reconman** [comment]
So what's the problem?

**Comment by Np100ops** [comment]
I see, i was make some mistake on the program code, sorry for the this,  and thanks for answer.
