### ISSUE TITLE
possible alignment issues on phones with gesture control?

### ISSUE THREAD

**Issue by Wingi91** [Fate-Grand-Automata/FGA#965]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

well i have trouble describing into words what exactly i have discovered so i dont want to open another bug ticket unnecessarily but i hope the video will clear this up a lot better. 

basically if my phone is set to the android gesture control, FGA doesnt work whatsoever (no support select, no skills, no battles). its like it isnt properly aligned with the fgo app (it was before the fullscreen update).

but weirdly if i set the phone to the 3-button-control, fgo somehow moves over to "complete fullscreen" where it doesnt leave out the punchhole anymore for the selfie camera. there fga works flawlessly.

[fgo with android gesture control](https://youtu.be/0qzqwWiwPOg) 
[fgo with android 3-button-control](https://youtu.be/vNf_hnDrQio)

in case this is some kind of unique issue only affecting my type of phone model heres some more info about the phone itself:

fga version: 1556
phone: Google Pixel 5
resolution: 2340x1080
RAM: 8 GB

**Comment by brightEcho** [comment]
I've tried enabling 3-button control for my device (samsung galaxy S20 ultra), and while it fixes the issue of not being able to progress pass the friend selection screen, once I'm actually in battle the button press alignment is still off to the point where it still misses all of the servant skills and master skills.

**Comment by Wingi91** [comment]
> I've tried enabling 3-button control for my device (samsung galaxy S20 ultra), and while it fixes the issue of not being able to progress pass the friend selection screen, once I'm actually in battle the button press alignment is still off to the point where it still misses all of the servant skills and master skills.

not a dev and got no idea what in talking about but does your fgo app also go complete full screen where it doesn't leave space for the notch / punch hole?

**Comment by reconman** [comment]
@Wingi91 Your issue is already covered by the wiki: https://github.com/Fate-Grand-Automata/FGA/wiki/Game-Area-detection#how-fgo-should-look-with-wide-screen-update

My own phone has gesture control and still works, but for some phones it doesn't. We can't really change the app for every device since we can't test it against anything but our own phones.
