### ISSUE TITLE
Unable to start service on Bluestacks

### ISSUE THREAD

**Issue by codingcode2codecode** [Fate-Grand-Automata/FGA#967]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1556

### Describe the bug

Whenever I click start service the "start now" button is unable to be pressed.

I have on compatibility mode as recommended (I searched up the issue and it seems the previous individual with this issue did not).

I recently uninstalled and reinstalled the app. It was working perfectly before, I've tried creating new instances of blue stacks and installing FGA there with no luck.

To replicate please download a fresh instance of FGA onto a blue stacks 32bit instance and try to start the service after giving the appropriate permissions.

### Video

Was not able to record as I was unable to start service
![Capture](https://user-images.githubusercontent.com/43768565/142562519-6f7b1916-1801-47d4-b2c2-67d231fc6394.PNG)

Here is an image to show the screen i'm stuck on. The "start service" button doesn't do anything however the cancel button works. When I exit the app after unsuccessfully starting the service I can see the play button flash on the bottom left corner sometimes.

### Device model

Samsung Galaxy S8 Plus (Bluestacks 32bit)

### Android version

7

### Screen size

1600x900

### RAM

2

**Comment by ArthurZCB** [comment]
I'm having the same problem. Another thread suggested rotating on bluestack fixes it but it didn't work for me.

**Comment by QQHgenz** [comment]
you can resize the screen (720x1280)

**Comment by ArthurZCB** [comment]
> you can resize the screen (720x1280)

I resized it but I still can't click Start Now.

**Comment by MathewSachin** [comment]
I've verified myself that rotating is enough for latest Bluestacks with FGA 1556.

1. Switch to portrait orientation.
2. Start Service is portrait orientation.
3. Switch to Landcape.

You only have to do this the first time anyways if you click the 'Don't ask me again' checkbox.

**Comment by codingcode2codecode** [comment]
Thank you rotating worked for me

**Comment by uhnini** [comment]
rotating isn't working for me?? i use fga on bluestacks 4 and switched the portrait and started in portrait and switched to landscape but it still didn't do anything

**Comment by MathewSachin** [comment]
I mentioned latest Bluestacks which is Bluestacks 5, try updating

**Comment by uhnini** [comment]
sorry i forgot to mention i tried doing it on bluestacks 5 but fga just freezes completely

**Comment by MathewSachin** [comment]
that means you didn't set compatibility mode. troubleshooting guide exists.

**Comment by marcovelarde** [comment]
This works for Memu too

**Comment by stigmatixx** [comment]
I can't even get FGA to open in portrait mode it automatically puts it in landscape. How do you open it in portrait mode?

**Comment by reconman** [comment]
@stigmatixx Click on the rotate button on the right (Bluestacks 5)

**Comment by stigmatixx** [comment]
> @stigmatixx Click on the rotate button on the right (Bluestacks 5)

Thanks, I overlooked that bit. I did want to add that you can also get past that by using the arrow keys on your keyboard and using enter to select.

**Comment by lehuydiep4** [comment]
> I've verified myself that rotating is enough for latest Bluestacks 5 with FGA 1556.
> 
> 1. Switch to portrait orientation.
> 2. Start Service is portrait orientation.
> 3. Switch to Landcape.
> 
> You only have to do this the first time anyways if you click the 'Don't ask me again' checkbox.

Help, after i switch to portrait orientation, i got stuck at this screen too, then i switch to landcape, i just get black screen.
