### ISSUE TITLE
"Also Check All" feature does not scroll back up to view most All tab supports

### ISSUE THREAD

**Issue by Djinnistorm** [Fate-Grand-Automata/FGA#968]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1556

### Describe the bug

With the "Also check All" option checked, the script will scroll down through, for example, the caster supports, then swap to the all tab. However, the support window is still scrolled down most of the way, causing the check of the all tab to uselessly bump the bottom of the list until the refresh count. This defeats the purpose of that feature, as it doesn't actually check most of the all list this way. 

### Video

https://i.imgur.com/VuiqrGh.mp4

### Device model

Bluestacks

### Android version

7

### Screen size

1600x900

### RAM

4gb

**Comment by reconman** [comment]
Sorting by anything other than Login fixes the scroll position.

**Comment by Djinnistorm** [comment]
that's...really strange, but yea it does. Not sure if that's worth fixing on FGA's end then, though maybe some mention of this particular behavior on the option might prevent future issue tickets.

**Comment by MathewSachin** [comment]
Should be simple to fix

https://github.com/Fate-Grand-Automata/FGA/blob/008368affe45badf9f1e5407ddf859af99ec6934/scripts/src/main/java/com/mathewsachin/fategrandautomata/scripts/modules/Support.kt#L61-L66

Before setting swipes to 0, should check if we had scrolled and based on that click on the top of support list scrollbar (we already have this location in code).
