### ISSUE TITLE
Clicks misaligned after full screen update (19.5 : 9 Screen)

### ISSUE THREAD

**Issue by lawliet013** [Fate-Grand-Automata/FGA#969]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1556

### Describe the bug

After the full screen update, FGA hasn't been able to run scripts due to the clicks being misaligned. This occurs when using either gesture controls or 3 button navigation. With gesture controls, the game has black bars at the sides with the side with the notch having a bigger bar. With 3 button navigation, the game covers the entire screen, including the notch. I have tried "Ignore Notch Calculation" but it didn't resolve the issue.

I have been able to get FGA to work by going into developer options in the Android system settings and turning cutout display to Hide.

### Video

https://streamable.com/dn7wj1

![Screenshot_20211119-083335](https://user-images.githubusercontent.com/94567075/142635036-7731bd8c-e9b6-4756-b6a6-8b529d7ed6ef.png)
![Screenshot_20211119-082332](https://user-images.githubusercontent.com/94567075/142635043-3ff2fd7a-bc3f-4a0d-b785-2d3928cfefd4.png)
![Screenshot_20211119-082316](https://user-images.githubusercontent.com/94567075/142635049-89579be9-a31d-4fa5-9adc-4d67f99e2214.png)
![Screenshot_20211119-082256](https://user-images.githubusercontent.com/94567075/142635065-8d14a78d-cd69-409a-b512-a4d126e2dc38.png)

### Device model

Moto Edge 5G 2020

### Android version

11

### Screen size

2340 x 1080

### RAM

6GB

**Comment by reconman** [comment]
What's the thin black line at the bottom? I think that's causing the problems.

**Comment by lawliet013** [comment]
> What's the thin black line at the bottom? I think that's causing the problems.

The phone has a curved screen on both sides. The default setting is to not run apps on the curved edges. That's what I think the black line is.

Going into my display settings and allowing FGO to display on the curved edges did fix the issue.
