### ISSUE TITLE
error in use master skill

### ISSUE THREAD

**Issue by QQHgenz** [Fate-Grand-Automata/FGA#970]
### Preparation

- [ ] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1554

### Describe the bug

i tried to resize the screen but still error

### Video

https://user-images.githubusercontent.com/94516873/142716333-7314f788-bf60-4357-8aa7-7b7f08963009.mp4

### Device model

lenovo thinkbook 15 gen 2

### Android version

10

### Screen size

720x1280

### RAM

8GB

**Comment by MathewSachin** [comment]
1554 is not latest

**Comment by QQHgenz** [comment]
> 1554 is not latest

i know but t have tried the newest version bụt it doesn't work

**Comment by MathewSachin** [comment]
Then you shouldn't check the 'I tested the latest release'.
Anyways, the master skills issue had been solved in 1556 if you looked at other closed issues.
