### ISSUE TITLE
Unable to Select Support

### ISSUE THREAD

**Issue by egomest** [Fate-Grand-Automata/FGA#971]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA, JP

### FGA build number

1556

### Describe the bug

The script is not selecting support automatically and must be done manually by player. The utomation during turns are working well, but when the run end and returns to select support for the next run, the same thing happens.

### Video

https://streamable.com/folqct

### Device model

Samsung Galaxy S10+

### Android version

11

### Screen size

1440x3040

### RAM

12GB

**Comment by MathewSachin** [comment]
Move the Play button away from the place it checks for support screen.
Similar case is already mentioned in troubleshooting guide
