### ISSUE TITLE
Can Fga run on virtual machine ? ( Vmos ,F1 vm)

### ISSUE THREAD

**Issue by ThieuMinh26** [Fate-Grand-Automata/FGA#974]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

I want to use Virtual machine (Vmos , F1 VM ) to change the screen to 16:9 
I Think use virtual machine can fix full screen problem of fga

**Comment by reconman** [comment]
You'll have to test it yourself. But which device do you have where you can't set FGO to full screen?

**Comment by ThieuMinh26** [comment]
> You'll have to test it yourself. But which device do you have where you can't set FGO to full screen?

nah im just curious if fga buster can run correctly on 16:9 screen or not
sorry for bad grammar

**Comment by ThieuMinh26** [comment]
ok
F1 Vm can run FGA buster without problem 
auto farm still ok
