### ISSUE TITLE
Unable to run even after trying different methods

### ISSUE THREAD

**Issue by dixin10** [Fate-Grand-Automata/FGA#975]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA, JP

### FGA build number

Every single version

### Describe the bug

So I'm having the the same issue as other people where I try to click the Start Now button but nothing happens.
I've tried to get it to work by switching from Bluestacks 4 to 5,tried it on Nox,tried it on Memu but all give the same result.Older versions of FGA don't work anymore either.
The portrait mode solution also doesn't work at all,tho it seems to have worked for others.
Any idea on what else I can try or did I just get super unlucky here?

### Video

![image](https://user-images.githubusercontent.com/73478179/143039483-693f3fef-d7cb-4d49-8cef-188913a76d56.png)

### Device model

One Plus 3T(Bluestacks 64bit)

### Android version

10

### Screen size

1600x900

### RAM

4GB

**Comment by GabrielTFV** [comment]
I have the same issue, as a suggestion please leave the .apk for previous versions available for download in case someone has problems with the current version.

**Comment by Yukinon101** [comment]
I was having the same issue where pressing the start does not do anything for me. Decided to re-install mine and it works for me as of today. 

1) Un-Installing FGA
2) Deleting FGA Files & Images on your phone
3) Re-Installing FGA

All custom commands that I made did not get deleted either. Hopefully that helps!

**Comment by akano12** [comment]
@dixin10 
had the same issue on bluestacks and here's how i fixed it:

open settings => graphics and change the graphics engine mode from Performance to Compativility

**Comment by Ryrin45** [comment]
> @dixin10 had the same issue on bluestacks and here's how i fixed it:
> 
> open settings => graphics and change the graphics engine mode from Performance to Compativility

Are you sure it's the same issue? Bluestacks has always had that issue and that's always been the fix. It would freeze upon trying to start a script. But this issue, where clicking "start now" does nothing, is happening even with LDPlayer which it never has before.

**Comment by KyanZennaro** [comment]
I still got that issue too, on ver 1577,
