### ISSUE TITLE
Automated run not distinguishing between battles

### ISSUE THREAD

**Issue by pokechumaster** [Fate-Grand-Automata/FGA#982]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1556

### Describe the bug

After updating to FGA (1556), it doesn’t automate correctly. It works for the 1st battle, but it doesn’t recognize the start of the 2nd battle and just uses facecards. The end screen for using apples also doesn’t get recognized. Adjusting the % similarity and timing didn’t help either. This hasn’t happened prior to the FGO and FGA updates. 

### Video

https://www.youtube.com/watch?v=pQQBOANwBCo

### Device model

Huawei Honor V10

### Android version

11

### Screen size

2160 x 1080

**Comment by reconman** [comment]
Can reproduce it by setting the support Servant to the first slot.

I usually don't do that, so I never noticed.

**Comment by reconman** [comment]
Can you check whether limiting the runs to 1 makes FGA stop?

The weird thing is that I see a click on the Repeat button, but without a "Ran x times" notification. But the "Failed to determine card type" notifications do pop up.

What's your Min Similarity setting?

**Comment by pokechumaster** [comment]
My min similarity setting is 68% and stage counter similarity is 85%.
I tried running FGA on the Fuyuki with face cards only, and it was done as 1 continuous run. Friend support goes through, but it gets stuck on the apple screen post-battle (script is still running at this point). If I press on Close and let it go to the apple refill from the free quest screen, then the script stops by itself.

**Comment by reconman** [comment]
Can you reset the similarity to default and try again?

**Comment by pokechumaster** [comment]
That fixed it, thanks a lot
