### ISSUE TITLE
FGA 1556 Bluestacks Not Tapping On The Right Spot

### ISSUE THREAD

**Issue by Claey** [Fate-Grand-Automata/FGA#985]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1556

### Describe the bug

The bot doesn't seem to tap on the right spot, it's tapping a lot higher than it's supposed to be on bluestacks 4, I've tried searching for the same issue but I can't really find one (maybe I just suck at searching or it's only happening to me)

### Video

https://user-images.githubusercontent.com/62210258/144207148-64fede28-51fe-49fd-95f7-099152dbf249.mp4

### Device model

Bluestacks 4 - Nougat 32-bit

### Android version

7

### Screen size

1920x1080

### RAM

2GB

**Comment by TripleBrass** [comment]
I recently switched to BlueStacks HyperV and reinstalled FGO/FGA from scratch today.  I'm experiencing similar behavior, although I am on build 1562.

**Comment by Claey** [comment]
> I recently switched to BlueStacks HyperV and reinstalled FGO/FGA from scratch today. I'm experiencing similar behavior, although I am on build 1562.

I don't know if it's on purpose or not but after letting it tap on random servants profiles for a bit it started to work properly.

**Comment by reconman** [comment]
@Claey See the last question in the troubleshooting guide, it's normal.
