### ISSUE TITLE
Click on play but does not activate script

### ISSUE THREAD

**Issue by Martherius** [Fate-Grand-Automata/FGA#986]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1562

### Describe the bug

It used to work fine but after updating it stopped working, I have remade my scripts but none seems to work, I just click play and nothing happens

### Video

https://drive.google.com/file/d/1Ti8zsBW4ZrNQOsPsG9LFDtX4ZhzCQOLu/view?usp=drivesdk

### Device model

Motorola edge

### Android version

11

### Screen size

2340x1080

### RAM

6GB

**Comment by reconman** [comment]
Can't access your video freely. Make sure to set it so anyone with the link can see it.

**Comment by Martherius** [comment]
https://drive.google.com/file/d/1Ti8zsBW4ZrNQOsPsG9LFDtX4ZhzCQOLu/view?usp=drivesdk

The link is now open for anyone, here it goes again just in case

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by reconman** [comment]
Get rid of the black bars, then it will work.

**Comment by Martherius** [comment]
> Get rid of the black bars, then it will work.

How?

**Comment by reconman** [comment]
We can't give you guides because every phone has different system settings.

It should be somewhere in the display settings.

**Comment by Martherius** [comment]
> 

No problem, found where it is activated, on display settings, finally working, thanks

**Comment by McMaster01** [comment]
Mine doesn't even select the quest, how did you set it to work, Help pls
