### ISSUE TITLE
Support Not Found is not detected

### ISSUE THREAD

**Issue by Munung** [Fate-Grand-Automata/FGA#989]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

KR

### FGA build number

1564

### Describe the bug

![1638731882](https://user-images.githubusercontent.com/30804080/144761295-a33db8b5-65c7-4b65-b0eb-9509961a5ca4.png)
it doesn't work on this screen

### Video

Example of not working normally:: https://www.youtube.com/watch?v=5XwbZEbov-I

Example of normal operation: : https://www.youtube.com/watch?v=fqQThQ6HIZg

### Device model

bluestacks 5

### Android version

9

### Screen size

2560x1440

### RAM

4GB

**Comment by reconman** [comment]
Try 1566, which will be available in a few minutes.

**Comment by Munung** [comment]
> 

i think it's still not working..

**Comment by Munung** [comment]
> 

i think it's still not working..

**Comment by Munung** [comment]
> Try 1566, which will be available in a few minutes.

i think it's still not working..

**Comment by reconman** [comment]
Video?

**Comment by Munung** [comment]
> 

https://www.youtube.com/watch?v=BbgotVlvPFo

**Comment by reconman** [comment]
Sorry, mixed up X and Y. 1567 should work.

**Comment by Munung** [comment]
It's still not working properly
It's the same as 1566

**Comment by Munung** [comment]
> Sorry, mixed up X and Y. 1567 should work.
It's still not working properly
It's the same as 1566

**Comment by Munung** [comment]
1567 video
https://www.youtube.com/watch?v=_EhswG1r60s

**Comment by reconman** [comment]
If this one doesn't work, then I'm out of ideas for now: https://github.com/Fate-Grand-Automata/FGA/suites/4569851450/artifacts/122925296

**Comment by Munung** [comment]
What kind of video should I provide? 
For example another KR user's video?

**Comment by reconman** [comment]
I mean a video with 1568 like you did with the other videos.

**Comment by Munung** [comment]
https://youtu.be/IrMldX0QMIU

**Comment by reconman** [comment]
Your min similarity in Advanced -> Fine-tune is 80 %, right?

I can try lowering that value for this image search.

**Comment by Munung** [comment]
Oh, I lowered the min similarity to 63% and it works.

**Comment by reconman** [comment]
Can you check how high you can go? I can adjust the min similarity for that one image accordingly then.

**Comment by Munung** [comment]
It only works up to 63%
It's not working from 64%.

**Comment by reconman** [comment]
That's bad, 63 % is too low to reliably match.

I will change the matching so the text is used instead of the corner of the textbox, but I'll need a screenshot from CN first: https://github.com/Fate-Grand-Automata/FGA/issues/244#issuecomment-987139777

I would recommend increasing the min similarity to 80 % again.

**Comment by Munung** [comment]
> That's bad, 63 % is too low to reliably match.
> 
> I will change the matching so the text is used instead of the corner of the textbox, but I'll need a screenshot from CN first: [#244 (comment)](https://github.com/Fate-Grand-Automata/FGA/issues/244#issuecomment-987139777)
> 
> I would recommend increasing the min similarity to 80 % again.

Do you still need a screenshot?

**Comment by reconman** [comment]
@Munung Yes, of CN.

**Comment by reconman** [comment]
This build should probably work, at least it does for NA and I created the new image based off your screenshot: https://github.com/Fate-Grand-Automata/FGA/suites/4694803813/artifacts/128225527
