### ISSUE TITLE
It keep show error "Width must be positive"

### ISSUE THREAD

**Issue by kaitoreee** [Fate-Grand-Automata/FGA#992]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1567

### Describe the bug

after choose a class servant,it show error "Width must be positive". i even look up problem about error "Width must be positive" and it said turn off battery optimization on FGA,try run on fullscreen,try turn on and off ignore notch calculation so i tried it them but still same

### Video

https://user-images.githubusercontent.com/87101553/145013713-cb720885-878b-412a-b8e9-0e3412de84e6.mp4

### Device model

Xiaomi Poco X3 Pro

### Android version

11

### Screen size

1080 x 2400 with screen ratio 20:9 

### RAM

8GB

**Comment by reconman** [comment]
Corrupted support image, closing afer inactivity.
