### ISSUE TITLE
Option for the script to play until certain amount of AP is left

### ISSUE THREAD

**Issue by The-Intelligent-One** [Fate-Grand-Automata/FGA#994]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

This is not a particularly important feature, but there's many many times when I don't have time yet to play the stages I want (e.g. going through story), so I just want to set FGA on whatever node I'm farming to use a certain amount of AP/do runs until I have X amount of AP left, so I don't have to worry about reaching the cap, and I'll have AP for the nodes I want to do myself when I have time.

**Comment by reconman** [comment]
Reading the amount of AP left is really hard, you'll have to use the "Run x times" feature instead.
