### ISSUE TITLE
What Nox version I should use ?

### ISSUE THREAD

**Issue by killedbydagger** [Fate-Grand-Automata/FGA#996]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Hello, with the recent lottery event in JP (Christmas Martha), I had found this script (or should I say app ?) useful for other people so I decided to test it.

I got 'Failed to install' message when trying to install on Nox Emulator version 7.0.17, yes I had read the troubleshooting that FGA could not be installed on latest version of Nox Emulator. So the question is, which versions are considered 'old' ?

Thank you.

**Comment by reconman** [comment]
https://github.com/Fate-Grand-Automata/FGA/issues/748#issuecomment-903131657

Can't tell you which one higher than that works, Nox can't run on Windows 11, it seems.

**Comment by killedbydagger** [comment]
alright im gonna try it, thank you

**Comment by killedbydagger** [comment]
I tested it already, I am using Nox Emulator version 7.0.1.3 tried 3 ways of installing
1. Using APK icon at sidebar, the issue is "Failed to install"
2. Using File manager, the issue is "This package is corrupted" something like that
3. Download the apk from Nox directly and installed it, the issue is the same as number 2

Any suggestion?

**Comment by reconman** [comment]
You did create an Android 7 instance, right?

**Comment by reconman** [comment]
And you could try installing it with `adb install FGA.apk`, maybe you see more details that way.

**Comment by killedbydagger** [comment]
Yeah im creating new android instances with Android 7, but still cannot install

**Comment by reconman** [comment]
What about my adb suggestion?

**Comment by killedbydagger** [comment]
i dont have adb or android studio package, should i downloaded it ?

**Comment by reconman** [comment]
See https://www.xda-developers.com/install-adb-windows-macos-linux/

**Comment by killedbydagger** [comment]
![image](https://user-images.githubusercontent.com/48778430/145385840-a8ed6098-5c37-4b10-8995-1c4b3c219afc.png)

Here i got an error

**Comment by reconman** [comment]
Did you change the apk in any way?

Can you try downloading it again from https://github.com/Fate-Grand-Automata/FGA/releases/download/canary/com.mathewsachin.fategrandautomata.apk?

Works fine on my machine even on newest Nox.

I just had to disable some Windows security setting to make it work again on Windows 11.

**Comment by killedbydagger** [comment]
1. No, i did not change anything regarding the apk
2. I asked my friend, he used Nox Emulator with 7.0.1.3 version and he couldn't. But I tried installing on my laptop using Nox Emulator with 7.0.1.0 and succeed. 
3. My os is windows 10.

**Comment by reconman** [comment]
What I wanted to indicate is that the error above usually pops up if the apk was corrupted in some way.

You could run `certutil -hashfile FGA.apk MD5` on the command line. It should be `592e1bf22ab751b100d88de129c2d325` for the latest apk.

Otherwise, the apk is corrupted.

**Comment by killedbydagger** [comment]
Okay , ill give it a try

**Comment by killedbydagger** [comment]
I got same md5 hash, but still file is corrupted.

As for now, I need to downgrade my Nox again to version 7.0.1.0 for it to run smoothly.
