### ISSUE TITLE
fga didn't work on both ldplayer and bluestack

### ISSUE THREAD

**Issue by nobrain1412** [Fate-Grand-Automata/FGA#997]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA, JP

### FGA build number

1556

### Describe the bug

start button didn't work. i tried uninstall fga, fgo and ldplayer

### Video

https://www.youtube.com/watch?v=3HqHpNGC2lU

### Device model

ASUS_Z01QD

### Android version

9

### Screen size

1280x720

### RAM

3gb

**Comment by reconman** [comment]
Did you enable root in the LDPlayer settings?

**Comment by reconman** [comment]
For bluestacks see #967
