### ISSUE TITLE
Unable to choose a folder in Android 8+

### ISSUE THREAD

**Issue by KaitoKid** [Fate-Grand-Automata/FGA#999]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1567

### Describe the bug

Exact same situation as #677 where the app crashes upon trying to select a home/default folder. I believe it's crashing while trying to redirect to the default file manager (Files by Google) on the clean OS.

It seems to be exclusive to FGA as I'm able to select files from Discord to upload, Ankulua's own file manager works, etc.

Has anyone else figured out a workaround?

### Video

N/A

### Device model

RedFinger Cloud 

### Android version

8

**Comment by KaitoKid** [comment]
I've tried installing multiple file managers on the system and the app still crashes - possibly a solution would be to prompt a selection?

**Comment by reconman** [comment]
OpenDocTreePersistable calls https://developer.android.com/reference/androidx/activity/result/contract/ActivityResultContracts.OpenDocumentTree which is part of Android since Android 5.

You can try this: https://android.stackexchange.com/a/155989

We haven't had any Redfinger users yet and I can barely find any info. Are you connecting from your phone or PC to an emulator running in the cloud? And that one os causing issues?

**Comment by KaitoKid** [comment]
Unfortunately no defaults were set - I think that's the strangest part where there was no prompt at all.

RE: [RedFinger](https://cloudemulator.net), its run by a TW startup which runs Android as a service in the cloud accessible via browser. 

I'd tag this as low priority/won't fix until it becomes an issue for others. I'm definitely a unique case as I'm usually traveling for business purposes and would prefer to have FGO run/farm in the cloud so I can just occasionally check in on it regardless of what device I'm using (e.g. macbook, phone, etc.)

[Full video here](https://streamable.com/fnngaw) with settings

**Comment by ItsKuro** [comment]
Exact problem persists on my S20 SM-G981U1

**Comment by reconman** [comment]
> Exact problem persists on my S20 SM-G981U1

Now that's weird, we have quite a few S20 users, none had this problem. Did you disable some system apps?

**Comment by ItsKuro** [comment]
Thank you, that was it. The culprit was Package Disabler and was resolved once I re-enabled all the disabled packages. Now it's only a matter of which package was causing the issue.
